project:
  type: website
  output-dir: _site

website:
  title: "My Writings"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Blog
      - href: literature/index.qmd
        text: Literature
      - href: chapters/index.qmd
        text: Chapters
      - href: tutorials/index.qmd
        text: Tutorials
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
