{
  "hash": "85eb6fbbf556829539918443a9809033",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The 2019 SI Redefinition: Anchoring Metrology to Fundamental Quantum Constants\"\ndescription: \"A comprehensive metrological treatise on the 2019 redefinition of the International System of Units (SI): Le Grand K, the Kibble balance, the Avogadro Silicon Project, Johnson noise thermometry, and the quantum closure of physics.\"\ndate: \"2026-09-07\"\ncategories: [Physics, Metrology, Quantum Mechanics, Science History]\nformat:\n  html:\n    code-fold: true\n    toc: true\n    toc-depth: 3\nimage: \"si_redefinition_header.jpg\"\njupyter: python3\ndraft: true\n---\n\n![Fundamental Constants Visualization](si_redefinition_header.jpg)\n\nOn **May 20, 2019** (World Metrology Day), the 26th General Conference on Weights and Measures (CGPM) enacted the most profound conceptual revolution in metrology since the inception of the metric system during the French Revolution. \n\nFor the first time in human history, **every single one of the seven base units of the International System of Units (SI) is defined entirely in terms of fixed, exact numerical values of fundamental physical constants**. Physical artifacts subject to decay, contamination, and loss have been permanently banished from the foundations of physical law.\n\n---\n\n## 1. The Definitional Architecture of the Revised SI\n\nThe modern SI is anchored by fixing the exact numerical values of seven defining constants:\n\n| Base Unit | Dimension | Defining Constant | Symbol | Fixed Numerical Value | Units |\n|:---|:---|:---|:---:|:---|:---|\n| **Second** | Time ($\\text{T}$) | Hyperfine transition of $^{133}\\text{Cs}$ | $\\Delta\\nu_{\\text{Cs}}$ | $9{,}192{,}631{,}770$ | $\\text{Hz} = \\text{s}^{-1}$ |\n| **Meter** | Length ($\\text{L}$) | Speed of light in vacuum | $c$ | $299{,}792{,}458$ | $\\text{m}\\cdot\\text{s}^{-1}$ |\n| **Kilogram** | Mass ($\\text{M}$) | Planck constant | $h$ | $6.62607015 \\times 10^{-34}$ | $\\text{J}\\cdot\\text{s} = \\text{kg}\\cdot\\text{m}^2\\cdot\\text{s}^{-1}$ |\n| **Ampere** | Electric current ($\\text{I}$) | Elementary charge | $e$ | $1.602176634 \\times 10^{-19}$ | $\\text{C} = \\text{A}\\cdot\\text{s}$ |\n| **Kelvin** | Thermodynamic temp ($\\Theta$) | Boltzmann constant | $k$ | $1.380649 \\times 10^{-23}$ | $\\text{J}\\cdot\\text{K}^{-1} = \\text{kg}\\cdot\\text{m}^2\\cdot\\text{s}^{-2}\\cdot\\text{K}^{-1}$ |\n| **Mole** | Amount of substance ($\\text{N}$) | Avogadro constant | $N_{\\text{A}}$ | $6.02214076 \\times 10^{23}$ | $\\text{mol}^{-1}$ |\n| **Candela** | Luminous intensity ($\\text{J}$) | Luminous efficacy of $540\\text{ THz}$ radiation | $K_{\\text{cd}}$ | $683$ | $\\text{lm}\\cdot\\text{W}^{-1} = \\text{cd}\\cdot\\text{sr}\\cdot\\text{kg}^{-1}\\cdot\\text{m}^{-2}\\cdot\\text{s}^3$ |\n\n---\n\n## 2. A Critical History: From Human Body Parts to Artifacts\n\n### The Pre-Metric Patchwork\nFor millennia, human weights and measures were anthropomorphic or agricultural:\n* **Length:** The cubit (forearm length), the foot, the inch (width of three barleycorns).\n* **Mass:** The **avoirdupois pound**, established in England in the 14th century, defined as exactly $7{,}000$ troy grains of wheat taken from the middle of the ear.\n* Local barons, guilds, and kings minted arbitrary standards, creating thousands of mutually incompatible systems that made honest trade and rigorous scientific comparison nearly impossible.\n\n### The Metric Revolution: CGS vs. MKS\nIn the 1790s, the French Academy of Sciences set out to create a system \"for all people, for all time\" (*à tous les temps, à tous les peuples*):\n* The **meter** was originally defined as $1/10{,}000{,}000$ of the meridian distance from the North Pole to the Equator passing through Paris.\n* The **grave** (later renamed **kilogram**) was the mass of one cubic decimeter ($1\\text{ liter}$) of pure water at its freezing point.\n\nIn the late 19th century, physicists developed the **CGS system** (centimeter-gram-second). Championed by James Clerk Maxwell and Carl Friedrich Gauss, CGS cleanly unified mechanics with electrostatics (esu) and electrodynamics (emu). However, units like the dyne ($10^{-5}\\text{ N}$) and erg ($10^{-7}\\text{ J}$) were impractical for mechanical engineering and electrical power distribution. \n\nIn 1901, Italian engineer Giovanni Giorgi demonstrated that adding a fourth electrical unit (the ohm or ampere) unified mechanics and electromagnetism into the **MKS system** (meter-kilogram-second-ampere), which became the direct forerunner of the modern SI established in 1960.\n\n---\n\n## 3. The Fatal Flaws of *Le Grand K* (IPK)\n\nIn 1889, metrologists manufactured the **International Prototype of the Kilogram (IPK)**, known colloquially as *Le Grand K*. It was a right-circular cylinder ($39\\text{ mm}$ height by $39\\text{ mm}$ diameter) machined from an alloy of $90\\%$ platinum and $10\\%$ iridium, chosen for its extreme density ($\\approx 21.5\\text{ g/cm}^3$) and corrosion resistance. It was housed under three concentric glass bell jars in an environmentally controlled subterranean vault at the BIPM in Sèvres, France.\n\nOver its 130-year reign, the IPK revealed unavoidable physical pathologies:\n\n1. **Surface Contamination & Volatile Adsorption:** Despite hermetic glass vaults, atmospheric hydrocarbons, volatile organic compounds (VOCs), and airborne mercury vapor gradually diffused onto the cylinder's surface, steadily increasing its mass by approximately $1\\text{ }\\mu\\text{g}$ per year.\n2. **The Cleaning/Washing Dilemma:** Before periodic calibrations, the BIPM washed the IPK using a standardized protocol: rubbing with solvent-soaked chamois followed by steam cleaning with bi-distilled water. Each cleaning inevitably abraded microscopic clusters of platinum and iridium atoms, causing irreversible mass loss.\n3. **Divergence of National Sister Prototypes:** Every few decades, the IPK was compared against its identical official sister copies (*témoins*) distributed to national metrology institutes worldwide (such as K20 at NIST in the United States). By the 3rd Periodic Verification (1988–1992), the national prototypes had diverged from the IPK by more than **$50\\text{ micrograms}$**.\n4. **The Epistemological Paradox:** Because the IPK was *by definition* exactly one kilogram ($\\Delta m \\equiv 0$), it was impossible to determine whether the IPK was losing mass or the copies were gaining mass. If a stray cosmic ray knocked off an atom from Le Grand K, the mass of every star, atom, and galaxy in the universe instantly increased by definition!\n\n---\n\n## 4. Quantum Realization of Mass: The Kibble Balance\n\nTo sever mass from a physical object, metrologists turned to quantum mechanics, linking mass directly to the **Planck constant** ($h$). The primary realization instrument is the **Kibble Balance** (conceived by Bryan Kibble in 1975 at the NPL).\n\nThe balance eliminates unmeasurable geometric uncertainties in magnetic coils by operating in two distinct alternating phases:\n\n### Phase 1: Weighing Mode (Static Force Equilibrium)\nA calibration mass $m$ rests on a circular coil of wire of length $L$ suspended in a radial magnetic field of flux density $B$. A direct current $I$ is passed through the coil, creating an upward electromagnetic Lorentz force that precisely counterbalances gravity:\n\n$$ m g = I \\oint (\\mathbf{dl} \\times \\mathbf{B}) = I (B L) $$\n\nwhere $g$ is local gravitational acceleration (measured simultaneously with absolute gravimeters to parts in $10^9$).\n\n### Phase 2: Velocity Mode (Dynamic Induction)\nThe mass is removed. The coil is moved vertically through the exact same radial magnetic field at a constant controlled velocity $v$. By Faraday's Law of Induction, a voltage $V$ is induced across the coil terminals:\n\n$$ V = - \\frac{d\\Phi}{dt} = v (B L) \\implies B L = \\frac{V}{v} $$\n\n### The Kibble Cancellation\nSubstituting the geometric product $B L = V / v$ back into the weighing equation:\n\n$$ m g = I \\left( \\frac{V}{v} \\right) \\implies m g v = I V $$\n\n**Mechanical power equals electrical power!** \n\n### Macroscopic Quantum Standards\nTo tie electrical power ($I V$) to Planck's constant $h$, the voltage and current are measured using macroscopic quantum effects:\n\n1. **Josephson Effect (Voltage Standard):**\n   When a microwave frequency $f_{\\text{J}}$ irradiates a superconductor-insulator-superconductor tunnel junction, the voltage across the junction is quantized in exact steps:\n   $$ V = n \\left( \\frac{h}{2e} \\right) f_{\\text{J}} $$\n\n2. **Quantum Hall Effect (Resistance Standard):**\n   At cryogenic temperatures ($< 1\\text{ K}$) and strong magnetic fields ($> 10\\text{ T}$), the Hall resistance of a 2D electron gas is strictly quantized:\n   $$ R_{\\text{H}} = \\frac{1}{p} \\left( \\frac{h}{e^2} \\right) $$\n\nExpressing current via Ohm's Law through a quantum Hall resistor ($I = V' / R_{\\text{H}}$), the electrical power product becomes:\n\n$$ I V = \\frac{V \\cdot V'}{R_{\\text{H}}} = \\frac{\\left[ n_1 \\left(\\frac{h}{2e}\\right) f_1 \\right] \\left[ n_2 \\left(\\frac{h}{2e}\\right) f_2 \\right]}{\\frac{1}{p} \\left(\\frac{h}{e^2}\\right)} = \\left( \\frac{p \\, n_1 n_2}{4} \\right) h \\, f_1 f_2 $$\n\n**The elementary charge $e$ cancels out completely!**\n\n$$ m = \\frac{p \\, n_1 n_2}{4 g v} h \\, f_1 f_2 $$\n\nBecause frequencies ($f_1, f_2$) and length/velocity ($v$) are referenced to atomic clocks and laser interferometers, **mass is measured directly in terms of Planck's constant $h$**.\n\n---\n\n## 5. The Alternative Realization: The Silicon Avogadro Sphere (XRCD)\n\nThe Kibble balance was validated against an independent physical method: the **International Avogadro Coordination (IAC)** X-Ray Crystal Density (XRCD) project.\n\nMetrologists enriched silicon gas to $99.9995\\%$ pure isotope $^{28}\\text{Si}$ using Russian centrifuges previously used for uranium enrichment. From this ingots, opticians polished two nearly perfect $1\\text{ kg}$ spheres whose roundness deviates by less than **$5\\text{ nanometers}$** across their $93.7\\text{ mm}$ diameter.\n\nThe number of atoms $N$ inside the sphere is determined by dividing the macroscopic volume $V_{\\text{sphere}}$ (measured by spherical optical interferometry) by the microscopic unit cell volume $V_{\\text{cell}} = a_0^3$ (measured by X-ray interferometry):\n\n$$ N = 8 \\left( \\frac{V_{\\text{sphere}}}{a_0^3} \\right) $$\n\n(Since a silicon face-centered diamond cubic unit cell contains exactly 8 atoms). The Avogadro constant is then:\n\n$$ N_{\\text{A}} = \\frac{M(\\text{Si}) \\cdot N}{m_{\\text{sphere}}} $$\n\nBecause $h$ and $N_{\\text{A}}$ are related through the Rydberg constant $R_\\infty$ and the fine-structure constant $\\alpha$:\n\n$$ h = \\frac{c \\, \\alpha^2 \\, M_u \\, A_r(e)}{2 R_\\infty N_{\\text{A}}} $$\n\nthe silicon spheres provided an independent, sub-$20\\text{ ppb}$ precision cross-check of Planck's constant prior to the redefinition.\n\n---\n\n## 6. The Thermodynamics and Electrodynamic Revisions\n\n### The Kelvin: Fixing Boltzmann's Constant $k$\n* **Old Definition:** $1/273.16$ of the thermodynamic temperature of the triple point of Vienna Standard Mean Ocean Water (VSMOW).\n  * *Flaw:* The isotopic composition of water varies naturally; isotopic shifts alter the triple point by hundreds of microkelvins.\n* **New Definition:** Fixes $k = 1.380649 \\times 10^{-23}\\text{ J/K}$.\n* **Realization:** \n  * **Acoustic Gas Thermometry (AGT):** Measuring the speed of sound $u$ in noble gases at low pressure: $u^2 = \\gamma k T / m$.\n  * **Johnson Noise Thermometry:** Measuring thermal voltage fluctuations in resistors: $\\langle V^2 \\rangle = 4 k T R \\Delta f$.\n\n### The Ampere and the Decoupling of $\\mu_0$ and $\\varepsilon_0$\nPrior to 2019, the ampere was defined via the force between two infinitely long, infinitesimally thin parallel wires separated by $1\\text{ meter}$, which artificially set the magnetic permeability of vacuum to an exact integer multiple:\n\n$$ \\mu_0 \\equiv 4\\pi \\times 10^{-7}\\text{ N/A}^2 \\quad (\\text{exact by definition}) $$\n\nUnder the revised SI, the **elementary charge** $e = 1.602176634 \\times 10^{-19}\\text{ C}$ is fixed instead. Consequently, $\\mu_0$ and vacuum permittivity $\\varepsilon_0 = 1/(\\mu_0 c^2)$ are **no longer exact constants**! They depend on the dimensionless fine-structure constant $\\alpha$:\n\n$$ \\mu_0 = \\frac{2\\alpha h}{e^2 c}, \\quad \\varepsilon_0 = \\frac{e^2}{2\\alpha h c} $$\n\nBecause $\\alpha \\approx 1/137.035999...$ is an experimentally determined quantum electrodynamic coupling constant, $\\mu_0$ and $\\varepsilon_0$ now carry experimental measurement uncertainty (approximately $1.5 \\times 10^{-10}$).\n\n---\n\n## 7. Dependency Architecture of the Revised SI\n\nBelow is a Python visualization showing the hierarchical network of how the seven fundamental constants define the seven SI base units.\n\n::: {#cell-fig-si-network .cell execution_count=1}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as patches\n\nfig, ax = plt.subplots(figsize=(10, 6))\n\n# Coordinates for Constants (Inner circle / Top) and Units (Outer circle / Bottom)\nconstants = {\n    r'$\\Delta\\nu_{\\mathrm{Cs}}$': (2, 4),\n    r'$c$': (4, 4),\n    r'$h$': (6, 4),\n    r'$e$': (8, 4),\n    r'$k$': (1, 2),\n    r'$N_{\\mathrm{A}}$': (5, 2),\n    r'$K_{\\mathrm{cd}}$': (9, 2)\n}\n\nunits = {\n    'Second (s)': (2, 5),\n    'Meter (m)': (4, 5.2),\n    'Kilogram (kg)': (6, 5.2),\n    'Ampere (A)': (8, 5),\n    'Kelvin (K)': (1, 0.8),\n    'Mole (mol)': (5, 0.8),\n    'Candela (cd)': (9, 0.8)\n}\n\n# Draw Constants (Diamonds)\nfor label, (x, y) in constants.items():\n    ax.scatter(x, y, s=1500, marker='s', color='#2ca02c', alpha=0.85, zorder=4)\n    ax.text(x, y, label, ha='center', va='center', color='white', fontsize=11, fontweight='bold')\n\n# Draw Units (Circles)\nfor label, (x, y) in units.items():\n    ax.scatter(x, y, s=1700, marker='o', color='#1f77b4', alpha=0.85, zorder=4)\n    ax.text(x, y, label, ha='center', va='center', color='white', fontsize=8.5, fontweight='bold')\n\n# Directed connections (Constant -> Unit)\nedges = [\n    (constants[r'$\\Delta\\nu_{\\mathrm{Cs}}$'], units['Second (s)']),\n    (constants[r'$c$'], units['Meter (m)']),\n    (constants[r'$\\Delta\\nu_{\\mathrm{Cs}}$'], units['Meter (m)']),\n    (constants[r'$h$'], units['Kilogram (kg)']),\n    (constants[r'$c$'], units['Kilogram (kg)']),\n    (constants[r'$\\Delta\\nu_{\\mathrm{Cs}}$'], units['Kilogram (kg)']),\n    (constants[r'$e$'], units['Ampere (A)']),\n    (constants[r'$\\Delta\\nu_{\\mathrm{Cs}}$'], units['Ampere (A)']),\n    (constants[r'$k$'], units['Kelvin (K)']),\n    (constants[r'$h$'], units['Kelvin (K)']),\n    (constants[r'$N_{\\mathrm{A}}$'], units['Mole (mol)']),\n    (constants[r'$K_{\\mathrm{cd}}$'], units['Candela (cd)'])\n]\n\nfor (x1, y1), (x2, y2) in edges:\n    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),\n                arrowprops=dict(arrowstyle=\"->\", color='gray', lw=1.5, alpha=0.6, shrinkA=18, shrinkB=18))\n\nax.set_xlim(-0.2, 10.2)\nax.set_ylim(0, 6)\nax.axis('off')\nax.set_title(\"Dependency Graph: Constants (Green Squares) $\\\\longrightarrow$ SI Base Units (Blue Circles)\", \n             fontsize=12, fontweight='bold', pad=20)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The network of dependencies between the 7 defining constants and the 7 SI base units.](si-redefinition-2019_files/figure-html/fig-si-network-output-1.png){#fig-si-network width=950 height=565}\n:::\n:::\n\n\n---\n\n## 8. Further Viewing & Literature on the SI Redefinition\n\nTo explore how these redefining measurements were performed in national metrology laboratories, check out these essential video breakdowns and papers:\n\n* **The Silicon Sphere & Kilogram Redefinition (Veritasium):**\n{{< video https://www.youtube.com/watch?v=Oo0jm1PPRuo&t=187s >}}\n\n* **The World's Roundest Object (Avogadro Project):**\n{{< video https://www.youtube.com/watch?v=ZMByI4s-D-Y >}}\n\n* **The Transition to the New SI Units:**\n{{< video https://www.youtube.com/watch?v=c_e1wITe_ig >}}\n\n* **NIST DIY LEGO Watt Balance Demonstration:**\n{{< video https://www.youtube.com/watch?v=oST_krdqLPQ >}}\n\n* **Peer-Reviewed Reference:** [A LEGO Watt balance: An apparatus to determine a fundamental constant](https://pubs.aip.org/aapt/ajp/article/83/11/913/1039505/A-LEGO-Watt-balance-An-apparatus-to-determine-a) (*American Journal of Physics*, L. S. Chao et al., 2015).\n\n* **Additional Documentary Overviews:**\n{{< video https://www.youtube.com/watch?v=0fKBhvDjuy0 >}}\n\n{{< video https://www.youtube.com/watch?v=44cv416bKP4 >}}\n\n{{< video https://www.youtube.com/watch?v=GtOGurrUPmQ&t=62s >}}\n\n",
    "supporting": [
      "si-redefinition-2019_files"
    ],
    "filters": [],
    "includes": {}
  }
}