---
title: "Romeo and Juliet - Act III"
author: "William Shakespeare"
description: "Act III of Romeo and Juliet."
categories: [Literature, Classic]
format:
  html:
    page-layout: article
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 300px
    reference-location: margin
    citation-location: margin
---

# Act III

SCENE I. A public Place.


 Enter Mercutio, Benvolio, Page and Servants.

BENVOLIO.
I pray thee, good Mercutio, let’s retire:
The day is hot, the Capulets abroad,
And if we meet, we shall not scape a brawl,
For now these hot days, is the mad blood stirring.

MERCUTIO.
Thou art like one of these fellows that, when he enters the confines of
a tavern, claps me his sword upon the table, and says ‘God send me no
need of thee!’ and by the operation of the second cup draws him on the
drawer, when indeed there is no need.

BENVOLIO.
Am I like such a fellow?

MERCUTIO.
Come, come, thou art as hot a Jack in thy mood as any in Italy; and as
soon moved to be moody, and as soon moody to be moved.

BENVOLIO.
And what to?

MERCUTIO.
Nay, an there were two such, we should have none shortly, for one would
kill the other. Thou? Why, thou wilt quarrel with a man that hath a
hair more or a hair less in his beard than thou hast. Thou wilt quarrel
with a man for cracking nuts, having no other reason but because thou
hast hazel eyes. What eye but such an eye would spy out such a quarrel?
Thy head is as full of quarrels as an egg is full of meat, and yet thy
head hath been beaten as addle as an egg for quarrelling. Thou hast
quarrelled with a man for coughing in the street, because he hath
wakened thy dog that hath lain asleep in the sun. Didst thou not fall
out with a tailor for wearing his new doublet before Easter? with
another for tying his new shoes with an old riband? And yet thou wilt
tutor me from quarrelling!

BENVOLIO.
And I were so apt to quarrel as thou art, any man should buy the fee
simple of my life for an hour and a quarter.

MERCUTIO.
The fee simple! O simple!

 Enter Tybalt and others.

BENVOLIO.
By my head, here comes the Capulets.

MERCUTIO.
By my heel, I care not.

TYBALT.
Follow me close, for I will speak to them.
Gentlemen, good-den: a word with one of you.

MERCUTIO.
And but one word with one of us? Couple it with something; make it a
word and a blow.

TYBALT.
You shall find me apt enough to that, sir, and you will give me
occasion.

MERCUTIO.
Could you not take some occasion without giving?

TYBALT.
Mercutio, thou consortest with Romeo.

MERCUTIO.
Consort? What, dost thou make us minstrels? And thou make minstrels of
us, look to hear nothing but discords. Here’s my fiddlestick, here’s
that shall make you dance. Zounds, consort!

BENVOLIO.
We talk here in the public haunt of men.
Either withdraw unto some private place,
And reason coldly of your grievances,
Or else depart; here all eyes gaze on us.

MERCUTIO.
Men’s eyes were made to look, and let them gaze.
I will not budge for no man’s pleasure, I.

 Enter Romeo.

TYBALT.
Well, peace be with you, sir, here comes my man.

MERCUTIO.
But I’ll be hanged, sir, if he wear your livery.
Marry, go before to field, he’ll be your follower;
Your worship in that sense may call him man.

TYBALT.
Romeo, the love I bear thee can afford
No better term than this: Thou art a villain.

ROMEO.
Tybalt, the reason that I have to love thee
Doth much excuse the appertaining rage
To such a greeting. Villain am I none;
Therefore farewell; I see thou know’st me not.

TYBALT.
Boy, this shall not excuse the injuries
That thou hast done me, therefore turn and draw.

ROMEO.
I do protest I never injur’d thee,
But love thee better than thou canst devise
Till thou shalt know the reason of my love.
And so good Capulet, which name I tender
As dearly as mine own, be satisfied.

MERCUTIO.
O calm, dishonourable, vile submission!
[_Draws._] Alla stoccata carries it away.
Tybalt, you rat-catcher, will you walk?

TYBALT.
What wouldst thou have with me?

MERCUTIO.
Good King of Cats, nothing but one of your nine lives; that I mean to
make bold withal, and, as you shall use me hereafter, dry-beat the rest
of the eight. Will you pluck your sword out of his pilcher by the ears?
Make haste, lest mine be about your ears ere it be out.

TYBALT.
[_Drawing._] I am for you.

ROMEO.
Gentle Mercutio, put thy rapier up.

MERCUTIO.
Come, sir, your passado.

 [_They fight._]

ROMEO.
Draw, Benvolio; beat down their weapons.
Gentlemen, for shame, forbear this outrage,
Tybalt, Mercutio, the Prince expressly hath
Forbid this bandying in Verona streets.
Hold, Tybalt! Good Mercutio!

 [_Exeunt Tybalt with his Partizans._]

MERCUTIO.
I am hurt.
A plague o’ both your houses. I am sped.
Is he gone, and hath nothing?

BENVOLIO.
What, art thou hurt?

MERCUTIO.
Ay, ay, a scratch, a scratch. Marry, ’tis enough.
Where is my page? Go villain, fetch a surgeon.

 [_Exit Page._]

ROMEO.
Courage, man; the hurt cannot be much.

MERCUTIO.
No, ’tis not so deep as a well, nor so wide as a church door, but ’tis
enough, ’twill serve. Ask for me tomorrow, and you shall find me a
grave man. I am peppered, I warrant, for this world. A plague o’ both
your houses. Zounds, a dog, a rat, a mouse, a cat, to scratch a man to
death. A braggart, a rogue, a villain, that fights by the book of
arithmetic!—Why the devil came you between us? I was hurt under your
arm.

ROMEO.
I thought all for the best.

MERCUTIO.
Help me into some house, Benvolio,
Or I shall faint. A plague o’ both your houses.
They have made worms’ meat of me.
I have it, and soundly too. Your houses!

 [_Exeunt Mercutio and Benvolio._]

ROMEO.
This gentleman, the Prince’s near ally,
My very friend, hath got his mortal hurt
In my behalf; my reputation stain’d
With Tybalt’s slander,—Tybalt, that an hour
Hath been my cousin. O sweet Juliet,
Thy beauty hath made me effeminate
And in my temper soften’d valour’s steel.

 Re-enter Benvolio.

BENVOLIO.
O Romeo, Romeo, brave Mercutio’s dead,
That gallant spirit hath aspir’d the clouds,
Which too untimely here did scorn the earth.

ROMEO.
This day’s black fate on mo days doth depend;
This but begins the woe others must end.

 Re-enter Tybalt.

BENVOLIO.
Here comes the furious Tybalt back again.

ROMEO.
Again in triumph, and Mercutio slain?
Away to heaven respective lenity,
And fire-ey’d fury be my conduct now!
Now, Tybalt, take the ‘villain’ back again
That late thou gav’st me, for Mercutio’s soul
Is but a little way above our heads,
Staying for thine to keep him company.
Either thou or I, or both, must go with him.

TYBALT.
Thou wretched boy, that didst consort him here,
Shalt with him hence.

ROMEO.
This shall determine that.

 [_They fight; Tybalt falls._]

BENVOLIO.
Romeo, away, be gone!
The citizens are up, and Tybalt slain.
Stand not amaz’d. The Prince will doom thee death
If thou art taken. Hence, be gone, away!

ROMEO.
O, I am fortune’s fool!

BENVOLIO.
Why dost thou stay?

 [_Exit Romeo._]

 Enter Citizens.

FIRST CITIZEN.
Which way ran he that kill’d Mercutio?
Tybalt, that murderer, which way ran he?

BENVOLIO.
There lies that Tybalt.

FIRST CITIZEN.
Up, sir, go with me.
I charge thee in the Prince’s name obey.

 Enter Prince, attended; Montague, Capulet, their Wives and others.

PRINCE.
Where are the vile beginners of this fray?

BENVOLIO.
O noble Prince, I can discover all
The unlucky manage of this fatal brawl.
There lies the man, slain by young Romeo,
That slew thy kinsman, brave Mercutio.

LADY CAPULET.
Tybalt, my cousin! O my brother’s child!
O Prince! O husband! O, the blood is spill’d
Of my dear kinsman! Prince, as thou art true,
For blood of ours shed blood of Montague.
O cousin, cousin.

PRINCE.
Benvolio, who began this bloody fray?

BENVOLIO.
Tybalt, here slain, whom Romeo’s hand did slay;
Romeo, that spoke him fair, bid him bethink
How nice the quarrel was, and urg’d withal
Your high displeasure. All this uttered
With gentle breath, calm look, knees humbly bow’d
Could not take truce with the unruly spleen
Of Tybalt, deaf to peace, but that he tilts
With piercing steel at bold Mercutio’s breast,
Who, all as hot, turns deadly point to point,
And, with a martial scorn, with one hand beats
Cold death aside, and with the other sends
It back to Tybalt, whose dexterity
Retorts it. Romeo he cries aloud,
‘Hold, friends! Friends, part!’ and swifter than his tongue,
His agile arm beats down their fatal points,
And ’twixt them rushes; underneath whose arm
An envious thrust from Tybalt hit the life
Of stout Mercutio, and then Tybalt fled.
But by and by comes back to Romeo,
Who had but newly entertain’d revenge,
And to’t they go like lightning; for, ere I
Could draw to part them was stout Tybalt slain;
And as he fell did Romeo turn and fly.
This is the truth, or let Benvolio die.

LADY CAPULET.
He is a kinsman to the Montague.
Affection makes him false, he speaks not true.
Some twenty of them fought in this black strife,
And all those twenty could but kill one life.
I beg for justice, which thou, Prince, must give;
Romeo slew Tybalt, Romeo must not live.

PRINCE.
Romeo slew him, he slew Mercutio.
Who now the price of his dear blood doth owe?

MONTAGUE.
Not Romeo, Prince, he was Mercutio’s friend;
His fault concludes but what the law should end,
The life of Tybalt.

PRINCE.
And for that offence
Immediately we do exile him hence.
I have an interest in your hate’s proceeding,
My blood for your rude brawls doth lie a-bleeding.
But I’ll amerce you with so strong a fine
That you shall all repent the loss of mine.
I will be deaf to pleading and excuses;
Nor tears nor prayers shall purchase out abuses.
Therefore use none. Let Romeo hence in haste,
Else, when he is found, that hour is his last.
Bear hence this body, and attend our will.
Mercy but murders, pardoning those that kill.

 [_Exeunt._]

SCENE II. A Room in Capulet’s House.

 Enter Juliet.

JULIET.
Gallop apace, you fiery-footed steeds,
Towards Phoebus’ lodging. Such a waggoner
As Phaeton would whip you to the west
And bring in cloudy night immediately.
Spread thy close curtain, love-performing night,
That runaway’s eyes may wink, and Romeo
Leap to these arms, untalk’d of and unseen.
Lovers can see to do their amorous rites
By their own beauties: or, if love be blind,
It best agrees with night. Come, civil night,
Thou sober-suited matron, all in black,
And learn me how to lose a winning match,
Play’d for a pair of stainless maidenhoods.
Hood my unmann’d blood, bating in my cheeks,
With thy black mantle, till strange love, grow bold,
Think true love acted simple modesty.
Come, night, come Romeo; come, thou day in night;
For thou wilt lie upon the wings of night
Whiter than new snow upon a raven’s back.
Come gentle night, come loving black-brow’d night,
Give me my Romeo, and when I shall die,
Take him and cut him out in little stars,
And he will make the face of heaven so fine
That all the world will be in love with night,
And pay no worship to the garish sun.
O, I have bought the mansion of a love,
But not possess’d it; and though I am sold,
Not yet enjoy’d. So tedious is this day
As is the night before some festival
To an impatient child that hath new robes
And may not wear them. O, here comes my Nurse,
And she brings news, and every tongue that speaks
But Romeo’s name speaks heavenly eloquence.

 Enter Nurse, with cords.

Now, Nurse, what news? What hast thou there?
The cords that Romeo bid thee fetch?

NURSE.
Ay, ay, the cords.

 [_Throws them down._]

JULIET.
Ay me, what news? Why dost thou wring thy hands?

NURSE.
Ah, well-a-day, he’s dead, he’s dead, he’s dead!
We are undone, lady, we are undone.
Alack the day, he’s gone, he’s kill’d, he’s dead.

JULIET.
Can heaven be so envious?

NURSE.
Romeo can,
Though heaven cannot. O Romeo, Romeo.
Who ever would have thought it? Romeo!

JULIET.
What devil art thou, that dost torment me thus?
This torture should be roar’d in dismal hell.
Hath Romeo slain himself? Say thou but Ay,
And that bare vowel I shall poison more
Than the death-darting eye of cockatrice.
I am not I if there be such an I;
Or those eyes shut that make thee answer Ay.
If he be slain, say Ay; or if not, No.
Brief sounds determine of my weal or woe.

NURSE.
I saw the wound, I saw it with mine eyes,
God save the mark!—here on his manly breast.
A piteous corse, a bloody piteous corse;
Pale, pale as ashes, all bedaub’d in blood,
All in gore-blood. I swounded at the sight.

JULIET.
O, break, my heart. Poor bankrout, break at once.
To prison, eyes; ne’er look on liberty.
Vile earth to earth resign; end motion here,
And thou and Romeo press one heavy bier.

NURSE.
O Tybalt, Tybalt, the best friend I had.
O courteous Tybalt, honest gentleman!
That ever I should live to see thee dead.

JULIET.
What storm is this that blows so contrary?
Is Romeo slaughter’d and is Tybalt dead?
My dearest cousin, and my dearer lord?
Then dreadful trumpet sound the general doom,
For who is living, if those two are gone?

NURSE.
Tybalt is gone, and Romeo banished,
Romeo that kill’d him, he is banished.

JULIET.
O God! Did Romeo’s hand shed Tybalt’s blood?

NURSE.
It did, it did; alas the day, it did.

JULIET.
O serpent heart, hid with a flowering face!
Did ever dragon keep so fair a cave?
Beautiful tyrant, fiend angelical,
Dove-feather’d raven, wolvish-ravening lamb!
Despised substance of divinest show!
Just opposite to what thou justly seem’st,
A damned saint, an honourable villain!
O nature, what hadst thou to do in hell
When thou didst bower the spirit of a fiend
In mortal paradise of such sweet flesh?
Was ever book containing such vile matter
So fairly bound? O, that deceit should dwell
In such a gorgeous palace.

NURSE.
There’s no trust,
No faith, no honesty in men. All perjur’d,
All forsworn, all naught, all dissemblers.
Ah, where’s my man? Give me some aqua vitae.
These griefs, these woes, these sorrows make me old.
Shame come to Romeo.

JULIET.
Blister’d be thy tongue
For such a wish! He was not born to shame.
Upon his brow shame is asham’d to sit;
For ’tis a throne where honour may be crown’d
Sole monarch of the universal earth.
O, what a beast was I to chide at him!

NURSE.
Will you speak well of him that kill’d your cousin?

JULIET.
Shall I speak ill of him that is my husband?
Ah, poor my lord, what tongue shall smooth thy name,
When I thy three-hours’ wife have mangled it?
But wherefore, villain, didst thou kill my cousin?
That villain cousin would have kill’d my husband.
Back, foolish tears, back to your native spring,
Your tributary drops belong to woe,
Which you mistaking offer up to joy.
My husband lives, that Tybalt would have slain,
And Tybalt’s dead, that would have slain my husband.
All this is comfort; wherefore weep I then?
Some word there was, worser than Tybalt’s death,
That murder’d me. I would forget it fain,
But O, it presses to my memory
Like damned guilty deeds to sinners’ minds.
Tybalt is dead, and Romeo banished.
That ‘banished,’ that one word ‘banished,’
Hath slain ten thousand Tybalts. Tybalt’s death
Was woe enough, if it had ended there.
Or if sour woe delights in fellowship,
And needly will be rank’d with other griefs,
Why follow’d not, when she said Tybalt’s dead,
Thy father or thy mother, nay or both,
Which modern lamentation might have mov’d?
But with a rear-ward following Tybalt’s death,
‘Romeo is banished’—to speak that word
Is father, mother, Tybalt, Romeo, Juliet,
All slain, all dead. Romeo is banished,
There is no end, no limit, measure, bound,
In that word’s death, no words can that woe sound.
Where is my father and my mother, Nurse?

NURSE.
Weeping and wailing over Tybalt’s corse.
Will you go to them? I will bring you thither.

JULIET.
Wash they his wounds with tears. Mine shall be spent,
When theirs are dry, for Romeo’s banishment.
Take up those cords. Poor ropes, you are beguil’d,
Both you and I; for Romeo is exil’d.
He made you for a highway to my bed,
But I, a maid, die maiden-widowed.
Come cords, come Nurse, I’ll to my wedding bed,
And death, not Romeo, take my maidenhead.

NURSE.
Hie to your chamber. I’ll find Romeo
To comfort you. I wot well where he is.
Hark ye, your Romeo will be here at night.
I’ll to him, he is hid at Lawrence’ cell.

JULIET.
O find him, give this ring to my true knight,
And bid him come to take his last farewell.

 [_Exeunt._]

SCENE III. Friar Lawrence’s cell.

 Enter Friar Lawrence.

FRIAR LAWRENCE.
Romeo, come forth; come forth, thou fearful man.
Affliction is enanmour’d of thy parts
And thou art wedded to calamity.

 Enter Romeo.

ROMEO.
Father, what news? What is the Prince’s doom?
What sorrow craves acquaintance at my hand,
That I yet know not?

FRIAR LAWRENCE.
Too familiar
Is my dear son with such sour company.
I bring thee tidings of the Prince’s doom.

ROMEO.
What less than doomsday is the Prince’s doom?

FRIAR LAWRENCE.
A gentler judgment vanish’d from his lips,
Not body’s death, but body’s banishment.

ROMEO.
Ha, banishment? Be merciful, say death;
For exile hath more terror in his look,
Much more than death. Do not say banishment.

FRIAR LAWRENCE.
Hence from Verona art thou banished.
Be patient, for the world is broad and wide.

ROMEO.
There is no world without Verona walls,
But purgatory, torture, hell itself.
Hence banished is banish’d from the world,
And world’s exile is death. Then banished
Is death misterm’d. Calling death banished,
Thou cutt’st my head off with a golden axe,
And smilest upon the stroke that murders me.

FRIAR LAWRENCE.
O deadly sin, O rude unthankfulness!
Thy fault our law calls death, but the kind Prince,
Taking thy part, hath brush’d aside the law,
And turn’d that black word death to banishment.
This is dear mercy, and thou see’st it not.

ROMEO.
’Tis torture, and not mercy. Heaven is here
Where Juliet lives, and every cat and dog,
And little mouse, every unworthy thing,
Live here in heaven and may look on her,
But Romeo may not. More validity,
More honourable state, more courtship lives
In carrion flies than Romeo. They may seize
On the white wonder of dear Juliet’s hand,
And steal immortal blessing from her lips,
Who, even in pure and vestal modesty
Still blush, as thinking their own kisses sin.
But Romeo may not, he is banished.
This may flies do, when I from this must fly.
They are free men but I am banished.
And say’st thou yet that exile is not death?
Hadst thou no poison mix’d, no sharp-ground knife,
No sudden mean of death, though ne’er so mean,
But banished to kill me? Banished?
O Friar, the damned use that word in hell.
Howling attends it. How hast thou the heart,
Being a divine, a ghostly confessor,
A sin-absolver, and my friend profess’d,
To mangle me with that word banished?

FRIAR LAWRENCE.
Thou fond mad man, hear me speak a little,

ROMEO.
O, thou wilt speak again of banishment.

FRIAR LAWRENCE.
I’ll give thee armour to keep off that word,
Adversity’s sweet milk, philosophy,
To comfort thee, though thou art banished.

ROMEO.
Yet banished? Hang up philosophy.
Unless philosophy can make a Juliet,
Displant a town, reverse a Prince’s doom,
It helps not, it prevails not, talk no more.

FRIAR LAWRENCE.
O, then I see that mad men have no ears.

ROMEO.
How should they, when that wise men have no eyes?

FRIAR LAWRENCE.
Let me dispute with thee of thy estate.

ROMEO.
Thou canst not speak of that thou dost not feel.
Wert thou as young as I, Juliet thy love,
An hour but married, Tybalt murdered,
Doting like me, and like me banished,
Then mightst thou speak, then mightst thou tear thy hair,
And fall upon the ground as I do now,
Taking the measure of an unmade grave.

 [_Knocking within._]

FRIAR LAWRENCE.
Arise; one knocks. Good Romeo, hide thyself.

ROMEO.
Not I, unless the breath of heartsick groans
Mist-like infold me from the search of eyes.

 [_Knocking._]

FRIAR LAWRENCE.
Hark, how they knock!—Who’s there?—Romeo, arise,
Thou wilt be taken.—Stay awhile.—Stand up.

 [_Knocking._]

Run to my study.—By-and-by.—God’s will,
What simpleness is this.—I come, I come.

 [_Knocking._]

Who knocks so hard? Whence come you, what’s your will?

NURSE.
[_Within._] Let me come in, and you shall know my errand.
I come from Lady Juliet.

FRIAR LAWRENCE.
Welcome then.

 Enter Nurse.

NURSE.
O holy Friar, O, tell me, holy Friar,
Where is my lady’s lord, where’s Romeo?

FRIAR LAWRENCE.
There on the ground, with his own tears made drunk.

NURSE.
O, he is even in my mistress’ case.
Just in her case! O woeful sympathy!
Piteous predicament. Even so lies she,
Blubbering and weeping, weeping and blubbering.
Stand up, stand up; stand, and you be a man.
For Juliet’s sake, for her sake, rise and stand.
Why should you fall into so deep an O?

ROMEO.
Nurse.

NURSE.
Ah sir, ah sir, death’s the end of all.

ROMEO.
Spakest thou of Juliet? How is it with her?
Doth not she think me an old murderer,
Now I have stain’d the childhood of our joy
With blood remov’d but little from her own?
Where is she? And how doth she? And what says
My conceal’d lady to our cancell’d love?

NURSE.
O, she says nothing, sir, but weeps and weeps;
And now falls on her bed, and then starts up,
And Tybalt calls, and then on Romeo cries,
And then down falls again.

ROMEO.
As if that name,
Shot from the deadly level of a gun,
Did murder her, as that name’s cursed hand
Murder’d her kinsman. O, tell me, Friar, tell me,
In what vile part of this anatomy
Doth my name lodge? Tell me, that I may sack
The hateful mansion.

 [_Drawing his sword._]

FRIAR LAWRENCE.
Hold thy desperate hand.
Art thou a man? Thy form cries out thou art.
Thy tears are womanish, thy wild acts denote
The unreasonable fury of a beast.
Unseemly woman in a seeming man,
And ill-beseeming beast in seeming both!
Thou hast amaz’d me. By my holy order,
I thought thy disposition better temper’d.
Hast thou slain Tybalt? Wilt thou slay thyself?
And slay thy lady, that in thy life lives,
By doing damned hate upon thyself?
Why rail’st thou on thy birth, the heaven and earth?
Since birth, and heaven and earth, all three do meet
In thee at once; which thou at once wouldst lose.
Fie, fie, thou sham’st thy shape, thy love, thy wit,
Which, like a usurer, abound’st in all,
And usest none in that true use indeed
Which should bedeck thy shape, thy love, thy wit.
Thy noble shape is but a form of wax,
Digressing from the valour of a man;
Thy dear love sworn but hollow perjury,
Killing that love which thou hast vow’d to cherish;
Thy wit, that ornament to shape and love,
Misshapen in the conduct of them both,
Like powder in a skilless soldier’s flask,
Is set afire by thine own ignorance,
And thou dismember’d with thine own defence.
What, rouse thee, man. Thy Juliet is alive,
For whose dear sake thou wast but lately dead.
There art thou happy. Tybalt would kill thee,
But thou slew’st Tybalt; there art thou happy.
The law that threaten’d death becomes thy friend,
And turns it to exile; there art thou happy.
A pack of blessings light upon thy back;
Happiness courts thee in her best array;
But like a misshaped and sullen wench,
Thou putt’st up thy Fortune and thy love.
Take heed, take heed, for such die miserable.
Go, get thee to thy love as was decreed,
Ascend her chamber, hence and comfort her.
But look thou stay not till the watch be set,
For then thou canst not pass to Mantua;
Where thou shalt live till we can find a time
To blaze your marriage, reconcile your friends,
Beg pardon of the Prince, and call thee back
With twenty hundred thousand times more joy
Than thou went’st forth in lamentation.
Go before, Nurse. Commend me to thy lady,
And bid her hasten all the house to bed,
Which heavy sorrow makes them apt unto.
Romeo is coming.

NURSE.
O Lord, I could have stay’d here all the night
To hear good counsel. O, what learning is!
My lord, I’ll tell my lady you will come.

ROMEO.
Do so, and bid my sweet prepare to chide.

NURSE.
Here sir, a ring she bid me give you, sir.
Hie you, make haste, for it grows very late.

 [_Exit._]

ROMEO.
How well my comfort is reviv’d by this.

FRIAR LAWRENCE.
Go hence, good night, and here stands all your state:
Either be gone before the watch be set,
Or by the break of day disguis’d from hence.
Sojourn in Mantua. I’ll find out your man,
And he shall signify from time to time
Every good hap to you that chances here.
Give me thy hand; ’tis late; farewell; good night.

ROMEO.
But that a joy past joy calls out on me,
It were a grief so brief to part with thee.
Farewell.

 [_Exeunt._]

SCENE IV. A Room in Capulet’s House.

 Enter Capulet, Lady Capulet and Paris.

CAPULET.
Things have fallen out, sir, so unluckily
That we have had no time to move our daughter.
Look you, she lov’d her kinsman Tybalt dearly,
And so did I. Well, we were born to die.
’Tis very late; she’ll not come down tonight.
I promise you, but for your company,
I would have been abed an hour ago.

PARIS.
These times of woe afford no tune to woo.
Madam, good night. Commend me to your daughter.

LADY CAPULET.
I will, and know her mind early tomorrow;
Tonight she’s mew’d up to her heaviness.

CAPULET.
Sir Paris, I will make a desperate tender
Of my child’s love. I think she will be rul’d
In all respects by me; nay more, I doubt it not.
Wife, go you to her ere you go to bed,
Acquaint her here of my son Paris’ love,
And bid her, mark you me, on Wednesday next,
But, soft, what day is this?

PARIS.
Monday, my lord.

CAPULET.
Monday! Ha, ha! Well, Wednesday is too soon,
A Thursday let it be; a Thursday, tell her,
She shall be married to this noble earl.
Will you be ready? Do you like this haste?
We’ll keep no great ado,—a friend or two,
For, hark you, Tybalt being slain so late,
It may be thought we held him carelessly,
Being our kinsman, if we revel much.
Therefore we’ll have some half a dozen friends,
And there an end. But what say you to Thursday?

PARIS.
My lord, I would that Thursday were tomorrow.

CAPULET.
Well, get you gone. A Thursday be it then.
Go you to Juliet ere you go to bed,
Prepare her, wife, against this wedding day.
Farewell, my lord.—Light to my chamber, ho!
Afore me, it is so very very late that we
May call it early by and by. Good night.

 [_Exeunt._]

SCENE V. An open Gallery to Juliet’s Chamber, overlooking the Garden.

 Enter Romeo and Juliet.

JULIET.
Wilt thou be gone? It is not yet near day.
It was the nightingale, and not the lark,
That pierc’d the fearful hollow of thine ear;
Nightly she sings on yond pomegranate tree.
Believe me, love, it was the nightingale.

ROMEO.
It was the lark, the herald of the morn,
No nightingale. Look, love, what envious streaks
Do lace the severing clouds in yonder east.
Night’s candles are burnt out, and jocund day
Stands tiptoe on the misty mountain tops.
I must be gone and live, or stay and die.

JULIET.
Yond light is not daylight, I know it, I.
It is some meteor that the sun exhales
To be to thee this night a torchbearer
And light thee on thy way to Mantua.
Therefore stay yet, thou need’st not to be gone.

ROMEO.
Let me be ta’en, let me be put to death,
I am content, so thou wilt have it so.
I’ll say yon grey is not the morning’s eye,
’Tis but the pale reflex of Cynthia’s brow.
Nor that is not the lark whose notes do beat
The vaulty heaven so high above our heads.
I have more care to stay than will to go.
Come, death, and welcome. Juliet wills it so.
How is’t, my soul? Let’s talk. It is not day.

JULIET.
It is, it is! Hie hence, be gone, away.
It is the lark that sings so out of tune,
Straining harsh discords and unpleasing sharps.
Some say the lark makes sweet division;
This doth not so, for she divideth us.
Some say the lark and loathed toad change eyes.
O, now I would they had chang’d voices too,
Since arm from arm that voice doth us affray,
Hunting thee hence with hunt’s-up to the day.
O now be gone, more light and light it grows.

ROMEO.
More light and light, more dark and dark our woes.

 Enter Nurse.

NURSE.
Madam.

JULIET.
Nurse?

NURSE.
Your lady mother is coming to your chamber.
The day is broke, be wary, look about.

 [_Exit._]

JULIET.
Then, window, let day in, and let life out.

ROMEO.
Farewell, farewell, one kiss, and I’ll descend.

 [_Descends._]

JULIET.
Art thou gone so? Love, lord, ay husband, friend,
I must hear from thee every day in the hour,
For in a minute there are many days.
O, by this count I shall be much in years
Ere I again behold my Romeo.

ROMEO.
Farewell!
I will omit no opportunity
That may convey my greetings, love, to thee.

JULIET.
O thinkest thou we shall ever meet again?

ROMEO.
I doubt it not, and all these woes shall serve
For sweet discourses in our time to come.

JULIET.
O God! I have an ill-divining soul!
Methinks I see thee, now thou art so low,
As one dead in the bottom of a tomb.
Either my eyesight fails, or thou look’st pale.

ROMEO.
And trust me, love, in my eye so do you.
Dry sorrow drinks our blood. Adieu, adieu.

 [_Exit below._]

JULIET.
O Fortune, Fortune! All men call thee fickle,
If thou art fickle, what dost thou with him
That is renown’d for faith? Be fickle, Fortune;
For then, I hope thou wilt not keep him long
But send him back.

LADY CAPULET.
[_Within._] Ho, daughter, are you up?

JULIET.
Who is’t that calls? Is it my lady mother?
Is she not down so late, or up so early?
What unaccustom’d cause procures her hither?

 Enter Lady Capulet.

LADY CAPULET.
Why, how now, Juliet?

JULIET.
Madam, I am not well.

LADY CAPULET.
Evermore weeping for your cousin’s death?
What, wilt thou wash him from his grave with tears?
And if thou couldst, thou couldst not make him live.
Therefore have done: some grief shows much of love,
But much of grief shows still some want of wit.

JULIET.
Yet let me weep for such a feeling loss.

LADY CAPULET.
So shall you feel the loss, but not the friend
Which you weep for.

JULIET.
Feeling so the loss,
I cannot choose but ever weep the friend.

LADY CAPULET.
Well, girl, thou weep’st not so much for his death
As that the villain lives which slaughter’d him.

JULIET.
What villain, madam?

LADY CAPULET.
That same villain Romeo.

JULIET.
Villain and he be many miles asunder.
God pardon him. I do, with all my heart.
And yet no man like he doth grieve my heart.

LADY CAPULET.
That is because the traitor murderer lives.

JULIET.
Ay madam, from the reach of these my hands.
Would none but I might venge my cousin’s death.

LADY CAPULET.
We will have vengeance for it, fear thou not.
Then weep no more. I’ll send to one in Mantua,
Where that same banish’d runagate doth live,
Shall give him such an unaccustom’d dram
That he shall soon keep Tybalt company:
And then I hope thou wilt be satisfied.

JULIET.
Indeed I never shall be satisfied
With Romeo till I behold him—dead—
Is my poor heart so for a kinsman vex’d.
Madam, if you could find out but a man
To bear a poison, I would temper it,
That Romeo should upon receipt thereof,
Soon sleep in quiet. O, how my heart abhors
To hear him nam’d, and cannot come to him,
To wreak the love I bore my cousin
Upon his body that hath slaughter’d him.

LADY CAPULET.
Find thou the means, and I’ll find such a man.
But now I’ll tell thee joyful tidings, girl.

JULIET.
And joy comes well in such a needy time.
What are they, I beseech your ladyship?

LADY CAPULET.
Well, well, thou hast a careful father, child;
One who to put thee from thy heaviness,
Hath sorted out a sudden day of joy,
That thou expects not, nor I look’d not for.

JULIET.
Madam, in happy time, what day is that?

LADY CAPULET.
Marry, my child, early next Thursday morn
The gallant, young, and noble gentleman,
The County Paris, at Saint Peter’s Church,
Shall happily make thee there a joyful bride.

JULIET.
Now by Saint Peter’s Church, and Peter too,
He shall not make me there a joyful bride.
I wonder at this haste, that I must wed
Ere he that should be husband comes to woo.
I pray you tell my lord and father, madam,
I will not marry yet; and when I do, I swear
It shall be Romeo, whom you know I hate,
Rather than Paris. These are news indeed.

LADY CAPULET.
Here comes your father, tell him so yourself,
And see how he will take it at your hands.

 Enter Capulet and Nurse.

CAPULET.
When the sun sets, the air doth drizzle dew;
But for the sunset of my brother’s son
It rains downright.
How now? A conduit, girl? What, still in tears?
Evermore showering? In one little body
Thou counterfeits a bark, a sea, a wind.
For still thy eyes, which I may call the sea,
Do ebb and flow with tears; the bark thy body is,
Sailing in this salt flood, the winds, thy sighs,
Who raging with thy tears and they with them,
Without a sudden calm will overset
Thy tempest-tossed body. How now, wife?
Have you deliver’d to her our decree?

LADY CAPULET.
Ay, sir; but she will none, she gives you thanks.
I would the fool were married to her grave.

CAPULET.
Soft. Take me with you, take me with you, wife.
How, will she none? Doth she not give us thanks?
Is she not proud? Doth she not count her blest,
Unworthy as she is, that we have wrought
So worthy a gentleman to be her bridegroom?

JULIET.
Not proud you have, but thankful that you have.
Proud can I never be of what I hate;
But thankful even for hate that is meant love.

CAPULET.
How now, how now, chopp’d logic? What is this?
Proud, and, I thank you, and I thank you not;
And yet not proud. Mistress minion you,
Thank me no thankings, nor proud me no prouds,
But fettle your fine joints ’gainst Thursday next
To go with Paris to Saint Peter’s Church,
Or I will drag thee on a hurdle thither.
Out, you green-sickness carrion! Out, you baggage!
You tallow-face!

LADY CAPULET.
Fie, fie! What, are you mad?

JULIET.
Good father, I beseech you on my knees,
Hear me with patience but to speak a word.

CAPULET.
Hang thee young baggage, disobedient wretch!
I tell thee what,—get thee to church a Thursday,
Or never after look me in the face.
Speak not, reply not, do not answer me.
My fingers itch. Wife, we scarce thought us blest
That God had lent us but this only child;
But now I see this one is one too much,
And that we have a curse in having her.
Out on her, hilding.

NURSE.
God in heaven bless her.
You are to blame, my lord, to rate her so.

CAPULET.
And why, my lady wisdom? Hold your tongue,
Good prudence; smatter with your gossips, go.

NURSE.
I speak no treason.

CAPULET.
O God ye good-en!

NURSE.
May not one speak?

CAPULET.
Peace, you mumbling fool!
Utter your gravity o’er a gossip’s bowl,
For here we need it not.

LADY CAPULET.
You are too hot.

CAPULET.
God’s bread, it makes me mad!
Day, night, hour, ride, time, work, play,
Alone, in company, still my care hath been
To have her match’d, and having now provided
A gentleman of noble parentage,
Of fair demesnes, youthful, and nobly allied,
Stuff’d, as they say, with honourable parts,
Proportion’d as one’s thought would wish a man,
And then to have a wretched puling fool,
A whining mammet, in her fortune’s tender,
To answer, ‘I’ll not wed, I cannot love,
I am too young, I pray you pardon me.’
But, and you will not wed, I’ll pardon you.
Graze where you will, you shall not house with me.
Look to’t, think on’t, I do not use to jest.
Thursday is near; lay hand on heart, advise.
And you be mine, I’ll give you to my friend;
And you be not, hang, beg, starve, die in the streets,
For by my soul, I’ll ne’er acknowledge thee,
Nor what is mine shall never do thee good.
Trust to’t, bethink you, I’ll not be forsworn.

 [_Exit._]

JULIET.
Is there no pity sitting in the clouds,
That sees into the bottom of my grief?
O sweet my mother, cast me not away,
Delay this marriage for a month, a week,
Or, if you do not, make the bridal bed
In that dim monument where Tybalt lies.

LADY CAPULET.
Talk not to me, for I’ll not speak a word.
Do as thou wilt, for I have done with thee.

 [_Exit._]

JULIET.
O God! O Nurse, how shall this be prevented?
My husband is on earth, my faith in heaven.
How shall that faith return again to earth,
Unless that husband send it me from heaven
By leaving earth? Comfort me, counsel me.
Alack, alack, that heaven should practise stratagems
Upon so soft a subject as myself.
What say’st thou? Hast thou not a word of joy?
Some comfort, Nurse.

NURSE.
Faith, here it is.
Romeo is banished; and all the world to nothing
That he dares ne’er come back to challenge you.
Or if he do, it needs must be by stealth.
Then, since the case so stands as now it doth,
I think it best you married with the County.
O, he’s a lovely gentleman.
Romeo’s a dishclout to him. An eagle, madam,
Hath not so green, so quick, so fair an eye
As Paris hath. Beshrew my very heart,
I think you are happy in this second match,
For it excels your first: or if it did not,
Your first is dead, or ’twere as good he were,
As living here and you no use of him.

JULIET.
Speakest thou from thy heart?

NURSE.
And from my soul too,
Or else beshrew them both.

JULIET.
Amen.

NURSE.
What?

JULIET.
Well, thou hast comforted me marvellous much.
Go in, and tell my lady I am gone,
Having displeas’d my father, to Lawrence’ cell,
To make confession and to be absolv’d.

NURSE.
Marry, I will; and this is wisely done.

 [_Exit._]

JULIET.
Ancient damnation! O most wicked fiend!
Is it more sin to wish me thus forsworn,
Or to dispraise my lord with that same tongue
Which she hath prais’d him with above compare
So many thousand times? Go, counsellor.
Thou and my bosom henceforth shall be twain.
I’ll to the Friar to know his remedy.
If all else fail, myself have power to die.

 [_Exit._]
