---
title: "Romeo and Juliet - Act II"
author: "William Shakespeare"
description: "Act II of Romeo and Juliet."
categories: [Literature, Classic]
format:
  html:
    page-layout: article
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 300px
    reference-location: margin
    citation-location: margin
---

# Act II

Enter Chorus.

CHORUS.
Now old desire doth in his deathbed lie,
And young affection gapes to be his heir;
That fair for which love groan’d for and would die,
With tender Juliet match’d, is now not fair.
Now Romeo is belov’d, and loves again,
Alike bewitched by the charm of looks;
But to his foe suppos’d he must complain,
And she steal love’s sweet bait from fearful hooks:
Being held a foe, he may not have access
To breathe such vows as lovers use to swear;
And she as much in love, her means much less
To meet her new beloved anywhere.
But passion lends them power, time means, to meet,
Tempering extremities with extreme sweet.

 [_Exit._]

SCENE I. An open place adjoining Capulet’s Garden.

 Enter Romeo.

ROMEO.
Can I go forward when my heart is here?
Turn back, dull earth, and find thy centre out.

 [_He climbs the wall and leaps down within it._]

 Enter Benvolio and Mercutio.

BENVOLIO.
Romeo! My cousin Romeo! Romeo!

MERCUTIO.
He is wise,
And on my life hath stol’n him home to bed.

BENVOLIO.
He ran this way, and leap’d this orchard wall:
Call, good Mercutio.

MERCUTIO.
Nay, I’ll conjure too.
Romeo! Humours! Madman! Passion! Lover!
Appear thou in the likeness of a sigh,
Speak but one rhyme, and I am satisfied;
Cry but ‘Ah me!’ Pronounce but Love and dove;
Speak to my gossip Venus one fair word,
One nickname for her purblind son and heir,
Young Abraham Cupid, he that shot so trim
When King Cophetua lov’d the beggar-maid.
He heareth not, he stirreth not, he moveth not;
The ape is dead, and I must conjure him.
I conjure thee by Rosaline’s bright eyes,
By her high forehead and her scarlet lip,
By her fine foot, straight leg, and quivering thigh,
And the demesnes that there adjacent lie,
That in thy likeness thou appear to us.

BENVOLIO.
An if he hear thee, thou wilt anger him.

MERCUTIO.
This cannot anger him. ’Twould anger him
To raise a spirit in his mistress’ circle,
Of some strange nature, letting it there stand
Till she had laid it, and conjur’d it down;
That were some spite. My invocation
Is fair and honest, and, in his mistress’ name,
I conjure only but to raise up him.

BENVOLIO.
Come, he hath hid himself among these trees
To be consorted with the humorous night.
Blind is his love, and best befits the dark.

MERCUTIO.
If love be blind, love cannot hit the mark.
Now will he sit under a medlar tree,
And wish his mistress were that kind of fruit
As maids call medlars when they laugh alone.
O Romeo, that she were, O that she were
An open-arse and thou a poperin pear!
Romeo, good night. I’ll to my truckle-bed.
This field-bed is too cold for me to sleep.
Come, shall we go?

BENVOLIO.
Go then; for ’tis in vain
To seek him here that means not to be found.

 [_Exeunt._]

SCENE II. Capulet’s Garden.

 Enter Romeo.

ROMEO.
He jests at scars that never felt a wound.

 Juliet appears above at a window.

But soft, what light through yonder window breaks?
It is the east, and Juliet is the sun!
Arise fair sun and kill the envious moon,
Who is already sick and pale with grief,
That thou her maid art far more fair than she.
Be not her maid since she is envious;
Her vestal livery is but sick and green,
And none but fools do wear it; cast it off.
It is my lady, O it is my love!
O, that she knew she were!
She speaks, yet she says nothing. What of that?
Her eye discourses, I will answer it.
I am too bold, ’tis not to me she speaks.
Two of the fairest stars in all the heaven,
Having some business, do entreat her eyes
To twinkle in their spheres till they return.
What if her eyes were there, they in her head?
The brightness of her cheek would shame those stars,
As daylight doth a lamp; her eyes in heaven
Would through the airy region stream so bright
That birds would sing and think it were not night.
See how she leans her cheek upon her hand.
O that I were a glove upon that hand,
That I might touch that cheek.

JULIET.
Ay me.

ROMEO.
She speaks.
O speak again bright angel, for thou art
As glorious to this night, being o’er my head,
As is a winged messenger of heaven
Unto the white-upturned wondering eyes
Of mortals that fall back to gaze on him
When he bestrides the lazy-puffing clouds
And sails upon the bosom of the air.

JULIET.
O Romeo, Romeo, wherefore art thou Romeo?
Deny thy father and refuse thy name.
Or if thou wilt not, be but sworn my love,
And I’ll no longer be a Capulet.

ROMEO.
[_Aside._] Shall I hear more, or shall I speak at this?

JULIET.
’Tis but thy name that is my enemy;
Thou art thyself, though not a Montague.
What’s Montague? It is nor hand nor foot,
Nor arm, nor face, nor any other part
Belonging to a man. O be some other name.
What’s in a name? That which we call a rose
By any other name would smell as sweet;
So Romeo would, were he not Romeo call’d,
Retain that dear perfection which he owes
Without that title. Romeo, doff thy name,
And for thy name, which is no part of thee,
Take all myself.

ROMEO.
I take thee at thy word.
Call me but love, and I’ll be new baptis’d;
Henceforth I never will be Romeo.

JULIET.
What man art thou that, thus bescreen’d in night
So stumblest on my counsel?

ROMEO.
By a name
I know not how to tell thee who I am:
My name, dear saint, is hateful to myself,
Because it is an enemy to thee.
Had I it written, I would tear the word.

JULIET.
My ears have yet not drunk a hundred words
Of thy tongue’s utterance, yet I know the sound.
Art thou not Romeo, and a Montague?

ROMEO.
Neither, fair maid, if either thee dislike.

JULIET.
How cam’st thou hither, tell me, and wherefore?
The orchard walls are high and hard to climb,
And the place death, considering who thou art,
If any of my kinsmen find thee here.

ROMEO.
With love’s light wings did I o’erperch these walls,
For stony limits cannot hold love out,
And what love can do, that dares love attempt:
Therefore thy kinsmen are no stop to me.

JULIET.
If they do see thee, they will murder thee.

ROMEO.
Alack, there lies more peril in thine eye
Than twenty of their swords. Look thou but sweet,
And I am proof against their enmity.

JULIET.
I would not for the world they saw thee here.

ROMEO.
I have night’s cloak to hide me from their eyes,
And but thou love me, let them find me here.
My life were better ended by their hate
Than death prorogued, wanting of thy love.

JULIET.
By whose direction found’st thou out this place?

ROMEO.
By love, that first did prompt me to enquire;
He lent me counsel, and I lent him eyes.
I am no pilot; yet wert thou as far
As that vast shore wash’d with the farthest sea,
I should adventure for such merchandise.

JULIET.
Thou knowest the mask of night is on my face,
Else would a maiden blush bepaint my cheek
For that which thou hast heard me speak tonight.
Fain would I dwell on form, fain, fain deny
What I have spoke; but farewell compliment.
Dost thou love me? I know thou wilt say Ay,
And I will take thy word. Yet, if thou swear’st,
Thou mayst prove false. At lovers’ perjuries,
They say Jove laughs. O gentle Romeo,
If thou dost love, pronounce it faithfully.
Or if thou thinkest I am too quickly won,
I’ll frown and be perverse, and say thee nay,
So thou wilt woo. But else, not for the world.
In truth, fair Montague, I am too fond;
And therefore thou mayst think my ’haviour light:
But trust me, gentleman, I’ll prove more true
Than those that have more cunning to be strange.
I should have been more strange, I must confess,
But that thou overheard’st, ere I was ’ware,
My true-love passion; therefore pardon me,
And not impute this yielding to light love,
Which the dark night hath so discovered.

ROMEO.
Lady, by yonder blessed moon I vow,
That tips with silver all these fruit-tree tops,—

JULIET.
O swear not by the moon, th’inconstant moon,
That monthly changes in her circled orb,
Lest that thy love prove likewise variable.

ROMEO.
What shall I swear by?

JULIET.
Do not swear at all.
Or if thou wilt, swear by thy gracious self,
Which is the god of my idolatry,
And I’ll believe thee.

ROMEO.
If my heart’s dear love,—

JULIET.
Well, do not swear. Although I joy in thee,
I have no joy of this contract tonight;
It is too rash, too unadvis’d, too sudden,
Too like the lightning, which doth cease to be
Ere one can say “It lightens.” Sweet, good night.
This bud of love, by summer’s ripening breath,
May prove a beauteous flower when next we meet.
Good night, good night. As sweet repose and rest
Come to thy heart as that within my breast.

ROMEO.
O wilt thou leave me so unsatisfied?

JULIET.
What satisfaction canst thou have tonight?

ROMEO.
Th’exchange of thy love’s faithful vow for mine.

JULIET.
I gave thee mine before thou didst request it;
And yet I would it were to give again.

ROMEO.
Would’st thou withdraw it? For what purpose, love?

JULIET.
But to be frank and give it thee again.
And yet I wish but for the thing I have;
My bounty is as boundless as the sea,
My love as deep; the more I give to thee,
The more I have, for both are infinite.
I hear some noise within. Dear love, adieu.
[_Nurse calls within._]
Anon, good Nurse!—Sweet Montague be true.
Stay but a little, I will come again.

 [_Exit._]

ROMEO.
O blessed, blessed night. I am afeard,
Being in night, all this is but a dream,
Too flattering sweet to be substantial.

 Enter Juliet above.

JULIET.
Three words, dear Romeo, and good night indeed.
If that thy bent of love be honourable,
Thy purpose marriage, send me word tomorrow,
By one that I’ll procure to come to thee,
Where and what time thou wilt perform the rite,
And all my fortunes at thy foot I’ll lay
And follow thee my lord throughout the world.

NURSE.
[_Within._] Madam.

JULIET.
I come, anon.— But if thou meanest not well,
I do beseech thee,—

NURSE.
[_Within._] Madam.

JULIET.
By and by I come—
To cease thy strife and leave me to my grief.
Tomorrow will I send.

ROMEO.
So thrive my soul,—

JULIET.
A thousand times good night.

 [_Exit._]

ROMEO.
A thousand times the worse, to want thy light.
Love goes toward love as schoolboys from their books,
But love from love, towards school with heavy looks.

 [_Retiring slowly._]

 Re-enter Juliet, above.

JULIET.
Hist! Romeo, hist! O for a falconer’s voice
To lure this tassel-gentle back again.
Bondage is hoarse and may not speak aloud,
Else would I tear the cave where Echo lies,
And make her airy tongue more hoarse than mine
With repetition of my Romeo’s name.

ROMEO.
It is my soul that calls upon my name.
How silver-sweet sound lovers’ tongues by night,
Like softest music to attending ears.

JULIET.
Romeo.

ROMEO.
My dear?

JULIET.
What o’clock tomorrow
Shall I send to thee?

ROMEO.
By the hour of nine.

JULIET.
I will not fail. ’Tis twenty years till then.
I have forgot why I did call thee back.

ROMEO.
Let me stand here till thou remember it.

JULIET.
I shall forget, to have thee still stand there,
Remembering how I love thy company.

ROMEO.
And I’ll still stay, to have thee still forget,
Forgetting any other home but this.

JULIET.
’Tis almost morning; I would have thee gone,
And yet no farther than a wanton’s bird,
That lets it hop a little from her hand,
Like a poor prisoner in his twisted gyves,
And with a silk thread plucks it back again,
So loving-jealous of his liberty.

ROMEO.
I would I were thy bird.

JULIET.
Sweet, so would I:
Yet I should kill thee with much cherishing.
Good night, good night. Parting is such sweet sorrow
That I shall say good night till it be morrow.

 [_Exit._]

ROMEO.
Sleep dwell upon thine eyes, peace in thy breast.
Would I were sleep and peace, so sweet to rest.
Hence will I to my ghostly Sire’s cell,
His help to crave and my dear hap to tell.

 [_Exit._]

SCENE III. Friar Lawrence’s Cell.

 Enter Friar Lawrence with a basket.

FRIAR LAWRENCE.
The grey-ey’d morn smiles on the frowning night,
Chequering the eastern clouds with streaks of light;
And fleckled darkness like a drunkard reels
From forth day’s pathway, made by Titan’s fiery wheels
Now, ere the sun advance his burning eye,
The day to cheer, and night’s dank dew to dry,
I must upfill this osier cage of ours
With baleful weeds and precious-juiced flowers.
The earth that’s nature’s mother, is her tomb;
What is her burying grave, that is her womb:
And from her womb children of divers kind
We sucking on her natural bosom find.
Many for many virtues excellent,
None but for some, and yet all different.
O, mickle is the powerful grace that lies
In plants, herbs, stones, and their true qualities.
For naught so vile that on the earth doth live
But to the earth some special good doth give;
Nor aught so good but, strain’d from that fair use,
Revolts from true birth, stumbling on abuse.
Virtue itself turns vice being misapplied,
And vice sometime’s by action dignified.

 Enter Romeo.

Within the infant rind of this weak flower
Poison hath residence, and medicine power:
For this, being smelt, with that part cheers each part;
Being tasted, slays all senses with the heart.
Two such opposed kings encamp them still
In man as well as herbs,—grace and rude will;
And where the worser is predominant,
Full soon the canker death eats up that plant.

ROMEO.
Good morrow, father.

FRIAR LAWRENCE.
Benedicite!
What early tongue so sweet saluteth me?
Young son, it argues a distemper’d head
So soon to bid good morrow to thy bed.
Care keeps his watch in every old man’s eye,
And where care lodges sleep will never lie;
But where unbruised youth with unstuff’d brain
Doth couch his limbs, there golden sleep doth reign.
Therefore thy earliness doth me assure
Thou art uprous’d with some distemperature;
Or if not so, then here I hit it right,
Our Romeo hath not been in bed tonight.

ROMEO.
That last is true; the sweeter rest was mine.

FRIAR LAWRENCE.
God pardon sin. Wast thou with Rosaline?

ROMEO.
With Rosaline, my ghostly father? No.
I have forgot that name, and that name’s woe.

FRIAR LAWRENCE.
That’s my good son. But where hast thou been then?

ROMEO.
I’ll tell thee ere thou ask it me again.
I have been feasting with mine enemy,
Where on a sudden one hath wounded me
That’s by me wounded. Both our remedies
Within thy help and holy physic lies.
I bear no hatred, blessed man; for lo,
My intercession likewise steads my foe.

FRIAR LAWRENCE.
Be plain, good son, and homely in thy drift;
Riddling confession finds but riddling shrift.

ROMEO.
Then plainly know my heart’s dear love is set
On the fair daughter of rich Capulet.
As mine on hers, so hers is set on mine;
And all combin’d, save what thou must combine
By holy marriage. When, and where, and how
We met, we woo’d, and made exchange of vow,
I’ll tell thee as we pass; but this I pray,
That thou consent to marry us today.

FRIAR LAWRENCE.
Holy Saint Francis! What a change is here!
Is Rosaline, that thou didst love so dear,
So soon forsaken? Young men’s love then lies
Not truly in their hearts, but in their eyes.
Jesu Maria, what a deal of brine
Hath wash’d thy sallow cheeks for Rosaline!
How much salt water thrown away in waste,
To season love, that of it doth not taste.
The sun not yet thy sighs from heaven clears,
Thy old groans yet ring in mine ancient ears.
Lo here upon thy cheek the stain doth sit
Of an old tear that is not wash’d off yet.
If ere thou wast thyself, and these woes thine,
Thou and these woes were all for Rosaline,
And art thou chang’d? Pronounce this sentence then,
Women may fall, when there’s no strength in men.

ROMEO.
Thou chidd’st me oft for loving Rosaline.

FRIAR LAWRENCE.
For doting, not for loving, pupil mine.

ROMEO.
And bad’st me bury love.

FRIAR LAWRENCE.
Not in a grave
To lay one in, another out to have.

ROMEO.
I pray thee chide me not, her I love now
Doth grace for grace and love for love allow.
The other did not so.

FRIAR LAWRENCE.
O, she knew well
Thy love did read by rote, that could not spell.
But come young waverer, come go with me,
In one respect I’ll thy assistant be;
For this alliance may so happy prove,
To turn your households’ rancour to pure love.

ROMEO.
O let us hence; I stand on sudden haste.

FRIAR LAWRENCE.
Wisely and slow; they stumble that run fast.

 [_Exeunt._]

SCENE IV. A Street.

 Enter Benvolio and Mercutio.

MERCUTIO.
Where the devil should this Romeo be? Came he not home tonight?

BENVOLIO.
Not to his father’s; I spoke with his man.

MERCUTIO.
Why, that same pale hard-hearted wench, that Rosaline, torments him so
that he will sure run mad.

BENVOLIO.
Tybalt, the kinsman to old Capulet, hath sent a letter to his father’s
house.

MERCUTIO.
A challenge, on my life.

BENVOLIO.
Romeo will answer it.

MERCUTIO.
Any man that can write may answer a letter.

BENVOLIO.
Nay, he will answer the letter’s master, how he dares, being dared.

MERCUTIO.
Alas poor Romeo, he is already dead, stabbed with a white wench’s black
eye; run through the ear with a love song, the very pin of his heart
cleft with the blind bow-boy’s butt-shaft. And is he a man to encounter
Tybalt?

BENVOLIO.
Why, what is Tybalt?

MERCUTIO.
More than Prince of cats. O, he’s the courageous captain of
compliments. He fights as you sing prick-song, keeps time, distance,
and proportion. He rests his minim rest, one, two, and the third in
your bosom: the very butcher of a silk button, a duellist, a duellist;
a gentleman of the very first house, of the first and second cause. Ah,
the immortal passado, the punto reverso, the hay.

BENVOLIO.
The what?

MERCUTIO.
The pox of such antic lisping, affecting phantasies; these new tuners
of accent. By Jesu, a very good blade, a very tall man, a very good
whore. Why, is not this a lamentable thing, grandsire, that we should
be thus afflicted with these strange flies, these fashion-mongers,
these pardon-me’s, who stand so much on the new form that they cannot
sit at ease on the old bench? O their bones, their bones!

 Enter Romeo.

BENVOLIO.
Here comes Romeo, here comes Romeo!

MERCUTIO.
Without his roe, like a dried herring. O flesh, flesh, how art thou
fishified! Now is he for the numbers that Petrarch flowed in. Laura, to
his lady, was but a kitchen wench,—marry, she had a better love to
berhyme her: Dido a dowdy; Cleopatra a gypsy; Helen and Hero hildings
and harlots; Thisbe a grey eye or so, but not to the purpose. Signior
Romeo, bonjour! There’s a French salutation to your French slop. You
gave us the counterfeit fairly last night.

ROMEO.
Good morrow to you both. What counterfeit did I give you?

MERCUTIO.
The slip sir, the slip; can you not conceive?

ROMEO.
Pardon, good Mercutio, my business was great, and in such a case as
mine a man may strain courtesy.

MERCUTIO.
That’s as much as to say, such a case as yours constrains a man to bow
in the hams.

ROMEO.
Meaning, to curtsy.

MERCUTIO.
Thou hast most kindly hit it.

ROMEO.
A most courteous exposition.

MERCUTIO.
Nay, I am the very pink of courtesy.

ROMEO.
Pink for flower.

MERCUTIO.
Right.

ROMEO.
Why, then is my pump well flowered.

MERCUTIO.
Sure wit, follow me this jest now, till thou hast worn out thy pump,
that when the single sole of it is worn, the jest may remain after the
wearing, solely singular.

ROMEO.
O single-soled jest, solely singular for the singleness!

MERCUTIO.
Come between us, good Benvolio; my wits faint.

ROMEO.
Swits and spurs, swits and spurs; or I’ll cry a match.

MERCUTIO.
Nay, if thy wits run the wild-goose chase, I am done. For thou hast
more of the wild-goose in one of thy wits, than I am sure, I have in my
whole five. Was I with you there for the goose?

ROMEO.
Thou wast never with me for anything, when thou wast not there for the
goose.

MERCUTIO.
I will bite thee by the ear for that jest.

ROMEO.
Nay, good goose, bite not.

MERCUTIO.
Thy wit is a very bitter sweeting, it is a most sharp sauce.

ROMEO.
And is it not then well served in to a sweet goose?

MERCUTIO.
O here’s a wit of cheveril, that stretches from an inch narrow to an
ell broad.

ROMEO.
I stretch it out for that word broad, which added to the goose, proves
thee far and wide a broad goose.

MERCUTIO.
Why, is not this better now than groaning for love? Now art thou
sociable, now art thou Romeo; now art thou what thou art, by art as
well as by nature. For this drivelling love is like a great natural,
that runs lolling up and down to hide his bauble in a hole.

BENVOLIO.
Stop there, stop there.

MERCUTIO.
Thou desirest me to stop in my tale against the hair.

BENVOLIO.
Thou wouldst else have made thy tale large.

MERCUTIO.
O, thou art deceived; I would have made it short, for I was come to the
whole depth of my tale, and meant indeed to occupy the argument no
longer.

 Enter Nurse and Peter.

ROMEO.
Here’s goodly gear!
A sail, a sail!

MERCUTIO.
Two, two; a shirt and a smock.

NURSE.
Peter!

PETER.
Anon.

NURSE.
My fan, Peter.

MERCUTIO.
Good Peter, to hide her face; for her fan’s the fairer face.

NURSE.
God ye good morrow, gentlemen.

MERCUTIO.
God ye good-den, fair gentlewoman.

NURSE.
Is it good-den?

MERCUTIO.
’Tis no less, I tell ye; for the bawdy hand of the dial is now upon the
prick of noon.

NURSE.
Out upon you! What a man are you?

ROMEO.
One, gentlewoman, that God hath made for himself to mar.

NURSE.
By my troth, it is well said; for himself to mar, quoth a? Gentlemen,
can any of you tell me where I may find the young Romeo?

ROMEO.
I can tell you: but young Romeo will be older when you have found him
than he was when you sought him. I am the youngest of that name, for
fault of a worse.

NURSE.
You say well.

MERCUTIO.
Yea, is the worst well? Very well took, i’faith; wisely, wisely.

NURSE.
If you be he, sir, I desire some confidence with you.

BENVOLIO.
She will endite him to some supper.

MERCUTIO.
A bawd, a bawd, a bawd! So ho!

ROMEO.
What hast thou found?

MERCUTIO.
No hare, sir; unless a hare, sir, in a lenten pie, that is something
stale and hoar ere it be spent.
[_Sings._]
    An old hare hoar,
    And an old hare hoar,
  Is very good meat in Lent;
    But a hare that is hoar
    Is too much for a score
  When it hoars ere it be spent.
Romeo, will you come to your father’s? We’ll to dinner thither.

ROMEO.
I will follow you.

MERCUTIO.
Farewell, ancient lady; farewell, lady, lady, lady.

 [_Exeunt Mercutio and Benvolio._]

NURSE.
I pray you, sir, what saucy merchant was this that was so full of his
ropery?

ROMEO.
A gentleman, Nurse, that loves to hear himself talk, and will speak
more in a minute than he will stand to in a month.

NURSE.
And a speak anything against me, I’ll take him down, and a were lustier
than he is, and twenty such Jacks. And if I cannot, I’ll find those
that shall. Scurvy knave! I am none of his flirt-gills; I am none of
his skains-mates.—And thou must stand by too and suffer every knave to
use me at his pleasure!

PETER.
I saw no man use you at his pleasure; if I had, my weapon should
quickly have been out. I warrant you, I dare draw as soon as another
man, if I see occasion in a good quarrel, and the law on my side.

NURSE.
Now, afore God, I am so vexed that every part about me quivers. Scurvy
knave. Pray you, sir, a word: and as I told you, my young lady bid me
enquire you out; what she bade me say, I will keep to myself. But first
let me tell ye, if ye should lead her in a fool’s paradise, as they
say, it were a very gross kind of behaviour, as they say; for the
gentlewoman is young. And therefore, if you should deal double with
her, truly it were an ill thing to be offered to any gentlewoman, and
very weak dealing.

ROMEO. Nurse, commend me to thy lady and mistress. I protest unto
thee,—

NURSE.
Good heart, and i’faith I will tell her as much. Lord, Lord, she will
be a joyful woman.

ROMEO.
What wilt thou tell her, Nurse? Thou dost not mark me.

NURSE.
I will tell her, sir, that you do protest, which, as I take it, is a
gentlemanlike offer.

ROMEO.
Bid her devise
Some means to come to shrift this afternoon,
And there she shall at Friar Lawrence’ cell
Be shriv’d and married. Here is for thy pains.

NURSE.
No truly, sir; not a penny.

ROMEO.
Go to; I say you shall.

NURSE.
This afternoon, sir? Well, she shall be there.

ROMEO.
And stay, good Nurse, behind the abbey wall.
Within this hour my man shall be with thee,
And bring thee cords made like a tackled stair,
Which to the high topgallant of my joy
Must be my convoy in the secret night.
Farewell, be trusty, and I’ll quit thy pains;
Farewell; commend me to thy mistress.

NURSE.
Now God in heaven bless thee. Hark you, sir.

ROMEO.
What say’st thou, my dear Nurse?

NURSE.
Is your man secret? Did you ne’er hear say,
Two may keep counsel, putting one away?

ROMEO.
I warrant thee my man’s as true as steel.

NURSE.
Well, sir, my mistress is the sweetest lady. Lord, Lord! When ’twas a
little prating thing,—O, there is a nobleman in town, one Paris, that
would fain lay knife aboard; but she, good soul, had as lief see a
toad, a very toad, as see him. I anger her sometimes, and tell her that
Paris is the properer man, but I’ll warrant you, when I say so, she
looks as pale as any clout in the versal world. Doth not rosemary and
Romeo begin both with a letter?

ROMEO.
Ay, Nurse; what of that? Both with an R.

NURSE.
Ah, mocker! That’s the dog’s name. R is for the—no, I know it begins
with some other letter, and she hath the prettiest sententious of it,
of you and rosemary, that it would do you good to hear it.

ROMEO.
Commend me to thy lady.

NURSE.
Ay, a thousand times. Peter!

 [_Exit Romeo._]

PETER.
Anon.

NURSE.
Before and apace.

 [_Exeunt._]

SCENE V. Capulet’s Garden.

 Enter Juliet.

JULIET.
The clock struck nine when I did send the Nurse,
In half an hour she promised to return.
Perchance she cannot meet him. That’s not so.
O, she is lame. Love’s heralds should be thoughts,
Which ten times faster glides than the sun’s beams,
Driving back shadows over lowering hills:
Therefore do nimble-pinion’d doves draw love,
And therefore hath the wind-swift Cupid wings.
Now is the sun upon the highmost hill
Of this day’s journey, and from nine till twelve
Is three long hours, yet she is not come.
Had she affections and warm youthful blood,
She’d be as swift in motion as a ball;
My words would bandy her to my sweet love,
And his to me.
But old folks, many feign as they were dead;
Unwieldy, slow, heavy and pale as lead.

 Enter Nurse and Peter.

O God, she comes. O honey Nurse, what news?
Hast thou met with him? Send thy man away.

NURSE.
Peter, stay at the gate.

 [_Exit Peter._]

JULIET.
Now, good sweet Nurse,—O Lord, why look’st thou sad?
Though news be sad, yet tell them merrily;
If good, thou sham’st the music of sweet news
By playing it to me with so sour a face.

NURSE.
I am aweary, give me leave awhile;
Fie, how my bones ache! What a jaunt have I had!

JULIET.
I would thou hadst my bones, and I thy news:
Nay come, I pray thee speak; good, good Nurse, speak.

NURSE.
Jesu, what haste? Can you not stay a while? Do you not see that I am
out of breath?

JULIET.
How art thou out of breath, when thou hast breath
To say to me that thou art out of breath?
The excuse that thou dost make in this delay
Is longer than the tale thou dost excuse.
Is thy news good or bad? Answer to that;
Say either, and I’ll stay the circumstance.
Let me be satisfied, is’t good or bad?

NURSE.
Well, you have made a simple choice; you know not how to choose a man.
Romeo? No, not he. Though his face be better than any man’s, yet his
leg excels all men’s, and for a hand and a foot, and a body, though
they be not to be talked on, yet they are past compare. He is not the
flower of courtesy, but I’ll warrant him as gentle as a lamb. Go thy
ways, wench, serve God. What, have you dined at home?

JULIET.
No, no. But all this did I know before.
What says he of our marriage? What of that?

NURSE.
Lord, how my head aches! What a head have I!
It beats as it would fall in twenty pieces.
My back o’ t’other side,—O my back, my back!
Beshrew your heart for sending me about
To catch my death with jauncing up and down.

JULIET.
I’faith, I am sorry that thou art not well.
Sweet, sweet, sweet Nurse, tell me, what says my love?

NURSE.
Your love says like an honest gentleman,
And a courteous, and a kind, and a handsome,
And I warrant a virtuous,—Where is your mother?

JULIET.
Where is my mother? Why, she is within.
Where should she be? How oddly thou repliest.
‘Your love says, like an honest gentleman,
‘Where is your mother?’

NURSE.
O God’s lady dear,
Are you so hot? Marry, come up, I trow.
Is this the poultice for my aching bones?
Henceforward do your messages yourself.

JULIET.
Here’s such a coil. Come, what says Romeo?

NURSE.
Have you got leave to go to shrift today?

JULIET.
I have.

NURSE.
Then hie you hence to Friar Lawrence’ cell;
There stays a husband to make you a wife.
Now comes the wanton blood up in your cheeks,
They’ll be in scarlet straight at any news.
Hie you to church. I must another way,
To fetch a ladder by the which your love
Must climb a bird’s nest soon when it is dark.
I am the drudge, and toil in your delight;
But you shall bear the burden soon at night.
Go. I’ll to dinner; hie you to the cell.

JULIET.
Hie to high fortune! Honest Nurse, farewell.

 [_Exeunt._]

SCENE VI. Friar Lawrence’s Cell.

 Enter Friar Lawrence and Romeo.

FRIAR LAWRENCE.
So smile the heavens upon this holy act
That after-hours with sorrow chide us not.

ROMEO.
Amen, amen, but come what sorrow can,
It cannot countervail the exchange of joy
That one short minute gives me in her sight.
Do thou but close our hands with holy words,
Then love-devouring death do what he dare,
It is enough I may but call her mine.

FRIAR LAWRENCE.
These violent delights have violent ends,
And in their triumph die; like fire and powder,
Which as they kiss consume. The sweetest honey
Is loathsome in his own deliciousness,
And in the taste confounds the appetite.
Therefore love moderately: long love doth so;
Too swift arrives as tardy as too slow.

 Enter Juliet.

Here comes the lady. O, so light a foot
Will ne’er wear out the everlasting flint.
A lover may bestride the gossamers
That idles in the wanton summer air
And yet not fall; so light is vanity.

JULIET.
Good even to my ghostly confessor.

FRIAR LAWRENCE.
Romeo shall thank thee, daughter, for us both.

JULIET.
As much to him, else is his thanks too much.

ROMEO.
Ah, Juliet, if the measure of thy joy
Be heap’d like mine, and that thy skill be more
To blazon it, then sweeten with thy breath
This neighbour air, and let rich music’s tongue
Unfold the imagin’d happiness that both
Receive in either by this dear encounter.

JULIET.
Conceit more rich in matter than in words,
Brags of his substance, not of ornament.
They are but beggars that can count their worth;
But my true love is grown to such excess,
I cannot sum up sum of half my wealth.

FRIAR LAWRENCE.
Come, come with me, and we will make short work,
For, by your leaves, you shall not stay alone
Till holy church incorporate two in one.

 [_Exeunt._]
