{
  "hash": "8f47e4df8721c89897ffa2764cf02500",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Great Constants: φ, e, π, and τ\"\nsubtitle: \"The Golden Ratio in Nature, the Cardinality of the Irrationals, Euler's Number, the Derivative Fixed Point, the Link Between e and π, Transcendental Constants in the Wild, and the Lost Art of the Slide Rule\"\nauthor: \"Igor Kan\"\ndate: \"2026-09-14\"\ncategories: [Mathematics, Number Theory, Analysis, Geometry, History of Mathematics, Applied Mathematics]\ndescription: \"A comprehensive first-principles treatment of the great mathematical constants: the golden ratio φ and how it arises in nature and phyllotaxis, the cardinality of rationals versus irrationals and transcendentals (Cantor, measure theory, normality), the definitions and ubiquity of π and τ, Euler's number e and its applications, a rigorous proof that e is the unique base whose exponential is its own derivative, the deep links between e and π (Euler's identity, the Gaussian integral, Stirling, near-integers), transcendental constants across unexpected fields, historical and modern techniques for bounding and computing them (Archimedes, Machin, Ramanujan, Chudnovsky, BBP, AGM, PSLQ), the properties and theorems of logarithms, and how to multiply and divide with a slide rule.\"\ntoc: true\ntoc-depth: 4\nnumber-sections: true\nformat:\n  html:\n    html-math-method: mathjax\n    code-fold: show\n    code-tools: true\njupyter: python3\n---\n\n::: {.callout-note appearance=\"simple\"}\n*\"Mathematics is the art of giving the same name to different things.\"*  \n— **Henri Poincaré**\n\nA handful of real numbers — $\\varphi$, $e$, $\\pi$, $\\tau$ — recur across geometry, analysis, physics, biology, statistics, and finance. This essay unifies their definitions, derivations, and appearances, and examines why \"most\" real numbers are irrational, why transcendentals dominate the continuum, and how human beings computed these constants long before silicon.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Companion Treatises in this Series\n- [Logarithms, Log Scales, and the Slide Rule](logarithms-log-scales-and-the-slide-rule.qmd)\n- [Axiomatic Set Theory, ZFC, Ordinals, Cardinals, and Paradoxes](axiomatic-set-theory-zfc-ordinals-cardinals-and-paradoxes.qmd)\n- [The Rational Line: Density, Enumeration, Cauchy Sequences, Dedekind Cuts, Metric Spaces, and Topology](rationals-density-enumeration-metric-spaces-and-topology.qmd)\n- [Algebraic and Transcendental Numbers: Field Extensions, Minimal Polynomials, and Transcendence Proofs](algebraic-and-transcendental-numbers-foundations-and-proofs.qmd)\n- [Real Numbers, Dedekind Cuts, and Topological Completeness](analysis-01-real-numbers-completeness.qmd)\n- [The Deep Structure of Numbers: From Decimals and Radicals to Unique Factorization and the Riemann Hypothesis](foundations-of-arithmetic-primes-radicals-and-the-riemann-hypothesis.qmd)\n- [The Architecture of Number Systems: Axiomatic Constructions, Cayley-Dickson Algebras, and Recursive Sequences](the-architecture-of-number-systems-constructions-cayley-dickson-and-recursion.qmd)\n- [Putnam and Olympiad Mathematical Physics Masterclass](putnam-and-olympiad-mathematical-physics-masterclass.qmd)\n:::\n\n---\n\n## 1. Introduction: The Constants That Structure Reality\n\nThe real line is overwhelmingly inhabited by numbers that no finite formula can name. Yet a tiny handful of constants — the **golden ratio** $\\varphi$, **Euler's number** $e$, **Archimedes' constant** $\\pi$, and its doubled sibling **$\\tau = 2\\pi$** — appear again and again, from the arrangement of seeds in a sunflower to the normalization constant of the Gaussian distribution, from the cooling of coffee to the geometry of spacetime.\n\nThis essay answers several overlapping questions:\n\n1. What is the golden ratio, exactly, and *how* does it arise in mathematics and in living systems?\n2. How many rationals, irrationals, and transcendental numbers are there? (Spoiler: almost all reals are transcendental.)\n3. What are $\\pi$, $\\tau$, and $e$ — and where do they hide?\n4. Why is $e$ *the* unique base for which the exponential function is its own derivative?\n5. How are $e$ and $\\pi$ secretly the same story?\n6. Which transcendental constants appear in unexpected places?\n7. How have mathematicians bounded and computed these constants, from Archimedes to the Chudnovsky brothers?\n8. What are the laws of logarithms — and how did a wooden stick exploit them to multiply?\n\nA central theme is the **density of the transcendental**. The continuum is not built mostly of comfortable fractions; it is built mostly of objects we can barely describe. The constants we *can* describe are the rare, luminous exceptions.\n\n---\n\n## 2. The Golden Ratio: The Most Irrational Number\n\n### 2.1 Definition and Algebraic Characterization\n\n::: {#def-golden-ratio}\n#### Definition 2.1 (Golden Ratio)\nThe **golden ratio** $\\varphi$ is the unique positive real number satisfying the self-similarity (or \"division in extreme and mean ratio\") relation:\n$$\n\\frac{a + b}{a} = \\frac{a}{b} = \\varphi, \\qquad a > b > 0.\n$$\nEquivalently, it is the unique positive solution of the quadratic\n$$\n\\varphi^2 = \\varphi + 1.\n$$\n:::\n\nSolving $\\varphi^2 - \\varphi - 1 = 0$:\n$$\n\\boxed{\\;\\varphi = \\frac{1 + \\sqrt{5}}{2} = 1.6180339887498948482\\ldots\\;}\n$$\n\nThe other root is the **conjugate** $\\psi = \\dfrac{1 - \\sqrt{5}}{2} = -\\dfrac{1}{\\varphi} = -0.6180339887\\ldots$\n\n### 2.2 Formulas and Identities\n\nThe golden ratio is governed by an unusually rich algebra:\n\n$$\n\\begin{aligned}\n\\varphi^2 &= \\varphi + 1, \\\\\n\\frac{1}{\\varphi} &= \\varphi - 1 = 0.6180339887\\ldots, \\\\\n\\varphi &= 1 + \\dfrac{1}{\\varphi} = 1 + \\cfrac{1}{1 + \\cfrac{1}{1 + \\cfrac{1}{1 + \\cdots}}}, \\\\\n\\varphi &= \\sqrt{1 + \\sqrt{1 + \\sqrt{1 + \\cdots}}}, \\\\\n\\varphi^{n} &= F_n \\varphi + F_{n-1}, \\\\\n\\varphi &= 2\\cos\\!\\left(\\frac{\\pi}{5}\\right) = 2\\cos 36^\\circ.\n\\end{aligned}\n$$\n\nThe two continued-fraction and nested-radical representations above are *self-referential*: they encode the fixed-point equation $\\varphi = 1 + 1/\\varphi$. This self-similarity is precisely what makes $\\varphi$ the **most irrational** of all irrational numbers — its continued fraction $[1; 1, 1, 1, \\ldots]$ uses the smallest possible partial quotients, so its convergents (the best rational approximations) approach it more slowly than for any other irrational.\n\n::: {.callout-note}\n**The \"most irrational\" number.** Rational approximation error is controlled by the *continued fraction* expansion. For a number $\\alpha = [a_0; a_1, a_2, \\ldots]$, the largest possible partial quotient $a_i = 1$ makes the denominators grow as slowly as possible. Since all $a_i = 1$ for $\\varphi$, it is the hardest number to approximate by rationals — the worst case of the Hurwitz bound $|\\alpha - p/q| < 1/(\\sqrt{5}\\,q^2)$.\n:::\n\n### 2.3 The Golden Ratio and the Fibonacci Numbers\n\nLet $F_0 = 0,\\ F_1 = 1,\\ F_{n+1} = F_n + F_{n-1}$. The ratios of consecutive Fibonacci numbers converge to $\\varphi$:\n$$\n\\lim_{n \\to \\infty} \\frac{F_{n+1}}{F_n} = \\varphi.\n$$\nThe exact formula is **Binet's formula**:\n$$\nF_n = \\frac{\\varphi^n - \\psi^n}{\\sqrt{5}}, \\qquad \\psi = \\frac{1 - \\sqrt{5}}{2}.\n$$\nBecause $|\\psi| < 1$, the term $\\psi^n \\to 0$, giving the striking approximation\n$$\nF_n \\approx \\frac{\\varphi^n}{\\sqrt{5}} \\quad (\\text{nearest integer}).\n$$\n\nThe continued fraction of $\\varphi$ has convergents exactly equal to ratios of Fibonacci numbers:\n$$\n1, \\frac{2}{1}, \\frac{3}{2}, \\frac{5}{3}, \\frac{8}{5}, \\frac{13}{8}, \\ldots \\longrightarrow \\varphi.\n$$\n\n### 2.4 The Golden Ratio in Geometry\n\n$\\varphi$ is woven into the regular pentagon. For a regular pentagon of side length $s$ and diagonal length $d$:\n$$\n\\frac{d}{s} = \\varphi.\n$$\nThe regular pentagon, pentagram, icosahedron, and dodecahedron all use $\\varphi$ as their characteristic ratio. A **golden rectangle** (sides in ratio $\\varphi:1$) has the property that removing a square leaves a smaller rectangle similar to the original — an infinite self-similar dissection that generates the **golden spiral** when quarter-circles are inscribed.\n\n```text\n        GOLDEN RECTANGLE SELF-SIMILARITY\n        ┌───────────────────────┬───────────┐\n        │                       │           │\n        │                       │   SQUARE  │\n        │                       │  (removed)│\n        │                       │           │\n        │       GOLDEN          ├───────────┤\n        │       RECTANGLE       │  SMALLER  │\n        │      (φ : 1)          │  GOLDEN   │\n        │                       │ RECTANGLE │\n        │                       │           │\n        └───────────────────────┴───────────┘\n   Removing a square from a φ-rectangle leaves a\n   φ-rectangle. Repeating forever traces a golden spiral.\n```\n\n### 2.5 How the Golden Ratio Arises in Nature\n\nThe most defensible and beautiful occurrence of $\\varphi$ in biology is **phyllotaxis** — the arrangement of leaves, seeds, and petals. Consider a plant that emits new primordia (leaf or seed buds) at a constant angular increment $\\theta$ from the previous one. What increment minimizes *shadowing* and packs seeds most efficiently?\n\nRepresent successive buds at angles $n\\theta \\pmod{2\\pi}$. The packing is optimal when $\\theta/2\\pi$ is irrational with the *worst* rational approximations — i.e., when it is related to $\\varphi$. The **golden angle** is\n$$\n\\theta_{\\text{gold}} = 2\\pi\\left(1 - \\frac{1}{\\varphi}\\right) = \\frac{2\\pi}{\\varphi^2} \\approx 2.399963\\ \\text{rad} \\approx 137.507764^\\circ.\n$$\nWhen a plant places successive seeds at $137.5^\\circ$ intervals, the resulting spiral parastichy numbers are consecutive Fibonacci numbers $(8, 13)$, $(13, 21)$, $(21, 34)$, etc. This is observed in:\n\n- **Sunflower heads** (spiral counts $34/55$ or $55/89$),\n- **Pinecones** ($8$ and $13$),\n- **Pineapples** ($8$, $13$, $21$),\n- **Romanesco broccoli** (self-similar logarithmic spirals),\n- **Aloe polyphylla** and many succulents.\n\n::: {.callout-warning}\n**Myth-busting.** The golden ratio is genuinely present in phyllotaxis, pentagonal symmetry, and certain optimal packing problems. It is **not** reliably present in the Great Pyramid, the Parthenon, the human navel, most seashells (the nautilus is a *logarithmic* spiral with a different growth ratio), galaxy arms, or the \"ideal face.\" Much \"golden ratio in nature\" writing is numerology retrofitted to measurements. Trust the mathematics; be skeptical of the mythology.\n:::\n\n### 2.6 Bridge: φ Is Algebraic, Not Transcendental\n\nBecause $\\varphi$ is a root of $x^2 - x - 1 = 0$, it is an **algebraic number of degree 2**. It is *irrational* (as $\\sqrt{5}$ is irrational) but emphatically **not transcendental**. This makes it an instructive contrast: $\\varphi$ is the epitome of a \"tame\" irrational — beautifully self-similar, but entirely describable by a finite polynomial. The transcendentals of Sections 5–8 are of a fundamentally wilder species.\n\n---\n\n## 3. Cardinality: Why Almost Every Real Number Is Irrational\n\n### 3.1 Countable Sets\n\n::: {#def-countable}\n#### Definition 3.1 (Countable)\nA set $S$ is **countable** if it is finite or if there exists a bijection $S \\to \\mathbb{N}$. Countably infinite sets all have the same cardinality, written $\\aleph_0$ (\"aleph-null\").\n:::\n\nThe surprise is that \"more\" apparent elements does not mean larger cardinality:\n\n$$\n|\\mathbb{N}| = |\\mathbb{Z}| = |\\mathbb{Q}| = \\aleph_0.\n$$\n\n**$\\mathbb{Q}$ is countable.** Enumerate rationals by a diagonal sweep over the grid of numerators and denominators, skipping non-reduced pairs:\n\n```text\n   q=1   q=2   q=3   q=4\n p=1  1/1 → 1/2   1/3 → 1/4\n          ↙    ↗     ↙\n p=2  2/1   2/2   2/3   2/4\n       ↓  ↗    ↙    ↗\n p=3  3/1   3/2   3/3   3/4\n          ↙    ↗\n p=4  4/1   4/2   4/3   4/4\n```\nA snake-like traversal visits every positive rational. Rationals are **dense** (between any two reals there is a rational) yet **countable**.\n\n### 3.2 Cantor's Diagonal Argument\n\n::: {#thm-uncountable-reals}\n#### Theorem 3.1 (Cantor, 1874)\nThe set of real numbers $\\mathbb{R}$ is **uncountable**; $|\\mathbb{R}| = 2^{\\aleph_0} = \\mathfrak{c}$, the **cardinality of the continuum**.\n:::\n\n*Proof.* It suffices to show $(0,1)$ is uncountable. Suppose, for contradiction, that we could list every real in $(0,1)$ as an infinite sequence of decimal expansions:\n$$\n\\begin{aligned}\nx_1 &= 0.d_{11}d_{12}d_{13}d_{14}\\ldots \\\\\nx_2 &= 0.d_{21}d_{22}d_{23}d_{24}\\ldots \\\\\nx_3 &= 0.d_{31}d_{32}d_{33}d_{34}\\ldots \\\\\n   &\\;\\;\\vdots\n\\end{aligned}\n$$\nConstruct a new number $y = 0.e_1 e_2 e_3 \\ldots$ by setting\n$$\ne_n = \\begin{cases} 1 & d_{nn} \\neq 1,\\\\ 2 & d_{nn} = 1. \\end{cases}\n$$\nThen $y$ differs from $x_n$ in the $n$-th decimal place for every $n$, so $y$ is in the list nowhere — contradicting the assumption that the list was complete. (Using digits $1,2$ avoids the $0.4999\\ldots = 0.5000\\ldots$ ambiguity.) Hence no such list exists. $\\blacksquare$\n\n### 3.3 Consequences: The Irrational and Transcendental Majority\n\nCombine the pieces:\n\n1. **$\\mathbb{Q}$ is countable** ($\\aleph_0$).\n2. **$\\mathbb{R}$ is uncountable** ($\\mathfrak{c}$).\n3. Therefore the **irrationals** $\\mathbb{R} \\setminus \\mathbb{Q}$ are **uncountable**: removing a countable set from an uncountable set leaves an uncountable set.\n\nEven more strikingly, let $\\overline{\\mathbb{Q}}$ be the algebraic numbers (roots of polynomials with rational coefficients). Since each polynomial has finitely many roots and there are countably many polynomials with rational coefficients, $\\overline{\\mathbb{Q}}$ is countable. Hence:\n\n$$\n\\boxed{\\;\\text{The transcendental numbers } \\mathbb{R} \\setminus \\overline{\\mathbb{Q}} \\text{ are uncountable, with cardinality } \\mathfrak{c}.\\;}\n$$\n\nIntuitively: **almost every real number is transcendental**, yet proving that any *particular natural constant* is transcendental is a monumental achievement (Hermite, Lindemann, Gelfond). This is the \"transcendental paradox.\"\n\n### 3.4 The Measure-Theoretic View\n\nCardinality is one lens; **Lebesgue measure** is another. On any interval $[a,b]$:\n\n- $\\mathbb{Q} \\cap [a,b]$ has **Lebesgue measure zero** (it is a countable union of points). So the rationals occupy \"no length\" at all.\n- The algebraic numbers likewise have measure zero, being countable.\n- Therefore the **transcendentals have full measure**: on $[0,1]$, the set of transcendentals has measure $1$.\n\nSo the rationals are simultaneously **dense** (in every interval) and **negligible** (measure zero). Density describes *where*; measure describes *how much*.\n\n```text\n        THE REAL LINE [0, 1]\n   ┌────────────────────────────────────────────┐\n   │••• •  •   •     •        •          •      │  ← Q: dense but measure 0\n   │                                            │\n   │                                            │\n   │████████████████████████████████████████████│  ← Transcendentals: measure 1\n   │                                            │\n   └────────────────────────────────────────────┘\n   Intuition: randomly throw a dart at [0,1].\n   P(hitting a rational) = 0.  P(transcendental) = 1.\n```\n\n### 3.5 Normality, and the Limits of Our Knowledge\n\nA number is **normal** in base $b$ if every finite digit string occurs with the expected asymptotic frequency. **Borel's theorem (1909)** states that almost every real number is normal — a measure-theoretic statement. And yet:\n\n- We do not know whether $\\pi$, $e$, $\\sqrt{2}$, or $\\ln 2$ are normal in base 10.\n- $\\varphi$'s decimal digits are believed normal but unproven.\n- The only \"natural\" numbers *proven* normal tend to be constructed ad hoc, e.g. **Champernowne's constant** $0.12345678910111213\\ldots$ and the **Copeland–Erdős constant** $0.235711131719\\ldots$ (concatenation of primes).\n\nThis gap — between what is true of \"almost all\" numbers and what we can prove about any specific one — is one of the deepest themes of this essay.\n\n---\n\n## 4. π and τ: The Circle Constants\n\n### 4.1 Definitions\n\n::: {#def-pi}\n#### Definition 4.1 (Archimedes' Constant)\nGeometrically, $\\pi$ is the ratio of a circle's circumference to its diameter:\n$$\n\\pi = \\frac{C}{d} = \\frac{C}{2r}.\n$$\nAnalytically, $\\pi$ is the smallest positive zero of the sine function, or equivalently\n$$\n\\pi = 4\\arctan 1 = 4\\sum_{k=0}^{\\infty} \\frac{(-1)^k}{2k+1} = 2\\int_{-1}^{1}\\sqrt{1-x^2}\\,dx.\n$$\n:::\n\nThe doubling defines the **turn constant**:\n$$\n\\tau := 2\\pi = \\frac{C}{r} \\approx 6.2831853071795864769\\ldots\n$$\n\n### 4.2 Where π Appears\n\n$\\pi$ is not really \"about circles.\" It is the natural constant of **periodicity and rotation**, and hence of anything with a Fourier transform, a wave, a Gaussian, or a sphere:\n\n- **Geometry**: circumferences, areas, volumes, spherical harmonics.\n- **Trigonometry**: periods of $\\sin, \\cos$; radian measure.\n- **Analysis**: $\\displaystyle\\sum_{n=1}^\\infty \\frac{1}{n^2} = \\frac{\\pi^2}{6}$ (Basel problem), $\\displaystyle\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}$.\n- **Probability**: the normal density $\\frac{1}{\\sqrt{2\\pi}\\sigma}e^{-(x-\\mu)^2/2\\sigma^2}$; **Buffon's needle** gives $2/\\pi$.\n- **Physics**: the uncertainty principle $\\Delta x\\,\\Delta p \\ge \\hbar/2$; the Einstein field equations $G_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4}T_{\\mu\\nu}$; blackbody radiation; the period of a pendulum.\n- **Signal processing**: the Fourier transform carries a $1/\\sqrt{2\\pi}$ normalization.\n\n### 4.3 π versus τ: The Debate\n\nSince a full turn is $\\tau$ radians, many identities look cleaner with $\\tau$:\n\n| With $\\pi$ | With $\\tau = 2\\pi$ |\n| :--- | :--- |\n| Full turn $= 2\\pi$ | Full turn $= \\tau$ |\n| Half turn $= \\pi$ | Half turn $= \\tau/2$ |\n| $\\sin(x + 2\\pi) = \\sin x$ | $\\sin(x + \\tau) = \\sin x$ |\n| Circumference $= 2\\pi r$ | Circumference $= \\tau r$ |\n| Gaussian $\\propto e^{-x^2/2}$ with $\\sqrt{2\\pi}$ | $\\sqrt{\\tau}$ |\n| $\\omega = 2\\pi f$ | $\\omega = \\tau f$ |\n\nThe case for $\\tau$ (Michael Hartl's *Tau Manifesto*) is that \"circle constant\" should be circumference *per radius*, not per diameter, eliminating ubiquitous factors of $2$. The case for $\\pi$ is two millennia of inertia and the elegance of $\\pi r^2$ and Euler's identity $e^{i\\pi}+1=0$. This essay uses both, but observes that **the factor of 2 is not an accident**: it reflects the tension between the *diameter* (a line) and the *turn* (an angle).\n\n### 4.4 Irrationality and Transcendence\n\n- **Irrational** (Johann Heinrich Lambert, 1761): no integers $p,q$ with $\\pi = p/q$.\n- **Transcendental** (Ferdinand von Lindemann, 1882): no nonzero rational polynomial vanishes at $\\pi$. This resolved the ancient problem of **squaring the circle** — impossible with straightedge and compass.\n\n---\n\n## 5. Euler's Number: The Constant of Growth\n\n### 5.1 Three Equivalent Definitions\n\n::: {#def-e}\n#### Definition 5.1 (Euler's Number)\nEuler's number $e$ can be defined equivalently by:\n$$\ne := \\lim_{n\\to\\infty}\\left(1 + \\frac{1}{n}\\right)^{n} = \\sum_{n=0}^{\\infty}\\frac{1}{n!} = \\text{the unique } x > 0 \\text{ with } \\int_{1}^{x}\\frac{dt}{t} = 1.\n$$\nNumerically,\n$$\ne = 2.71828182845904523536\\ldots\n$$\n:::\n\nThe equivalence of the limit and the series is a beautiful exercise: expand the binomial $\\left(1+\\frac1n\\right)^n$ and let $n\\to\\infty$.\n\n### 5.2 The Compound-Interest Origin\n\nJacob Bernoulli (1683) asked: if interest is compounded more and more frequently, does the money grow without bound? Compounding $n$ times per year at nominal rate $1$ yields $\\left(1+\\frac1n\\right)^n$, which converges to $e \\approx 2.718$ rather than diverging. **Continuous compounding** is therefore\n$$\nA(t) = A_0\\, e^{rt}.\n$$\nThis is the historical root of $e$: not a geometric constant, but a **limit of growth**.\n\n### 5.3 e in Nature and Science\n\nWherever the **rate of change is proportional to the current amount**, $e$ appears:\n\n- **Population growth / decay**: $P(t) = P_0 e^{rt}$.\n- **Radioactive decay**: $N(t) = N_0 e^{-\\lambda t}$, half-life $t_{1/2} = \\ln 2/\\lambda$.\n- **Newton's law of cooling**: $T(t) = T_\\infty + (T_0 - T_\\infty)e^{-kt}$.\n- **RC and RL circuits**: capacitor discharge $V(t) = V_0 e^{-t/RC}$.\n- **Arrhenius equation**: $k = A e^{-E_a/(RT)}$.\n- **Boltzmann factor**: $e^{-E/(kT)}$.\n- **Logistic growth** (carrying capacity $K$): $P(t) = \\dfrac{K}{1 + e^{-rt}}$.\n- **Information/entropy** and maximum-entropy distributions.\n\n### 5.4 e in Unexpected Places\n\n- **Derangements.** The number of permutations of $n$ objects with *no* fixed point is $!n = n!\\sum_{k=0}^n \\frac{(-1)^k}{k!}$, and\n$$\n\\frac{!n}{n!} \\longrightarrow \\frac{1}{e} \\approx 0.367879\\ldots\n$$\nSo the probability a random permutation is a derangement (e.g. no letter in the correct envelope) approaches $1/e$.\n- **The secretary problem.** To maximize the chance of hiring the best candidate, reject the first $n/e$ applicants, then take the next one better than all seen. The success probability also approaches $1/e$.\n- **Prime distribution.** The Prime Number Theorem states $\\pi(x) \\sim x/\\ln x$ — note the unfortunate notation clash: here $\\pi(x)$ is the prime-counting function, not the circle constant.\n- **Mean of $1/e$.** The expected number of random uniform draws needed to exceed $1$ is $e$.\n\n### 5.5 Irrationality and Transcendence\n\n- **Irrational** (Euler, 1737), via the continued fraction $e = [2; 1, 2, 1, 1, 4, 1, 1, 6, 1, 1, 8, \\ldots]$, whose partial quotients grow without bound (a fact that precludes rationality).\n- **Transcendental** (Charles Hermite, 1873). Hermite's proof was later generalized by Lindemann to settle $\\pi$.\n\n---\n\n## 6. The Differential Fixed Point: Why e Is Unique\n\nThis section makes precise the statement that *$e$ is the only real base for which the exponential function equals its own derivative*.\n\n### 6.1 The Derivative of a General Exponential\n\n::: {#thm-deriv-exp}\n#### Theorem 6.1 (Derivative of $a^x$)\nFor any base $a > 0$, the function $f(x) = a^x$ is differentiable with\n$$\n\\frac{d}{dx}a^x = a^x \\ln a.\n$$\n:::\n\n*Proof (sketch).* Write $a^x = e^{x\\ln a}$ and apply the chain rule to $e^u$ with $u = x\\ln a$:\n$$\n\\frac{d}{dx} e^{x\\ln a} = e^{x\\ln a}\\cdot \\ln a = a^x \\ln a. \\qquad\\blacksquare\n$$\n\nEvaluating at $x=0$:\n$$\nf'(0) = a^0 \\ln a = \\ln a, \\qquad f(0) = a^0 = 1.\n$$\nThe **slope of the tangent to $y = a^x$ at the point $(0,1)$ is exactly $\\ln a$**. Thus:\n\n::: {#thm-e-unique}\n#### Theorem 6.2 (Characterization of $e$)\nThere is exactly one base $a > 0$ for which $f(x) = a^x$ satisfies $f' = f$, namely\n$$\n\\ln a = 1 \\iff a = e.\n$$\nEquivalently, $e$ is the unique real number such that the tangent to $y = e^x$ at $(0,1)$ has slope $1$.\n:::\n\n*Proof.* If $f' = f$, then $a^x \\ln a = a^x$ for all $x$. Since $a^x > 0$, divide through to get $\\ln a = 1$, hence $a = e$. Conversely, for $a = e$, $\\ln e = 1$ gives $(e^x)' = e^x$. $\\blacksquare$\n\n```text\n          y\n          │                 y = e^x   (slope 1 at x=0)\n          │                /\n          │               /\n          │              /\n          │             /   ← tangent at (0,1) has slope 1\n       1  ─ ─ ─ ─ ─ ─ ─●\n          │            /│\n          │           / │   y = 2^x  (slope ln2 ≈ 0.69)\n          │          /  │\n          │         /   │   y = 3^x  (slope ln3 ≈ 1.10)\n          │        /    │\n          └──────────────┴────────────────────────────► x\n                    0\n   Only y = e^x has the tangent at (0,1) slanted at exactly 45°.\n```\n\n### 6.2 Uniqueness of the Solution to $y' = y$\n\nThe characterization above is about *bases*. There is a stronger statement about *functions*:\n\n::: {#thm-ode}\n#### Theorem 6.3 (Uniqueness up to Scaling)\nEvery differentiable $f : \\mathbb{R} \\to \\mathbb{R}$ satisfying the differential equation\n$$\nf'(x) = f(x) \\quad \\text{for all } x\n$$\nhas the form $f(x) = C e^{x}$ for some constant $C = f(0)$.\n:::\n\n*Proof.* Define $h(x) = f(x)e^{-x}$. Differentiate with the product rule:\n$$\nh'(x) = f'(x)e^{-x} - f(x)e^{-x} = \\bigl(f'(x) - f(x)\\bigr)e^{-x} = 0.\n$$\nSince $h' \\equiv 0$ on the connected interval $\\mathbb{R}$, $h$ is constant: $h(x) = C$. Hence $f(x) = C e^{x}$. Imposing $f(0) = 1$ pins down $f(x) = e^x$. $\\blacksquare$\n\nTwo further characterizations of the same fact:\n\n$$\n\\lim_{h\\to 0}\\frac{e^{h}-1}{h} = 1, \\qquad \\int_1^e \\frac{dt}{t} = 1.\n$$\n\nThe first says $e^x$ has *unit logarithmic slope at the origin*; the second says $e$ is the number whose natural logarithm is $1$. These are the same statement.\n\n---\n\n## 7. The Bridge Between e and π\n\nAt first glance $e$ (growth) and $\\pi$ (rotation) seem unrelated. They are, in fact, two faces of the complex exponential.\n\n### 7.1 Euler's Formula and Identity\n\n::: {#thm-euler-formula}\n#### Theorem 7.1 (Euler's Formula, 1748)\nFor every real $\\theta$,\n$$\ne^{i\\theta} = \\cos\\theta + i\\sin\\theta.\n$$\n:::\n\nSetting $\\theta = \\pi$ gives **Euler's identity**:\n$$\n\\boxed{\\;e^{i\\pi} + 1 = 0.\\;}\n$$\nThis single relation binds the five fundamental constants $e,\\ i,\\ \\pi,\\ 1,\\ 0$ and the three fundamental operations (addition, multiplication, exponentiation). Setting $\\theta = \\tau$ gives the arguably cleaner $e^{i\\tau} = 1$, and $\\theta=\\pi/2$ gives $e^{i\\pi/2} = i$.\n\nThe formula also yields the multi-valued complex logarithm:\n$$\n\\ln z = \\ln|z| + i\\arg z, \\qquad \\arg z \\in (-\\pi, \\pi],\n$$\nwhere $\\pi$ controls the **branch cut**. The interplay of $e$ and $\\pi$ here is structural, not coincidental: rotation by $\\pi$ is multiplication by $-1$.\n\n### 7.2 The Gaussian Integral\n\nThe normalization of the normal distribution — the heartbeat of statistics — is the **Gaussian integral**:\n$$\n\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}.\n$$\nIts proof (square the integral, switch to polar coordinates, and use $x^2 + y^2 = r^2$, $dx\\,dy = r\\,dr\\,d\\theta$ with $\\theta \\in [0, 2\\pi]$) is where $e$ and $\\pi$ collide: the radial integral produces the $e$-part, the angular integral produces the $2\\pi$. This is arguably the most consequential formula linking the two constants.\n\n### 7.3 Stirling's Approximation\n\nThe factorial is bridged to both constants:\n$$\nn! \\sim \\sqrt{2\\pi n}\\left(\\frac{n}{e}\\right)^{n}.\n$$\nHere $e$ arises from summing $\\ln k \\approx \\int \\ln x\\,dx$, and $\\pi$ arises from the Gaussian correction (the $\\sqrt{2\\pi n}$ factor). Stirling is how combinatorial quantities \"know\" both constants.\n\n### 7.4 Near-Integers: $e^{\\pi\\sqrt{n}}$\n\nA startling numerical coincidence: for the Heegner numbers $n = 1,2,3,7,11,19,43,67,163$,\n$$\ne^{\\pi\\sqrt{163}} = 262\\,537\\,412\\,640\\,768\\,743.99999999999925\\ldots\n$$\nso close to an integer that early calculators mistook it for one. The explanation is deep: it comes from the theory of **complex multiplication** and the $j$-invariant, specifically\n$$\ne^{\\pi\\sqrt{163}} = (-640320)^3 + 744 - \\varepsilon,\n$$\nwhere $\\varepsilon \\approx 7.5\\times 10^{-13}$. This is the same theory underlying Ramanujan's rapidly convergent series for $1/\\pi$.\n\n### 7.5 Gelfond's Constant\n\n$$\ne^{\\pi} = (-1)^{-i} \\approx 23.140692632779\\ldots\n$$\nis **transcendental** by the Gelfond–Schneider theorem (Section 8.3). It is one of the few non-contrived constants we fully control. Notably, $e^\\pi$ and $\\pi^e$ are different ($\\pi^e \\approx 22.459$), and it is known that $\\pi^e$ is *not* an integer but its transcendence is open.\n\n---\n\n## 8. Transcendental Constants in the Wild\n\n### 8.1 The Classical Zoo\n\n| Constant | Value / Form | Status | Proved by |\n| :--- | :--- | :--- | :--- |\n| Liouville's constant | $\\sum 10^{-k!}$ | Transcendental | Liouville, 1844 |\n| $e$ | $2.71828\\ldots$ | Transcendental | Hermite, 1873 |\n| $\\pi$ | $3.14159\\ldots$ | Transcendental | Lindemann, 1882 |\n| $2^{\\sqrt{2}}$ | $2.66514\\ldots$ | Transcendental | Gelfond–Schneider, 1934 |\n| $e^{\\pi}$ | $23.1407\\ldots$ | Transcendental | Gelfond–Schneider, 1934 |\n| $\\ln 2$ | $0.6931\\ldots$ | Transcendental | Lindemann–Weierstrass |\n| $\\zeta(3)$ | $1.20206\\ldots$ | **Irrational** | Apéry, 1978 |\n| Euler–Mascheroni $\\gamma$ | $0.57721\\ldots$ | **Unknown if even irrational** | — |\n| Catalan's constant $G$ | $0.91596\\ldots$ | Irrationality unknown | — |\n\n### 8.2 Unexpected Appearances\n\nTranscendental constants surface in places with no apparent connection to geometry or growth:\n\n- **Champernowne's constant** $0.123456789101112\\ldots$ (concatenate the integers) is transcendental and normal in base 10.\n- **Copeland–Erdős constant** $0.235711131719\\ldots$ (concatenate the primes) is transcendental and normal.\n- **Chaitin's constant** $\\Omega$ — the halting probability of a prefix-free universal Turing machine — is a **non-computable, transcendental** real. It encodes deep information-theoretic randomness.\n- **Feigenbaum constants** $\\delta \\approx 4.6692$ and $\\alpha \\approx 2.5029$ (period-doubling route to chaos) are universal in nonlinear dynamics; whether they are irrational remains open.\n- **The Prouhet–Thue–Morse constant** (built from the parity of digit sums) is transcendental.\n- **Nesterenko's theorem (1996)**: $\\pi$, $e^{\\pi}$, and $\\Gamma(1/4)$ are **algebraically independent**, and so are $e^{\\pi\\sqrt{n}}$ for Heegner $n$. This is a modern high-water mark relating $e$, $\\pi$, and the Gamma function.\n\n::: {.callout-note}\n**The pattern.** Many \"naturally defined\" irrationals are transcendental precisely because they cannot satisfy a finite polynomial relation. Proving this for any given constant requires showing that a whole infinite family of approximating rationals fails to be \"too good.\" The measure-theoretic truth (nearly all reals are transcendental) makes the difficulty a matter of *construction*, not *existence*.\n:::\n\n### 8.3 The Three Master Theorems\n\n$$\n\\begin{aligned}\n&\\textbf{Lindemann–Weierstrass: } && \\text{If } \\alpha_1,\\ldots,\\alpha_n \\text{ are linearly independent over } \\mathbb{Q},\\\\ \n& && \\text{then } e^{\\alpha_1},\\ldots,e^{\\alpha_n} \\text{ are algebraically independent over } \\mathbb{Q}.\\\\[4pt]\n&\\textbf{Gelfond–Schneider: } && \\alpha^\\beta \\text{ is transcendental for algebraic } \\alpha \\notin \\{0,1\\},\\\\ \n& && \\beta \\text{ irrational algebraic.}\\\\[4pt]\n&\\textbf{Baker (1966): } && \\text{Effective lower bounds for nonzero linear forms}\\\\ \n& && \\text{in logarithms } \\sum \\beta_i \\ln \\alpha_i.\n\\end{aligned}\n$$\n\n**Gelfond–Schneider** immediately gives the transcendence of $2^{\\sqrt{2}}$ and $e^{\\pi} = (-1)^{-i}$. **Baker's theorem** is the workhorse for *effective* bounds: it turns transcendence into explicit, computable inequalities, with major applications to Diophantine equations (e.g. effective solutions to Mordell and Thue equations).\n\n---\n\n## 9. Bounding and Computing Transcendental Constants\n\nThe history of computing $\\pi$ is a history of mathematics itself. Below, \"bounding\" means squeezing a constant between rationals; \"computing\" means refining the squeeze to many digits.\n\n### 9.1 Historical Methods (Antiquity to the 17th Century)\n\n**Archimedes' method of exhaustion (c. 250 BCE).** Inscribe and circumscribe regular polygons of $n$ sides about a circle. For $n=96$, Archimedes obtained\n$$\n\\frac{223}{71} < \\pi < \\frac{22}{7}, \\qquad 3.1408 < \\pi < 3.1429.\n$$\nEach doubling of $n$ refines the bound — a rigorous lower/upper bound pair, exactly in the modern sense. **Liu Hui** (c. 263 CE) and **Zu Chongzhi** (c. 480 CE, $355/113 = 3.14159292\\ldots$) pushed the method far further.\n\n**Viète's infinite product (1593).** The first exact closed form:\n$$\n\\frac{2}{\\pi} = \\frac{\\sqrt2}{2}\\cdot\\frac{\\sqrt{2+\\sqrt2}}{2}\\cdot\\frac{\\sqrt{2+\\sqrt{2+\\sqrt2}}}{2}\\cdots\n$$\n\n**Wallis's product (1655).**\n$$\n\\frac{\\pi}{2} = \\frac{2}{1}\\cdot\\frac{2}{3}\\cdot\\frac{4}{3}\\cdot\\frac{4}{5}\\cdot\\frac{6}{5}\\cdot\\frac{6}{7}\\cdots\n$$\n\n**Gregory–Leibniz series (1671–1674).** Beautiful but glacially slow:\n$$\n\\frac{\\pi}{4} = 1 - \\frac13 + \\frac15 - \\frac17 + \\frac19 - \\cdots\n$$\nConvergence is $O(1/n)$, requiring ~10 million terms for 7 digits.\n\n**Machin's formula (1706).** The key invention was to express $\\pi$ via *fast-converging* arctangents:\n$$\n\\frac{\\pi}{4} = 4\\arctan\\frac15 - \\arctan\\frac{1}{239},\n$$\nwhich John Machin used to compute **100 digits**. Using $\\arctan x = x - x^3/3 + x^5/5 - \\cdots$ with $x = 1/5$ (not $1$) converges rapidly.\n\n**Euler's acceleration** and the discovery of $e$'s series $\\sum 1/n!$ enabled arbitrary-precision computation of $e$.\n\n### 9.2 Modern Algorithms\n\n**Machin-like formulas.** A family of $\\pi = \\sum c_i \\arctan(1/m_i)$ identities. All computation before 1970 used these.\n\n**Ramanujan's series (1914).** Astoundingly, ~8 digits per term:\n$$\n\\frac{1}{\\pi} = \\frac{2\\sqrt2}{9801}\\sum_{k=0}^{\\infty}\\frac{(4k)!\\,(1103 + 26390k)}{(k!)^4\\,396^{4k}}.\n$$\n\n**Chudnovsky algorithm (1989).** ~14 correct digits per term; the basis of all modern world records:\n$$\n\\frac{1}{\\pi} = 12\\sum_{k=0}^{\\infty}\\frac{(-1)^k (6k)!\\,(545140134k + 13591409)}{(3k)!\\,(k!)^3\\,640320^{3k+3/2}}.\n$$\n\n**BBP formula (Bailey–Borwein–Plouffe, 1997).** A **spigot** algorithm: it computes the $n$-th hexadecimal digit of $\\pi$ *without* computing the preceding digits.\n$$\n\\pi = \\sum_{k=0}^{\\infty}\\frac{1}{16^k}\\left(\\frac{4}{8k+1} - \\frac{2}{8k+4} - \\frac{1}{8k+5} - \\frac{1}{8k+6}\\right).\n$$\n\n**AGM / Gauss–Legendre (Brent–Salamin).** Quadratic convergence — each iteration roughly **doubles** the number of correct digits:\n$$\na_{n+1} = \\frac{a_n + b_n}{2}, \\quad b_{n+1} = \\sqrt{a_n b_n}, \\quad t_{n+1} = t_n - p_n(a_n - a_{n+1})^2,\n$$\nwith $a_0=1,\\ b_0=1/\\sqrt2,\\ t_0=1/4,\\ p_0=1$, and $\\pi \\approx (a_n+b_n)^2/(4t_n)$.\n\nFor $e$, the series $e = \\sum 1/n!$ converges with **factorial** speed: even 100 digits needs only ~70 terms.\n\n### 9.3 Bounds from Number Theory\n\nComputation gives decimal digits; number theory gives *qualitative* and *effective* bounds.\n\n- **Liouville's bound (1844)**: an algebraic number $\\alpha$ of degree $d$ cannot be approximated by rationals too well — there is a constant $c(\\alpha)$ with $|\\alpha - p/q| > c/q^{d}$. Conversely, a number that *violates* every such bound is transcendental. Liouville built the first explicit transcendental this way.\n- **Roth's theorem (1955)**: for any $\\varepsilon > 0$, algebraic $\\alpha$ satisfies $|\\alpha - p/q| > 1/q^{2+\\varepsilon}$ for all sufficiently large $q$. This says algebraic numbers are \"not Liouville\"; it is the sharp quantitative form and earned Roth a Fields Medal.\n- **Baker's linear forms**: effective lower bounds of the form $|\\beta_0 + \\beta_1\\ln\\alpha_1 + \\cdots| > e^{-C}$, which let one *compute* bounds on solutions to Diophantine equations.\n- **Irrationality measure** $\\mu(\\alpha) = \\sup\\{ m : |\\alpha - p/q| < q^{-m} \\text{ for infinitely many } p/q\\}$. For rationals $\\mu = 1$; for algebraic irrationals $\\mu = 2$ (Roth); for $\\pi$ and $e$, $\\mu$ is finite and known to be small (but the exact value is open).\n\n### 9.4 Integer-Relation Detection: PSLQ\n\nThe **PSLQ algorithm** (Ferguson, Bailey) searches for integer relations among high-precision constants: given $x_1,\\ldots,x_n$, find integers $a_i$, not all zero, with $\\sum a_i x_i = 0$. It was used to discover the BBP formula, to test whether $\\pi$ is an algebraic combination of $e$ and $\\gamma$ (no relation found), and to verify new identities. The failure to find such relations is strong empirical evidence for the algebraic *independence* conjectured by Schanuel.\n\n---\n\n## 10. Logarithms: The Arithmetic of Exponents\n\n### 10.1 Definition and Basic Properties\n\n::: {#def-log}\n#### Definition 10.1 (Logarithm)\nFor base $b > 0$, $b \\neq 1$, and $x > 0$, the **logarithm** $\\log_b x$ is the unique real number $y$ with\n$$\nb^{y} = x.\n$$\n:::\n\nThe **common** logarithm is $\\log x = \\log_{10} x$ (engineering), and the **natural** logarithm is $\\ln x = \\log_e x$ (analysis).\n\n**Laws of logarithms** (all for $x,y>0$, $b>0$, $b\\neq 1$):\n\n$$\n\\begin{aligned}\n\\log_b(xy) &= \\log_b x + \\log_b y && \\text{(product $\\to$ sum)}\\\\\n\\log_b\\!\\left(\\frac{x}{y}\\right) &= \\log_b x - \\log_b y && \\text{(quotient $\\to$ difference)}\\\\\n\\log_b(x^{n}) &= n\\log_b x && \\text{(power $\\to$ product)}\\\\\n\\log_b\\!\\left(x^{1/n}\\right) &= \\frac{1}{n}\\log_b x && \\text{(roots)}\\\\\n\\log_b 1 &= 0, \\qquad \\log_b b = 1,\\\\\nb^{\\log_b x} &= x, \\qquad \\log_b(b^{x}) = x,\\\\\n\\log_c x &= \\frac{\\log_b x}{\\log_b c} && \\text{(change of base)}.\n\\end{aligned}\n$$\n\nThe **change-of-base** identity explains why all log scales differ by a constant: $\\log_{10} x = \\ln x / \\ln 10$. It also underlies the conversion between units of information: base $2$ gives **bits**, base $e$ gives **nats**, base $10$ gives **hartleys/dits**.\n\n### 10.2 Theorems\n\n::: {#thm-log-properties}\n#### Theorem 10.1 (Structural Properties)\nFor fixed base $b > 1$, the map $x \\mapsto \\log_b x$ is a strictly increasing, continuous bijection $(0,\\infty) \\to \\mathbb{R}$. It is the unique continuous group homomorphism from the multiplicative group $(0,\\infty)$ to the additive group $(\\mathbb{R},+)$ normalised by $\\log_b b = 1$.\n:::\n\nThe last clause is the deep one: **logarithms convert multiplication into addition**. Any continuous function satisfying $f(xy) = f(x) + f(y)$ must be a constant multiple of a logarithm. This single property is the entire basis of the slide rule.\n\n::: {#thm-ln-integral}\n#### Theorem 10.2 (Natural Logarithm as an Integral)\nFor $x > 0$,\n$$\n\\ln x = \\int_1^x \\frac{dt}{t},\n$$\nand consequently $\\ln(ab) = \\ln a + \\ln b$.\n:::\n\n*Proof of the product rule.*\n$$\n\\ln(ab) = \\int_1^{ab}\\frac{dt}{t} = \\int_1^{a}\\frac{dt}{t} + \\int_a^{ab}\\frac{dt}{t}.\n$$\nSubstitute $t = au$ in the second integral ($dt = a\\,du$):\n$$\n\\int_a^{ab}\\frac{dt}{t} = \\int_1^{b}\\frac{a\\,du}{au} = \\int_1^{b}\\frac{du}{u} = \\ln b.\n$$\nHence $\\ln(ab) = \\ln a + \\ln b$. $\\blacksquare$\n\nThe number $e$ is then defined by $\\ln e = \\int_1^e dt/t = 1$.\n\n### 10.3 Series and Computation\n\nFor computation, the Taylor series of $\\ln(1+x)$:\n$$\n\\ln(1+x) = x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\frac{x^4}{4} + \\cdots, \\qquad -1 < x \\le 1.\n$$\nConvergence is slow near $x = 1$, so one uses the accelerated form\n$$\n\\ln x = 2\\left(z + \\frac{z^3}{3} + \\frac{z^5}{5} + \\cdots\\right), \\qquad z = \\frac{x-1}{x+1},\n$$\nwhich converges geometrically and is how logarithms were tabulated by hand.\n\nFor **large** arguments, the leading approximation $\\ln n! \\approx n\\ln n - n$ is refined by Stirling (Section 7.3).\n\n---\n\n## 11. The Slide Rule: Logarithms in the Hand\n\nThe slide rule is the physical embodiment of $\\log(xy) = \\log x + \\log y$. It multiplies by **adding lengths proportional to logarithms**. For three centuries it was the symbol of the engineer — used to build bridges, airplanes, and the first atomic bombs — until the pocket calculator made it obsolete in the 1970s.\n\n### 11.1 The Principle\n\nPrint a ruler whose marks are placed at positions proportional to the **logarithm** of the labeled number. Then the length from the index $1$ to a mark $x$ is $\\log x$. Place two such rulers side by side and slide one:\n\n$$\n\\underbrace{\\log x}_{\\text{length}} + \\underbrace{\\log y}_{\\text{length}} = \\log(xy) \\quad\\Longleftrightarrow\\quad \\text{the sum length points at } xy.\n$$\n\nAddition of distances becomes multiplication of numbers. Division is subtraction (slide in the opposite direction).\n\n```text\n             THE SLIDE RULE PRINCIPLE\n   C scale (sliding):    1     2     3   4  5 6 7 8 9 10\n                         |-----|-----|--|--|--|--|--|-|\n                         |  log 2 = .301   log 3 = .477\n\n   D scale (fixed):      1     2     3   4  5 6 7 8 9 10\n                         |-----|-----|--|--|--|--|--|-|\n\n   To compute 2 × 3:\n     (1) Align the \"1\" of C with \"2\" on D.\n     (2) Read the D value under \"3\" on C  →  6.\n         Because  log2 + log3 = 0.301 + 0.477 = 0.778 = log6.\n```\n\n### 11.2 The Scales\n\nA typical engineering slide rule carries several scales:\n\n| Scale | Function | Length (decades) | Use |\n| :--- | :--- | :--- | :--- |\n| **C, D** | $\\log x$ | 1 (from 1 to 10) | multiply, divide |\n| **A, B** | $\\tfrac12\\log x$ | 2 (1–10, 10–100) | squares, square roots |\n| **K** | $\\tfrac13\\log x$ | 3 (1–1000) | cubes, cube roots |\n| **CI** | $-\\log x$ (inverted) | 1 | reciprocals, chained division |\n| **L** | linear ($\\log_{10}\\log x$) | linear mantissa | base-10 logarithms |\n| **S** | $\\log(\\sin\\theta)$ | — | trigonometry |\n| **T** | $\\log(\\tan\\theta)$ | — | trigonometry |\n| **ST** | small angles | — | $\\sin\\theta \\approx \\tan\\theta \\approx \\theta$ |\n\nThe transparent **cursor** (runner) with a hairline allows reading and transferring values across scales.\n\n### 11.3 Worked Operations\n\n**Multiplication** $a \\times b$: align the index $1$ on C with $a$ on D; move the cursor to $b$ on C; read the D value. If $b$ lies beyond the scale end (product exceeds $10$), use the *right* index $10$ instead — this \"decade shift\" corresponds to subtracting $\\log 10 = 1$ and tracking the decimal point in your head.\n\n**Division** $a \\div b$: align $b$ on C with $a$ on D; read D under $1$ on C. Equivalently, subtract lengths.\n\n**Squares and square roots**: use the A/B scales, which are half-logarithmic. Squares multiply logarithms by 2; square roots halve them.\n\n**Cubes and cube roots**: use the K scale (third-logarithmic).\n\n**Reciprocals**: read across from C to CI.\n\n**Trigonometry**: the S and T scales place $\\log(\\sin\\theta)$ and $\\log(\\tan\\theta)$ directly against the C/D scales, so multiplying a length by a sine is one movement.\n\n**Chain calculations**: the cursor lets you chain $a\\times b\\times c$ without recording intermediate values.\n\n::: {.callout-note}\n**Precision.** A 25 cm slide rule yields about **3 significant figures** — adequate for engineering but not for accounting. The skill lay in (1) mentally tracking the decimal point and (2) ordering operations to minimise accumulated error. Slide-rule fluency was once a required engineering competency.\n:::\n\n### 11.4 A Short History\n\n- **Napier** publishes logarithms (1614); **Briggs** tabulates base-10 logs (1617).\n- **Gunter's line** (1620) puts logarithms on a rule but requires dividers.\n- **William Oughtred** invents the modern sliding pair (c. 1622).\n- Improvements over centuries: the cursor (1851, Amédée Mannheim standardised the modern scale set).\n- **20th century**: the slide rule is the emblem of the engineer; carried on Apollo, used in classrooms.\n- **1970s**: the HP-35 and other pocket calculators end the slide rule's reign within a decade.\n\nThe slide rule is the clearest physical demonstration of the logarithm's deepest property: **it turns multiplication into addition**.\n\n---\n\n## 12. Computational Laboratory\n\nThe following dependency-light Python program (standard library only, using `decimal` for precision) verifies the definitions, inequalities, and computations discussed above.\n\n::: {#0c9678b9 .cell execution_count=1}\n``` {.python .cell-code}\nfrom decimal import Decimal, getcontext\nimport math\n\ngetcontext().prec = 60\nD = Decimal\nPI = D(\"3.14159265358979323846264338327950288419716939937510582097494\")\nE = sum(D(1) / D(math.factorial(n)) for n in range(45))\n\ndef close(a, b, tol=D(\"1e-50\")):\n    return abs(a - b) < tol\n\ndef dsin(x, terms=90):\n    \"\"\"Sine via Taylor series, in Decimal, for the pi-bisection demo.\"\"\"\n    total, power, fact, sign = D(0), x, D(1), 1\n    for k in range(terms):\n        term = power / fact\n        total += term if sign > 0 else -term\n        power *= x * x\n        fact *= (2 * k + 2) * (2 * k + 3)\n        sign = -sign\n    return total\n\nprint(\"=== 1. THE GOLDEN RATIO ===\")\nphi = (D(1) + D(5).sqrt()) / D(2)\npsi = (D(1) - D(5).sqrt()) / D(2)\nprint(f\"phi          = {phi}\")\nprint(f\"phi^2        = {phi * phi}\")\nprint(f\"phi^2 = phi+1: {close(phi * phi, phi + 1)}\")\nprint(f\"1/phi        = {1 / phi}\")\nprint(f\"1/phi = phi-1: {close(1 / phi, phi - 1)}\")\nprint(f\"psi = -1/phi : {close(psi, -1 / phi)}\")\nprint(f\"golden angle = {360 * (1 - 1 / phi)} degrees\")\n\nprev, cur = 1, 1                      # Fibonacci ratios -> phi\nfor _ in range(80):\n    prev, cur = cur, prev + cur\nprint(f\"F/F ratio    = {D(cur) / D(prev)} -> phi\")\n\nprint(\"\\n=== 2. COUNTABILITY OF THE RATIONALS ===\")\nimport fractions\nrats = sorted({fractions.Fraction(p, q) for q in range(1, 13) for p in range(1, 13)})\nprint(f\"Reduced fractions with p, q <= 12: {len(rats)}  (a countable set)\")\nprint(f\"Of these, strictly inside (0,1):   {sum(1 for r in rats if 0 < r < 1)}\")\nprint(\"Cantor: Q is countable, R is uncountable, so R\\\\Q is uncountable.\")\n\nprint(\"\\n=== 3. PI AND TAU ===\")\nprint(f\"pi           = {PI}\")\nprint(f\"tau = 2*pi   = {2 * PI}\")\nprint(f\"Basel pi^2/6 = {PI * PI / 6}\")\n\nprint(\"\\n=== 4. EULER'S NUMBER: SERIES VS LIMIT ===\")\nprint(f\"e (series)   = {E}\")\nn = 10**7\nprint(f\"e (1+1/n)^n  = {(D(1) + D(1) / D(n)) ** n}\")\nprint(f\"  limit is slow: residual ~ e/(2n) = {E / (2 * n)}\")\n\nprint(\"\\n=== 5. DERIVATIVE FIXED POINT: (a^x)' = a^x ln a ===\")\nh = D(10) ** -8\nfor a in [D(2), E, D(3)]:\n    slope = (a**h - a ** (-h)) / (2 * h)      # central difference at x = 0\n    print(f\"a = {a}: slope = {slope}   ln a = {a.ln()}\")\nprint(\"Only a = e gives slope 1 at (0,1).\")\n\nprint(\"\\n=== 6. e AND pi LINKED (Gaussian integral + Stirling) ===\")\ndef f(x):\n    return (-x * x).exp()\nN, lo, hi = 2000, D(-8), D(8)                # Simpson's rule\ndx = (hi - lo) / N\ntotal = f(lo) + f(hi)\nfor k in range(1, N):\n    total += (4 if k % 2 else 2) * f(lo + k * dx)\nprint(f\"integral exp(-x^2) dx ~ {total * dx / 3}\")\nprint(f\"sqrt(pi)              ~ {PI.sqrt()}\")\nfor Nf in [30, 50]:\n    stir = (2 * PI * Nf).sqrt() * (D(Nf) / E) ** Nf\n    print(f\"Stirling: {Nf}! ~ {stir}\")\n\nprint(\"\\n=== 7. ARCHIMEDES-STYLE BOUNDS ON PI (bisection of sin) ===\")\nlo, hi = D(3), D(4)\nfor _ in range(200):\n    mid = (lo + hi) / 2\n    if dsin(mid) > 0:\n        lo = mid\n    else:\n        hi = mid\nprint(f\"smallest positive root of sin = {(lo + hi) / 2}\")\nprint(f\"223/71 < pi < 22/7 : {D(223) / D(71) < PI < D(22) / D(7)}\")\n\nprint(\"\\n=== 8. LOGARITHMS & THE SLIDE RULE: log(a*b) = log a + log b ===\")\nx, y = D(2), D(3)\nprint(f\"ln2 + ln3 = {x.ln() + y.ln()}\")\nprint(f\"ln(2*3)   = {(x * y).ln()}   (equal: {close(x.ln() + y.ln(), (x * y).ln())})\")\nprint(f\"exp(ln2+ln3) = {(x.ln() + y.ln()).exp()}\")\nprint(f\"Slide-rule reading of 2*3 (3 sig figs) = {float((x.ln() + y.ln()).exp()):.3g}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== 1. THE GOLDEN RATIO ===\nphi          = 1.61803398874989484820458683436563811772030917980576286213545\nphi^2        = 2.61803398874989484820458683436563811772030917980576286213545\nphi^2 = phi+1: True\n1/phi        = 0.618033988749894848204586834365638117720309179805762862135448\n1/phi = phi-1: True\npsi = -1/phi : True\ngolden angle = 137.507764050037854646348739628370277620688695269925369631239 degrees\nF/F ratio    = 1.61803398874989484820458683436563780619934261802274970224191 -> phi\n\n=== 2. COUNTABILITY OF THE RATIONALS ===\nReduced fractions with p, q <= 12: 91  (a countable set)\nOf these, strictly inside (0,1):   45\nCantor: Q is countable, R is uncountable, so R\\Q is uncountable.\n\n=== 3. PI AND TAU ===\npi           = 3.14159265358979323846264338327950288419716939937510582097494\ntau = 2*pi   = 6.28318530717958647692528676655900576839433879875021164194988\nBasel pi^2/6 = 1.64493406684822643647241516664602518921894990120679843773555\n\n=== 4. EULER'S NUMBER: SERIES VS LIMIT ===\ne (series)   = 2.71828182845904523536028747135266249775724709369995957495845\ne (1+1/n)^n  = 2.71828169254496627119855022577781327315350827128440406388550\n  limit is slow: residual ~ e/(2n) = 1.35914091422952261768014373567633124887862354684997978747922E-7\n\n=== 5. DERIVATIVE FIXED POINT: (a^x)' = a^x ln a ===\na = 2: slope = 0.69314718055994531496764298794033457672328465765087435   ln a = 0.693147180559945309417232121458176568075500134360255254120680\na = 2.71828182845904523536028747135266249775724709369995957495845: slope = 1.0000000000000000166666666666666667500000000000000003   ln a = 0.999999999999999999999999999999999999999999999999999999996867\na = 3: slope = 1.09861228866810971349472790598764789809265496607396485   ln a = 1.09861228866810969139524523692252570464749055782274945173469\nOnly a = e gives slope 1 at (0,1).\n\n=== 6. e AND pi LINKED (Gaussian integral + Stirling) ===\nintegral exp(-x^2) dx ~ 1.77245385090551602729816748332125060490682874452037158663663\nsqrt(pi)              ~ 1.77245385090551602729816748334114518279754945612238712821381\nStirling: 30! ~ 264517095922964306151924784891709.847893298401161883257983814\nStirling: 50! ~ 3.03634459393815582079837267521120939590525998022862969566659E+64\n\n=== 7. ARCHIMEDES-STYLE BOUNDS ON PI (bisection of sin) ===\nsmallest positive root of sin = 3.14159265358979323846264338327950288419716939937510582097494\n223/71 < pi < 22/7 : True\n\n=== 8. LOGARITHMS & THE SLIDE RULE: log(a*b) = log a + log b ===\nln2 + ln3 = 1.79175946922805500081247735838070227272299069218300470585537\nln(2*3)   = 1.79175946922805500081247735838070227272299069218300470585537   (equal: True)\nexp(ln2+ln3) = 5.99999999999999999999999999999999999999999999999999999999997\nSlide-rule reading of 2*3 (3 sig figs) = 6\n```\n:::\n:::\n\n\nSample output (abridged to the key lines):\n\n```text\n=== 1. THE GOLDEN RATIO ===\nphi          = 1.61803398874989484820458683436563811772030917980576286213545\nphi^2        = 2.61803398874989484820458683436563811772030917980576286213545\nphi^2 = phi+1: True\n1/phi = phi-1: True\npsi = -1/phi : True\ngolden angle = 137.507764050037854646348739628370277620688695269925369631239 degrees\nF/F ratio    = 1.61803398874989484820458683436563780619934261802274970224191 -> phi\n\n=== 4. EULER'S NUMBER: SERIES VS LIMIT ===\ne (series)   = 2.71828182845904523536028747135266249775724709369995957495845\ne (1+1/n)^n  = 2.71828169254496627119855022577781327315350827128440406388550\n  limit is slow: residual ~ e/(2n) = 1.35914091422952261768014373567633124887862354684997978747922E-7\n\n=== 5. DERIVATIVE FIXED POINT: (a^x)' = a^x ln a ===\na = 2:  slope = 0.69314718055994531496764298794033457672328465765087435  ln a = 0.693147180559945309417232121458176568075500134360255254120680\na = 2.71828182845904523536028747135266249775724709369995957495845: slope = 1.0000000000000000166666666666666667500000000000000003  ln a = 0.999999999999999999999999999999999999999999999999999999996867\na = 3:  slope = 1.09861228866810971349472790598764789809265496607396485  ln a = 1.09861228866810969139524523692252570464749055782274945173469\nOnly a = e gives slope 1 at (0,1).\n\n=== 6. e AND pi LINKED (Gaussian integral + Stirling) ===\nintegral exp(-x^2) dx ~ 1.77245385090551602729816748332125060490682874452037158663663\nsqrt(pi)              ~ 1.77245385090551602729816748334114518279754945612238712821381\n\n=== 8. LOGARITHMS & THE SLIDE RULE: log(a*b) = log a + log b ===\nln2 + ln3 = 1.79175946922805500081247735838070227272299069218300470585537\nln(2*3)   = 1.79175946922805500081247735838070227272299069218300470585537   (equal: True)\nSlide-rule reading of 2*3 (3 sig figs) = 6\n```\n\n---\n\n## 13. Summary Matrix\n\n| Constant | Symbol | Value | Type | Principal Origins | Key Identities |\n| :--- | :--- | :--- | :--- | :--- | :--- |\n| Golden ratio | $\\varphi$ | $1.6180339887\\ldots$ | Algebraic (degree 2) | Self-similar division, pentagon, phyllotaxis | $\\varphi^2 = \\varphi + 1$, $[1;1,1,\\ldots]$, Binet |\n| Archimedes' constant | $\\pi$ | $3.1415926535\\ldots$ | Transcendental | Circles, periodicity, Gaussian | $e^{i\\pi}+1=0$, $\\zeta(2)=\\pi^2/6$, $\\int e^{-x^2}=\\sqrt\\pi$ |\n| Turn constant | $\\tau$ | $6.2831853071\\ldots$ | Transcendental | Full rotation | $e^{i\\tau}=1$, $C = \\tau r$ |\n| Euler's number | $e$ | $2.7182818284\\ldots$ | Transcendental | Continuous growth, compound interest | $(e^x)'=e^x$, $\\sum 1/n!$, $\\int_1^e dt/t=1$ |\n| Euler–Mascheroni | $\\gamma$ | $0.5772156649\\ldots$ | Unknown | Harmonic–log gap | $\\gamma = \\lim(\\sum 1/k - \\ln n)$ |\n| Gelfond's constant | $e^{\\pi}$ | $23.1406926327\\ldots$ | Transcendental | Complex exponentiation | $e^\\pi = (-1)^{-i}$ |\n| Apéry's constant | $\\zeta(3)$ | $1.2020569031\\ldots$ | Irrational | Sum of inverse cubes | $\\zeta(3)=\\sum 1/n^3$ |\n\n**Cardinality summary:**\n\n$$\n\\underbrace{|\\mathbb{N}| = |\\mathbb{Z}| = |\\mathbb{Q}| = |\\overline{\\mathbb{Q}}| = \\aleph_0}_{\\text{countable, measure zero}}\n\\qquad < \\qquad\n\\underbrace{|\\mathbb{R}\\setminus\\mathbb{Q}| = |\\mathbb{R}\\setminus\\overline{\\mathbb{Q}}| = |\\mathbb{R}| = 2^{\\aleph_0} = \\mathfrak{c}}_{\\text{uncountable, full measure}}\n$$\n\nAlmost every real number is transcendental; almost every *named* constant was, until the 19th century, assumed to be tame. The tension between these facts is the engine of transcendence theory.\n\n---\n\n## 14. Curated References and Primary Sources\n\n1. **Archimedes (c. 250 BCE)**. *Measurement of a Circle* (Περὶ τοῦ κύκλου). Trans. T. L. Heath, *The Works of Archimedes*.\n2. **Euler, Leonhard (1748)**. *Introductio in analysin infinitorum*. Lausanne. (Euler's formula and the constant $e$.)\n3. **Hermite, Charles (1873)**. *\"Sur la fonction exponentielle\"*. Comptes Rendus de l'Académie des Sciences Paris, 77: 18–24, 74–79.\n4. **Lindemann, Ferdinand von (1882)**. *\"Über die Zahl $\\pi$\"*. Mathematische Annalen, 20: 213–225.\n5. **Cantor, Georg (1874)**. *\"Über eine Eigenschaft des Inbegriffes aller reellen algebraischen Zahlen\"*. Journal für die reine und angewandte Mathematik, 77: 258–262.\n6. **Gelfond, Aleksandr (1934)**. *\"Sur le septième problème de D. Hilbert\"*. Bulletin de l'Académie des Sciences de l'URSS, VII(4): 623–630.\n7. **Baker, Alan (1975)**. *Transcendental Number Theory*. Cambridge University Press.\n8. **Niven, Ivan (1956)**. *Irrational Numbers*. Carus Mathematical Monographs, MAA.\n9. **Bailey, D., Borwein, P., Plouffe, S. (1997)**. *\"On the Rapid Computation of Various Polylogarithmic Constants\"*. Mathematics of Computation, 66(218): 903–913.\n10. **Borwein, J. & Bailey, D. (2008)**. *Mathematics by Experiment: Plausible Reasoning in the 21st Century*. A K Peters.\n11. **Nesterenko, Yu. V. (1996)**. *\"Modular Functions and Transcendence Problems\"*. Comptes Rendus de l'Académie des Sciences Paris, 322: 909–914.\n12. **Hartl, Michael**. *The Tau Manifesto*. https://tauday.com\n13. **Livio, Mario (2002)**. *The Golden Ratio: The Story of Phi, the World's Most Astonishing Number*. Broadway Books. (Read with the myth-busting caveat of Section 2.5.)\n14. **Prudnikov, A. P., Brychkov, Yu. A., Marichev, O. I.** *Integrals and Series*, Vols. 1–3. Gordon and Breach.\n15. **Kline, Morris (1972)**. *Mathematical Thought from Ancient to Modern Times*. Oxford University Press.\n\n---\n\n*See also: [Algebraic and Transcendental Numbers](algebraic-and-transcendental-numbers-foundations-and-proofs.qmd) for the formal proofs of transcendence, and [Real Numbers and Completeness](analysis-01-real-numbers-completeness.qmd) for the construction of $\\mathbb{R}$ that underlies Cantor's cardinality theorem.*\n\n",
    "supporting": [
      "the-great-constants-golden-ratio-e-pi-tau-and-the-transcendental-fabric_files"
    ],
    "filters": [],
    "includes": {}
  }
}