{
  "hash": "916c80203e20a0c274f6a7fdca271969",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Deep Structure of Numbers: From Decimals and Radicals to Unique Factorization and the Riemann Hypothesis\"\nsubtitle: \"Cardinality vs. Completeness, The Algebraic Mechanics of Roots, The Fundamental Theorem of Arithmetic, Infinity of Primes, and the Geometry of the Zeta Function\"\nauthor: \"Igor Kan\"\ndate: \"2026-09-13\"\ncategories: [Mathematics, Number Theory, Analysis, Algebra, Arithmetic, Prime Numbers]\ndescription: \"An exhaustive first-principles treatise covering the essential spectrum of numbers: cardinality and completeness of integers vs rationals, terminating and repeating decimals via the Pigeonhole Principle and modular arithmetic, the exact algebra of radical functions (why sqrt(x^2) = |x|), the Fundamental Theorem of Arithmetic via Bézout's identity, three proofs of the infinitude of primes (Euclid, Euler, Furstenberg), and the Riemann Hypothesis connecting primes to the non-trivial zeros of the zeta function.\"\ntoc: true\ntoc-depth: 4\nnumber-sections: true\nformat:\n  html:\n    math: mathjax\n    code-fold: show\n    code-tools: true\njupyter: python3\n---\n\n::: {.callout-note appearance=\"simple\"}\n*\"Primes are the atomic elements of arithmetic, decimals are their positional shadows, and the Riemann zeta function is the spectral microscope that reveals their cosmic distribution.\"*  \n— **Foundations of Analytic Number Theory**\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Companion Treatises in this Series\n- [The Architecture of Number Systems: Axiomatic Constructions, Cayley-Dickson Algebras, and Recursive Sequences](the-architecture-of-number-systems-constructions-cayley-dickson-and-recursion.qmd)\n- [Algebraic and Transcendental Numbers: Foundations, Diophantine Approximations, and Proofs](algebraic-and-transcendental-numbers-foundations-and-proofs.qmd)\n- [Real Numbers, Dedekind Cuts, and Topological Completeness](analysis-01-real-numbers-completeness.qmd)\n:::\n\n---\n\n## 1. Cardinality and Completeness: The Structural Chasm Between $\\mathbb{Z}$, $\\mathbb{Q}$, and $\\mathbb{R}$\n\nTo navigate higher mathematics, one must distinguish between two fundamentally different concepts of size and fullness: **Cardinality** (how many elements exist) and **Topological Completeness** (whether limits of Cauchy sequences remain in the set).\n\n```\n                            CARDINALITY VS. COMPLETENESS MATRIX\n                            \n  Set               Cardinality        Topology in R        Metric Completeness    Algebraic Closure\n  ───               ───────────        ─────────────        ───────────────────    ─────────────────\n  Integers (Z)      Countable (aleph0) Discrete (Isolated)  Complete (Discrete)    No (Ring only)\n  Rationals (Q)     Countable (aleph0) Dense (Full of gaps) INCOMPLETE             No (Field, not closed)\n  Reals (R)         UNCOUNTABLE (c)    Continuous           COMPLETE               No (Ordered field)\n  Complex (C)       UNCOUNTABLE (c)    2D Metric Plane      COMPLETE               ALGEBRAICALLY CLOSED\n```\n\n---\n\n### 1.1 Cardinality: The Equivalence of $\\mathbb{Z}$ and $\\mathbb{Q}$ ($|\\mathbb{Z}| = |\\mathbb{Q}| = \\aleph_0$)\n\nIt is a common intuition that there are \"more\" rational numbers than integers because between any two integers lies an infinity of fractions. However, Georg Cantor proved that **$\\mathbb{Z}$ and $\\mathbb{Q}$ have the exact same cardinality**.\n\n::: {#def-countability}\n#### Definition 1.1 (Countability)\nA set $S$ is **countably infinite** ($|S| = \\aleph_0$) if there exists a bijective mapping $f: \\mathbb{N} \\to S$.\n:::\n\n#### A. The Integers are Countable:\nWe construct an explicit bijection interleaving positive and negative integers:\n$$f(n) = \\begin{cases} \\frac{n}{2} & \\text{if } n \\text{ is even} \\\\ -\\frac{n+1}{2} & \\text{if } n \\text{ is odd} \\end{cases}$$\n$$\\mathbb{N}: \\quad 0 \\quad 1 \\quad 2 \\quad 3 \\quad 4 \\quad 5 \\quad 6 \\quad \\dots$$\n$$\\mathbb{Z}: \\quad 0 \\quad -1 \\quad 1 \\quad -2 \\quad 2 \\quad -3 \\quad 3 \\quad \\dots$$\n\n#### B. The Rationals are Countable (Cantor's Snake Enumeration):\nEvery positive rational number is an ordered pair $(p, q) \\in \\mathbb{N} \\times \\mathbb{N}$ with $\\gcd(p, q) = 1$. We arrange all pairs in an infinite 2D grid and traverse them along antidiagonals (Cantor's snake):\n\n```\n        q=1     q=2     q=3     q=4     q=5  ...\n p=1    1/1 ──► 1/2     1/3 ──► 1/4     1/5\n         │     ↗       │     ↗\n p=2    2/1   2/2     2/3   2/4   ...\n        │     ↗       │\n p=3    3/1 ──► 3/2   3/3 ...\n        │\n p=4    4/1 ...\n```\n\nBy skipping unreduced fractions ($\\gcd(p, q) > 1$), every rational appears exactly once in the sequence:\n$$\\mathbb{Q}^+: \\quad \\frac{1}{1}, \\ \\frac{1}{2}, \\ \\frac{2}{1}, \\ \\frac{3}{1}, \\ \\frac{1}{3}, \\ \\frac{1}{4}, \\ \\frac{2}{3}, \\ \\frac{3}{2}, \\ \\frac{4}{1}, \\ \\dots$$\nExtending to negative fractions by alternating signs proves $|\\mathbb{Q}| = \\aleph_0$.\n\n---\n\n### 1.2 Topological Completeness: The Failure of $\\mathbb{Q}$\n\nWhile $\\mathbb{Z}$ and $\\mathbb{Q}$ have identical cardinalities, their topological structures are entirely distinct:\n\n1. **The Discrete Nature of $\\mathbb{Z}$**: Every integer is isolated. The distance between any two distinct integers is $|m - n| \\ge 1$. Under the standard Euclidean metric, any Cauchy sequence of integers $(a_n)$ must satisfy $|a_n - a_m| < 1/2$ for large $n, m$, which forces the sequence to become **eventually constant**. Therefore, every Cauchy sequence in $\\mathbb{Z}$ trivially converges to an element in $\\mathbb{Z}$.\n2. **The Incompleteness of $\\mathbb{Q}$**: The rationals are **dense** on the real line: between any two distinct rationals lies another rational. Yet, $\\mathbb{Q}$ is riddled with \"holes.\"  \n   Consider the Babylonian / Newton-Raphson sequence for $\\sqrt{2}$:\n   $$x_0 = 1, \\quad x_{n+1} = \\frac{x_n}{2} + \\frac{1}{x_n}$$\n   $$x_0 = 1, \\quad x_1 = \\frac{3}{2} = 1.5, \\quad x_2 = \\frac{17}{12} \\approx 1.4166, \\quad x_3 = \\frac{577}{408} \\approx 1.414215\\dots$$\n   Every term $x_n \\in \\mathbb{Q}$. The sequence is Cauchy: $|x_n - x_m| \\to 0$ as $n, m \\to \\infty$.  \n   Yet, **its limit does not exist in $\\mathbb{Q}$** because $\\sqrt{2} \\notin \\mathbb{Q}$!\n\nThe real numbers $\\mathbb{R}$ are synthesized precisely to repair this defect: $\\mathbb{R}$ is the topological completion of $\\mathbb{Q}$. In $\\mathbb{R}$, every Cauchy sequence converges to a real limit.\n\n---\n\n## 2. The Positional Mechanics of Decimals: Terminating vs. Periodic Fractions\n\nEvery rational number $\\frac{p}{q}$ can be expressed as a base-10 decimal. A fundamental question of arithmetic is: **Why does a fraction produce either a terminating decimal or an infinitely repeating decimal, and what governs the period length?**\n\n```\n                         THE TAXONOMY OF DECIMAL EXPANSIONS\n                                         │\n        ┌────────────────────────────────┴────────────────────────────────┐\n        ▼                                                                 ▼\n┌─────────────────────────────────┐                     ┌───────────────────────────────────┐\n│     RATIONAL NUMBERS (Q)        │                     │     IRRATIONAL NUMBERS (R \\ Q)    │\n│  Always Terminating OR Periodic │                     │    Aperiodic Infinite Decimals    │\n├─────────────────────────────────┤                     ├───────────────────────────────────┤\n│ • Terminating: 3/8 = 0.375      │                     │ • sqrt(2) = 1.41421356...         │\n│   (Denominator = 2^a * 5^b)     │                     │ • e = 2.718281828459...           │\n│ • Pure Repeating: 1/7 = 0.(142857)                    │ • pi = 3.141592653589...          │\n│   (gcd(q, 10) = 1)              │                     │ • Golden Ratio phi = 1.6180339... │\n│ • Mixed Repeating: 1/6 = 0.1(6) │                     │ • Transcendental Liouville L      │\n│   (Denominator has 2,5 AND other│                     │ • No repeating blocks forever     │\n└─────────────────────────────────┘                     └───────────────────────────────────┘\n```\n\n---\n\n### 2.1 Terminating Decimals ($q = 2^a \\cdot 5^b$)\n\n::: {#thm-terminating-decimals}\n#### Theorem 2.1 (Terminating Decimal Characterization)\nA rational number $\\frac{p}{q}$ in lowest terms ($\\gcd(p, q) = 1$) has a **terminating decimal representation** if and only if the prime factorization of the denominator contains **no prime factors other than $2$ and $5$**:\n$$q = 2^a \\cdot 5^b, \\quad a, b \\in \\mathbb{N}_0$$\n:::\n\n*Proof*:  \nA decimal terminates at $k$ decimal places if and only if it can be written as an integer divided by a power of 10:\n$$\\frac{p}{q} = \\frac{N}{10^k} \\iff p \\cdot 10^k = N \\cdot q$$\nSince $\\gcd(p, q) = 1$, by Euclid's lemma $q$ must divide $10^k = 2^k \\cdot 5^k$.  \nBy the Fundamental Theorem of Arithmetic, the only prime factors that can divide $2^k \\cdot 5^k$ are $2$ and $5$. Therefore, $q = 2^a \\cdot 5^b$ with $\\max(a, b) \\le k$.  \nConversely, if $q = 2^a 5^b$, let $k = \\max(a, b)$. Multiplying numerator and denominator by $2^{k-a} 5^{k-b}$ yields:\n$$\\frac{p}{q} = \\frac{p \\cdot 2^{k-a} 5^{k-b}}{2^k 5^k} = \\frac{p \\cdot 2^{k-a} 5^{k-b}}{10^k}$$\nwhich terminates in exactly $k = \\max(a, b)$ decimal digits. $\\blacksquare$\n\n*Example*: $\\frac{7}{40} = \\frac{7}{2^3 \\cdot 5^1}$. Here $k = \\max(3, 1) = 3$. Multiply by $5^2 / 5^2$:\n$$\\frac{7 \\cdot 25}{40 \\cdot 25} = \\frac{175}{1000} = 0.175 \\quad \\text{(exactly 3 decimal places)}.$$\n\n---\n\n### 2.2 Repeating Decimals and the Pigeonhole Principle\n\nWhat happens when $q$ contains prime factors other than $2$ and $5$ (e.g. $q = 3, 7, 11, 13$)?\n\n::: {#thm-repeating-decimals}\n#### Theorem 2.2 (Periodic Decimals via the Pigeonhole Principle)\nEvery rational number $\\frac{p}{q}$ produces an eventually periodic decimal. Furthermore, the length of the repeating period $L$ satisfies:\n$$L \\le q - 1$$\n:::\n\n*Proof via Long Division & The Pigeonhole Principle*:  \nConsider the standard long-division algorithm computing $\\frac{p}{q}$.  \nAt step $k$, let the remainder be $r_k$. To compute the next decimal digit, we perform:\n$$10 \\cdot r_k = d_{k+1} \\cdot q + r_{k+1}, \\quad \\text{where } 0 \\le r_{k+1} < q$$\nSince the division does not terminate, the remainder can never be zero: $r_k \\in \\{1, 2, 3, \\dots, q-1\\}$.  \nThere are **strictly $q - 1$ possible non-zero remainder values**.\n\nBy the **Dirichlet Pigeonhole Principle**, among any $q$ successive division steps:\n$$r_1, r_2, r_3, \\dots, r_q$$\nat least two remainders must be identical:\n$$r_{i} = r_{i + L} \\quad \\text{for some } L \\ge 1, \\ i + L \\le q$$\nBecause the next remainder $r_{k+1}$ and next digit $d_{k+1}$ depend *solely* on the current remainder $r_k$, the moment a remainder repeats, the entire sequence of digits must repeat in an identical cycle of period $L \\le q - 1$. $\\blacksquare$\n\n---\n\n### 2.3 Period Length and Modular Orders\n\nWhen $\\gcd(10, q) = 1$ (the denominator shares no factors with 10), the decimal is **purely repeating** ($0.\\overline{d_1 \\dots d_L}$). The exact period length $L$ is governed by modular arithmetic:\n\n::: {#thm-period-length}\n#### Theorem 2.3 (Multiplicative Order of 10)\nIf $\\gcd(10, q) = 1$, the length $L$ of the repetend of $\\frac{p}{q}$ is the **multiplicative order of 10 modulo $q$**:\n$$L = \\operatorname{ord}_q(10) = \\min \\{ k \\in \\mathbb{N} : 10^k \\equiv 1 \\pmod q \\}$$\nBy Euler's Totient Theorem, $L \\mid \\phi(q)$.\n:::\n\n*Famous Example ($q = 7$)*:  \n$\\phi(7) = 6$. We test powers of 10 modulo 7:\n$$10^1 \\equiv 3 \\pmod 7$$\n$$10^2 \\equiv 2 \\pmod 7$$\n$$10^3 \\equiv 6 \\equiv -1 \\pmod 7$$\n$$10^4 \\equiv 4 \\pmod 7$$\n$$10^5 \\equiv 5 \\pmod 7$$\n$$10^6 \\equiv 1 \\pmod 7$$\nThe order is $L = 6$. Hence, $1/7$ has a maximal period of $6$ digits:\n$$\\frac{1}{7} = 0.\\overline{142857}$$\n\n---\n\n### 2.4 Converting Repeating Decimals to Fractions: The Dual Representation of 1\n\nTo convert $x = 0.\\overline{d_1 \\dots d_k}$ back to a fraction:\n$$10^k x = d_1 \\dots d_k.\\overline{d_1 \\dots d_k}$$\nSubtracting $x$:\n$$10^k x - x = d_1 \\dots d_k \\implies x = \\frac{d_1 \\dots d_k}{10^k - 1}$$\n\n#### The Proof that $0.999\\dots = 1$:\nLet $x = 0.\\overline{9} = 0.9999\\dots$\n$$10x = 9.9999\\dots$$\n$$10x - x = 9.9999\\dots - 0.9999\\dots \\implies 9x = 9 \\implies x = 1$$\nAlternatively, via infinite geometric series with $a = 9/10, r = 1/10$:\n$$0.999\\dots = \\sum_{n=1}^\\infty \\frac{9}{10^n} = \\frac{9/10}{1 - 1/10} = \\frac{9/10}{9/10} = 1$$\n\nThis reflects an inherent feature of positional base representations: **every terminating decimal has a dual representation ending in an infinite sequence of $9$s**.\n\n---\n\n## 3. The Algebra of Radicals: Equations vs. Functions and $\\sqrt{x^2} = |x|$\n\nFew mathematical concepts cause as much confusion as the square root. Students frequently ask:\n* *\"Why is the square root of $9$ both $+3$ and $-3$?\"*\n* *\"Why do textbooks say $\\sqrt{9} = 3$ only?\"*\n* *\"Why is $\\sqrt{x^2} = |x|$ instead of $\\pm x$?\"*\n\nThe confusion stems from a failure to distinguish between an **algebraic equation** and an **analytical function**.\n\n```\n                   THE CRITICAL EPISTEMIC DISTINCTION\n                   \n       THE ALGEBRAIC EQUATION                  THE PRINCIPAL ROOT FUNCTION\n       ──────────────────────                  ───────────────────────────\n             x^2 = 9                                     y = sqrt(x)\n                 │                                           │\n                 ▼                                           ▼\n       Find ALL solutions in R                 Single-valued mapping f: [0, inf) -> [0, inf)\n       Two solutions exist:                    Must satisfy the Vertical Line Test:\n       x = +3  OR  x = -3                      sqrt(9) = +3 ONLY!\n       Solution Set = {-3, +3}                 sqrt(9) != -3\n```\n\n---\n\n### 3.1 The Algebraic Equation: $x^2 = c$\n\nWhen solving the equation:\n$$x^2 = c \\quad (c > 0)$$\nwe are asking: *\"Which real numbers, when squared, yield $c$?\"*  \nBecause $(-a)^2 = (-1)^2 a^2 = a^2$, every positive real number $c$ has **two distinct square roots** in $\\mathbb{R}$:\n$$x = \\sqrt{c} \\quad \\text{and} \\quad x = -\\sqrt{c}$$\nWe express this concisely as $x = \\pm \\sqrt{c}$.\n\n---\n\n### 3.2 The Principal Square Root Function: Single-Valuedness\n\nIn mathematical analysis, a **function** $f: A \\to B$ must assign to each input $x \\in A$ **exactly one** output $y \\in B$. If $f(x)$ assigned both $+3$ and $-3$, it would fail the **Vertical Line Test** and cease to be a function.\n\n::: {#def-principal-root}\n#### Definition 3.1 (The Principal Square Root)\nFor any non-negative real number $x \\ge 0$, the radical symbol $\\sqrt{x}$ is defined as the **unique non-negative real number** $y \\ge 0$ such that $y^2 = x$:\n$$\\sqrt{x} = y \\iff y^2 = x \\quad \\text{and} \\quad y \\ge 0$$\n:::\n\nTherefore:\n$$\\sqrt{9} = +3 \\quad (\\text{NEVER } -3 \\text{ and NEVER } \\pm 3)$$\nThe symbol $\\pm$ does not belong to the root; it belongs to the *equation* solver.\n\n---\n\n### 3.3 Why $\\sqrt{x^2} = |x|$ (and NOT $x$)\n\nConsider the expression $\\sqrt{x^2}$ for an arbitrary real number $x \\in \\mathbb{R}$:\n\n* Let $x = 5$: $\\sqrt{5^2} = \\sqrt{25} = 5 = x$.\n* Let $x = -5$: $\\sqrt{(-5)^2} = \\sqrt{25} = 5 \\neq x$!\n\nIf we claimed that $\\sqrt{x^2} = x$, then for $x = -5$ we would conclude that $5 = -5$, which is absurd!  \nBecause the radical symbol $\\sqrt{\\cdot}$ always outputs a non-negative value:\n\n::: {#thm-abs-root}\n#### Theorem 3.1 (Square Root of a Square)\nFor all real numbers $x \\in \\mathbb{R}$:\n$$\\sqrt{x^2} = |x| = \\begin{cases} x & \\text{if } x \\ge 0 \\\\ -x & \\text{if } x < 0 \\end{cases}$$\n:::\n\nWriting $\\sqrt{x^2} = \\pm x$ is a fatal category error: $\\sqrt{x^2}$ is a single real number, not a two-element set.\n\n---\n\n### 3.4 Even vs. Odd Roots\n\nThe parity of the root index completely alters its algebraic topology:\n\n| Root Type | General Form | Natural Domain | Range | Invertible without restriction? | Identity on $x^n$ | Preserves Sign? |\n| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n| **Even Roots** | $f(x) = \\sqrt[2k]{x}$ | $[0, \\infty)$ | $[0, \\infty)$ | **NO** (Not injective on $\\mathbb{R}$) | $\\sqrt[2k]{x^{2k}} = |x|$ | **NO** (Always $\\ge 0$) |\n| **Odd Roots** | $f(x) = \\sqrt[2k+1]{x}$ | $(-\\infty, \\infty)$ | $(-\\infty, \\infty)$ | **YES** (Strictly monotonic bijection) | $\\sqrt[2k+1]{x^{2k+1}} = x$ | **YES** ($\\sqrt[3]{-8} = -2$) |\n\n```\n                       EVEN ROOT VS. ODD ROOT DYNAMICS\n                       \n         Even Root: y = sqrt(x)                      Odd Root: y = cbrt(x)\n              y                                           y\n              │   ╭─────                                  │       ╭─────\n              │  ╭                                        │      ╭\n              │ ╭                                         │     ╭\n       ───────┴───────────────── x                 ───────┼───────*─────── x\n              │                                         ╭ │\n              │                                        ╭  │\n              │                                  ─────╯   │\n       Domain: [0, inf)                           Domain: (-inf, inf)\n       Range:  [0, inf)                           Range:  (-inf, inf)\n```\n\n---\n\n### 3.5 Pitfalls with Complex Radicals: Why $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$ Fails\n\nIn high-school algebra, students learn the identity $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$.  \nIn the complex numbers, this identity breaks down and leads to classic pseudo-proofs:\n\n$$1 = \\sqrt{1} = \\sqrt{(-1) \\cdot (-1)} \\stackrel{\\text{FALLACY}}{=} \\sqrt{-1} \\cdot \\sqrt{-1} = i \\cdot i = -1 \\implies 1 = -1$$\n\n#### What Went Wrong?\nThe multiplicative rule $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$ holds **if and only if at least one of $a$ or $b$ is a non-negative real number**.\n\nIn the complex plane, the square root is a **multi-valued function** requiring a **branch cut** (conventionally along the negative real axis $(-\\infty, 0]$):\n$$z^{1/2} = \\sqrt{|z|} \\exp\\left(i \\frac{\\operatorname{Arg}(z) + 2\\pi k}{2}\\right), \\quad k \\in \\{0, 1\\}$$\nCrossing the branch cut introduces a sign inversion ($e^{i\\pi} \\leftrightarrow e^{-i\\pi}$), destroying naive algebraic manipulation.\n\n---\n\n## 4. The Bedrock of Arithmetic: Unique Factorization & The Infinity of Primes\n\n### 4.1 The Fundamental Theorem of Arithmetic\n\nThe Fundamental Theorem of Arithmetic (FTA) asserts that prime numbers are the atomic multiplicative building blocks of all integers:\n\n::: {#thm-fta}\n#### Theorem 4.1 (The Fundamental Theorem of Arithmetic)\nEvery integer $n > 1$ can be represented as a product of prime numbers:\n$$n = p_1^{a_1} p_2^{a_2} \\cdots p_k^{a_k}$$\nwhere $p_1 < p_2 < \\dots < p_k$ are primes and $a_i \\ge 1$ are positive integers. Furthermore, this factorization is **unique** up to the order of the factors.\n:::\n\n#### Proof of Existence (Strong Induction):\n* Base case: $n = 2$ is prime.\n* Inductive hypothesis: Assume true for all integers $2 \\le k \\le n$.\n* If $n+1$ is prime, we are done. If $n+1$ is composite, $n+1 = a \\cdot b$ where $1 < a, b < n+1$.  \n  By hypothesis, both $a$ and $b$ factor into primes. Thus, $n+1 = a \\cdot b$ factors into primes.\n\n#### Proof of Uniqueness: Why Euclid's Lemma is Mandatory\nMany students assume uniqueness is obvious. It is not! In other number systems, unique factorization fails catastrophically.  \nFor example, in the ring $\\mathbb{Z}[\\sqrt{-5}] = \\{a + b\\sqrt{-5} : a, b \\in \\mathbb{Z}\\}$:\n$$6 = 2 \\cdot 3 = (1 + \\sqrt{-5})(1 - \\sqrt{-5})$$\nHere, $2, 3, 1+\\sqrt{-5}$, and $1-\\sqrt{-5}$ are all irreducible, yet $6$ factors in two fundamentally different ways!\n\nTo prove uniqueness in $\\mathbb{Z}$, we require **Euclid's Lemma**:\n\n::: {#lem-euclid}\n#### Lemma 4.1 (Euclid's Lemma)\nIf a prime $p$ divides a product $ab$, then $p$ divides $a$ or $p$ divides $b$:\n$$p \\mid ab \\implies p \\mid a \\quad \\text{or} \\quad p \\mid b$$\n:::\n\n*Proof of Euclid's Lemma via Bézout's Identity*:  \nSuppose $p \\mid ab$ and $p \\nmid a$.  \nSince $p$ is prime and $p \\nmid a$, their greatest common divisor is $\\gcd(a, p) = 1$.  \nBy the [**Extended Euclidean Algorithm**](euclidean-algorithm-foundations-variants-and-numerical-computing.qmd) (see our exhaustive treatise on Euclidean variants and Bézout derivations), there exist integers $x, y \\in \\mathbb{Z}$ such that:\n$$a x + p y = 1 \\quad (\\text{Bézout's Identity})$$\nMultiply the entire equation by $b$:\n$$a b x + p b y = b$$\nNotice that $p \\mid abx$ (since $p \\mid ab$) and $p \\mid pby$ (since $p \\mid p$).  \nTherefore, $p$ divides their sum:\n$$p \\mid (abx + pby) \\implies p \\mid b$$\nThis completes Euclid's Lemma. $\\blacksquare$\n\n*Proof of FTA Uniqueness*:  \nSuppose $n = p_1 p_2 \\dots p_r = q_1 q_2 \\dots q_s$.  \nSince $p_1 \\mid n$, $p_1 \\mid (q_1 \\dots q_s)$. By repeated application of Euclid's lemma, $p_1 \\mid q_j$ for some $j$.  \nSince $q_j$ is prime, $p_1 = q_j$. Cancel $p_1$ from both sides and repeat inductively until all primes are matched. $\\blacksquare$\n\n---\n\n### 4.2 Three Master Proofs of the Infinitude of Primes\n\nIs the supply of prime numbers finite, or does it extend forever?\n\n#### Proof 1: Euclid's Constructive Reductio Proof (Elements IX, 20)\n* Assume for contradiction that the set of all primes is finite: $\\mathbb{P} = \\{p_1, p_2, \\dots, p_n\\}$.\n* Construct the integer:\n  $$N = (p_1 \\cdot p_2 \\dots p_n) + 1$$\n* Since $N > 1$, by FTA $N$ must have at least one prime divisor $q$.\n* If $q$ were in our list $\\mathbb{P}$, then $q = p_k$ for some $k$, so $q \\mid (p_1 \\dots p_n)$.\n* But $q \\mid N$, so $q$ must divide their difference:\n  $$q \\mid (N - p_1 \\dots p_n) \\implies q \\mid 1$$\n* This is impossible since no prime divides $1$.\n* Therefore, $q$ must be a new prime not in our list. Primes are infinite. $\\blacksquare$\n\n---\n\n#### Proof 2: Euler's Analytic Proof via the Harmonic Series (1737)\nEuler proved that not only are primes infinite, but **the sum of their reciprocals diverges**: $\\sum \\frac{1}{p} = \\infty$.\n\nBy the Fundamental Theorem of Arithmetic, every integer $n$ factors uniquely into primes. For any bound $X$:\n$$\\sum_{n \\le X} \\frac{1}{n} \\le \\prod_{p \\le X} \\left( 1 + \\frac{1}{p} + \\frac{1}{p^2} + \\frac{1}{p^3} + \\dots \\right) = \\prod_{p \\le X} \\frac{1}{1 - p^{-1}}$$\n\nAs $X \\to \\infty$, the harmonic series $\\sum_{n=1}^\\infty \\frac{1}{n}$ diverges to $\\infty$:\n$$\\lim_{X \\to \\infty} \\sum_{n \\le X} \\frac{1}{n} = \\infty \\implies \\prod_{p \\le X} \\frac{1}{1 - p^{-1}} \\to \\infty$$\nIf there were only finitely many primes, the product on the right would evaluate to a finite real number, which is a contradiction! Therefore, primes must be infinite. $\\blacksquare$\n\n---\n\n#### Proof 3: Furstenberg's Topological Proof (1955)\nIn 1955, as an undergraduate, **Hillel Furstenberg** proved the infinitude of primes using point-set topology on $\\mathbb{Z}$.\n\n* Define a topology on $\\mathbb{Z}$ where open sets are unions of two-sided arithmetic progressions:\n  $$N_{a, b} = a \\mathbb{Z} + b = \\{a k + b : k \\in \\mathbb{Z}\\} \\quad (a \\ge 1, b \\in \\mathbb{Z})$$\n* Each progression $N_{a, b}$ is **open** by definition.\n* But $N_{a, b}$ is also **closed**, because its complement is the union of the other $a-1$ disjoint residue classes:\n  $$\\mathbb{Z} \\setminus N_{a, b} = \\bigcup_{r=1}^{a-1} N_{a, b+r}$$\n  which is a finite union of open sets, hence open! Thus, $N_{a, b}$ is **clopen** (both closed and open).\n* Every integer $n \\notin \\{-1, 1\\}$ has at least one prime divisor. Therefore:\n  $$\\mathbb{Z} \\setminus \\{-1, 1\\} = \\bigcup_{p \\in \\mathbb{P}} N_{p, 0} = \\bigcup_{p \\in \\mathbb{P}} p\\mathbb{Z}$$\n* If the set of primes $\\mathbb{P}$ were finite, then $\\bigcup_{p \\in \\mathbb{P}} p\\mathbb{Z}$ would be a **finite union of closed sets**, which is **closed**!\n* If $\\mathbb{Z} \\setminus \\{-1, 1\\}$ were closed, its complement $\\{-1, 1\\}$ would have to be **open**.\n* But every non-empty open set in this topology is an infinite arithmetic progression, so $\\{-1, 1\\}$ cannot be open!\n* Contradiction! Hence, $\\mathbb{P}$ must be infinite. $\\blacksquare$\n\n---\n\n### 4.3 The Hidden Architecture of Perfect Numbers and Mersenne Primes\n\nSince Pythagorean antiquity, mathematicians have studied **perfect numbers**: integers that are equal to the exact sum of their proper positive divisors.\n\n::: {#def-perfect-number}\n#### Definition 4.2 (Divisor Sum Function and Perfect Numbers)\nLet $\\sigma(n) = \\sum_{d \\mid n} d$ denote the sum of all positive divisors of $n$. An integer $n \\ge 2$ is **perfect** if:\n$$\\sigma(n) = 2n \\iff \\sum_{d \\mid n, \\, d < n} d = n$$\n:::\n\n#### A. The Euclid-Euler Characterization Theorem\nThe complete classification of **even** perfect numbers is one of the most beautiful achievements in classical number theory, established across two millennia by Euclid (Elements IX, Prop. 36) and Leonhard Euler (1747).\n\n::: {#thm-euclid-euler}\n#### Theorem 4.3 (The Euclid-Euler Theorem)\nAn even positive integer $N$ is perfect if and only if it has the form:\n$$N = 2^{p-1}(2^p - 1)$$\nwhere $M_p = 2^p - 1$ is a **Mersenne prime** (which in turn requires that the exponent $p$ is prime).\n:::\n\n*Proof (Part 1: Euclid's Sufficiency)*:  \nSuppose $M_p = 2^p - 1$ is prime. The prime factorization of $N = 2^{p-1} M_p$ consists of powers of 2 and the single prime $M_p$.  \nBecause the divisor sum function $\\sigma$ is **multiplicative** ($\\gcd(2^{p-1}, M_p) = 1$):\n$$\\sigma(N) = \\sigma(2^{p-1}) \\cdot \\sigma(M_p)$$\nUsing the geometric series formula for powers of 2:\n$$\\sigma(2^{p-1}) = 1 + 2 + 2^2 + \\dots + 2^{p-1} = 2^p - 1 = M_p$$\nSince $M_p$ is prime, its only divisors are $1$ and $M_p$:\n$$\\sigma(M_p) = 1 + M_p = 1 + (2^p - 1) = 2^p$$\nMultiplying these together:\n$$\\sigma(N) = M_p \\cdot 2^p = (2^p - 1) \\cdot 2^p = 2 \\cdot \\left[2^{p-1}(2^p - 1)\\right] = 2N$$\nTherefore, $N$ is unconditionally perfect! $\\blacksquare$\n\n*Proof (Part 2: Euler's Necessity)*:  \nSuppose $N$ is an even perfect number. Factor out all powers of 2: $N = 2^{k-1} m$, where $k \\ge 2$ and $m$ is odd.  \nSince $\\sigma$ is multiplicative:\n$$\\sigma(N) = \\sigma(2^{k-1}) \\sigma(m) = (2^k - 1) \\sigma(m)$$\nBecause $N$ is perfect, $\\sigma(N) = 2N = 2^k m$. Thus:\n$$2^k m = (2^k - 1) \\sigma(m) \\implies \\frac{\\sigma(m)}{m} = \\frac{2^k}{2^k - 1}$$\nSince $\\gcd(2^k, 2^k - 1) = 1$, $m$ must be a multiple of $2^k - 1$. Let $m = c(2^k - 1)$ for some integer $c \\ge 1$.  \nThen $\\sigma(m) = c 2^k = c(2^k - 1) + c = m + c$.  \nIf $c > 1$, then $m$ would have at least three distinct divisors: $1, c, m$, so $\\sigma(m) \\ge m + c + 1 > m + c$, a contradiction!  \nTherefore, $c = 1$, which forces $m = 2^k - 1$ and $\\sigma(m) = m + 1$.  \nThe condition $\\sigma(m) = m + 1$ means that $m$ has **no proper divisors other than 1**—that is, $m = 2^k - 1$ must be **prime**! Setting $k = p$ completes the proof. $\\blacksquare$\n\n---\n\n#### B. The Hidden Binary Shift Pattern: Divisors as Differences of Powers of 2 ($2^{p+k} - 2^k$)\n\nA profound and underappreciated structural symmetry governs the divisors of every even perfect number $N = 2^{p-1}(2^p - 1)$. \n\nEvery divisor of $N$ is either of the form $2^a$ (for $0 \\le a \\le p-1$) or $2^k M_p = 2^k (2^p - 1)$ where $0 \\le k \\le p-1$. Expanding the product algebraically:\n$$d_k = 2^k (2^p - 1) = 2^{p+k} - 2^k$$\nEvery composite divisor involving the Mersenne factor is **identically the difference between two powers of 2 separated by exponent $p$**!\n\n```\n                  THE SUBTRACTIVE POWERS-OF-2 DIVISOR MATRIX\n                  \n  Perfect Number       Mersenne Factor     Divisor d_k = 2^k * M_p      Binary Shift Form (2^{p+k} - 2^k)\n  ──────────────       ───────────────     ───────────────────────      ─────────────────────────────────\n  6 (p=2)              M_2 = 3             d_0 = 1 * 3 = 3              2^2 - 2^0  (4 - 1 = 3)\n                                           d_1 = 2 * 3 = 6              2^3 - 2^1  (8 - 2 = 6)\n  ─────────────────────────────────────────────────────────────────────────────────────────────────\n  28 (p=3)             M_3 = 7             d_0 = 1 * 7 = 7              2^3 - 2^0  (8 - 1 = 7)\n                                           d_1 = 2 * 7 = 14             2^4 - 2^1  (16 - 2 = 14)\n                                           d_2 = 4 * 7 = 28             2^5 - 2^2  (32 - 4 = 28)\n  ─────────────────────────────────────────────────────────────────────────────────────────────────\n  496 (p=5)            M_5 = 31            d_0 = 1 * 31 = 31            2^5 - 2^0  (32 - 1 = 31)\n                                           d_1 = 2 * 31 = 62            2^6 - 2^1  (64 - 2 = 62)\n                                           d_2 = 4 * 31 = 124           2^7 - 2^2  (128 - 4 = 124)\n                                           d_3 = 8 * 31 = 248           2^8 - 2^3  (256 - 8 = 248)\n                                           d_4 = 16 * 31 = 496          2^9 - 2^4  (512 - 16 = 496)\n  ─────────────────────────────────────────────────────────────────────────────────────────────────\n  8128 (p=7)           M_7 = 127           d_0 = 1 * 127 = 127          2^7 - 2^0  (128 - 1 = 127)\n                                           d_1 = 2 * 127 = 254          2^8 - 2^1  (256 - 2 = 254)\n                                           d_2 = 4 * 127 = 508          2^9 - 2^2  (512 - 4 = 508)\n                                           d_3 = 8 * 127 = 1016         2^{10} - 2^3 (1024 - 8 = 1016)\n                                           d_4 = 16 * 127 = 2032        2^{11} - 2^4 (2048 - 16 = 2032)\n                                           d_5 = 32 * 127 = 4064        2^{12} - 2^5 (4096 - 32 = 4064)\n                                           d_6 = 64 * 127 = 8128        2^{13} - 2^6 (8192 - 64 = 8128)\n```\n\n##### Why This Occurs: The Positional Binary Bit-Shift\nIn base-2 (binary), $2^p - 1$ is represented as a solid block of $p$ consecutive ones:\n$$M_p = 2^p - 1 = \\underbrace{11\\dots 1}_{p \\text{ ones}}_2$$\nMultiplying any binary number by $2^k$ is equivalent to a **logical bit-shift to the left by $k$ positions**, appending $k$ trailing zeros:\n$$d_k = 2^k \\cdot M_p = \\underbrace{11\\dots 1}_{p \\text{ ones}}\\underbrace{00\\dots 0}_{k \\text{ zeros}}_2$$\nSubtracting $2^k = 1\\underbrace{00\\dots 0}_{k \\text{ zeros}}_2$ from $2^{p+k} = 1\\underbrace{00\\dots 0}_{p+k \\text{ zeros}}_2$ algebraically produces precisely that block of $p$ ones shifted by $k$ positions!\n\nThis reveals the stunning geometric structure of perfect numbers in binary:\n* $6_{10} = 110_2$ (two 1s, one 0)\n* $28_{10} = 11100_2$ (three 1s, two 0s)\n* $496_{10} = 111110000_2$ (five 1s, four 0s)\n* $8128_{10} = 1111111000000_2$ (seven 1s, six 0s)\n* $33550336_{10} = 1111111111111000000000000_2$ (thirteen 1s, twelve 0s)\n\n::: {#thm-binary-perfect}\n#### Theorem 4.4 (Binary Characterization of Even Perfect Numbers)\nIn base 2, every even perfect number $N = 2^{p-1}(2^p - 1)$ is represented by exactly $p$ consecutive ones followed by $p - 1$ consecutive zeros, spanning a total bit length of $2p - 1$.\n:::\n\n---\n\n#### C. Other Deep Symmetries of Perfect Numbers\n\n1. **Triangular Numbers:**\n   Every even perfect number is the $M_p$-th triangular number:\n   $$N = T_{M_p} = \\frac{M_p(M_p + 1)}{2} = \\frac{(2^p - 1)2^p}{2} = 2^{p-1}(2^p - 1)$$\n   For example: $6 = T_3 = 1+2+3$, $28 = T_7 = 1+2+\\dots+7$, $496 = T_{31} = 1+2+\\dots+31$.\n\n2. **Sum of Consecutive Odd Cubes:**\n   Every even perfect number (except 6) is the sum of the first $2^{(p-1)/2}$ consecutive odd cubes:\n   $$N = \\sum_{k=1}^{2^{(p-1)/2}} (2k - 1)^3$$\n   * $p = 3 \\implies 28 = 1^3 + 3^3 = 1 + 27$\n   * $p = 5 \\implies 496 = 1^3 + 3^3 + 5^3 + 7^3 = 1 + 27 + 125 + 343$\n   * $p = 7 \\implies 8128 = 1^3 + 3^3 + 5^3 + 7^3 + 9^3 + 11^3 + 13^3 + 15^3$\n\n3. **Sum of Reciprocals of All Divisors:**\n   The sum of the reciprocals of all positive divisors of any perfect number is **identically 2**:\n   $$\\sum_{d \\mid N} \\frac{1}{d} = \\frac{1}{N} \\sum_{d \\mid N} d = \\frac{\\sigma(N)}{N} = \\frac{2N}{N} = 2$$\n   * For $6$: $\\frac{1}{1} + \\frac{1}{2} + \\frac{1}{3} + \\frac{1}{6} = \\frac{6+3+2+1}{6} = \\frac{12}{6} = 2$.\n   * For $28$: $\\frac{1}{1} + \\frac{1}{2} + \\frac{1}{4} + \\frac{1}{7} + \\frac{1}{14} + \\frac{1}{28} = \\frac{28+14+7+4+2+1}{28} = \\frac{56}{28} = 2$.\n   This implies that the **harmonic mean** of the divisors of a perfect number is always an integer (an Ore harmonic number): $H(N) = \\frac{\\tau(N)}{\\sum_{d \\mid N} 1/d} = \\frac{\\tau(N)}{2} = p$.\n\n4. **Digital Roots in Base 10:**\n   Except for 6, the digital root (repeated sum of digits modulo 9) of every even perfect number is **strictly 1**:\n   * $28 \\to 2 + 8 = 10 \\to 1 + 0 = 1$\n   * $496 \\to 4 + 9 + 6 = 19 \\to 1 + 9 = 10 \\to 1$\n   * $8128 \\to 8 + 1 + 2 + 8 = 19 \\to 10 \\to 1$\n   *Proof:* Since $p \\ge 3$ is prime, $p$ is odd, so $p \\equiv 1 \\text{ or } 5 \\pmod 6$. Computing $2^{p-1}(2^p - 1) \\pmod 9$ yields $1$ in all cases.\n\n5. **The Unsolved Millennium Mystery: Do Odd Perfect Numbers Exist?**\n   No odd perfect number has ever been found, nor has their nonexistence been proven. Euler proved that if an odd perfect number $N$ exists, it must have the special form $N = q^k \\prod_{i=1}^r p_i^{2e_i}$ where $q \\equiv k \\equiv 1 \\pmod 4$ and $q$ is prime (the \"special\" prime). Modern computational searches (Ochem & Rao, 2012) have proven that any odd perfect number must satisfy:\n   $$N > 10^{1500}, \\quad \\text{and must contain at least 101 prime factors (not necessarily distinct)}.$$\n\n---\n\n## 5. The Riemann Hypothesis: The Cosmic Blueprint of the Primes\n\nHow are prime numbers distributed across the infinite expanse of integers? \n\nIn 1859, **Bernhard Riemann** published an 8-page paper—*Ueber die Anzahl der Primzahlen unter einer gegebenen Grösse* (\"On the Number of Primes Less Than a Given Magnitude\")—that connected the discrete distribution of prime numbers to the zeros of an analytical complex function.\n\n```\n                              THE RIEMANN ZETA LANDSCAPE\n                              \n                Im(s)\n                  │\n                  │              CRITICAL STRIP (0 < Re(s) < 1)\n                  │                            │\n             +25i ┼                           │  * (1/2 + 25.01i)\n                  │                            │\n             +21i ┼                           │  * (1/2 + 21.02i)\n                  │                            │\n             +14i ┼                           │  * (1/2 + 14.13i)\n                  │                            │\n                  │     TRIVIAL ZEROS          │   CRITICAL LINE\n                  │     (Negative Evens)       │   Re(s) = 1/2\n       ───────────┼──*─────*─────*─────*───────┼─────────────────► Re(s)\n                  │ -6    -4    -2     0       │ 1/2      1\n                  │                            │\n             -14i ┼                           │  * (1/2 - 14.13i)\n                  │                            │\n             -21i ┼                           │  * (1/2 - 21.02i)\n                  │                            │\n```\n\n---\n\n### 5.1 The Riemann Zeta Function & The Euler Product\n\nFor complex numbers $s = \\sigma + i t$ with $\\operatorname{Re}(s) = \\sigma > 1$, the zeta function is defined by the Dirichlet series:\n$$\\zeta(s) = \\sum_{n=1}^\\infty \\frac{1}{n^s} = 1 + \\frac{1}{2^s} + \\frac{1}{3^s} + \\frac{1}{4^s} + \\dots$$\n\nBy the Fundamental Theorem of Arithmetic, this sum factors into **Euler's Product Formula**:\n$$\\zeta(s) = \\prod_{p \\in \\mathbb{P}} \\frac{1}{1 - p^{-s}} = \\frac{1}{1 - 2^{-s}} \\cdot \\frac{1}{1 - 3^{-s}} \\cdot \\frac{1}{1 - 5^{-s}} \\cdots$$\n\nThis product is the bridge between discrete primes and continuous complex analysis: **the prime numbers are encoded into the analytic structure of $\\zeta(s)$**.\n\n---\n\n### 5.2 Analytic Continuation & The Functional Equation\n\nThe Dirichlet series diverges when $\\operatorname{Re}(s) \\le 1$. Riemann extended $\\zeta(s)$ across the entire complex plane $\\mathbb{C}$ via **analytic continuation**, showing it has a single simple pole at $s = 1$ with residue $1$.\n\nRiemann established the pristine **functional equation**:\n$$\\pi^{-s/2} \\Gamma\\left(\\frac{s}{2}\\right) \\zeta(s) = \\pi^{-(1-s)/2} \\Gamma\\left(\\frac{1-s}{2}\\right) \\zeta(1-s)$$\nwhere $\\Gamma(z) = \\int_0^\\infty t^{z-1} e^{-t} dt$ is the Gamma function.\n\nDefining the completed **Riemann $\\xi$-function** (Xi):\n$$\\xi(s) = \\frac{1}{2} s(s-1) \\pi^{-s/2} \\Gamma\\left(\\frac{s}{2}\\right) \\zeta(s)$$\nthe functional equation becomes a reflection symmetry across the line $\\operatorname{Re}(s) = 1/2$:\n$$\\xi(s) = \\xi(1-s)$$\n\n---\n\n### 5.3 The Geometry of the Zeros\n\nThe zeros of $\\zeta(s)$ are divided into two distinct categories:\n\n1. **The Trivial Zeros**: The Gamma function $\\Gamma(s/2)$ has poles at $s = 0, -2, -4, -6, \\dots$. In the functional equation, to cancel these poles, $\\zeta(s)$ must vanish at the negative even integers:\n   $$s \\in \\{-2, -4, -6, -8, -10, \\dots\\}$$\n2. **The Non-Trivial Zeros**: Lie exclusively in the **Critical Strip**:\n   $$0 \\le \\operatorname{Re}(s) \\le 1$$\n   Because of the reflection symmetry $\\xi(s) = \\xi(1-s)$ and complex conjugation $\\zeta(\\bar{s}) = \\overline{\\zeta(s)}$, non-trivial zeros are symmetric across both the real axis and the **Critical Line** $\\operatorname{Re}(s) = 1/2$.\n\n::: {#thm-riemann-hypothesis}\n#### The Riemann Hypothesis (Bernhard Riemann, 1859)\nEvery non-trivial zero $\\rho$ of the Riemann zeta function has real part equal to $1/2$:\n$$\\zeta(\\rho) = 0, \\ \\rho \\notin \\{-2, -4, \\dots\\} \\implies \\operatorname{Re}(\\rho) = \\frac{1}{2}$$\nThat is, all non-trivial zeros lie precisely on the **Critical Line**:\n$$\\rho_n = \\frac{1}{2} \\pm i \\gamma_n$$\n:::\n\n#### The First Non-Trivial Zeros (Computed to High Precision):\n* $\\rho_1 = \\frac{1}{2} \\pm 14.134725141734693\\dots i$\n* $\\rho_2 = \\frac{1}{2} \\pm 21.022039638771554\\dots i$\n* $\\rho_3 = \\frac{1}{2} \\pm 25.010857580145688\\dots i$\n* $\\rho_4 = \\frac{1}{2} \\pm 30.424876125859513\\dots i$\n* Over **10 trillion** zeros have been computed numerically—every single one lies on the line $\\operatorname{Re}(s) = 1/2$!\n\n---\n\n### 5.4 The Explicit Formula: \"The Music of the Primes\"\n\nWhy do the zeros on the line $\\operatorname{Re}(s) = 1/2$ matter? Because Riemann derived an **Exact Formula** for the distribution of prime numbers.\n\nLet $\\psi(x) = \\sum_{p^k \\le x} \\ln p$ be Chebyshev's prime-counting function. Riemann proved:\n$$\\psi(x) = x - \\sum_{\\rho} \\frac{x^\\rho}{\\rho} - \\ln(2\\pi) - \\frac{1}{2} \\ln(1 - x^{-2})$$\n\n```\n                            RIEMANN'S EXPLICIT FORMULA\n                            \n   psi(x)  =      x      -      sum_rho ( x^rho / rho )      -   ln(2*pi)\n                  │                        │\n                  ▼                        ▼\n           Smooth Linear Trend       Oscillatory Waves\n           (Average prime growth)    (Harmonics generated by each zero rho)\n```\n\nEach zero $\\rho = \\frac{1}{2} + i \\gamma$ contributes a sinusoidal fluctuation:\n$$\\frac{x^\\rho}{\\rho} = \\frac{x^{1/2 + i\\gamma}}{\\frac{1}{2} + i\\gamma} = \\frac{x^{1/2} e^{i \\gamma \\ln x}}{\\frac{1}{2} + i\\gamma}$$\n\n#### The Physical Analogy:\n* In acoustics, a musical sound is decomposed by Fourier analysis into a fundamental tone plus harmonic overtones.\n* In number theory, the prime numbers are the discrete spikes (the sound), and the zeros of the zeta function $\\gamma_n$ are the **frequencies of the harmonic overtones**!\n\n#### The Prime Number Theorem and the Error Bound:\n* **The Prime Number Theorem (1896)**: $\\pi(x) \\sim \\operatorname{Li}(x) = \\int_2^x \\frac{dt}{\\ln t}$ is mathematically equivalent to the statement that **$\\zeta(s)$ has no zeros on the boundary $\\operatorname{Re}(s) = 1$**. (Proved independently by Jacques Hadamard and Charles Jean de la Vallée Poussin).\n* **The Power of RH**: If the Riemann Hypothesis is true, the real part of every zero is $\\operatorname{Re}(\\rho) = 1/2$. Therefore, the magnitude of every fluctuation $x^\\rho$ is exactly $x^{1/2} = \\sqrt{x}$.  \n  This guarantees that the prime numbers are distributed with **the minimum possible statistical fluctuation**:\n  $$|\\pi(x) - \\operatorname{Li}(x)| \\le \\frac{1}{8\\pi} \\sqrt{x} \\ln x \\quad (\\text{for } x \\ge 2657)$$\n  If any zero had $\\operatorname{Re}(\\rho) > 1/2$, say $\\operatorname{Re}(\\rho) = 0.8$, the prime counting error would wildly oscillate like $x^{0.8}$, which has never been observed in any computation.\n\n---\n\n## 6. Computational Laboratory: Python Numerical Engine\n\nBelow is a Python demonstration showing:\n1. Long-division repetend detector and period analyzer.\n2. Verification of the radical identity $\\sqrt{x^2} = |x|$ across negative and positive numbers.\n3. Fast prime factorization via trial division.\n4. Evaluation of the Riemann zeta function $\\zeta(1/2 + it)$ along the critical line using `mpmath`.\n\n```python\nimport mpmath as mp\nimport numpy as np\n\n# Set precision to 30 decimal digits\nmp.mp.dps = 30\n\nprint(\"=== 1. DECIMAL REPETEND & PERIOD DETECTOR ===\")\ndef get_decimal_expansion(p, q):\n    \"\"\"Computes decimal representation, detecting terminating vs repeating periods.\"\"\"\n    integer_part = p // q\n    remainder = p % q\n    if remainder == 0:\n        return f\"{integer_part}.0 (Terminating)\"\n    \n    seen_remainders = {}\n    digits = []\n    step = 0\n    \n    while remainder != 0 and remainder not in seen_remainders:\n        seen_remainders[remainder] = step\n        remainder *= 10\n        digits.append(str(remainder // q))\n        remainder = remainder % q\n        step += 1\n        \n    if remainder == 0:\n        return f\"{integer_part}.\" + \"\".join(digits) + \" (Terminating)\"\n    else:\n        loop_start = seen_remainders[remainder]\n        non_rep = \"\".join(digits[:loop_start])\n        rep = \"\".join(digits[loop_start:])\n        return f\"{integer_part}.{non_rep}({rep}) [Period L = {len(rep)}]\"\n\nfractions = [(3, 8), (1, 7), (1, 6), (7, 13), (1, 17), (1, 19)]\nfor p, q in fractions:\n    print(f\"{p}/{q:2d} = {get_decimal_expansion(p, q)}\")\n\nprint(\"\\n=== 2. RADICAL IDENTITY: sqrt(x^2) = |x| ===\")\ntest_values = [-10.5, -3, 0, 4, 9.2]\nfor x in test_values:\n    calc_root = float(mp.sqrt(x**2))\n    abs_val = abs(x)\n    print(f\"x = {x:5.1f} | x^2 = {x**2:6.2f} | sqrt(x^2) = {calc_root:5.1f} | |x| = {abs_val:5.1f} | Matches? {calc_root == abs_val}\")\n\nprint(\"\\n=== 3. PRIME FACTORIZATION (FUNDAMENTAL THEOREM OF ARITHMETIC) ===\")\ndef prime_factors(n):\n    factors = {}\n    d = 2\n    temp = n\n    while d * d <= temp:\n        while temp % d == 0:\n            factors[d] = factors.get(d, 0) + 1\n            temp //= d\n        d += 1\n    if temp > 1:\n        factors[temp] = factors.get(temp, 0) + 1\n    return factors\n\ntest_numbers = [84, 360, 2026, 104729 * 13]\nfor num in test_numbers:\n    facs = prime_factors(num)\n    fac_str = \" * \".join([f\"{p}^{a}\" if a > 1 else f\"{p}\" for p, a in facs.items()])\n    print(f\"{num} = {fac_str}\")\n\nprint(\"\\n=== 4. RIEMANN ZETA FUNCTION ON THE CRITICAL LINE Re(s) = 1/2 ===\")\n# Evaluate |zeta(1/2 + it)| around the first three non-trivial zeros\nt_values = [14.134725, 21.022040, 25.010858, 30.424876]\nprint(\"Evaluating |zeta(1/2 + it)| at the known zeros:\")\nfor t in t_values:\n    s = mp.mpc(0.5, t)\n    val = mp.zeta(s)\n    print(f\"t = {t:9.6f} | zeta(1/2 + {t:9.6f}i) = {mp.nstr(val, 6)} | |zeta| = {mp.nstr(abs(val), 6)} (≈ 0)\")\n\nprint(\"\\n=== 5. PERFECT NUMBERS: SUBTRACTIVE POWERS-OF-2 & BINARY SHIFTS ===\")\ndef analyze_perfect_number(p):\n    M_p = 2**p - 1\n    N = 2**(p - 1) * M_p\n    # Generate all divisors\n    divs = []\n    for d in range(1, int(N**0.5) + 1):\n        if N % d == 0:\n            divs.append(d)\n            if d*d != N:\n                divs.append(N // d)\n    all_divs = sorted(divs)\n    \n    is_perf = sum(all_divs[:-1]) == N\n    shift_matches = []\n    for k in range(p):\n        d_k = (2**k) * M_p\n        formula_val = 2**(p + k) - 2**k\n        shift_matches.append((k, d_k, formula_val, d_k == formula_val))\n        \n    bin_str = bin(N)[2:]\n    expected_bin = \"1\" * p + \"0\" * (p - 1)\n    harmonic_mean = len(all_divs) / sum(1.0 / d for d in all_divs)\n    \n    return {\n        \"p\": p, \"N\": N, \"M_p\": M_p, \"is_perfect\": is_perf,\n        \"bin_str\": bin_str, \"bin_matches\": bin_str == expected_bin,\n        \"shift_matches\": shift_matches, \"harmonic_mean\": harmonic_mean\n    }\n\nfor p_val in [2, 3, 5, 7]:\n    res = analyze_perfect_number(p_val)\n    print(f\"p = {res['p']} | N = {res['N']:5d} | M_p = {res['M_p']:3d} | Binary: {res['bin_str']} (Matches? {res['bin_matches']}) | H(N) = {res['harmonic_mean']:.1f}\")\n    for k, d_k, form_val, ok in res['shift_matches']:\n        print(f\"   k={k}: 2^{res['p']+k} - 2^{k} = {form_val:5d} == divisor {d_k:5d} ({ok})\")\n```\n\n---\n\n## 7. Curated References and Primary Sources\n\n1. **Euclid of Alexandria (c. 300 BCE)**. *The Elements*, Books VII & IX (Unique Factorization, Euclid's Lemma, Infinitude of Primes).\n2. **Euler, Leonhard (1737)**. *\"Variae observationes circa series infinitas\"*. Commentarii academiae scientiarum Petropolitanae, 9: 160–188 (Introduction of the Euler product).\n3. **Riemann, Bernhard (1859)**. *\"Ueber die Anzahl der Primzahlen unter einer gegebenen Grösse\"*. Monatsberichte der Berliner Akademie, 671–680.\n4. **Furstenberg, Hillel (1955)**. *\"On the infinitude of primes\"*. American Mathematical Monthly, 62(5): 353.\n5. **Cantor, Georg (1874)**. *\"Über eine Eigenschaft des Inbegriffes aller reellen algebraischen Zahlen\"*. Crelle's Journal, 77: 258–262.\n6. **Hardy, G. H., & Wright, E. M. (2008)**. *An Introduction to the Theory of Numbers* (6th ed.). Oxford University Press.\n7. **Titchmarsh, E. C. (1986)**. *The Theory of the Riemann Zeta-Function* (2nd ed., rev. by D. R. Heath-Brown). Oxford University Press.\n8. **Ore, Øystein (1948)**. *\"On the averages of the divisors of a number\"*. The American Mathematical Monthly, 55(10): 615–619.\n9. **Ochem, Pascal, & Rao, Michaël (2012)**. *\"Odd perfect numbers are greater than $10^{1500}$\"*. Mathematics of Computation, 81(279): 1869–1877.\n\n\n## Appendix: Readily Applicable Code — Counting Primes and the Zeta Function\n\nTwo of the article's central objects are easy to experiment with: the prime-counting function pi(x) and the Riemann zeta function zeta(s).\n\n::: {#e951d38b .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport mpmath as mp\n\ndef sieve(n):\n    s = np.ones(n + 1, bool); s[:2] = False\n    for i in range(2, int(n**0.5) + 1):\n        if s[i]:\n            s[i*i::i] = False\n    return np.nonzero(s)[0]\n\nN = 5_000_000\nprimes = sieve(N)\nxs = np.logspace(2, np.log10(N), 24).astype(int)\nprint(\"=== PRIME COUNTING THEOREM ===\")\nprint(f\"{'x':>10} {'pi(x)':>10} {'x/ln x':>10} {'Li(x)':>10}\")\nfor xv in xs[::4]:\n    pi = np.searchsorted(primes, xv, side=\"right\")\n    print(f\"{xv:>10} {pi:>10} {xv/np.log(xv):>10.0f} {float(mp.li(xv)):>10.0f}\")\n\nprint(\"\\n=== RIEMANN ZETA ===\")\nprint(f\"  zeta(2) = {float(mp.zeta(2)):.10f}  (pi^2/6 = {np.pi**2/6:.10f})\")\nrho = mp.zetazero(1)\nprint(f\"  first nontrivial zero: rho = 0.5 + {float(rho.imag):.6f}i\")\nprint(\"  the Riemann Hypothesis says every nontrivial zero has real part 1/2.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== PRIME COUNTING THEOREM ===\n         x      pi(x)     x/ln x      Li(x)\n       100         25         22         30\n       656        119        101        126\n      4309        590        515        602\n     28290       3081       2760       3111\n    185715      16808      15308      16862\n   1219160      94286      86998      94374\n\n=== RIEMANN ZETA ===\n  zeta(2) = 1.6449340668  (pi^2/6 = 1.6449340668)\n  first nontrivial zero: rho = 0.5 + 14.134725i\n  the Riemann Hypothesis says every nontrivial zero has real part 1/2.\n```\n:::\n:::\n\n\n",
    "supporting": [
      "foundations-of-arithmetic-primes-radicals-and-the-riemann-hypothesis_files"
    ],
    "filters": [],
    "includes": {}
  }
}