{
  "hash": "e82e04d676b503814943c23072ad1e50",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Dynamical Systems and Chaos: Iteration, Initial Conditions, and the Butterfly Effect\"\nsubtitle: \"Fixed points, stability, and the logistic map; period-doubling and the Feigenbaum constant; sensitive dependence and Lyapunov exponents; strange attractors and the Lorenz system; the butterfly effect, predictability horizons, and why deterministic does not mean predictable\"\nauthor: \"Igor Kan\"\ndate: \"2026-09-14\"\ncategories: [Mathematics, Dynamical Systems, Chaos Theory, Nonlinear Systems, Physics, Computation]\ndescription: \"A comprehensive treatment of dynamical systems and chaos. It defines discrete maps and continuous flows, fixed points, periodic orbits, and stability via linearization; develops the logistic map from stable fixed points through period-doubling to chaos and the Feigenbaum universality; defines sensitive dependence on initial conditions and the Lyapunov exponent and relates them to stretching-and-folding and mixing; explains the butterfly effect through the Lorenz equations and the three-body problem; describes attractors from fixed points and limit cycles to strange attractors and their fractal dimension; surveys routes to chaos including period-doubling, intermittency, and quasiperiodicity; connects chaos to ergodic theory, unpredictability horizons, and applications, and relates iteration to the Collatz problem and Newton's method, with an executable Python laboratory producing bifurcation diagrams, Lyapunov exponents, sensitivity experiments, and the Lorenz attractor.\"\nformat:\n  html:\n    html-math-method: mathjax\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 4\n    number-sections: true\njupyter: python3\ntoc: true\ntoc-depth: 4\nnumber-sections: true\n---\n\n::: {.callout-note appearance=\"simple\"}\n*\"The flapping of a butterfly's wings in Brazil could set off a tornado in Texas.\"* — attributed to Edward Lorenz\n\nA **dynamical system** is a rule for how a state evolves. When the rule is nonlinear, tiny differences in the initial condition can grow exponentially, so long-term prediction becomes impossible even though the system is fully deterministic. This is **chaos**, and it is everywhere: weather, ecosystems, fluids, circuits, orbits, populations.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Companion Treatises in this Series\n- [The 3x+1 Problem: Collatz Orbits and Similar Iterations](collatz-conjecture-3x-plus-1-orbits-and-similar-iterations.qmd)\n- [Iterative Methods and Computing the Constants](iterative-methods-and-computing-constants-pi-and-eulers-constant.qmd)\n- [Phase Space, Systems, and Sturm–Liouville](analysis-17-phase-space-systems-sturm-liouville.qmd)\n- [Dynamical Systems, Picard–Lindelöf, and Lie Theory](analysis-09-dynamical-systems-picard-lindelof-lie.qmd)\n- [Functions of Several Variables and Submanifolds](analysis-14-multivariable-derivatives-submanifolds.qmd)\n:::\n\n---\n\n## What Is a Dynamical System?\n\nA **dynamical system** consists of a **state space** $M$ and an **evolution rule**:\n\n- **Discrete-time (map):** $x_{n+1}=f(x_n)$, $f:M\\to M$. This is iteration.\n- **Continuous-time (flow):** $\\dot x=F(x)$, a differential equation; the solution is a curve $\\varphi_t(x_0)$.\n\nThe system is **deterministic**: the future is uniquely fixed by the present state. Determinism, however, does **not** imply predictability — that is the central lesson of chaos.\n\n### Fixed Points, Periodic Orbits, Stability\n\nA **fixed point** $x^\\*$ satisfies $f(x^\\*)=x^\\*$ (discrete) or $F(x^\\*)=0$ (continuous). Its **stability** is decided by linearization:\n\n- Discrete: the eigenvalue(s) of $Df(x^\\*)$; stable if all $|\\lambda|<1$; the **multiplier**.\n- Continuous: the eigenvalues of $DF(x^\\*)$; stable if all have negative real part.\n\nA **periodic orbit** has $f^p(x)=x$ for some $p>0$; its stability is decided by the derivative of the $p$-th iterate, the **multiplier** $\\prod_{i=0}^{p-1}f'(x_i)$.\n\n**Bifurcations** are qualitative changes as a parameter varies: saddle-node, transcritical, pitchfork, Hopf, and period-doubling.\n\n---\n\n## The Logistic Map\n\nThe textbook discrete system is the **logistic map**\n\n$$\nx_{n+1}=r\\,x_n(1-x_n),\\qquad x\\in[0,1],\\ r\\in[0,4],\n$$\n\na model of population with growth rate $r$ and crowding.\n\n### Fixed Points and Stability\n\nNonzero fixed point: $x^\\*=1-1/r$ (for $r>1$). The multiplier is $f'(x^\\*)=2-r$, so:\n\n- $0<r<1$: $x^\\*=0$ stable; population dies out.\n- $1<r<3$: $x^\\*=1-1/r$ stable.\n- $r=3$: **period-doubling** — the fixed point loses stability and a stable 2-cycle appears.\n- $r=3.449\\ldots$: the 2-cycle doubles to a 4-cycle.\n- Cascades continue at $r=3.544, 3.564, \\dots$ accumulating at $r_\\infty\\approx3.5699$.\n\n### Period-Doubling and Feigenbaum Universality\n\nThe bifurcation points $r_n$ converge geometrically with ratio\n\n$$\n\\delta=\\lim_{n\\to\\infty}\\frac{r_{n}-r_{n-1}}{r_{n+1}-r_n}\\approx4.6692,\n$$\n\nthe **Feigenbaum constant**. Astonishingly, $\\delta$ (and the scaling $\\alpha\\approx2.5029$) is **universal**: the same constants appear in any smooth unimodal map undergoing period-doubling — a deep statement about the geometry of bifurcations, not about the logistic map specifically.\n\nBeyond $r_\\infty$, the dynamics is chaotic for most $r$, punctuated by **periodic windows** (e.g. a stable 3-cycle near $r\\approx3.83$).\n\n---\n\n## Chaos: Sensitive Dependence\n\nA map is **chaotic** (on an invariant set) if it has:\n\n1. **Sensitive dependence on initial conditions** — nearby states separate exponentially.\n2. **Topological transitivity / mixing** — the orbit wanders densely through the set.\n3. **Dense periodic orbits.**\n\nThe first is quantified by the **Lyapunov exponent**\n$$\n\\lambda=\\lim_{n\\to\\infty}\\frac1n\\sum_{i=0}^{n-1}\\ln|f'(x_i)|.\n$$\n$\\lambda>0$ means exponential divergence: an initial error $\\epsilon$ grows like $\\epsilon e^{\\lambda n}$. Positive Lyapunov exponent is the formal signature of chaos; a **predictability horizon** follows: to predict $T$ steps, the initial uncertainty must be below $\\sim e^{-\\lambda T}$.\n\n### Stretching and Folding\n\nChaos requires two competing actions: **stretching** (which amplifies differences) and **folding** (which keeps the state bounded). The logistic map's parabola does both. This is why chaotic attractors are **fractal** — infinitely layered sets of non-integer dimension.\n\n---\n\n## The Butterfly Effect and the Lorenz System\n\n**Edward Lorenz (1963)** studied a truncated model of atmospheric convection:\n\n$$\n\\dot x=\\sigma(y-x),\\qquad\n\\dot y=x(\\rho-z)-y,\\qquad\n\\dot z=xy-\\beta z,\n$$\n\nwith classical parameters $\\sigma=10$, $\\rho=28$, $\\beta=8/3$. The flow has a **strange attractor** — the \"butterfly.\" Two trajectories from almost identical initial conditions separate exponentially, so weather forecasts lose skill beyond roughly two weeks. Lorenz's observation — that rounding a printed initial value from six digits to three changed a long-term forecast — became the **butterfly effect**.\n\nThe same phenomenon appears in the **three-body problem** (Poincaré, 1890): no general closed-form solution, and arbitrarily small changes produce qualitatively different orbits. **Deterministic chaos is the norm in nonlinear systems, not the exception.**\n\n---\n\n## Attractors and Routes to Chaos\n\nAn **attractor** is a set toward which nearby trajectories converge:\n\n| Attractor | Dimension | Example |\n|---|---|---|\n| Fixed point | 0 | damped pendulum at rest |\n| Limit cycle | 1 | Van der Pol oscillator, heartbeat |\n| Torus | integer | quasiperiodic motion |\n| **Strange attractor** | **fractal** | Lorenz, Rössler, logistic map |\n\n**Routes to chaos** (all observed in experiment):\n\n- **Period-doubling (Feigenbaum):** the logistic route; universal.\n- **Intermittency (Pomeau–Manneville):** long regular phases interrupted by chaotic bursts.\n- **Quasiperiodicity (Ruelle–Takens–Newhouse):** two/three incommensurate frequencies destabilize into a strange attractor.\n\nChaos links to **ergodic theory** (invariant measures, mixing, Birkhoff's ergodic theorem), **fractal geometry** (Hausdorff dimension, the Mandelbrot and Julia sets of $z\\mapsto z^2+c$), and **information theory** (positive entropy = information generation).\n\n---\n\n## Why It Matters\n\n- **Weather and climate:** prediction horizons; ensemble forecasting.\n- **Ecology and epidemiology:** population cycles, tipping points.\n- **Engineering:** turbulence, laser dynamics, secure communication via chaos synchronization.\n- **Physics:** the KAM theorem and near-integrable systems; chaos in the solar system.\n- **Computation:** Newton's method is itself a dynamical system — its fractal **basins of attraction** explain why some initial guesses fail. The [Collatz map](collatz-conjecture-3x-plus-1-orbits-and-similar-iterations.qmd) is another deterministic iteration whose global behavior resists proof.\n\nThe synthesis: **nonlinearity plus iteration generates complexity; determinism and predictability are different properties.**\n\n---\n\n## Laboratory: Seeing Chaos\n\n### The Logistic Map: Fixed Points to Chaos\n\n::: {#cell-fig-logistic .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ndef logistic_orbit(r, x0, n, discard=0):\n    xs = []\n    x = x0\n    for i in range(n + discard):\n        x = r * x * (1 - x)\n        if i >= discard:\n            xs.append(x)\n    return np.array(xs)\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\nfor r, col in [(2.8, \"#2980b9\"), (3.2, \"#27ae60\"), (3.5, \"#e67e22\"), (3.9, \"#e74c3c\")]:\n    axes[0].plot(logistic_orbit(r, 0.4, 60), \"o-\", ms=3, color=col, label=f\"r={r}\")\naxes[0].set_title(\"Logistic map trajectories\")\naxes[0].set_xlabel(\"n\"); axes[0].set_ylabel(r\"$x_n$\"); axes[0].legend(); axes[0].grid(alpha=0.3)\n\nrs = np.linspace(2.5, 4.0, 1200)\nfor r in rs:\n    xs = logistic_orbit(r, 0.4, 300, discard=200)\n    axes[1].plot([r] * len(xs), xs, \",\", color=\"#2980b9\", alpha=0.25)\naxes[1].set_title(\"Bifurcation diagram\")\naxes[1].set_xlabel(\"r\"); axes[1].set_ylabel(r\"attracting $x$\"); axes[1].grid(alpha=0.3)\nplt.tight_layout(); plt.show()\n\nr_inf = 3.5699456\nprint(\"=== LOGISTIC MAP BIFURCATIONS ===\")\nprint(f\"  fixed point stable : 1 < r < 3\")\nprint(f\"  2-cycle starts     : r = 3\")\nprint(f\"  cascade accumulates: r_inf = {r_inf} (Feigenbaum)\")\nprint(f\"  first three doubling points: 3, 3.449, 3.544\")\nprint(f\"  Feigenbaum delta   = 4.669201609...  (universal)\")\n```\n\n::: {.cell-output .cell-output-display}\n![The logistic map x_{n+1}=r x_n(1−x_n). Left: trajectories for increasing r, showing convergence to a fixed point (r=2.8), a 2-cycle (r=3.2), a 4-cycle (r=3.5), and chaos (r=3.9). Right: the bifurcation diagram — for each r the map's attracting set is plotted, revealing the period-doubling cascade to chaos, the Feigenbaum accumulation point, and periodic windows embedded in the chaotic region.](dynamical-systems-chaos-and-the-butterfly-effect_files/figure-html/fig-logistic-output-1.png){#fig-logistic width=1334 height=470}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=== LOGISTIC MAP BIFURCATIONS ===\n  fixed point stable : 1 < r < 3\n  2-cycle starts     : r = 3\n  cascade accumulates: r_inf = 3.5699456 (Feigenbaum)\n  first three doubling points: 3, 3.449, 3.544\n  Feigenbaum delta   = 4.669201609...  (universal)\n```\n:::\n:::\n\n\n### Lyapunov Exponent\n\n::: {#cell-fig-lyapunov .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ndef lyapunov(r, n=2000, discard=500):\n    x = 0.4\n    s = 0.0\n    for i in range(n + discard):\n        x = r * x * (1 - x)\n        d = abs(r * (1 - 2 * x))\n        if i >= discard and d > 0:\n            s += np.log(d)\n    return s / n\n\nrs = np.linspace(2.5, 4.0, 800)\nlam = np.array([lyapunov(r) for r in rs])\nfig, ax = plt.subplots(figsize=(12, 4.6))\nax.plot(rs, lam, color=\"#333\", lw=0.8)\nax.fill_between(rs, 0, lam, where=lam > 0, color=\"#e74c3c\", alpha=0.6, label=\"chaotic (λ>0)\")\nax.fill_between(rs, 0, lam, where=lam <= 0, color=\"#2980b9\", alpha=0.4, label=\"periodic (λ<0)\")\nax.axhline(0, color=\"k\", lw=0.6)\nax.set_title(\"Lyapunov exponent of the logistic map\")\nax.set_xlabel(\"r\"); ax.set_ylabel(r\"$\\lambda$\"); ax.legend(); ax.grid(alpha=0.3)\nplt.tight_layout(); plt.show()\n\nprint(\"=== LYAPUNOV EXPONENT ===\")\nfor r in [2.8, 3.2, 3.5, 3.83, 3.9, 4.0]:\n    print(f\"  r={r:<5}: lambda = {lyapunov(r):+.4f}  ({'chaotic' if lyapunov(r)>0 else 'periodic'})\")\nprint(\"  r=3.83 is a periodic window (stable 3-cycle) inside the chaotic range.\")\n```\n\n::: {.cell-output .cell-output-display}\n![The Lyapunov exponent of the logistic map versus r. Where λ > 0 (red) the dynamics is chaotic and nearby trajectories diverge exponentially; where λ < 0 (blue) it converges to a periodic orbit. The sharp downward spikes are the periodic windows inside the chaotic region. Positive Lyapunov exponent is the quantitative definition of sensitive dependence.](dynamical-systems-chaos-and-the-butterfly-effect_files/figure-html/fig-lyapunov-output-1.png){#fig-lyapunov width=1141 height=432}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=== LYAPUNOV EXPONENT ===\n  r=2.8  : lambda = -0.2231  (periodic)\n  r=3.2  : lambda = -0.9163  (periodic)\n  r=3.5  : lambda = -0.8725  (periodic)\n  r=3.83 : lambda = -0.3705  (periodic)\n  r=3.9  : lambda = +0.5024  (chaotic)\n  r=4.0  : lambda = +0.6934  (chaotic)\n  r=3.83 is a periodic window (stable 3-cycle) inside the chaotic range.\n```\n:::\n:::\n\n\n### Sensitivity to Initial Conditions (Butterfly Effect)\n\n::: {#cell-fig-sensitivity .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nr = 3.9\nx0, x1 = 0.4, 0.4 + 1e-6\nn = 50\ntraj0, traj1 = logistic_orbit(r, x0, n), logistic_orbit(r, x1, n)\nsep = np.abs(traj0 - traj1)\n\nfig, ax = plt.subplots(figsize=(10, 4.8))\nax.plot(traj0, \"o-\", ms=3, color=\"#2980b9\", label=r\"$x_0=0.4$\")\nax.plot(traj1, \"s-\", ms=3, color=\"#e67e22\", label=r\"$x_0=0.4+10^{-6}$\")\nax.set_title(\"Butterfly effect: initial separation 10⁻⁶, r=3.9\")\nax.set_xlabel(\"step\"); ax.set_ylabel(r\"$x_n$\"); ax.legend(); ax.grid(alpha=0.3)\nplt.tight_layout(); plt.show()\n\nprint(\"=== DIVERGENCE ===\")\nfor k in [0, 5, 10, 15, 20, 25, 30]:\n    print(f\"  step {k:>2}: separation = {sep[k]:.3e}\")\nprint(f\"  Lyapunov estimate from growth: {np.polyfit(range(1,15), np.log(sep[1:15]), 1)[0]:.3f}\")\nprint(\"  (separation saturates once it reaches the size of the attractor.)\")\n```\n\n::: {.cell-output .cell-output-display}\n![Sensitive dependence in the logistic map at r=3.9. Two trajectories starting 10^-6 apart track each other closely for about twenty steps, then diverge completely — the hallmark of chaos. The separation grows exponentially at the Lyapunov rate until it saturates. This is why long-term prediction is impossible even though the rule is exact.](dynamical-systems-chaos-and-the-butterfly-effect_files/figure-html/fig-sensitivity-output-1.png){#fig-sensitivity width=950 height=451}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=== DIVERGENCE ===\n  step  0: separation = 7.800e-07\n  step  5: separation = 1.191e-05\n  step 10: separation = 3.976e-04\n  step 15: separation = 5.953e-03\n  step 20: separation = 1.670e-01\n  step 25: separation = 7.640e-01\n  step 30: separation = 2.213e-01\n  Lyapunov estimate from growth: 0.504\n  (separation saturates once it reaches the size of the attractor.)\n```\n:::\n:::\n\n\n### The Lorenz Attractor\n\n::: {#cell-fig-lorenz .cell execution_count=4}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom scipy.integrate import solve_ivp\n\nsigma, rho, beta = 10.0, 28.0, 8.0 / 3.0\n\ndef lorenz(t, s):\n    x, y, z = s\n    return [sigma * (y - x), x * (rho - z) - y, x * y - beta * z]\n\nt = np.linspace(0, 40, 20000)\nsol = solve_ivp(lorenz, [0, 40], [1.0, 1.0, 1.0], t_eval=t, rtol=1e-9, atol=1e-9)\nsol2 = solve_ivp(lorenz, [0, 40], [1.0 + 1e-8, 1.0, 1.0], t_eval=t, rtol=1e-9, atol=1e-9)\ndist = np.linalg.norm(sol.y - sol2.y, axis=0)\n\nfig = plt.figure(figsize=(13, 5.5))\nax1 = fig.add_subplot(1, 2, 1, projection=\"3d\")\nax1.plot(sol.y[0], sol.y[1], sol.y[2], lw=0.5, color=\"#2980b9\")\nax1.set_title(\"Lorenz strange attractor\"); ax1.set_xlabel(\"x\"); ax1.set_ylabel(\"y\"); ax1.set_zlabel(\"z\")\n\nax2 = fig.add_subplot(1, 2, 2)\nax2.semilogy(t, dist, color=\"#e74c3c\")\nax2.set_title(r\"Separation of two orbits ($\\Delta x_0=10^{-8}$)\")\nax2.set_xlabel(\"time\"); ax2.set_ylabel(\"separation\"); ax2.grid(alpha=0.3, which=\"both\")\nplt.tight_layout(); plt.show()\n\nprint(\"=== LORENZ SEPARATION ===\")\nfor k in [0, 5, 10, 15, 20, 25, 30]:\n    print(f\"  t={k:>2}: separation = {dist[np.argmin(abs(t - k))]:.3e}\")\nprint(\"  Exponential divergence from a 1e-8 error -> finite predictability horizon.\")\n```\n\n::: {.cell-output .cell-output-display}\n![The Lorenz system. Left: the butterfly-shaped strange attractor traced by a single trajectory; the flow is bounded but never repeats, and its fractal geometry is visible. Right: two trajectories from initial conditions differing by 10^-8 separate exponentially, until they occupy different lobes of the attractor — Lorenz's original demonstration that deterministic weather is inherently unpredictable in the long run.](dynamical-systems-chaos-and-the-butterfly-effect_files/figure-html/fig-lorenz-output-1.png){#fig-lorenz width=1165 height=517}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=== LORENZ SEPARATION ===\n  t= 0: separation = 1.000e-08\n  t= 5: separation = 1.245e-08\n  t=10: separation = 1.755e-08\n  t=15: separation = 2.374e-07\n  t=20: separation = 9.258e-06\n  t=25: separation = 1.845e-03\n  t=30: separation = 1.435e-01\n  Exponential divergence from a 1e-8 error -> finite predictability horizon.\n```\n:::\n:::\n\n\nThe laboratory makes chaos visible and quantitative: a single parameter sweeps the system from order to chaos (bifurcation diagram); the Lyapunov exponent separates the two regimes; infinitesimal differences explode (butterfly effect); and the Lorenz system shows a bounded, non-repeating, fractal attractor.\n\n---\n\n## Summary\n\n$$\n\\begin{aligned}\n&\\textbf{Dynamical system: } && \\text{state space + evolution } x_{n+1}=f(x_n) \\text{ or } \\dot x=F(x). \\\\[3pt]\n&\\textbf{Fixed points: } && \\text{stability via } |f'(x^*)|<1 \\text{ or } \\operatorname{Re}\\lambda<0. \\\\[3pt]\n&\\textbf{Logistic map: } && \\text{fixed point} \\to \\text{period-doubling} \\to \\text{chaos};\\\\ &&& r_\\infty=3.5699,\\ \\text{Feigenbaum } \\delta=4.6692 \\text{ (universal).} \\\\[3pt]\n&\\textbf{Chaos: } && \\text{sensitive dependence, mixing, dense periodic orbits; } \\lambda>0. \\\\[3pt]\n&\\textbf{Butterfly effect: } && \\text{Lorenz; exponential error growth; predictability horizon.} \\\\[3pt]\n&\\textbf{Attractors: } && \\text{fixed point, limit cycle, torus, strange (fractal) attractor.} \\\\[3pt]\n&\\textbf{Routes: } && \\text{period-doubling, intermittency, quasiperiodicity.} \\\\[3pt]\n&\\textbf{Lesson: } && \\text{deterministic} \\ne \\text{predictable.}\n\\end{aligned}\n$$\n\nChaos is not a failure of mathematics but a feature of nonlinearity. The same iteration that makes the [Collatz conjecture](collatz-conjecture-3x-plus-1-orbits-and-similar-iterations.qmd) intractable makes weather unpredictable and gives fractals their infinite complexity — and it is why [iterative numerical methods](iterative-methods-and-computing-constants-pi-and-eulers-constant.qmd) must be analyzed, not just run.\n\n---\n\n## Curated References and Further Reading\n\n1. **Strogatz, Steven (2015).** *Nonlinear Dynamics and Chaos*, 2nd ed. Westview Press.\n2. **Lorenz, Edward (1963).** *Deterministic Nonperiodic Flow.* Journal of the Atmospheric Sciences.\n3. **Feigenbaum, Mitchell (1978).** *Quantitative Universality for a Class of Nonlinear Transformations.* Journal of Statistical Physics.\n4. **Ott, Edward (2002).** *Chaos in Dynamical Systems*, 2nd ed. Cambridge University Press.\n5. **Guckenheimer, J. & Holmes, P. (1983).** *Nonlinear Oscillations, Dynamical Systems, and Bifurcations of Vector Fields.* Springer.\n6. **Poincaré, Henri (1890).** *Sur le problème des trois corps et les équations de la dynamique.* Acta Mathematica.\n7. **Mandelbrot, Benoît (1982).** *The Fractal Geometry of Nature.* W. H. Freeman.\n8. **Alligood, K., Sauer, T. & Yorke, J. (1996).** *Chaos: An Introduction to Dynamical Systems.* Springer.\n\n",
    "supporting": [
      "dynamical-systems-chaos-and-the-butterfly-effect_files"
    ],
    "filters": [],
    "includes": {}
  }
}