---
title: "Shakespeare Sonnet 153: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 153 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 153



Cupid laid by his brand and fell asleep:
A maid of Dian’s this advantage found,
And his love-kindling fire did quickly steep
In a cold valley-fountain of that ground;
Which borrowed from this holy fire of Love,
A dateless lively heat, still to endure,
And grew a seething bath, which yet men prove
Against strange maladies a sovereign cure.
But at my mistress’ eye Love’s brand new-fired,
The boy for trial needs would touch my breast;
I, sick withal, the help of bath desired,
And thither hied, a sad distempered guest,
But found no cure, the bath for my help lies
Where Cupid got new fire; my mistress’ eyes.




Read Sonnet 153 in Easy, Modern English:


Cupid set his torch aside and fell asleep. 
A maid who served Diana took advantage 
and quickly immersed his love-inducing fire 
in a cold spring nearby. 
The spring borrowed heat from this holy fire of love 
and became an eternal, hot, bubbling bath 
which men still regard as a universal cure for illness. 
But, with one look from my mistress, Cupid’s torch flared up again 
and he tested it by touching my heart with it. 
Lovesick, I needed the bath to cure me of it 
so I hurried there, a sad, sick visitor, 
but I found no cure: the bath was of no help – 
the only thing that could work was the one thing that gave Cupid his new fire – a glance from my mistress’s eye.



