---
title: "Shakespeare Sonnet 145: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 145 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 145



Those lips that Love’s own hand did make,
Breathed forth the sound that said ‘I hate’,
To me that languished for her sake:
But when she saw my woeful state,
Straight in her heart did mercy come,
Chiding that tongue that ever sweet
Was used in giving gentle doom;
And taught it thus anew to greet;
‘I hate’ she altered with an end,
That followed it as gentle day,
Doth follow night, who like a fiend
From heaven to hell is flown away.
‘I hate’, from hate away she threw,
And saved my life, saying ‘not you’.




Read Sonnet 145 in Easy, Modern English:


Those lips, shaped by the goddess of love herself, 
breathed the words ‘I hate.’ 
To me! The man pining away for love of her! 
But when she saw the unhappy state I was in, 
her heart was immediately filled with pity 
and she checked the tongue 
that always used to treat me gently. 
She made it say something different. 
She changed what she was saying by adding a few words to ‘I hate’, 
making it seem a natural progression, in the way that the gentle day 
follows the night, chasing the fiend back to hell. 
She removed the hatred from the words ‘I hate’ 
and saved my life by adding ‘not you’.



