---
title: "Shakespeare Sonnet 143: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 143 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 143



Lo, as a careful housewife runs to catch
One of her feather’d creatures broke away,
Sets down her babe, and makes all swift dispatch
In pursuit of the thing she would have stay;
Whilst her neglected child holds her in chase,
Cries to catch her whose busy care is bent
To follow that which flies before her face,
Not prizing her poor infant’s discontent;
So runn’st thou after that which flies from thee,
Whilst I thy babe chase thee afar behind;
But if thou catch thy hope, turn back to me,
And play the mother’s part, kiss me, be kind;
So will I pray that thou mayst have thy ‘Will’,
If thou turn back and my loud crying still.




Read Sonnet 143 in Easy, Modern English:


See: like a conscientious housewife, running to catch 
one of her chickens that has broken free, 
setting down her baby and hurrying in pursuit 
of the creature she’s trying to catch; 
while her neglected child chases after her, 
cries in its efforts to catch up with her, 
while her preoccupation is with that thing that’s running away from her, 
and not caring about the poor infant’s distress – 
in the same way, you are running after the one who’s fleeing from you, 
while I, your baby, chasing you, am left far behind. 
But if you catch the one you’re after, turn back to me 
and be a good mother. Kiss me; be kind. 
I’ll pray that you will get your Will 
as long as you turn back and stop my loud crying.



