---
title: "Shakespeare Sonnet 100: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 100 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 100



Where art thou Muse that thou forget’st so long,
To speak of that which gives thee all thy might?
Spend’st thou thy fury on some worthless song,
Darkening thy power to lend base subjects light?
Return forgetful Muse, and straight redeem,
In gentle numbers time so idly spent;
Sing to the ear that doth thy lays esteem
And gives thy pen both skill and argument.
Rise, resty Muse, my love’s sweet face survey,
If Time have any wrinkle graven there;
If any, be a satire to decay,
And make time’s spoils despised every where.
Give my love fame faster than Time wastes life,
So thou prevent’st his scythe and crooked knife.




Read Sonnet 100 in Easy, Modern English:


Where are you, Muse, that you’ve forgotten for so long
to give me the inspiration to write about the one who gives you all your power? 
Are you using up your energy on some worthless poem, 
dimming your power in order to brighten unworthy subjects? 
Come back, forgetful Muse, 
and compensate for the wasted time by helping me to write some good verses. 
Sing to the ear that values your songs and gives you both the skills and the poetic subject. 
Get up, lazy Muse. Examine my love’s sweet face and see
if time has engraved any wrinkles there. 
If there are any be a satirist, attacking ageing 
and making everyone despise time’s power to destroy. 
Give my beloved more fame than time can destroy 
and so stop his scythe and crooked knife.



