---
title: "Shakespeare Sonnet 129: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 129 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 129



The expense of spirit in a waste of shame
Is lust in action: and till action, lust
Is perjured, murderous, bloody, full of blame,
Savage, extreme, rude, cruel, not to trust;
Enjoyed no sooner but despised straight;
Past reason hunted; and no sooner had,
Past reason hated, as a swallowed bait,
On purpose laid to make the taker mad.
Mad in pursuit and in possession so;
Had, having, and in quest to have extreme;
A bliss in proof, and proved, a very woe;
Before, a joy proposed; behind a dream.
All this the world well knows; yet none knows well
To shun the heaven that leads men to this hell.




Read Sonnet 129 in Easy, Modern English:


Squandering vital energy in a wasteland of moral decay 
is what satisfying one’s lust amounts to. 
And in the anticipation of it lust makes one dishonest, murderous, violent, blameworthy, 
savage, extreme, rude and not to be trusted. 
As soon as its goal has been achieved one despises it. 
It’s hunted beyond reason and as soon as it’s had 
it’s hated beyond reason, like an irresistible bait 
put in front of one on purpose to make the taker mad. 
One is crazy in the pursuit of sex, and during sex too: 
having had it, having it and hunting for it one goes to extremes. 
It’s blissful while it’s happening and a true sorrow afterwards – 
before an anticipated joy, afterwards nothing but a dream. 
Everyone knows this very well, yet no-one knows it well enough 
to avoid the heaven that leads men to this hell.


 



