---
title: "Shakespeare Sonnet 13: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 13 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 13



O, that you were yourself! but, love, you are
No longer yours than you yourself here live:
Against this coming end you should prepare,
And your sweet semblance to some other give.
So should that beauty which you hold in lease
Find no determination: then you were
Yourself again after yourself’s decease,
When your sweet issue your sweet form should bear.
Who lets so fair a house fall to decay,
Which husbandry in honour might uphold
Against the stormy gusts of winter’s day
And barren rage of death’s eternal cold?
O, none but unthrifts! Dear my love, you know
You had a father: let your son say so.




Read Sonnet 13 in Easy, Modern English:


Oh, how I long for you to be yourself forever, 
unchanged, but, my love, you don’t have any identity for any longer than your time on earth. 
You should prepare yourself for this approaching end 
and pass your sweet likeness on to someone else. 
In that way, the lease that you hold for that beauty 
would not expire and you would survive after your self’s death, 
when your beautiful children would carry your beautiful form. 
Who allows such a lovely house to fall into decay 
when it could, with good management, 
be properly protected from the stormy winds of winter 
and the frustration of the eternal coldness of death? 
Oh, no-one except the irresponsible. 
My dear love, you once had a father: let your son be able to say the same thing.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 13










Sonnet 13 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 13, as published in Shakespeare’s 1609 Quarto:


O That you were your ſelfe,but loue you are
No longer yours,then you your ſelfe here liue,
Againft this cumming end you ſhould prepare,
And your ſweet ſemblance to ſome other giue.
So ſhould that beauty which you hold in leaſe
Find no determination,then you were
You ſelfe again after your ſelfes deceaſe,
When your ſweet iſſue your ſweet forme ſhould beare.
Who lets ſo faire a houſe fall to decay,
Which husbandry in honour might vphold,
Againſt the ſtormy guſts of winters day
And barren rage of deaths eternall cold?
O none but vnthriſts,deare my loue you know,
You had a Father,let your Son ſay ſo.


 




 

