---
title: "Shakespeare Sonnet 107: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 107 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 107



Not mine own fears, nor the prophetic soul
Of the wide world dreaming on things to come,
Can yet the lease of my true love control,
Supposed as forfeit to a confined doom.
The mortal moon hath her eclipse endured,
And the sad augurs mock their own presage;
Incertainties now crown themselves assured,
And peace proclaims olives of endless age.
Now with the drops of this most balmy time,
My love looks fresh, and Death to me subscribes,
Since, spite of him, I’ll live in this poor rhyme,
While he insults o’er dull and speechless tribes:
And thou in this shalt find thy monument,
When tyrants’ crests and tombs of brass are spent.




Read Sonnet 107 in Easy, Modern English:


Neither my own fears nor anyone speculating 
about what will happen 
can stop me from being reunited with my beloved, 
whom everyone assumed was doomed to remain in prison. 
The mortal moon has suffered an eclipse 
and the prophets of doom are laughing at their own predictions. 
Things that were once uncertainties have now come to pass 
and peace is here to stay. 
Now, basking in these halcyon times, 
my beloved looks renewed and death has surrendered to me 
because in defiance of death I’ll continue to live in this poor poem 
while he prevails over stupid and illiterate people. 
And you will find your monument in this poem 
when tyrants reigns and their brass tombs have disappeared.


 



