---
title: "Shakespeare Sonnet 86: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 86 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 86



Was it the proud full sail of his great verse,
Bound for the prize of all too precious you,
That did my ripe thoughts in my brain inhearse,
Making their tomb the womb wherein they grew?
Was it his spirit, by spirits taught to write
Above a mortal pitch, that struck me dead?
No, neither he, nor his compeers by night
Giving him aid, my verse astonished.
He, nor that affable familiar ghost
Which nightly gulls him with intelligence
As victors of my silence cannot boast;
I was not sick of any fear from thence:
But when your countenance fill’d up his line,
Then lack’d I matter; that enfeebled mine.




Read Sonnet 86 in Easy, Modern English:


Was it the power of his poetry, 
intended to win you, 
that prevented me from putting my thoughts into words? 
Was it his creativity, influenced by writers now dead, 
that makes him write better than anyone else that beat me into silence? 
No, it wasn’t he, nor the great dead writers 
from whom he learns by reading them during the night, 
that inhibited my verse. 
Neither he nor that friendly ghost 
that tricks him with false information every night 
can boast of victory in this question of my silence. 
I wasn’t impaired because of any fear of them, 
but when you paid his verse attention, thereby making it more significant than it is, 
I found I had nothing to say. So it was you that made my verse feeble.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 86










Sonnet 86 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 86, as published in Shakespeare’s 1609 Quarto:


WAs it the proud full ſaile of his great verſe,
Bound for the prize of (all to precious) you,
That did my ripe thoughts in my braine inhearce,
Making their tombe the wombe wherein they grew?
Was it his ſpirit,by ſpirits taught to write,
Aboue a mortall pitch,that ſtruck me dead ?
No,neither he,nor his compiers by night
Giuing him ayde,my verſe aſtoniſhed.
He nor that affable familiar ghoſt
Which nightly gulls him with intelligence,
As victors of my ſilence cannot boaſt,
I was not ſick of any feare from thence.
But when your countinance fild vp his line,
Then lackt I matter,that infeebled mine.




 



