---
title: "Shakespeare Sonnet 23: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 23 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 23



As an unperfect actor on the stage,
Who with his fear is put beside his part,
Or some fierce thing replete with too much rage,
Whose strength’s abundance weakens his own heart;
So I, for fear of trust, forget to say
The perfect ceremony of love’s rite,
And in mine own love’s strength seem to decay,
O’ercharg’d with burthen of mine own love’s might.
O! let my books be then the eloquence
And dumb presagers of my speaking breast,
Who plead for love, and look for recompense,
More than that tongue that more hath more express’d.
O! learn to read what silent love hath writ:
To hear with eyes belongs to love’s fine wit.




Read Sonnet 23 in Easy, Modern English:


Like an unrehearsed actor on the stage, 
who forgets his lines because of nervousness, 
or some angry animal overwhelmed with rage 
so that in spite of its strength it is weakened by its loss of control, 
I, not trusting myself, am unable to articulate 
the love I feel, 
and the strength of my love seems to be less than it is, 
overloaded with the weight of my beloved’s dominating power. 
Oh, let my writings then be the speakers 
and the signals of my speaking heart, 
that beg for love and hopes for reciprocation, 
more eloquent than that tongue that more usually expresses the heart. 
Oh, learn to read the volumes that my silent love has written. 
To hear with eyes is something characteristic of lovers.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 23










Sonnet 23 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 23, as published in Shakespeare’s 1609 Quarto:


AS an vnperfect actor on the ſtage,
Who with his feare is put beſides his part,
Or ſome fierce thing repleat with too much rage,
Whoſe ſtrengths abondance weakens his owne heart;
So I for feare of truſt,forget to ſay,
The perfect ceremony of loues right,
And in mine owne loues ſtrength ſeeme to decay,
Ore-charg’d with burthen of mine owne loues might:
O let my books be then the eloquence,
And domb preſagers of my ſpeaking breſt,
Who pleade for loue,and look for recompence,
More then that tonge that more hath more expreſt.
O learne to read what ſilent loue hath writ,
To heare wit eies belongs to loues fine wiht.


 




 

