---
title: "Shakespeare Sonnet 11: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 11 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 11



As fast as thou shalt wane, so fast thou grow’st
In one of thine, from that which thou departest;
And that fresh blood which youngly thou bestow’st,
Thou mayst call thine when thou from youth convertest.
Herein lives wisdom, beauty, and increase;
Without this folly, age, and cold decay:
If all were minded so, the times should cease
And threescore year would make the world away.
Let those whom nature hath not made for store,
Harsh, featureless, and rude, barrenly perish:
Look whom she best endow’d, she gave the more;
Which bounteous gift thou shouldst in bounty cherish:
She carv’d thee for her seal, and meant thereby,
Thou shouldst print more, not let that copy die.




Read Sonnet 11 in Easy, Modern English:


Your beauty would grow in a child of yours as rapidly as it fades in you, 
and when you are leaving your youth 
you could call that fresh blood 
that you give in your youth your own. 
Accepting this would be wise and it would ensure the preservation of your beauty; 
not doing so would be foolish and age would decay it. 
If everyone were to think like you it would result in the end of time 
and a sixty-year lifespan would bring the end of the world. 
Let those coarse, unremarkable, and crude people 
whom nature has not intended for breeding perish without issue. 
Whatever she gave to the best,
she gave you more, and you should fully cherish those generous gifts. 
She printed her seal on you and by that meant that 
you should print more, not let that original die.




Watch Sir Patrick Stewart read Shakespeare’s sonnet 11








Sonnet 11 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 11, as published in Shakespeare’s 1609 Quarto:


AS faſt as thou ſhalt wane ſo faſt thou grow’ſt,
In one of thine,from that which thou departeſt,
And that freſh bloud which yongly thou beſtow’ſt,
Thou maiſt call thine,when thou from youth conuerteſt,
Herein liues wiſdome,beauty,and increaſe,
Without this follie,age,and could decay,
If all were minded ſo,the times ſhould ceaſe,
And threeſcore yeare would make the world away:
Let thoſe whom nature hath not made for ſtore,
Harſh,featureleſſe,and rude , barrenly perriſh,
Looke whom ſhe beſt indow’d,ſhe gaue the more;
Which bountious guift thou ſhouldſt in bounty cherriſh,
She caru’d thee for her ſeale,and ment therby,
Thou ſhouldſt print more,not let that coppy die.


 




 

