---
title: "Shakespeare Sonnet 32: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 32 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 32



If thou survive my well-contented day,
When that churl Death my bones with dust shall cover
And shalt by fortune once more re-survey
These poor rude lines of thy deceased lover,
Compare them with the bett’ring of the time,
And though they be outstripped by every pen,
Reserve them for my love, not for their rhyme,
Exceeded by the height of happier men.
O! then vouchsafe me but this loving thought:
‘Had my friend’s Muse grown with this growing age,
A dearer birth than this his love had brought,
To march in ranks of better equipage:
But since he died and poets better prove,
Theirs for their style I’ll read, his for his love.’




Read Sonnet 32 in Easy, Modern English:


If you survive me when my happy life is over 
and churlish death has covered my bones with dust, 
and you should by chance read again 
these poor, crude poems by your dead friend, 
compare them with the better poems that are being written these days. 
And though my poems are being outstripped by every other poet, 
keep them for love of me, not for their poetic quality, 
exceeded by the brilliant poems of better poets. 
So grant me just this one loving thought: 
“If my friend’s inspiration had been matched by the poetic excellence of the present time 
his love would have produced better poems than these, 
good enough to be ranked alongside those of today’s good poets. 
But since he died and poets are better now, 
I’ll read theirs for their style and his for his love.”




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 32










Sonnet 32 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 32, as published in Shakespeare’s 1609 Quarto:


IF thou ſuruiue my well contented daie,
When that churle death my bones with duſt ſhall couer
And ſhalt by fortune once more re-ſuruay:
Theſe poore rude lines of thy deceaſed Louer:
Compare them with the bett’ring of the time,
And though they be out-ſtript by euery pen,
Reſerue them for my loue,not for their rime,
Exceeded by the hight of happier men.
Oh then voutſafe me but this louing thought,
Had my friends Muſe growne with this growing age,
A dearer birth then this his loue had brought:
To march in ranckes of better equipage:
But ſince he died and Poets better proue,
Theirs for their ſtile ile read,his for his loue.






 



