---
title: "Shakespeare Sonnet 116: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 116 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 116



Shakespeare’s sonnet 116 can be seen as the definitive response to the ‘what is love’ question. The language of the sonnet is as deep and profound as any philosopher’s could be, expressed in the most beautiful language. Love is given an identity as an immortal force, which overcomes age, death, and time itself. Love, unlike the physical being, is not subject to decay.


Shakespeare employs an amazing array of poetic devices throughout the sonnet to convey 
the eternal nature of love
, and ends by staking everything on his observations by asserting that if he is wrong, then no-one ever wrote anything, and no-one ever loved. And in sonnet 116 – as with 
all of his sonnets
 – Shakespeare manages to squeeze all of these thoughts and words into just fourteen lines.




Shakespeare’s Complete Sonnet 116


Let me not to the marriage of true minds
Admit impediments. Love is not love
Which alters when it alteration finds,
Or bends with the remover to remove:
O, no! it is an ever-fixed mark,
That looks on tempests and is never shaken;
It is the star to every wandering bark,
Whose worth’s unknown, although his height be taken.
Love’s not Time’s fool, though rosy lips and cheeks
Within his bending sickle’s compass come;
Love alters not with his brief hours and weeks,
But bears it out even to the edge of doom.
If this be error and upon me proved,
I never writ, nor no man ever loved.




Read Sonnet 116 in Easy, Modern English:


I would not admit that anything could interfere 
with the union of two people who love each other. 
Love that alters with changing circumstances is not love, 
nor if it bends from its firm state when someone tries to destroy it. 
Oh no, it’s an eternally fixed point 
that watches storms but is never itself shaken by them. 
It is the star by which every lost ship can be guided: 
one can calculate its distance but not gauge its quality. 
Love doesn’t depend on Time, although the rosy lips and cheeks of youth 
eventually come within the compass of Time’s sickle. 
Love doesn’t alter as the days and weeks go by 
but endures until death. 
If I’m wrong about this 
then I’ve never written anything and no man has ever loved.


Love, Shakespeare tells us, isn’t something that wears itself out over weeks, months and years, but remains firm right throughout the lives of the lovers, and doesn’t even end with their death but continues until the world ends.


What’s your take on sonnet 116? Let us know in the comments section below!




Sonnet 116 is Shakespeare’s take on the ‘what is love’ question


 



