---
title: "Shakespeare Sonnet 109: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 109 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 109



O! never say that I was false of heart,
Though absence seem’d my flame to qualify,
As easy might I from my self depart
As from my soul which in thy breast doth lie:
That is my home of love: if I have ranged,
Like him that travels, I return again;
Just to the time, not with the time exchanged,
So that myself bring water for my stain.
Never believe though in my nature reigned,
All frailties that besiege all kinds of blood,
That it could so preposterously be stained,
To leave for nothing all thy sum of good;
For nothing this wide universe I call,
Save thou, my rose, in it thou art my all.




Read Sonnet 109 in Easy, Modern English:


Oh, don’t say that I was untrue, 
even though our being apart made me appear cool. 
It would be as easy to me to be separated from myself 
as from you, to whom, if I ever stray, 
I return, like a traveller coming home;
right on time, punctual, not affected by circumstances, 
so that I am myself bringing the water that will wash away my sin. 
Even if my nature had every kind of carnal weakness imaginable 
you shouldn’t believe that it could be so perversely sinful 
as to abandon all your goodness for worthless women, 
because I consider the whole universe worthless, 
apart from you, my rose of youth: you’re my everything in it.



