---
title: "Shakespeare Sonnet 6: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 6 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 6



Then let not winter’s ragged hand deface,
In thee thy summer, ere thou be distilled:
Make sweet some vial; treasure thou some place
With beauty’s treasure ere it be self-killed.
That use is not forbidden usury,
Which happies those that pay the willing loan;
That’s for thy self to breed another thee,
Or ten times happier, be it ten for one;
Ten times thy self were happier than thou art,
If ten of thine ten times refigured thee:
Then what could death do if thou shouldst depart,
Leaving thee living in posterity?
Be not self-willed, for thou art much too fair
To be death’s conquest and make worms thine heir.




Read Sonnet 6 in Easy, Modern English:


So don’t let winter’s ragged hand disfigure 
that summer in you before your essence is distilled. 
Fill some vial; enrich some woman’s womb 
with the treasure of your beauty before it dies. 
The interest from that would not be illegal lending 
if it made the willing borrower happy, 
which would happen if the loan was to breed another of yourself. 
Or ten times better if the interest were ten for one. 
Ten of yourself would be better than just one of you, 
with ten of your children existing, making ten images of you. 
Then what effect could death have if you should die, 
leaving you alive after your death? 
Don’t be obstinate because you are far too beautiful 
to be the victim of death and have only worms as your heirs.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 6










Sonnet 6 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 6, as published in Shakespeare’s 1609 Quarto:


THen let not winters wragged hand deface,
In thee thy ſummer ere thou be diſtil’d:
Make ſweet ſome viall;treaſure thou ſome place,
With beauties treaſure ere it be ſelfe kil’d:
That vſe is not forbidden vſery,
Which happies thoſe that pay the willing lone;
That’s for thy ſelfe to breed an other thee,
Or ten times happier be it ten for one,
Ten times thy ſelfe were happier then thou art,
If ten of thine ten times refigur’d thee,
Then what could death doe if thou ſhould’ſt depart,
Leauing thee liuing in poſterity?
Be not ſelfe-wild for thou art much too faire,
To be deaths conqueſt and make wormes thine heire.






 


Interested in Shakespeare’s sonnet 6? If so you can get some additional free information by visiting our friends over at 
PoemAnalysis to read their analysis of sonnet 6
.


 





