---
title: "Shakespeare Sonnet 118: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 118 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 118



Like as, to make our appetites more keen,
With eager compounds we our palate urge,
As, to prevent our maladies unseen,
We sicken to shun sickness when we purge;
Even so, being full or your ne’er-cloying sweetness,
To bitter sauces did I frame my feeding;
And, sick of welfare, found a kind of meetness
To be diseas’d, ere that there was true needing.
Thus policy in love, to anticipate
The ills that were not, grew to faults assur’d,
And brought to medicine a healthful state,
Which, rank of goodness, would by ill be cur’d;
But thence I learn, and find the lesson true,
Drugs poison him that so fell sick of you.




Read Sonnet 118 in Easy, Modern English:


Just as we take pungent substances, and make ourselves throw up, 
to sharpen our appetites and prevent other illnesses, 
making ourselves sick by this urging, in the same way, 
being sated by your never-cloying sweetness, 
I changed my diet from that to more bitter food. 
And, tired of being so healthy, 
making myself a bit sick to avoid becoming really sick appealed to me. 
And so, using this love strategy – anticipating difficulties that didn’t exist – 
I got used to being unfaithful to you. 
I used medicine to remedy what was already a healthy relationship, 
trying to cure something good by applying evil to it. 
But I have learnt from that – and I think it was a good lesson – 
that the drugs I used after being so lovesick over you, are poisoning me.



