---
title: "Shakespeare Sonnet 124: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 124 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 124



If my dear love were but the child of state,
It might for Fortune’s bastard be unfathered,
As subject to time’s love or to time’s hate,
Weeds among weeds, or flow’rs with flowers gathered.
No, it was builded far from accident;
It suffers not in smiling pomp, nor falls
Under the blow of thralled discontent,
Whereto th’ inviting time our fashion calls.
It fears not policy, that heretic,
Which works on leases of short numb’red hours.
But all alone stands hugely politic,
That it nor grows with heat nor drowns with showers.
To this I witness call the fools of time,
Which die for goodness, who have lived for crime.




Read Sonnet 124 in Easy, Modern English:


If the great love which I have for you had been created simply by circumstances 
it would be like an illegitimate child – 
at the mercy of changing circumstances. 
It would be subject to fashion – what’s in or out at any given time – 
rejected when seen as weeds and embraced when seen as flowers. 
No, it was created with more resolve. 
It’s affected neither by the approval of authority nor by the challenge to authority, 
which is the current fashion. 
It isn’t afraid of political plotting, 
which operates in a short time span, 
but stands alone – independent, wise and secure – 
neither growing in sunshine nor drowning in showers. 
As witness to that I call all those fashion-followers who, 
after living bad lives, repented on their deathbeds in the hope of transforming that bad into good.



