---
title: "Shakespeare Sonnet 34: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 34 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 34



Why didst thou promise such a beauteous day,
And make me travel forth without my cloak,
To let base clouds o’ertake me in my way,
Hiding thy bravery in their rotten smoke?
‘Tis not enough that through the cloud thou break,
To dry the rain on my storm-beaten face,
For no man well of such a salve can speak,
That heals the wound, and cures not the disgrace:
Nor can thy shame give physic to my grief;
Though thou repent, yet I have still the loss:
The offender’s sorrow lends but weak relief
To him that bears the strong offence’s cross.
Ah! but those tears are pearl which thy love sheds,
And they are rich and ransom all ill deeds.




Read Sonnet 34 in Easy, Modern English:


Why did you, like the sun, promise such a beautiful day 
and make me go out without my cloak 
then hide your brilliance behind the poisonous vapours of those nasty clouds, 
only to let them overtake me as I went?
It’s not good enough to break through the clouds 
and dry the rain off my storm-beaten face 
because no-one can be satisfied with a balm 
that heals the wound but doesn’t cure the hurt. 
Nor can the shame you exhibit help: 
even though you’re repentant, I’m still bereft. 
An offender’s regret doesn’t give much relief 
to the one who has been badly offended.
Ah, but those tears you’re shedding out of love are like pearls: 
they are very valuable and make up for all your bad deeds.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 34










Sonnet 34 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 34, as published in Shakespeare’s 1609 Quarto:


WHy didſt thou promiſe ſuch a beautious day,
And make me trauaile forth without my cloake,
To let bace cloudes ore-take me in my way,
Hiding thy brau’ry in their rotten ſmoke.
Tis not enough that through the cloude thou breake,
To dry the raine on my ſtorme-beaten face,
For no man well of ſuch a ſalue can ſpeake,
That heales the wound, and cures not the diſgrace:
Nor can thy ſhame give phiſicke to my griefe,
Though thou repent , yet I haue ſtill the loſſe,
Th’ offenders ſorrow lends but weake reliefe
To him that beares the ſtrong offenſes loſſe.
Ah but thoſe teares are pearle which thy loue ſheeds,
And they are ritch,and ranſome all ill deeds.






 



