---
title: "Shakespeare Sonnet 25: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 25 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 25



Let those who are in favour with their stars
Of public honour and proud titles boast,
Whilst I, whom fortune of such triumph bars
Unlook’d for joy in that I honour most.
Great princes’ favourites their fair leaves spread
But as the marigold at the sun’s eye,
And in themselves their pride lies buried,
For at a frown they in their glory die.
The painful warrior famoused for fight,
After a thousand victories once foiled,
Is from the book of honour razed quite,
And all the rest forgot for which he toiled:
Then happy I, that love and am beloved,
Where I may not remove nor be removed.




Read Sonnet 25 in Easy, Modern English:


Let those who have achieved success 
enjoy the glory of high office and aristocratic titles, 
while I, who have been barred by fortune from such triumph, 
take quiet delight in that which I most value. 
The favourites of great princes enjoy brief days of sunshine, 
as marigolds do for as long as the sun shines directly on them, 
their glory being confined to that moment, 
because it dies at a frown from the prince. 
The soldier, made famous for his military prowess, 
is stripped of his honour once he has been defeated, 
even after a thousand victories, 
and everything he strove for is forgotten. 
But I, who love and am loved, 
am fortunate in that I can’t remove myself from that state or be removed from it by anyone else.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 25










Sonnet 25 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 25, as published in Shakespeare’s 1609 Quarto:


LEt thoſe who are in fauor with their ſtars,
Of publike honour and proud titles boſt,
Whilſt I whome fortune of ſuch tryumph bars
Vnlookt for ioy in that I honour moſt;
Great Princes fauorites their fair leaues ſpread,
But as the Marygold at the ſuns eye,
And in them-ſelues their pride lies buried,
For at a frowne they in their glory die.
The painefull warrier famoſed for worth,
After a thouſand victories once foild,
Is from the booke of honour raſed quite,
And all the reſt forgot for which he toild:
Then happy I that loue and am beloued
Where I may not remoue,nor be remoued.


 




 

