---
title: "Shakespeare Sonnet 94: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 94 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 94



They that have power to hurt, and will do none,
That do not do the thing they most do show,
Who, moving others, are themselves as stone,
Unmoved, cold, and to temptation slow;
They rightly do inherit heaven’s graces,
And husband nature’s riches from expense;
They are the lords and owners of their faces,
Others, but stewards of their excellence.
The summer’s flower is to the summer sweet,
Though to itself, it only live and die,
But if that flower with base infection meet,
The basest weed outbraves his dignity:
For sweetest things turn sourest by their deeds;
Lilies that fester, smell far worse than weeds.




Read Sonnet 94 in Easy, Modern English:


They who have the power to hurt and won’t do it; 
who seem to be the epitome of some act but won’t commit it, 
who arouse others to sexual excitement but are themselves like stone-cold, 
unemotional, and not easily led into temptation – 
they will rightly inherit heaven’s graces 
and prevent nature’s treasures from being wasted. 
They are in possession of themselves; 
the rest are only managing their beauty for others’ use. 
The summer flower is lovely when at its peak, 
although it’s only fulfilling its function of living and dying, 
but if it falls victim to a serious infection 
the vilest weed will be better 
because the sweetest things become the most unattractive as a result of their bad deeds. 
Rotting lilies smell far worse than weeds.




Listen to Sir John Gielgud read Shakespeare’s sonnet 94










Sonnet 94 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 94, as published in Shakespeare’s 1609 Quarto:


THey that haue powre to hurt,and will doe none,
That doe not do the thing,they moſt do ſhowe,
Who mouing others,are themſelues as ſtone,
Vnmooued,could,and to temptation ſlow:
They rightly do inherrit heauens graces,
And husband natures ritches from expence,
They are the Lords and owners of their faces,
Others,but ſtewards of their excellence:
The ſommers flowre is to the ſommer ſweet,
Though to it ſelfe,it onely liue and die,
But if that flowre with baſe infection meete,
The baſeft weed out-braues his dignity:
For ſweeteſt things turne ſowreſt by their deedes,
Lillies that feſter,ſmell far worſe then weeds.




 





