---
title: "Shakespeare Sonnet 126: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 126 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 126



O thou, my lovely boy, who in thy pow’r
Dost hold time’s fickly glass, his sickle hour,
Who hast by waning grown, and therein show’st
Thy lovers withering, as they sweet self grow’st –
If nature, sovereign mistress over wrack,
As thou goest onwards still will pluck thee back,
She keeps thee to this purpose: that her skill
May time disgrace, and wretched minute kill.
Yet fear her, O thou minion of her pleasure;
She may detain, but not still keep, her treasure.
Her audit, though delayed, answered must be,
And her quietus is to render thee.




Read Sonnet 126 in Easy, Modern English:


Oh you, my lovely boy, who have power 
over time’s changing mirror – 
power over its ability to harvest all life – 
who have grown younger as you’ve aged, 
exposing during that process, how your lover has withered as you’ve become more beautiful. 
If nature, the ultimate authority over ruin, 
insists on rescuing you from decay, 
she’s doing it for this reason: 
to demonstrate that she is able to disgrace time and kill its wretched measurements. 
But fear her, oh you favourite of hers. 
She can slow her treasure’s decay down but she can’t prevent it forever. 
Even though it may be delayed she has to be accountable eventually. 
And the way she’ll settle her account will be to deliver you up.



