---
title: "Shakespeare Sonnet 142: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 142 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 142



Love is my sin, and thy dear virtue hate,
Hate of my sin, grounded on sinful loving:
O! but with mine compare thou thine own state,
And thou shalt find it merits not reproving;
Or, if it do, not from those lips of thine,
That have profaned their scarlet ornaments
And sealed false bonds of love as oft as mine,
Robbed others’ beds’ revenues of their rents.
Be it lawful I love thee, as thou lov’st those
Whom thine eyes woo as mine importune thee:
Root pity in thy heart, that, when it grows,
Thy pity may deserve to pitied be.
If thou dost seek to have what thou dost hide,
By self-example mayst thou be denied!




Read Sonnet 142 in Easy, Modern English:


Loving you is my sin, and your best virtue is hatred: 
hatred of my sin, based on your own illicit loving. 
But oh, compare your own position with mine 
and you will find that I don’t deserve to be reprimanded, 
or if I do, not from your lips,
 that have given as many sinful kisses 
and made as many false promises as mine have. 
We have both cheated in our marriages. 
If it’s fair for me to love you as much as you love those 
you lust after, while I lust after you, 
allow pity to be rooted in your heart so that when it grows 
you’ll also deserve to be pitied. 
If you expect to carry on with your illicit affairs and be pitied at the same time, 
you may be denied because of the example you are setting.



