---
title: "Shakespeare Sonnet 131: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 131 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 131



Thou art as tyrannous, so as thou art,
As those whose beauties proudly make them cruel;
For well thou know’st to my dear doting heart
Thou art the fairest and most precious jewel.
Yet, in good faith, some say that thee behold,
Thy face hath not the power to make love groan;
To say they err I dare not be so bold,
Although I swear it to myself alone.
And to be sure that is not false I swear,
A thousand groans, but thinking on thy face,
One on another’s neck, do witness bear
Thy black is fairest in my judgment’s place.
In nothing art thou black save in thy deeds,
And thence this slander, as I think, proceeds.




Read Sonnet 131 in Easy, Modern English:


You are as tyrannous
as those women whose beauty makes them proud and cruel, 
even though you look as you do, because you know full well that to my loving, doting heart, 
you are the most beautiful and most precious jewel. 
Yet, to be honest, some people, on seeing you, 
say that your face doesn’t have the power to make one groan with love. 
I wouldn’t be so bold as to tell them they’re mistaken, 
although I tell myself they are. 
And to make sure of that 
I groan a thousand groans just thinking about your face. 
Coming one after another my groans testify that in my opinion 
your dark complexion is most beautiful. 
There’s nothing dark about you, except your actions, 
and I think that’s why this slander about your looks continues.



