---
title: "Shakespeare Sonnet 71: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 71 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 71



No longer mourn for me when I am dead
Than you shall hear the surly sullen bell
Give warning to the world that I am fled
From this vile world with vilest worms to dwell:
Nay, if you read this line, remember not
The hand that writ it, for I love you so,
That I in your sweet thoughts would be forgot,
If thinking on me then should make you woe.
O! if, I say, you look upon this verse,
When I perhaps compounded am with clay,
Do not so much as my poor name rehearse;
But let your love even with my life decay;
Lest the wise world should look into your moan,
And mock you with me after I am gone.




Sonnet 71 in Easy, Modern English


When I’m dead don’t mourn for me any longer than you can hear the surly sullen bell telling the world that I’ve fled this vile world to live with the even more vile worms. No, if you read this line, don’t remember the hand that wrote it because I love you so much that I would like you to forget me rather than that, thinking about me, such thoughts would make you sad. Oh, I insist that if you read this poem when I’m, perhaps, mixed with clay, you must not even utter my poor name but let your love die with me in case the world, in its wisdom, should look closely at your mourning and mock you about me once I’ve gone.




Watch Sir Patrick Stewart read Shakespeare’s sonnet 71



https://youtube.com/watch?v=hoqY5nXcmRg%3Ffeature%3Doembed%26wmode%3Dopaque%26rel%3D0







Sonnet 71 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 71, as published in Shakespeare’s 1609 Quarto:


NOe Longer mourne for me when I am dead,
Then you ſhall heare the ſurly ſullen bell
Giue warning to the world that I am fled
From this vile world with vildeſt wormes to dwell:
Nay if you read this line,remember not,
The hand that writ it,for I loue you ſo,
That I in your ſweet thoughts would be forgot,
If thinking on me then ſhould make you woe.
O if(I ſay)you looke vpon this verſe,
When I (perhaps) compounded am with clay,
Do not ſo much as my poore name reherſe;
But let your loue euen with my life decay.
Leaſt the wiſe world ſhould looke into your mone,
And mocke you with me after I am gon.






See the 
British Library’s 1609 Quarto
.





