---
title: "Shakespeare Sonnet 150: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 150 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 150



O! from what power hast thou this powerful might,
With insufficiency my heart to sway?
To make me give the lie to my true sight,
And swear that brightness doth not grace the day?
Whence hast thou this becoming of things ill,
That in the very refuse of thy deeds
There is such strength and warrantise of skill,
That, in my mind, thy worst all best exceeds?
Who taught thee how to make me love thee more,
The more I hear and see just cause of hate?
O! though I love what others do abhor,
With others thou shouldst not abhor my state:
If thy unworthiness raised love in me,
More worthy I to be beloved of thee.




Read Sonnet 150 in Easy, Modern English:


Oh! where did you find this incredible power 
to control my heart in spite of your inadequacy? 
To make me disbelieve what my eyes see, 
making me swear that daylight isn’t bright? 
Where did you get this skill 
to make bad things look so good in you 
that even your most unworthy actions 
make my mind think that your worst is better than everyone else’s best? 
Who taught you how to make me love you more, 
the more I hear and see good reasons to hate you? 
Oh! even though I love what others hate 
you shouldn’t join them in despising me for loving you. 
I deserve to be loved by you 
because it was your unworthiness that made me love you.



