---
title: "Shakespeare Sonnet 97: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 97 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 97



How like a winter hath my absence been
From thee, the pleasure of the fleeting year!
What freezings have I felt, what dark days seen!
What old December’s bareness everywhere!
And yet this time removed was summer’s time;
The teeming autumn, big with rich increase,
Bearing the wanton burden of the prime,
Like widow’d wombs after their lords’ decease:
Yet this abundant issue seemed to me
But hope of orphans, and unfathered fruit;
For summer and his pleasures wait on thee,
And, thou away, the very birds are mute:
Or, if they sing, ’tis with so dull a cheer,
That leaves look pale, dreading the winter’s near.




Read Sonnet 97 in Easy, Modern English:


How like a winter my separation from you has been, 
since you provide the pleasure of the short year. 
What freezing cold and dark days I’ve experienced: 
it’s all been like dreary December. 
And yet this period of separation has actually been in summer time 
and productive autumn, rich with crops, 
bearing the fruit of a happier time, 
like a widow giving birth after her husband’s death. 
But this abundance seemed 
like a hopeless orphan to me because 
the summer and its pleasures all depend on you, 
and when you’re not with me even the birds are silent. 
If they sing it’s with such a lack of enthusiasm 
that the leaves grow pale with fear, dreading the closeness of winter.



