---
title: "Shakespeare Sonnet 44: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 44 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 44



If the dull substance of my flesh were thought,
Injurious distance should not stop my way;
For then despite of space I would be brought,
From limits far remote, where thou dost stay.
No matter then although my foot did stand
Upon the farthest earth remov’d from thee;
For nimble thought can jump both sea and land,
As soon as think the place where he would be.
But, ah! thought kills me that I am not thought,
To leap large lengths of miles when thou art gone,
But that so much of earth and water wrought,
I must attend time’s leisure with my moan;
Receiving nought by elements so slow
But heavy tears, badges of either’s woe.




Read Sonnet 44 in Easy, Modern English:


If the dull substance of my flesh were thought instead of flesh, 
this destructive distance between us wouldn’t be a barrier 
because then, no matter how far away they were, 
I would come from the most remote regions to where you are. 
It wouldn’t matter, then, that my feet were planted 
on the furthest place on earth from you: 
nimble thought can jump over both land and sea 
as quickly as it can think of the place where it wants to be. 
But, ah, it’s killing me that I’m not made of thought, 
to leap over the many miles when you are gone but, 
being made of so much earth and water, 
I must fill the long hours without you with my complaint. 
I get nothing from such slow elements, 
except heavy tears, the mark of both elements.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 44










Sonnet 44 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 44, as published in Shakespeare’s 1609 Quarto:


IF the dull ſubstance of my fleſh were thought,
Iniurious diſtance ſhould not ſtop my way,
For then diſpight of ſpace I would be brought,
From limits farre remote,where thou dooſt ſtay,
No matter then although my foote did ſtand
Vpon the fartheſt earth remoou’d from thee,
For nimble thought can iumpe both ſea and land,
As ſoone as thinke the place where he would be.
But ah,thought kills me that I am not thought
To leape large lengths of miles when thou art gone,
But that ſo much of earth and water wrought,
I muſt attend,times leaſure with my mone.
Receiuing naughts by elements ſo ſloe,
But heauie teares,badges of eithers woe.






 



