---
title: "Shakespeare Sonnet 9: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 9 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 9



Is it for fear to wet a widow’s eye,
That thou consum’st thy self in single life?
Ah! if thou issueless shalt hap to die,
The world will wail thee like a makeless wife;
The world will be thy widow and still weep
That thou no form of thee hast left behind,
When every private widow well may keep
By children’s eyes, her husband’s shape in mind:
Look what an unthrift in the world doth spend
Shifts but his place, for still the world enjoys it;
But beauty’s waste hath in the world an end,
And kept unused the user so destroys it.
No love toward others in that bosom sits
That on himself such murd’rous shame commits.




Read Sonnet 9 in Easy, Modern English:


Is it because you fear to make a widow grieve, 
that you waste yourself in bachelorhood? 
Ah, if you should happen to die childless 
the world will mourn for you like a bereaved widow. 
The world will be your widow and weep profusely 
because you have left no copy of yourself behind, 
while an ordinary widow 
is able to keep her husband’s memory fresh by looking at her children. 
Whatever a money-waster spends just moves from one pocket to another 
and the world continues to enjoy it, 
but squandered beauty is lost to the world, 
and by not using it the user destroys it. 
There is no love for others in the heart of one 
who murders himself so shamelessly.




Listen to Sir John Gielgud read Shakespeare’s sonnet 9










Sonnet 9 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 9, as published in Shakespeare’s 1609 Quarto:


IS it for feare to wet a widdowes eye,
That thou conſum’ſt thy ſelfe in ſingle life?
Ah;if thou iſſuleſſe ſhalt hap to die,
The world will waile thee like a makeleſſe wife,
The world wilbe thy widdow and ſtill weepe,
That thou no forme of thee haſt left behind ,
When euery priuat widdow well may keepe,
By childrens eyes,her husbands ſhape in minde:
Looke what an vnthrift in the world doth ſpend
Shifts but his place,for ſtill the world inioyes it
But beauties waſte hath in the world an end,
And kept vnvſde the vſer ſo deſtroyes it:
No loue toward others in that boſome ſits
That on himſelfe ſuch murdrous ſhame commits.






 



