---
title: "Shakespeare Sonnet 148: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 148 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 148



O me! What eyes hath Love put in my head,
Which have no correspondence with true sight;
Or, if they have, where is my judgment fled,
That censures falsely what they see aright?
If that be fair whereon my false eyes dote,
What means the world to say it is not so?
If it be not, then love doth well denote
Love’s eye is not so true as all men’s: no,
How can it? O! how can Love’s eye be true,
That is so vexed with watching and with tears?
No marvel then, though I mistake my view;
The sun itself sees not, till heaven clears.
O cunning Love! with tears thou keep’st me blind,
Lest eyes well-seeing thy foul faults should find.




Read Sonnet 148 in Easy, Modern English:


Oh me! What eyes Love has put into my head, 
that fail to see things undistorted! 
Or if they can see things accurately, what’s happened to my judgment,
that falsely criticises what they see? 
If the one my flawed eyes see as beautiful is beautiful, 
what does everyone else mean when they say she isn’t? 
If she isn’t it shows that 
when one is in love the eyes don’t see as clearly as other eyes do. No, 
how could they? Oh, how could the eyes of love see accurately 
when they’re so distraught by staying awake and crying? 
It’s no wonder, then, that I’m mistaken in what I see; 
the sun itself doesn’t see anything until the sky clears. 
Oh, my cunning love! You keep me blind with tears 
so that, not seeing clearly, I can’t discover your bad faults.



