---
title: "Shakespeare Sonnet 46: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 46 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 46



Mine eye and heart are at a mortal war,
How to divide the conquest of thy sight;
Mine eye my heart thy picture’s sight would bar,
My heart mine eye the freedom of that right.
My heart doth plead that thou in him dost lie,
A closet never pierc’d with crystal eyes,
But the defendant doth that plea deny,
And says in him thy fair appearance lies.
To ‘cide this title is impannelled
A quest of thoughts, all tenants to the heart;
And by their verdict is determined
The clear eye’s moiety, and the dear heart’s part:
As thus: mine eye’s due is thine outward part,
And my heart’s right, thine inward love of heart.




Read Sonnet 46 in Easy, Modern English:


My eye and heart are at deadly war with each other 
over which one will have control of your image. 
My eye wants to bar my heart from the sight of the picture it has of you; 
my heart wants to deny my eye the right to the image it has of you. 
My heart insists that the true picture of you lies locked inside of him, 
never penetrated by eyes, that can reveal it. 
But the defendant denies that charge 
and claims that your beauty lies in him. 
To decide this case a jury of my thoughts has been assembled, 
all of them holding allegiance to the heart. 
And their verdict on which portion of your image 
belongs to the eye and which to the heart is: 
my eye is awarded your outward part 
and my heart has the right to the inward love of your heart.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 46










Sonnet 46 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 46, as published in Shakespeare’s 1609 Quarto:


MIne eye and heart are at a mortall warre,
How to deuide the conqueſt of thy ſight,
Mine eye,my heart their pictures ſight would barre,
My heart,mine eye the freeedome of that right,
My heart doth plead that thou in him dooſt lye,
(A cloſet neuer pearſt with chriſtall eyes )
But the defendant doth that plea deny,
And ſayes in him their faire appearance lyes.
To ſide this title is impannelled
A queſt of thoughts,all tennants to the heart,
And by their verdict is determined
The cleere eyes moyitie,and the deare hearts part.
As thus,mine eyes due is their outward part,
And my hearts right,their inward loue of heart.






 



