---
title: "Shakespeare Sonnet 121: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 121 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 121



‘Tis better to be vile than vile esteemed,
When not to be receives reproach of being,
And the just pleasure lost which is so deemed
Not by our feeling but by others’ seeing.
For why should others’ false adulterate eyes
Give salutation to my sportive blood?
Or on my frailties why are frailer spies,
Which in their wills count bad what I think good?
No, I am that I am, and they that level
At my abuses reckon up their own;
I may be straight, though they themselves be bevel.
By their rank thoughts my deeds must not be shown,
Unless this general evil they maintain:
All men are bad, and in their badness reign.




Read Sonnet 121 in Easy, Modern English:


It’s better to be vile than to be thought vile 
when not being so gets the same response as it would if you were, 
and you don’t even have the pleasure of doing the thing that evokes the criticism from those who think you’re vile, 
even though you don’t consider yourself to be. 
For why should others’ hypocritical corruption be allowed to wink knowingly at my lustful tendencies? 
Or those weaker than I am comment on my weaknesses, 
presuming to judge what I think is good, bad? 
No, I am what I am 
and those who condemn me are only revealing their own corruptness. 
I may be the straight one and they the ones out of line. 
You can’t judge my actions in terms of their vile thoughts, 
unless they’re prepared to maintain this general dictum: 
all men are bad and thrive in their badness.



