---
title: "Shakespeare Sonnet 53: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 53 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 53



What is your substance, whereof are you made,
That millions of strange shadows on you tend?
Since every one hath, every one, one shade,
And you but one, can every shadow lend.
Describe Adonis, and the counterfeit
Is poorly imitated after you;
On Helen’s cheek all art of beauty set,
And you in Grecian tires are painted new:
Speak of the spring, and foison of the year,
The one doth shadow of your beauty show,
The other as your bounty doth appear;
And you in every blessed shape we know.
In all external grace you have some part,
But you like none, none you, for constant heart.




Read Sonnet 53 in Easy, Modern English:


What is there so special about you, what are you made of, 
that you can express millions of unusual forms? 
Everyone else has only one form but you, 
although just one person, can add something to everyone else’s form. 
Try and paint Adonis and the forgery is a poor imitation of you. 
Or capture Helen in all her beauty and it’s you, 
newly painted in Grecian clothes. 
Mention the spring and the rich harvest season – 
the one is just a weak reflection of your beauty 
and the other a pale imitation of your richness. 
We recognise you in every beautiful object we see. 
There’s something of you in every appearance of beauty 
but you’re not like any of them – and none of them are like you – in the constancy of your heart.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 53










Sonnet 53 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 53, as published in Shakespeare’s 1609 Quarto:


WHat is your ſubstance,whereof are you made,
That millions of ſtrange ſhaddowes on you tend?
Since euery one,hath euery one,one ſhade,
And you but one,can euery ſhaddow lend:
Deſcribe Adonis and the counterfet,
Is poorely immitated after you,
On Hellens cheeke all art of beautie ſet,
And you in Grecian tires are painted new:
Speake of the ſpring,and foyzon of the yeare,
The one doth ſhaddow of your beautie ſhow,
The other as your bountie doth appeare,
And you in euery bleſſed ſhape we know.
In all externall grace you haue ſome part,
But you like none,none you for conſtant heart.






 





