---
title: "Shakespeare Sonnet 114: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 114 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 114



Or whether doth my mind, being crowned with you,
Drink up the monarch’s plague, this flattery?
Or whether shall I say mine eye saith true,
And that your love taught it this alchemy,
To make of monsters and things indigest
Such cherubins as your sweet self resemble,
Creating every bad a perfect best
As fast as objects to his beams assemble?
O ’tis the first; ’tis flattery in my seeing,
And my great mind most kingly drinks it up.
Mine eye well knows what with his gust is greeing,
And to his palate doth prepare the cup.
If it be poisoned, tis the lesser sin
That mine eye loes it and doth first begin.




Read Sonnet 114 in Easy, Modern English:


Or is it that my mind, crowned by you, 
has become the victim of flattery, that weakness of monarchs? 
Or could it be that my eyes are seeing accurately 
and that your love has given it this magical power 
of transforming monsters and other unappetising things 
into cherubs that resemble your sweet shape, 
turning everything unattractive into perfection 
as soon as it appears before my eyes? 
Oh, it’s the first one: flattery in my eyesight, 
and my mind drinks it up as a kings drinks up flattery. 
My eye knows what I likes to see 
and that’s the cup it prepares for me. 
If it’s a poisoned cup there’s no risk to me: 
my eye will taste it first.



