---
title: "Shakespeare Sonnet 5: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 5 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 5



Those hours, that with gentle work did frame
The lovely gaze where every eye doth dwell,
Will play the tyrants to the very same
And that unfair which fairly doth excel;
For never-resting time leads summer on
To hideous winter, and confounds him there;
Sap checked with frost, and lusty leaves quite gone,
Beauty o’er-snowed and bareness every where:
Then were not summer’s distillation left,
A liquid prisoner pent in walls of glass,
Beauty’s effect with beauty were bereft,
Nor it, nor no remembrance what it was:
But flowers distill’d, though they with winter meet,
Leese but their show; their substance still lives sweet.




Read Sonnet 5 in Easy, Modern English:


Time, that so carefully made 
those beautiful eyes that every other eye gazes at, 
will become a tyrant to those same lovely eyes and make them ugly; 
because never-resting time leads summer 
into hideous winter and destroys it there. 
Sap is stopped from rising by the frost and the leaves disappear; 
beauty is covered with snow and all the trees are bare. 
Then, if summer’s distillation hadn’t been preserved as a prisoner in a glass vial, 
that summer’s legacy would be lost with that summer’s death. 
Neither it nor the memory of what it was would remain. 
But flowers that have been distilled, 
even though they’ve been destroyed by winter, 
lose only their outward appearance: 
their substance lives on sweetly.




Listen to Sir John Gielgud Read Sonnet 5 










Sonnet 5 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 5, as published in Shakespeare’s 1609 Quarto:


THoſe howers that with gentle worke did frame,
The louely gaze where euery eye doth dwell
Will play the tirants to the very ſame,
And that vnfaire which fairely doth excell:
For neuer reſting time leads Summer on,
To hidious winter and confounds him there,
Sap checkt with froſt and luſtie leau’s quite gon.
Beauty ore-ſnow’d and barenes euery where,
Then were not ſummers diſtillation left
A liquid priſoner pent in walls of glaſſe,
Beauties effect with beauty were bereft,
Nor it nor noe remembrance what it was.
But flowers diſtil’d though they with winter meete,
Leeſe but their ſhow,their ſubſtance ſtill liues ſweet.




 

