---
title: "Shakespeare Sonnet 88: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 88 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 88



When thou shalt be dispos’d to set me light,
And place my merit in the eye of scorn,
Upon thy side, against myself I’ll fight,
And prove thee virtuous, though thou art forsworn.
With mine own weakness being best acquainted,
Upon thy part I can set down a story
Of faults concealed, wherein I am attainted;
That thou in losing me shalt win much glory:
And I by this will be a gainer too;
For bending all my loving thoughts on thee,
The injuries that to myself I do,
Doing thee vantage, double-vantage me.
Such is my love, to thee I so belong,
That for thy right, myself will bear all wrong.




Read Sonnet 88 in Easy, Modern English:


Whenever you feel inclined to put me down 
and make me the object of scorn 
I’ll take your side and argue against myself, 
proving that you’re virtuous, even though you’re lying. 
Knowing my own failings best I can describe, on your behalf, 
the hidden faults with which I am afflicted so well 
that you will be admired for having disposed of me. 
And I will gain, too, 
by focusing all my loving thoughts on you. 
The injuries that I’ll do to myself 
will be to your advantage, thus benefiting me doubly. 
I love you so much – belong to you so completely – 
that ensuring that you receive your rights I will take all the blame.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 88










Sonnet 88 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 88, as published in Shakespeare’s 1609 Quarto:


WHen thou ſhalt be diſpode to ſet me light,
And place my merrit in the eie of skorne,
Vpon thy ſide,againſt my ſelfe ile fight,
And proue thee virtuous,though thou art forſworne:
With mine owne weakeneſſe being beſt acquainted,
Vpon thy part I can ſet downe a ſtory
Of faults conceald,wherein I am attainted :
That thou in looſing me,ſhall win much glory:
And I by this wil be a gainer too,
For bending all my louing thoughts on thee,
The iniuries that to my ſelfe I doe,
Doing thee vantage,duble vantage me.
Such is my loue,to thee I ſo belong,
That for thy right,my ſelfe will beare all wrong.




 



