---
title: "Shakespeare Sonnet 73: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 73 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 73



That time of year thou mayst in me behold
When yellow leaves, or none, or few, do hang
Upon those boughs which shake against the cold,
Bare ruined choirs, where late the sweet birds sang.
In me thou see’st the twilight of such day
As after sunset fadeth in the west;
Which by and by black night doth take away,
Death’s second self, that seals up all in rest.
In me thou see’st the glowing of such fire,
That on the ashes of his youth doth lie,
As the death-bed, whereon it must expire,
Consum’d with that which it was nourish’d by.
This thou perceiv’st, which makes thy love more strong,
To love that well, which thou must leave ere long.




Read Sonnet 73 in Easy,  Modern English:


You may see that time of year in me 
when few, or no, yellow leaves hang 
on those branches that shiver in the cold 
bare ruins of the choir stalls where sweet birds sang so recently. 
You see, in me, the twilight of a day, 
after the sun has set in the west, 
extinguished by the black night that imitates Death, 
which closes everything in rest. 
You see in me the glowing embers 
that are all that is left of the fire of my youth – 
the deathbed on which youth must inevitably die, 
consumed by the life that once fed it. 
This is something you can see, and it gives your love the strength deeply 
to love that which you have to lose soon.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 73










Sonnet 73 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 73, as published in Shakespeare’s 1609 Quarto:


THat time of yeeare thou maiſt in me behold,
When yellow leaues,or none,or fewe doe hange
Vpon thoſe boughes which ſhake againſt the could,
Bare rn’wd quiers,where late the ſweet birds ſang.
In me thou ſeeſt the twi-light of ſuch day,
As after Sun-ſet fadeth in the Weſt,
Which by and by blacke night doth take away,
Deaths ſecond ſelfe that ſeals vp all in reſt.
In me thou ſeeſt the glowing of ſuch fire,
That on the aſhes of his youth doth lye,
As the death bed,whereon it muſt expire,
Conſum’d with that which it was nurriſht by.
This thou perceu’ſt,which makes thy loue more ſtrong,
To loue that well,which thou muſt leaue ere long.






 


Interested in Shakespeare’s sonnet 73? If so you can get some additional free information by visiting our friends over at 
PoemAnalysis to read their analysis of sonnet 73
.


 





