---
title: "Shakespeare Sonnet 81: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 81 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 81



Or I shall live your epitaph to make,
Or you survive when I in earth am rotten,
From hence your memory death cannot take,
Although in me each part will be forgotten.
Your name from hence immortal life shall have,
Though I, once gone, to all the world must die:
The earth can yield me but a common grave,
When you entombed in men’s eyes shall lie.
Your monument shall be my gentle verse,
Which eyes not yet created shall o’er-read;
And tongues to be, your being shall rehearse,
When all the breathers of this world are dead;
You still shall live, such virtue hath my pen,
Where breath most breathes, even in the mouths of men.




Read Sonnet 81 in Easy, Modern English:


Either I will live to write your epitaph 
or you will survive my rotting in the grave. 
Death can’t obliterate the memory of you, 
although everything about me will be forgotten. 
Your name will live forever, 
whereas I, once I’m gone, will be dead to the world. 
All I will be able to get will be a simple grave 
but you will be in tombed in everyone’s eyes. 
Your monument will be my loving poems, 
which will be read by eyes not yet born, 
and tongues not yet born will recite them 
when everyone now breathing in this world will be dead. 
You’ll live on – my pen has that power – 
where life is most evident: in the very mouths of men.




Listen to Sir Ian McKellen read Shakespeare’s sonnet 81










Sonnet 81 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 81, as published in Shakespeare’s 1609 Quarto:


OR I fhall liue your Epitaph to make,
Or you ſuruiue when I in earth am rotten,
From hence your memory death cannot take,
Although in me each part will be forgotten.
Your name from hence immortall life ſhall haue,
Though I ( once gone) to all the world muſt dye,
The earth can yeeld me but a common graue,
When you intombed in mens eyes ſhall lye,
Your monument ſhall be my gentle verſe,
Which eyes not yet created ſhall ore-read,
And toungs to be, your beeing ſhall rehearſe,
When all the breathers of this world are dead,
  You ſtill ſhal liue (ſuch vertue hath my Pen)
  Where breath moſt breaths,euen in the mouths of men.




 



