---
title: "Shakespeare Sonnet 37: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 37 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 37



As a decrepit father takes delight
To see his active child do deeds of youth,
So I, made lame by Fortune’s dearest spite,
Take all my comfort of thy worth and truth;
For whether beauty, birth, or wealth, or wit,
Or any of these all, or all, or more,
Entitled in thy parts, do crowned sit,
I make my love engrafted to this store:
So then I am not lame, poor, nor despis’d,
Whilst that this shadow doth such substance give
That I in thy abundance am suffic’d,
And by a part of all thy glory live.
Look what is best, that best I wish in thee:
This wish I have; then ten times happy me!




Read Sonnet 37 in Easy, Modern English:


In the same way as a decrepit father delights 
in watching his energetic child’s youthful activities, 
I, who have been crippled by the spitefulness of fortune, 
take comfort in your qualities and fidelity. 
Because, whether beauty, rank, wealth, or intelligence, 
or any of those, or all of them, 
or any additional qualities, are your crowning glories, 
I’m attaching my love to them. 
By doing that I’m not lame, poor nor despised, 
as long as this illusion has enough substance 
to allow your good luck to satisfy me 
and let me live off some of your glory. 
Whatever you consider the best that’s what I wish for you. 
In having this wish I’m ten times lucky.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 37










Sonnet 37 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 37, as published in Shakespeare’s 1609 Quarto:


AS a decrepit father takes delight,
To ſee his actiue childe do deeds of youth,
So I , made lame by Fortunes deareſt ſpight
Take all my comfort of thy worth and truth.
For whether beauty,birth,or wealth,or wit,
Or any of theſe all,or all,or more
Intitled in their parts,do crowned ſit,
I make my loue ingrafted to this ſtore:
So then I am not lame,poore, nor diſpiſ’d,
Whilſt that this ſhadow doth ſuch ſubſtance giue,
That I in thy abundance am ſuffic’d,
And by a part of all thy glory liue:
Looke what is beſt,that beſt I wiſh in thee,
This wiſh I haue,then ten times happy me.






 



