---
title: "Shakespeare Sonnet 16: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 16 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 16



But wherefore do not you a mightier way
Make war upon this bloody tyrant, Time?
And fortify your self in your decay
With means more blessed than my barren rhyme?
Now stand you on the top of happy hours,
And many maiden gardens, yet unset,
With virtuous wish would bear you living flowers,
Much liker than your painted counterfeit:
So should the lines of life that life repair,
Which this, Time’s pencil, or my pupil pen,
Neither in inward worth nor outward fair,
Can make you live your self in eyes of men.
To give away yourself, keeps yourself still,
And you must live, drawn by your own sweet skill.




Read Sonnet 16 in Easy, Modern English:


But why don’t you use a more effective way 
of fighting this terrible tyrant, Time? 
And defend yourself 
with more effective methods than my useless poems? 
You are right at the peak of your life, 
and many maiden gardens, still unplanted, 
would love to bear you fresh young flowers 
much more like you than your portrait is. 
So your children, whose existence ensures your continuance, can give you perpetual life, 
something which neither Time’s paintbrush nor my poor pen can do. 
By giving yourself away you will preserve yourself, 
and so you will live, yourself being the artist who paints you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 16










Sonnet 16 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 16, as published in Shakespeare’s 1609 Quarto:


BVt wherefore do not you a mightier waie
Make warre vppon this bloudie tirant time?
And fortifie your ſelfe in your decay
With meanes more bleſſed then my barren rime?
Now ſtand you on the top of happie houres,
And many maiden gardens yet vnſet,
With vertuous wiſh would beare your liuing flowers,
Much liker then your painted counterfeit:
So ſhould the lines of life that life repaire
Which this (Times penſel or my pupill pen )
Neither in inward worth nor outward faire
Can make you liue your ſelfe in eies of men,
To giue away your ſelfe,keeps your ſelfe ſtill,
And you muſt liue drawne by your owne ſweet ſkill


 




 

