---
title: "Shakespeare Sonnet 120: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 120 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 120



That you were once unkind befriends me now,
And for that sorrow, which I then did feel,
Needs must I under my transgression bow,
Unless my nerves were brass or hammer’d steel.
For if you were by my unkindness shaken,
As I by yours, you’ve passed a hell of time;
And I, a tyrant, have no leisure taken
To weigh how once I suffered in your crime.
O! that our night of woe might have remembered
My deepest sense, how hard true sorrow hits,
And soon to you, as you to me, then tendered
The humble salve, which wounded bosoms fits!
But that your trespass now becomes a fee;
Mine ransoms yours, and yours must ransom me.




Read Sonnet 120 in Easy, Modern English:


That you were once unfaithful to me 
is now a benefit 
and, unless my nerves were made of brass or beaten steel, 
I have to bow my head as an act of repentance for the sorrow that I felt, 
because if you were as upset by my cruelty 
as I was by yours, then your agonies have been like those of hell. 
And I, a tyrant, haven’t taken the time 
to think about the suffering I’ve undergone from your treatment of me. 
Oh, if only our period of black depression had reminded 
my innermost soul of how pitilessly real sorrow strikes 
I would quickly have offered you the healing ointment of love that mends the wounded heart, 
as you once quickly offered it to me! 
But your crime against me has now become a debt. 
My crime cancels your debt, and yours must cancel mine.



