---
title: "Shakespeare Sonnet 60: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 60 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 60



Like as the waves make towards the pebbled shore,
So do our minutes hasten to their end;
Each changing place with that which goes before,
In sequent toil all forwards do contend.
Nativity, once in the main of light,
Crawls to maturity, wherewith being crowned,
Crooked eclipses ‘gainst his glory fight,
And Time that gave doth now his gift confound.
Time doth transfix the flourish set on youth
And delves the parallels in beauty’s brow,
Feeds on the rarities of nature’s truth,
And nothing stands but for his scythe to mow:
And yet to times in hope, my verse shall stand
Praising thy worth, despite his cruel hand.




Read Sonnet 60 in Easy, Modern English:


Just as the waves push toward the pebbled shore, 
our minutes hasten toward their end, 
each moment replacing the one that went before, 
straining against each other to move forward in successive effort. 
Once born, 
creatures crawl from that pre-birth ocean of light to maturity, 
facing cruel eclipses that obstruct their glory, 
and Time, that gives, begins to destroy its own gifts. 
Time pierces the flowering cast of youth 
and digs deep lines in beauty’s forehead: 
feeds on the most exquisite of nature’s specimens, 
and there’s nothing that its scythe won’t mow. 
And yet my verses will last to be read by future generations, 
praising your worth in spite of Time’s cruel hand.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 60










Sonnet 60 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 60, as published in Shakespeare’s 1609 Quarto:


LIke as the waues make towards the pibled ſhore,
So do our minuites haſten to their end,
Each changing place with that which goes before,
In ſequent toile all forwards do contend.
Natiuity once in the maine of light,
Crawles to maturity,wherewith being crown’d,
Crooked eclipſes gainſt his glory fight,
And time that gaue,doth now his gift confound.
Time doth tranſfixe the floriſh ſet on youth,
And delues the paralels in beauties brow,
Feedes on the rarities of natures truth,
And nothing ſtands but for his ſiethe to mow.
And yet to times in hope,my verſe ſhall ſtand
Praiſing thy worth,diſpight his cruell hand.






 





