---
title: "Shakespeare Sonnet 69: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 69 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 69



Those parts of thee that the world’s eye doth view
Want nothing that the thought of hearts can mend;
All tongues, the voice of souls, give thee that due,
Uttering bare truth, even so as foes commend.
Thy outward thus with outward praise is crown’d;
But those same tongues, that give thee so thine own,
In other accents do this praise confound
By seeing farther than the eye hath shown.
They look into the beauty of thy mind,
And that in guess they measure by thy deeds;
Then, churls, their thoughts, although their eyes were kind,
To thy fair flower add the rank smell of weeds:
But why thy odour matcheth not thy show,
The soil is this, that thou dost common grow.




Read Sonnet 69 in Easy, Modern English:


Those parts of you that the world can see 
leave nothing to be desired. 
Everyone says so, granting you that without reservation. 
They’re only speaking the obvious truth – even your enemies agree. 
And so, your outward self is rewarded with public praise. 
But those very people who give that well deserved praise to your beauty 
change their tune when they look beyond the superficial. 
They examine the beauty of your mind 
and gain insight by taking note of your deeds. 
Then, although they’ve been kind about the beautiful fragrance of your looks, 
they churlishly insist on the rank smell of the weeds of your actions. 
So if your deeds don’t match your looks, this is the reason: 
that you’re surrounding yourself with common companions.




Listen to Sir John Gielgud read Shakespeare’s sonnet 69










Sonnet 69 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 69, as published in Shakespeare’s 1609 Quarto:


THoſe parts of thee that the worlds eye doth view,
Want nothing that the thought of hearts can mend:
All toungs(the voice of ſoules)giue thee that end,
Vttring bare truth,euen ſo as foes Commend.
Their outward thus with outward praiſe is crownd,
But thoſe ſame toungs that giue thee ſo thine owne,
In other accents doe this praiſe confound
By ſeeing farther then the eye hath ſhowne.
They looke into the beauty of thy mind,
And that in gueſſe they meaſure by thy deeds,
Then churls their thoughts(although their eies were kind)
To thy faire flower ad the rancke ſmell of weeds,
But why thy odor matcheth not thy ſhow,
The ſolye is this,that thou doeſt common grow.




 





