---
title: "Shakespeare Sonnet 72: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 72 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 72



O! lest the world should task you to recite
What merit lived in me, that you should love
After my death,–dear love, forget me quite,
For you in me can nothing worthy prove.
Unless you would devise some virtuous lie,
To do more for me than mine own desert,
And hang more praise upon deceased I
Than niggard truth would willingly impart:
O! lest your true love may seem false in this
That you for love speak well of me untrue,
My name be buried where my body is,
And live no more to shame nor me nor you.
For I am shamed by that which I bring forth,
And so should you, to love things nothing worth.




Read Sonnet 72 in Easy, Modern English:


Oh, in case the world should challenge you to say 
what merit there was in me that could make you love me, 
forget me completely once I’m dead, dear love, 
because you couldn’t say anything convincing about me 
unless you could invent some generous lie 
which would make me sound better than I deserve 
and attach more praise to my deceased self 
than the ungenerous truth would. 
Oh, in case your true love should become false by doing that – 
as it will if you speak well of me, untruthfully, out of love for me – 
let my name be buried with my body 
and not live to bring shame to me nor you. 
Because I’m ashamed of the things I create, 
and you should be too, to love such worthless things.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 72










Sonnet 72 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 72, as published in Shakespeare’s 1609 Quarto:


O Leaſt the world ſhould taske you to recite,
 What merit liu’d in me that you ſhould loue
After my death(deare loue)for get me quite,
For you in me can nothing worthy proue.
Vnleſſe you would deuiſe ſome vertuous lye,
To doe more for me then mine owne deſert,
And hang more praiſe vpon deceaſed I,
Then nigard truth would willingly impart:
O leaſt your true loue may ſeeme falce in this,
That you for loue ſpeake well of me vntrue,
My name be buried where my body is,
And liue no more to ſhame nor me,nor you.
For I am ſhamd by that which I bring forth,
And ſo ſhould you,to loue things nothing worth.




 



