---
title: "Shakespeare Sonnet 21: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 21 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 21



So is it not with me as with that Muse,
Stirred by a painted beauty to his verse,
Who heaven itself for ornament doth use
And every fair with his fair doth rehearse,
Making a couplement of proud compare
With sun and moon, with earth and sea’s rich gems,
With April’s first-born flowers, and all things rare,
That heaven’s air in this huge rondure hems.
O! let me, true in love, but truly write,
And then believe me, my love is as fair
As any mother’s child, though not so bright
As those gold candles fixed in heaven’s air:
Let them say more that like of hearsay well;
I will not praise that purpose not to sell.




Read Sonnet 21 in Easy, Modern English:


I am not like that poet 
who uses artificial comparisons, 
even images of heaven itself, 
to enhance his descriptions of his loved one, 
tediously likening every beautiful object to his love, 
in exaggerated comparisons with the sun and the moon, 
the fresh spring flowers, 
and all those wonderful things that reflect heaven on earth. 
Oh, let me be truthful in love but match that with truth in my poems. 
Believe me, then, my love is as beautiful as anyone else, 
although not as bright as the stars. 
Let those who love gossip say, if they want to, 
that I won’t praise something that I have no intention of selling.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 21










Sonnet 21 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 21, as published in Shakespeare’s 1609 Quarto:


AWomans face with natures owne hande painted,
Haſte thou, the Maſter Miſtris of my paſſion,
A womans gentle hart but not acquainted
With ſhifting change as is falſe womens faſhion,
An eye more bright then theirs,leſſe falſe in rowling:
Gilding the obiect where-vpon it gazeth,
A man in hew all Hews in his controwling,
Which ſteales mens eyes and womens ſoules amaſeth,
And for a woman wert thou firſt created,
Till nature as ſhe wrought thee fell a dotinge,
And by addition me of thee defeated,
By adding one thing to my purpoſe nothing.
But ſince ſhe prickt thee out for womens pleaſure,
Mine be thy loue and thy loues vſe their treaſure.


 









