---
title: "Shakespeare Sonnet 104: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 104 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 104



To me, fair friend, you never can be old,
For as you were when first your eye I ey’d,
Such seems your beauty still. Three winters cold,
Have from the forests shook three summers’ pride,
Three beauteous springs to yellow autumn turn’d,
In process of the seasons have I seen,
Three April perfumes in three hot Junes burn’d,
Since first I saw you fresh, which yet are green.
Ah! yet doth beauty like a dial-hand,
Steal from his figure, and no pace perceiv’d;
So your sweet hue, which methinks still doth stand,
Hath motion, and mine eye may be deceiv’d:
For fear of which, hear this thou age unbred:
Ere you were born was beauty’s summer dead.




Read Sonnet 104 in Easy, Modern English:


To me, lovely friend, you could never be old, 
because your beauty seems unchanged 
from the time I first saw your eyes. 
Three cold winters have shaken the leaves of 
three beautiful springs and autumns from the forests 
as I have watched the seasons pass: 
The sweet smell of three Aprils have been burned up in three hot Junes 
since I first saw your youthful beauty, which is still in its prime. 
Ah! But beauty moves forward continually, imperceptibly, like the hands of a clock. 
In the same way, your beauty, which seems unchanged to me, 
moves forward, deceiving my eyes. 
In consideration of that, listen, you unborn generations: 
the height of beauty was dead before you were born.


 



