---
title: "Shakespeare Sonnet 68: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 68 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 68



Thus is his cheek the map of days outworn,
When beauty lived and died as flowers do now,
Before these bastard signs of fair were born,
Or durst inhabit on a living brow;
Before the golden tresses of the dead,
The right of sepulchres, were shorn away,
To live a second life on second head;
Ere beauty’s dead fleece made another gay:
In him those holy antique hours are seen,
Without all ornament, itself and true,
Making no summer of another’s green,
Robbing no old to dress his beauty new;
And him as for a map doth Nature store,
To show false Art what beauty was of yore.




Read Sonnet 68 in Easy, Modern English:


And so, his face is a map of times past – 
when beautiful people lived and died with the transience of flowers – 
before such illegitimate signs of beauty were created, 
or there was any thought of stamping them on the face of a living person; 
before the golden locks of dead bodies, 
which rightly belong in graves, were shorn 
to be made into wigs for living heads; 
before the beautiful fleece of dead people served to make living people happy. 
You can see those ancient times 
in his unadorned, naturally beautiful, face, 
which doesn’t capitalise on another’s glory, 
nor does he rob the old to adorn his beauty. 
Nature keeps him as a map 
to make a comparison between the cosmetic beauty of today and real beauty as it used to be.




Watch a performance of Shakespeare’s sonnet 68








Sonnet 68 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 68, as published in Shakespeare’s 1609 Quarto:


Thus is his cheeke the map of daies out-worne,
When beauty liu’d and dy’ed as flowers do now,
Before thee baſtard ſignes of faire were borne,
Or durſt inhabit on a liuing brow:
Before the goulden treſſes of the dead,
The right of ſepulchers,were ſhorne away,
To liue a ſcond life on ſecond head,
Ere beauties dead fleece made another gay:
In him thoſe holy antique howers are ſeene,
Without all ornament,it ſelfe and true,
Making no ſummer of an others greene,
Robbing no ould to dreſſe his beauty new,
And him as for a map doth Nature ſtore,
To ſhew faulſe Art what beauty was of yore.


 





