---
title: "Shakespeare Sonnet 141: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 141 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 141



In faith I do not love thee with mine eyes,
For they in thee a thousand errors note;
But ’tis my heart that loves what they despise,
Who, in despite of view, is pleased to dote.
Nor are mine ears with thy tongue’s tune delighted;
Nor tender feeling, to base touches prone,
Nor taste, nor smell, desire to be invited
To any sensual feast with thee alone:
But my five wits nor my five senses can
Dissuade one foolish heart from serving thee,
Who leaves unswayed the likeness of a man,
Thy proud heart’s slave and vassal wretch to be:
Only my plague thus far I count my gain,
That she that makes me sin awards me pain.




Read Sonnet 141 in Easy, Modern English:


No, really, it isn’t with my eyes that I love you, 
because they record a thousand flaws in you. 
Instead, it’s my heart that loves what my eyes despise 
and dotes on you in spite of what you look like. 
Nor are my ears delighted by the sound of your voice. 
Nor do I long to touch you sexually. 
Nor do my senses of taste and smell wish to be invited 
to any sensual feast in which you are the only item on the menu. 
But all my mental faculties and my five senses 
can’t persuade my foolish heart not to serve you; 
they leave me looking like a man but without the free will of a man, 
reduced to being the slave and property of your proud heart. 
The only thing I gain from being plagued like this 
is that the one who is making me sin rewards me with pain.




 



