---
title: "Shakespeare Sonnet 61: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 61 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 61



Is it thy will, thy image should keep open
My heavy eyelids to the weary night?
Dost thou desire my slumbers should be broken,
While shadows like to thee do mock my sight?
Is it thy spirit that thou send’st from thee
So far from home into my deeds to pry,
To find out shames and idle hours in me,
The scope and tenor of thy jealousy?
O, no! thy love, though much, is not so great:
It is my love that keeps mine eye awake:
Mine own true love that doth my rest defeat,
To play the watchman ever for thy sake:
For thee watch I, whilst thou dost wake elsewhere,
From me far off, with others all too near.




Read Sonnet 61 in Easy, Modern English:


Is this what you want – that the mental picture of you should keep 
my heavy eyelids open all through the weary night? 
Do you want my sleep to be interrupted by tantalizing images of you? 
Are you sending your spirit 
so far from home to pry into my affairs, 
to find out the shameful things I’ve been up to in my idle hours? 
Is that the extent and nature of your jealously? 
Oh no, although your love for me is great, it’s not that great! 
It’s my great love that confounds my sleep, 
constantly concerned about you. 
I watch over you while you are awake somewhere else, 
far away from me, while certain others are all too near to you!




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 61










Sonnet 61 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 61, as published in Shakespeare’s 1609 Quarto:


IS it thy wil,thy Image ſhould keepe open
My heauy eielids to the weary night?
Doſt thou deſire my ſlumbers ſhould be broken,
While ſhadowes like to thee do mocke my ſight?
Is it thy ſpirit that thou ſend’ſt from thee
So farre from home into my deeds to prye,
To find out ſhames and idle houres in me,
The skope and tenure of thy Ielouſie?
O no,thy loue though much,is not ſo great,
It is my loue that keepes mine eie awake,
Mine owne true loue that doth my reſt defeat,
To plaie the watch-man euer for thy ſake.
For thee watch I,whilſt thou doſt wake elſewhere,
From me farre of , with others all to neere.




 





