---
title: "Shakespeare Sonnet 57: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 57 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 57



Being your slave what should I do but tend
Upon the hours, and times of your desire?
I have no precious time at all to spend;
Nor services to do, till you require.
Nor dare I chide the world without end hour,
Whilst I, my sovereign, watch the clock for you,
Nor think the bitterness of absence sour,
When you have bid your servant once adieu;
Nor dare I question with my jealous thought
Where you may be, or your affairs suppose,
But, like a sad slave, stay and think of nought
Save, where you are, how happy you make those.
So true a fool is love, that in your will,
Though you do anything, he thinks no ill.




Read Sonnet 57 in Easy, Modern English:


As your slave, what else should I do 
but spend my time waiting to do whatever you want me to? 
I don’t have any valuable time to spend, 
or any tasks to do until you need that. 
Nor do I dare complain about the endless hours 
as I watch the clock, waiting for you, my sovereign, 
nor contemplate the bitterness of separation 
after you’ve said goodbye to your servant. 
Nor do I dare allow my jealous thoughts 
to wonder where you may be, or speculate about what you may be up to, 
but like a forlorn slave, I wait, thinking of nothing 
except how happy you’re making whoever you are with. 
Love makes such a fool out of one 
that he thinks nothing about whatever you do to satisfy your ideas.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 57










Sonnet 57 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 57, as published in Shakespeare’s 1609 Quarto:


BEing your ſlaue what ſhould I doe but tend,
Vpon the houres,and times of your deſire?
I haue no precious time at al to ſpend;
Nor ſeruices to doe til you require.
Nor dare I chide the world without end houre,
Whilſt I(my ſoueraine)watch the clock for you,
Nor thinke the bitterneſſe of abſence ſowre,
VVhen you haue bid your ſeruant once adieue.
Nor dare I question with my iealious thought,
VVhere you may be,or your affaires ſuppoſe,
But like a ſad ſlaue ſtay and thinke of nought
Saue where you are , how happy you make thoſe.
So true a fool is loue,that in your Will,
(Though you doe any thing)he thinkes no ill.




Interested in Shakespeare’s sonnet 57? If so you can get some additional free information by visiting our friends over at 
PoemAnalysis to read their analysis of sonnet 57
.


 





