---
title: "Shakespeare Sonnet 84: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 84 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 84



Who is it that says most, which can say more,
Than this rich praise, that you alone, are you,
In whose confine immured is the store
Which should example where your equal grew?
Lean penury within that pen doth dwell
That to his subject lends not some small glory;
But he that writes of you, if he can tell
That you are you, so dignifies his story.
Let him but copy what in you is writ,
Not making worse what nature made so clear,
And such a counterpart shall fame his wit,
Making his style admired every where.
You to your beauteous blessings add a curse,
Being fond on praise, which makes your praises worse.




Read Sonnet 84 in Easy, Modern English:


Which poet says the most? Which one can say 
more in praise of you than this: that you are unique? 
All beauty is packed into you, 
so what is there to compare you with anything other than yourself? 
It’s a very poor poet who can’t enhance his subject even a little. 
But whoever writes about you 
will dignify his writing by plain simple reporting. 
All he has to do is copy what is already written in you, 
not damaging what nature has made so perfectly, 
and he will have such an image that he will become famous, 
his style universally admired. 
In spite of all the beauty, you’re blessed with 
you make the mistake of being too fond of praise, 
because that makes them write even worse praise in their efforts to flatter you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 84










Sonnet 84 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 84, as published in Shakespeare’s 1609 Quarto:


WHo is it that ſayes moſt,which can ſay more,
Then this rich praiſe,that you alone,are you,
In whoſe confine immured if the ſtore,
Which ſhould example where your equall grew,
Leane penurie within that Pen doth dwell,
That to his ſubiect lends not ſome ſmall glory,
But he that writes of you,if he can tell,
That you are you,ſo dignifies his ſtory.
Let him but coppy what in you is writ,
Not making worſe what nature made ſo cleere.
And ſuch a counter-part ſhall fame his wit,
Making his ſtile admired euery where.
You to your beautious bleſſings adde a curſe,
Being fond on praiſe,which makes your praiſes worſe.




 



