---
title: "Shakespeare Sonnet 41: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 41 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 41



Those pretty wrongs that liberty commits,
When I am sometime absent from thy heart,
Thy beauty, and thy years full well befits,
For still temptation follows where thou art.
Gentle thou art, and therefore to be won,
Beauteous thou art, therefore to be assail’d;
And when a woman woos, what woman’s son
Will sourly leave her till he have prevail’d?
Ay me! but yet thou might’st my seat forbear,
And chide thy beauty and thy straying youth,
Who lead thee in their riot even there
Where thou art forced to break a twofold truth:–
Hers by thy beauty tempting her to thee,
Thine by thy beauty being false to me.




Read Sonnet 41 in Easy, Modern English:


Those innocent infidelities that your independence allows you to commit 
when you occasionally forget about me 
are normal for someone with your youthfulness and beauty 
because temptation follows you wherever you go. 
You’re noble and therefore regarded as someone to be won. 
You’re beautiful and therefore to be pursued. 
And when a woman is the wooer what man 
would rudely refuse her till he has had his way with her? 
But dear me, you might resist when it comes to my mistress, 
and keep your beauty and youthful wantonness in check: 
they’re leading you into a lack of control 
that makes you break a double bond – 
hers by being tempted by your beauty, 
and yours, where your beauty makes you false to me.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 41










Sonnet 41 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 41, as published in Shakespeare’s 1609 Quarto:


Thoſe pretty wrongs that liberty commits,
When I am ſome-time abſent from thy heart,
Thy beautie,and thy yeares full well befits,
For ſtill temptation followes where thou art.
Gentle thou art,and therefore to be wonne,
Beautious thou art,therefore to be aſſailed.
And when a woman woes,what womans ſonne,
Will ſourely leaue her till he haue preuailed.
Aye me,but yet thou mighſt my ſeate forbeare,
And chide thy beauty,and thy ſtraying youth,
Who lead thee in their ryot euen there
Where thou art forſt to break a two-fold truth:
Hers by thy beauty tempting her to thee,
Thine by thy beautie beeing falſe to me.






 



