---
title: "Shakespeare Sonnet 1: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 1 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 1



From fairest creatures we desire increase,
That thereby beauty’s rose might never die,
But as the riper should by time decrease,
His tender heir mught bear his memeory:
But thou, contracted to thine own bright eyes,
Feed’st thy light’st flame with self-substantial fuel,
Making a famine where abundance lies,
Thyself thy foe, to thy sweet self too cruel.
Thou that art now the world’s fresh ornament
And only herald to the gaudy spring,
Within thine own bud buriest thy content
And, tender churl, makest waste in niggarding.
Pity the world, or else this glutton be,
To eat the world’s due, by the grave and thee.




Read Sonnet 1 in Easy, Modern English:


We want all beautiful creatures to reproduce themselves 
so that beauty’s flower will not die out; 
but as an old man dies in time, 
he leaves a young heir to carry on his memory. 
But you, concerned only with your own beautiful eyes, 
feed the bright light of life with self-regarding fuel, 
making beauty shallow by your preoccupation with your looks.
In this you are your own enemy, 
being cruel to yourself. 
You, who are the world’s most beautiful ornament
and the chief messenger of spring, 
are burying your gifts within yourself. 
And, dear selfish one, because you decline to reproduce, 
you are actually wasting that beauty. 
Take pity on the world or else be the glutton
who devours, with the grave, what belongs to the world.




Listen to Sir Patrick Stewart Read Sonnet 1










Sonnet 1 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 1, as published in Shakespeare’s 1609 Quarto:


From faireſt creatures we deſire increaſe,
That thereby beauties Roſe might neuer die,
But as the riper ſhould by time deceaſe,
His tender heire might beare his memory:
But thou contracted to thine owne bright eyes,
Feed’ſt thy lights flame with ſelfe ſubſtantiall fewell,
Making a famine where aboundance lies,
Thy ſelfe thy foe,to thy ſweet ſelfe too cruell:
Thou that art now the worlds freſh ornament,
And only herauld to the gaudy ſpring,
Within thine owne bud burieſt thy content,
And tender chorle makſt waſt in niggarding:
Pitty the world,or elſe this glutton be,
 To eate the worlds due,by the graue and thee.




 

