---
title: "Shakespeare Sonnet 50: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 50 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 50



How heavy do I journey on the way,
When what I seek, my weary travel’s end,
Doth teach that ease and that repose to say,
‘Thus far the miles are measured from thy friend!’
The beast that bears me, tired with my woe,
Plods dully on, to bear that weight in me,
As if by some instinct the wretch did know
His rider lov’d not speed being made from thee.
The bloody spur cannot provoke him on,
That sometimes anger thrusts into his hide,
Which heavily he answers with a groan,
More sharp to me than spurring to his side;
For that same groan doth put this in my mind,
My grief lies onward, and my joy behind.




Read Sonnet 50 in Easy, Modern English:


How heavy my heart is as I travel 
because my goal – the weary destination – 
will provide, in its leisurely and relaxed state, the chance to think 
“I’m so many miles away from my friend.” 
The horse that’s carrying me, wearied by my sadness, 
plods heavily on, bearing the weight of my feelings 
as though the wretch knows by some instinct 
that his rider is reluctant to speed because he’s moving away from you. 
The blood-drawing spurs that I sometimes thrust into his hide in anger 
can’t make him go any faster. 
All he does is respond with a heavy groan 
that hurts me more than the spurs in his sides hurt him 
because it reminds me 
that my grief lies ahead and my joy is all behind.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 50










Sonnet 50 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 50, as published in Shakespeare’s 1609 Quarto:


HOw heauie doe I iourney on the way,
When what I ſeeke (my wearie trauels end)
Doth teach that eaſe and that repoſe to ſay
Thus farre the miles are meaſurde from thy friend.
The beaſt that beares me,tired with my woe,
Plods duly on,to beare that waight in me,
As if by ſome inſtinct the wretch did know
His rider lou’d not ſpeed being made from thee:
The bloody ſpurre cannot prouoke him on,
That ſome-times anger thruſts into his hide,
Which heauily he anſwers with a grone,
More ſharpe to me then ſpurring to his ſide,
For that ſame grone doth put this in my mind,
My greefe lies onward and my ioy behind.


 







