---
title: "Shakespeare Sonnet 152: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 152 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 152



In loving thee thou know’st I am forsworn,
But thou art twice forsworn, to me love swearing,
In act thy bed-vow broke and new faith torn,
In vowing new hate after new love bearing.
But why of two oaths’ breach do I accuse thee,
When I break twenty? I am perjured most;
For all my vows are oaths but to misuse thee
And all my honest faith in thee is lost,
For I have sworn deep oaths of thy deep kindness,
Oaths of thy love, thy truth, thy constancy,
And, to enlighten thee, gave eyes to blindness,
Or made them swear against the thing they see;
For I have sworn thee fair; more perjured I,
To swear against the truth so foul a lie!




Read Sonnet 152 in Easy, Modern English:


I realise that I’m breaking my promise by loving you; 
but by swearing that you love me you are breaking two promises: 
your marriage vow and, by making a new declaration of love, 
your promise to hate your new lover. 
But why am I accusing you of breaking two oaths 
when I break twenty? I am the bigger liar 
because all of my vows were made only to abuse you, 
and I’ve abandoned the truth. 
For I have sworn great oaths about your great kindness; 
oaths about your love, your fidelity, and your constancy. 
And to make you look better I gave my eyes up to blindness 
or made them see things that they didn’t: 
because I have sworn that you are beautiful my eye has perjured itself, 
telling such a foul lie when I have sworn to tell the truth!



