---
title: "Shakespeare Sonnet 15: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 15 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 15



When I consider every thing that grows
Holds in perfection but a little moment,
That this huge stage presenteth nought but shows
Whereon the stars in secret influence comment;
When I perceive that men as plants increase,
Cheered and checked even by the self-same sky,
Vaunt in their youthful sap, at height decrease,
And wear their brave state out of memory;
Then the conceit of this inconstant stay
Sets you most rich in youth before my sight,
Where wasteful Time debateth with decay
To change your day of youth to sullied night,
And all in war with Time for love of you,
As he takes from you, I engraft you new.




Read Sonnet 15 in Easy, Modern English:


When I consider that every living thing 
holds its state of perfection for only a brief moment; 
that this huge stage, the world, presents only sham performances, 
which the stars secretly influence; 
when I realise that men grow like plants, 
encouraged and inhibited by the same weather, 
show off when flushed with youthful sap, then declining when full-grown, 
wearing away until their youth has been forgotten; 
then the consideration of this short, unpredictable life 
makes me see you as rich in youth 
in the face of the plans of Time and Decay 
to change your day of youth to dingy night. 
And, at war with Time because of my love for you, 
as he’s taking from you I’m renewing you in my poetry.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 15










Sonnet 15 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 15, as published in Shakespeare’s 1609 Quarto:


WHen I conſider euery thing that growes
Holds in perfection but a little moment.
That this huge ſtage preſenteth nought but ſhowes
Whereon the Stars in ſecret influence comment.
When I perceiue that men as plants increaſe,
Cheared and checkt euen by the ſelfe-ſame skie:
Vaunt in their youthfull ſap,at height decreaſe,
And were their braue ſtate out of memory.
Then the conceit of this inconſtant ſtay,
Sets you moſt rich in youth before my ſight,
Where waſtfull time debateth with decay
To change your day of youth to ſullied night,
And all in war with Time for loue of you
As he takes from you, I ingraft you new.


 




 

