---
title: "Shakespeare Sonnet 137: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 137 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 137



Thou blind fool, Love, what dost thou to mine eyes,
That they behold, and see not what they see?
They know what beauty is, see where it lies,
Yet what the best is take the worst to be.
If eyes, corrupt by over-partial looks,
Be anchored in the bay where all men ride,
Why of eyes’ falsehood hast thou forged hooks,
Whereto the judgment of my heart is tied?
Why should my heart think that a several plot,
Which my heart knows the wide world’s common place?
Or mine eyes, seeing this, say this is not,
To put fair truth upon so foul a face?
In things right true my heart and eyes have erred,
And to this false plague are they now transferred.




Read Sonnet 137 in Easy, Modern English:


You blind fool, Love, what are you doing to my eyes, 
that they look but don’t see what they’re looking at? 
They know what beauty is and where it is 
but mistake the worst for the best. 
If eyes, seduced by flirtatious glances, 
always dwell on a woman’s sexual charms, 
why have you forged a link between that misleading impression of the eyes 
and the judgment of my heart? 
Why should I think that she is my exclusive property 
when I know that she is every man’s? 
Or allow my eyes to deny it and think that such a foul lie is the truth? 
My heart and my eyes have mistaken falsehood for truth 
and are now owned by this deceitful woman.



