---
title: "Shakespeare Sonnet 51: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 51 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 51



Thus can my love excuse the slow offence
Of my dull bearer when from thee I speed:
From where thou art why should I haste me thence?
Till I return, of posting is no need.
O! what excuse will my poor beast then find,
When swift extremity can seem but slow?
Then should I spur, though mounted on the wind,
In winged speed no motion shall I know,
Then can no horse with my desire keep pace.
Therefore desire, (of perfect’st love being made)
Shall neigh, no dull flesh, in his fiery race;
But love, for love, thus shall excuse my jade-
Since from thee going, he went wilful-slow,
Towards thee I’ll run, and give him leave to go.




Read Sonnet 51 in Easy, Modern English:


This is how my love for you excuses the slow progress 
of my weary horse as I speed away from you: 
“Why do I have to hurry there?” 
There’s no need to race until I’m on my way back. 
Oh, what excuse will my poor horse have then 
when even the most extreme speed will seem slow? 
Then, even if I were riding on the wind, I’d spur. 
Even in that flying speed I would feel as though I weren’t moving. 
No horse could keep pace with my desire then. 
My desire, made of the purest love, 
will deny that he’s a horse of 
flesh and blood
 in his fiery race. 
But, Love, for the sake of love I’ll excuse my old horse like this: 
since he deliberately slowed down as I was leaving you, 
I’ll let him go altogether and run back to you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 51










Sonnet 51 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 51, as published in Shakespeare’s 1609 Quarto:


THus can my loue excuſe the ſlow offence,
Of my dull bearer,when from thee I ſpeed,
From where thou art,why ſhoulld I haſt me thence,
Till I returne of poſting is noe need.
O what excuſe will my poore beaſt then find,
When ſwift extremity can ſeeme but ſlow,
Then ſhould I ſpurre though mounted on the wind,
In winged ſpeed no motion ſhall I know,
Then can no horſe with my deſire keepe pace,
Therefore deſire(of perfects loue being made)
Shall naigh noe dull fleſh in his fiery race,
But loue,for loue,thus ſhall excuſe my iade,
Since from thee going he went wilfull ſlow,
Towards thee ile run,and giue him leaue to goe.






 





