---
title: "Shakespeare Sonnet 7: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 7 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 7



Lo! in the orient when the gracious light
Lifts up his burning head, each under eye
Doth homage to his new-appearing sight,
Serving with looks his sacred majesty;
And having climb’d the steep-up heavenly hill,
Resembling strong youth in his middle age,
yet mortal looks adore his beauty still,
Attending on his golden pilgrimage;
But when from highmost pitch, with weary car,
Like feeble age, he reeleth from the day,
The eyes, ‘fore duteous, now converted are
From his low tract and look another way:
So thou, thyself out-going in thy noon,
Unlook’d on diest, unless thou get a son.




Read Sonnet 7 in Easy, Modern English:


Look! In the east when the glorious sun 
raises his burning head, all men’s eyes 
pay tribute to his new, fresh appearance, 
serving his majesty with looks of awe. 
And having climbed that steep hill to heaven 
like a strong youth in the prime of life, 
mortals still worship his beauty 
as they watch his golden climb into the sky. 
But when he staggers away, old and feeble, 
from his highest point with weary horses, 
the eyes that were dutiful before, 
now turn away from him and look elsewhere. 
So you, yourself, declining from your noonday glory, 
will die disregarded, unless you beget a son.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 7










Sonnet 7 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 7, as published in Shakespeare’s 1609 Quarto:


LOe in the Orient when the gracious light,
Lifts vp his burning head,each vnder eye
Doth homage to his new appearing ſight,
Seruing with lookes his ſacred maieſty,
And hauing climb’d the ſteepe vp heauenly hill,
Reſembling ſtrong youth in his middle age,
Yet mortall lookes adore his beauty ſtill,
Attending on his goulden pilgrimage:
But when from high-moſt pich with wery car,
Like feeble age he reeleth from the day,
The eyes(fore dutious )now conuerted are
From his low tract and looke an other way:
   So thou,thy ſelfe out-going in thy noon:
   Vnlok’d on dieſt vnleſſe thou get a ſonne.






 





