---
title: "Shakespeare Sonnet 42: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 42 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 42



That thou hast her it is not all my grief,
And yet it may be said I loved her dearly;
That she hath thee is of my wailing chief,
A loss in love that touches me more nearly.
Loving offenders thus I will excuse ye:
Thou dost love her, because thou know’st I love her;
And for my sake even so doth she abuse me,
Suffering my friend for my sake to approve her.
If I lose thee, my loss is my love’s gain,
And losing her, my friend hath found that loss;
Both find each other, and I lose both twain,
And both for my sake lay on me this cross:
But here’s the joy; my friend and I are one;
Sweet flattery! then she loves but me alone.




Read Sonnet 42 in Easy, Modern English:


That you have her isn’t the only thing that’s upsetting me, 
although I can tell you I loved her dearly. 
That she has you is the main reason that I’m crying – 
a loss of love that hurts me more. 
This is how I’ll make excuses for you two offenders in love: 
You love her because you know I love her. 
And in the same way, she abuses me for my own sake, 
putting up with my friend making love to her because she knows I love him. 
If I lose you my loss is my mistress’ gain. 
And in losing her my friend is gaining. 
You both gain each other and I lose both of you. 
And both lay this burden on me for my own sake. 
But here’s the happy part: my friend and I are one person. 
What flattery! So she loves only me!




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 42










Sonnet 42 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 42, as published in Shakespeare’s 1609 Quarto:


THat thou haſt her it is not all my griefe,
And yet it may be ſaid I lou’d her deerely,
That ſhe hath thee is of my wayling cheefe,
A loſſe in loue that touches me more neerely.
Louing offendors thus I will excuſe yee,
Thou dooſt loue her,becauſe thou knowſt I loue her,
And for my ſake euen ſo doth ſhe abuſe me,
Suffring my friend for my ſake to aprooue her,
If I looſe thee,my loſſe is my loues gaine,
And looſing her,my friend hath found that loſſe,
Both finde each other,and I looſe both twaine,
And both for my ſake lay on me this croſſe,
But here’s the ioy,my friend and I are one,
Sweete flattery,then ſhe loues but me alone.






 



