---
title: "Shakespeare Sonnet 75: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 75 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 75



So are you to my thoughts as food to life,
Or as sweet-season’d showers are to the ground;
And for the peace of you I hold such strife
As ‘twixt a miser and his wealth is found.
Now proud as an enjoyer, and anon
Doubting the filching age will steal his treasure;
Now counting best to be with you alone,
Then better’d that the world may see my pleasure:
Sometime all full with feasting on your sight,
And by and by clean starved for a look;
Possessing or pursuing no delight
Save what is had, or must from you be took.
Thus do I pine and surfeit day by day,
Or gluttoning on all, or all away.




Read Sonnet 75 in Easy, Modern English:


You are to me what food is to life, 
or what spring showers are to the earth, 
and to achieve peace of mind about you 
I struggle with myself as a miser struggles with his wealth. 
One moment he proudly enjoys it 
and the next he’s worried that the thieving age we live in will steal his treasure – 
now counting it best to keep you to myself, 
then reckoning it better if the world could see my pleasure. 
At times I feel full from feasting on your looks 
but eventually absolutely starving for a glimpse of you, 
having or looking for no pleasure
except what you give me and what I can take from you. 
That’s why I either waste away with hunger day after day, 
or either stuff myself with you or go without.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 75










Sonnet 75 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 75, as published in Shakespeare’s 1609 Quarto:


SO are you to my thoughts as food to life,
Or as ſweet ſeaſon’d ſhewers are to the ground;
And for the peace of you I hold ſuch ſtrife,
As twixt a miſer and his wealth is found.
Now proud as an inioyer,and anon
Doubting the filching age will ſteale his treaſure,
Now counting beſt to be with you alone,
Then betterd that the world may ſee my pleaſure,
Some-time all ful with feaſting on your ſight,
And by and by clean ſtarued for a looke,
Poſſeſſing or purſuing no delight
Saue what is had,or muſt from you be tooke.
Thus do I pine and ſurfet day by day,
Or gluttoning on all,or all away,




 





