---
title: "Shakespeare Sonnet 119: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 119 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 119



What potions have I drunk of siren tears,
Distilled from limbecks foul as hell within,
Applying fears to hopes, and hopes to fears,
Still losing when I saw myself to win!
What wretched errors have my heart committed,
Whilst it hath thought itself so blessed never!
How have my eyes out of their sheres been fitted
In the distraction of this maddening fever!
O benefit of ill, now I find true
That better is by evil still made better;
And ruined love when it is built anew
Grows fairer than at first, more strong, far greater,
So I return rebuked to my content,
And gain by ills thrice more than I have spent.




Read Sonnet 119 in Easy, Modern English:


What seductive potions I have drunk – 
sweet but distilled in reality from substances foul as hell – 
applying doubt to my hopes and hope to my doubts, 
ever losing just as I think myself to be on the brink of victory! 
What wretched mistakes my heart made 
at a time when I felt I had never been so blessed! 
How my eyes have popped out of their sockets 
in the throes of this maddening fever! 
But oh, the benefits of evil! Now I can see it’s true 
that good things can be made better by evil 
and that ruined love can become even better when it’s rebuilt – 
stronger and far greater. 
And so I return, chastened, to the one who makes me happy and, 
because of the evils I’ve committed, I get back three times what I’ve spent.



