---
title: "Shakespeare Sonnet 78: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 78 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 78



So oft have I invoked thee for my Muse,
And found such fair assistance in my verse
As every alien pen hath got my use
And under thee their poesy disperse.
Thine eyes, that taught the dumb on high to sing
And heavy ignorance aloft to fly,
Have added feathers to the learned’s wing
And given grace a double majesty.
Yet be most proud of that which I compile,
Whose influence is thine, and born of thee:
In others’ works thou dost but mend the style,
And arts with thy sweet graces graced be;
But thou art all my art, and dost advance
As high as learning my rude ignorance.




Read Sonnet 78 in Easy, Modern English:


I’ve invoked you as my muse so many times, 
and found my poetry to be so inspired by you 
that every other author imitates my style 
and publishes his poetry in your name. 
Your eyes, that inspire the dumb to sing, 
reaching the highest notes, raise the ignorant to soar in intelligence, 
inspire the educated to fly even higher, 
have enhanced the graceful’s grace. 
Even so, you should be most proud of my my poetry 
because it’s done directly under your influence and inspired by you. 
With the poetry of the others you merely improve their style, 
adding lustre to already lustrous verse. 
But your inspiration is everything to me 
and raises my great ignorance to high learning.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 78










Sonnet 78 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 78, as published in Shakespeare’s 1609 Quarto:


So oft haue I inuok’d thee for my Muſe,
And found ſuch faire aſſiſtance in my verſe,
As euery Alien pen hath got my vſe,
And vnder thee their poeſie diſperſe.
Thine eyes,that taught the dumbe on high to ſing,
And heauie ignorance aloft to flie,
Haue added fethers to the learneds wing,
And giuen grace a double Maieſtie.
Yet be moſt proud of that which I compile,
Whoſe influence is thine,and borne of thee,
In others workes thou dooſt but mend the ſtile,
And Arts with thy ſweete graces graced be.
But thou art all my art,and dooſt aduance
As high as learning,my rude ignorance.






 





