---
title: "Shakespeare Sonnet 62: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 62 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 62



Sin of self-love possesseth all mine eye
And all my soul, and all my every part;
And for this sin there is no remedy,
It is so grounded inward in my heart.
Methinks no face so gracious is as mine,
No shape so true, no truth of such account;
And for myself mine own worth do define,
As I all other in all worths surmount.
But when my glass shows me myself indeed
Beated and chopp’d with tanned antiquity,
Mine own self-love quite contrary I read;
Self so self-loving were iniquity.
‘Tis thee, myself, that for myself I praise,
Painting my age with beauty of thy days.




Read Sonnet 62 in Easy,  Modern English:


The sin of self-love conditions everything I see, 
and my entire soul, and every one of my faculties. 
And there’s no remedy for this sin, 
it’s so deeply rooted in my heart. 
I keep thinking that no-one’s face is as gracious as mine is; 
nobody as well-proportioned; no-one’s integrity as sound. 
I regard myself as surpassing everyone else in everything. 
But when my mirror shows me what I’m really like – 
beaten and creased by ageing and the sun – 
I conclude the exact opposite to what my self-love tells me. 
To love myself so much would be a disgrace. 
It’s you, my self, that I’m really praising when I praise myself, 
giving my old age the beauty of your youth.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 62










Sonnet 62 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 62, as published in Shakespeare’s 1609 Quarto:


SInne of ſelfe-loue poſſeſſeth al mine eie,
And all my ſoule,and al my euery part;
And for this ſinne there is no remedie,
It is ſo grounded inward in my heart.
Me thinkes no face ſo gratious is as mine,
No ſhape ſo true,no truth of ſuch account,
And for my ſelfe mine owne worth do define,
As I all other in all worths ſurmount.
But when my glaſſe ſhewes me my ſelfe indeed
Beated and chopt with tanned antiquitie,
Mine owne ſelfe loue quite contrary I read
Selfe,ſo ſelfe louing were iniquity,
T’is thee(my ſelfe)that for my ſelfe I praiſe,
Painting my age with beauty of thy daies,




 





