---
title: "Shakespeare Sonnet 67: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 67 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 67



Ah! wherefore with infection should he live,
And with his presence grace impiety,
That sin by him advantage should achieve,
And lace itself with his society?
Why should false painting imitate his cheek,
And steal dead seeing of his living hue?
Why should poor beauty indirectly seek
Roses of shadow, since his rose is true?
Why should he live, now Nature bankrupt is,
Beggar’d of blood to blush through lively veins?
For she hath no exchequer now but his,
And proud of many, lives upon his gains.
O! him she stores, to show what wealth she had
In days long since, before these last so bad.




Read Sonnet 67 in Easy, Modern English:


Ah, why should he have to be surrounded by corruption, 
gracing sinners with his presence, 
only to be taken advantage of by them? 
Why should shallow paintings be allowed to imitate his features, 
resulting in lifeless copies of his vital beauty? 
Why should the less beautiful be falsely represented 
as roses when he is a true rose? 
What’s the purpose of his being alive now that Nature has become bankrupt, 
unable to produce enough of the blood needed to imbue human beings with life and colour? 
It’s because he is the only treasure in her bank and, 
having so many children to support, she depends on that. 
Oh, she hoards him to show what wealth she had in times past, before these recent hard times.




Watch sonnet 67 performed by Atilla Akinci










Sonnet 67 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 67, as published in Shakespeare’s 1609 Quarto:


AH wherefore with infection ſhould he liue,
And with his preſence grace impietie,
That ſinne by him aduantage ſhould atchiue,
And lace it ſelfe with his ſocietie ?
Why ſhould ſalſe painting immitate his cheeke,
And ſteale dead ſeeing of his liuing hew?
Why ſhoulde poore beautie indirectly ſeeke,
Roſes of ſhaddow,ſince his Roſe is true?
Why ſhould he liue,now nature banckrout is,
Beggerd of blood to bluſh through liuely vaines,
For ſhe hath no exchecker now but his,
And proud of many,liues vpon his gaines?
O him ſhe ſtores,to ſhow what welth ſhe had,
In daies long ſince,before theſe laſt so bad.




 





