---
title: "Shakespeare Sonnet 56: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 56 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 56



Sweet love, renew thy force; be it not said
Thy edge should blunter be than appetite,
Which but to-day by feeding is allay’d,
To-morrow sharpened in his former might:
So, love, be thou, although to-day thou fill
Thy hungry eyes, even till they wink with fulness,
To-morrow see again, and do not kill
The spirit of love, with a perpetual dulness.
Let this sad interim like the ocean be
Which parts the shore, where two contracted new
Come daily to the banks, that when they see
Return of love, more blest may be the view;
As call it winter, which being full of care,
Makes summer’s welcome, thrice more wished, more rare.




Read Sonnet 56 in Easy, Modern English:


Sweet Love, renew the strength you once had. Don’t let it be said 
that your love is blunter than lust, 
which can be only temporarily allayed by satisfaction 
and comes back the next day, even stronger and sharper. 
Be like that, Love. Although you see so much of your love today 
that you want to shut your eyes with satiety, 
open them again tomorrow and don’t kill 
the love you have in you by blunting it. 
Let this sad separation be like the ocean 
between two shores, where two newly betrothed lovers 
come daily to the banks, and when they catch the occasional sight of each other, 
feel more blessed. 
Or call this period of separation winter, which being so miserable, 
makes the beginning of summer, so longed for, so much more special.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 56










Sonnet 56 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 56, as published in Shakespeare’s 1609 Quarto:


SWeet loue renew thy force , be it not ſaid
Thy edge ſhould blunter be then apetite,
Which but too daie by feeding is alaied,
To morrow ſharpned in his former might.
So loue be thou,although too daie thou fill
Thy hungry eies,euen till they winck with fulneſſe,
Too morrow ſee againe,and doe not kill
The ſpirit of Loue,with a perpetual dulneſſe:
Let this ſad Intrim like the Ocean be
Which parts the ſhore,where two contracted new,
Come daily to the banckes,that when they ſee:
Returne of loue,more bleſt may be the view.
As cal it Winter,which being ful of care,
Makes Somers welcome,thrice more wiſh’d,more rare:




 





