---
title: "Shakespeare Sonnet 52: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 52 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 52



So am I as the rich, whose blessed key,
Can bring him to his sweet up-locked treasure,
The which he will not every hour survey,
For blunting the fine point of seldom pleasure.
Therefore are feasts so solemn and so rare,
Since, seldom coming in the long year set,
Like stones of worth they thinly placed are,
Or captain jewels in the carcanet.
So is the time that keeps you as my chest,
Or as the wardrobe which the robe doth hide,
To make some special instant special-blest,
By new unfolding his imprison’d pride.
Blessed are you whose worthiness gives scope,
Being had, to triumph; being lacked, to hope.




Read Sonnet 52 in Easy, Modern English:


I am like the rich man whose key 
can give him access to his locked-up treasure, 
but who doesn’t want to view it all the time 
because that would blunt the sharp point that a rare pleasure has. 
That’s why feast days are so important and so infrequent. 
Coming so seldom in the space of a long year 
they are like precious jewels spread out in a crown. 
That’s what my treasure chest – the time that separates us – is like, 
or like a wardrobe that hides a suit 
that makes a special moment even more special 
when it’s opened to reveal its hidden pride. 
You are blessed with a worth 
that allows those who have you to feel triumphant, and those who don’t to be hopeful.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 52










Sonnet 52 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 52, as published in Shakespeare’s 1609 Quarto:


SO am I as the rich whoſe bleſſed key,
Can bring him to his ſweet vp-locked treaſure,
The which he will not eu’ry hower ſuruay,
For blunting the fine point of ſeldome pleaſure.
Therefore are feaſts ſo ſollemne and ſo rare,
Since ſildom comming in the long yeare ſet,
Like ſtones of worth they thinly placed are,
Or captaine Iewells in the carconet.
So is the time that keepes you as my cheſt,
Or as the ward-robe which the robe doth hide,
To make ſome ſpeciall inſtant ſpeciall bleſt,
By new vnfoulding his impriſon’d pride.
Bleſſed are you whoſe worthineſſe giues skope,
Being had to tryumph,being lackt to hope.






 





