---
title: "Shakespeare Sonnet 35: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 35 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 35



No more be grieved at that which thou hast done:
Roses have thorns, and silver fountains mud:
Clouds and eclipses stain both moon and sun,
And loathsome canker lives in sweetest bud.
All men make faults, and even I in this,
Authorizing thy trespass with compare,
Myself corrupting, salving thy amiss,
Excusing thy sins more than thy sins are;
For to thy sensual fault I bring in sense,
Thy adverse party is thy advocate,
And ‘gainst myself a lawful plea commence:
Such civil war is in my love and hate,
That I an accessary needs must be,
To that sweet thief which sourly robs from me.




Read Sonnet 35 in Easy, Modern English:


Stop worrying about what you did. 
Roses have thorns and silver fountains have mud; 
clouds and eclipses obscure both the moon and the sun, 
and loathsome diseases live in the sweetest buds. 
All people make mistakes, and even I am making one in writing this. 
In condoning your transgression by comparing it with other things 
I’m corrupting myself, making allowances for your misdeeds, 
giving more excuses for them than they warrant, 
because what I’m doing is using my rational mind 
to address what are only physical lapses on your part. 
The injured party is your defender 
and I’m now pleading your case against mine. 
My love and hate are so at war with each other 
that I can’t help being an accessory 
to that sweet thief who robs me every hour.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 35










Sonnet 35 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 35, as published in Shakespeare’s 1609 Quarto:


NO more bee greeu’d at that which thou haſt  done,
Roſes haue thornes,and ſiluer fountaines mud,
Cloudes and eclipſes ſtaine both Moone and Sunne,
And loathſome canker liues in ſweeteſt bud.
All men make faults,and euen I in this,
Authorizing thy treſpas with compare,
My ſelfe corrupting ſaluing thy amiſſe,
Excuſing their ſins more then their ſins are:
For to thy ſenſuall fault I bring in ſence,
Thy aduerſe party is thy Aduocate,
And gainſt my ſelfe a lawfull plea commence,
Such ciuill war is in my loue and hate,
That I an acceſſary needs muſt be,
To that ſweet theefe which ſourely robs from me






 



