---
title: "Shakespeare Sonnet 8: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 8 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 8



Music to hear, why hear’st thou music sadly?
Sweets with sweets war not, joy delights in joy:
Why lov’st thou that which thou receiv’st not gladly,
Or else receiv’st with pleasure thine annoy?
If the true concord of well-tuned sounds,
By unions married, do offend thine ear,
They do but sweetly chide thee, who confounds
In singleness the parts that thou shouldst bear.
Mark how one string, sweet husband to another,
Strikes each in each by mutual ordering;
Resembling sire and child and happy mother,
Who, all in one, one pleasing note do sing:
Whose speechless song being many, seeming one,
Sings this to thee: ‘Thou single wilt prove none.’




Read Sonnet 8 in Easy, Modern English:


Why do you, who are music to listen to, listen to music sadly? 
Sweet things don’t quarrel with sweet things, and joyful things delight in joyful things. 
Why do you love something that you don’t enjoy, 
or get pleasure from something that causes you pain? 
If the true harmony of well-tuned sounds, 
married to each other in counterpoint, offends your ear, 
it is gently reprimanding you because 
by staying single you are denying the part you should play. 
Remember that one string reverberates with the others to produce rich music, 
like father and child and happy mother in a family, 
who all sing together in pleasing harmony. 
Their instrumental performance is a unity, although made up of many parts, 
and make this point, in music, to you: ‘Being single you will be nothing.’




 


Listen to Sir Patrick Stewart read Shakespeare’s sonnet 8










Sonnet 8 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 8, as published in Shakespeare’s 1609 Quarto:


MVſick to heare,why hear’ſt thou muſick ſadly,
Sweets with ſweets warre not ,ioy delights in ioy:
Why lou’ſt thou that which thou receauſt not gladly,
Or elſe receau’ſt with pleaſure thine annoy ?
If the true concord of well tuned ſounds,
By vnions married do offend thine eare,
They do but ſweetly chide thee , who confounds
In ſingleneſſe the parts that thou ſhould’ſt beare:
Marke how one ſtring ſweet husband to an other,
Strikes each in each by mutuall ordering;
Reſembling ſier,and child, and happy mother,
Who all in one,one pleaſing note do ſing:
   Whoſe ſpeechleſſe ſong being many,ſeeming one,
   Sings this to thee thou ſingle wilt proue none.






 



