---
title: "Shakespeare Sonnet 139: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 139 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 139



O! call not me to justify the wrong
That thy unkindness lays upon my heart;
Wound me not with thine eye, but with thy tongue:
Use power with power, and slay me not by art,
Tell me thou lov’st elsewhere; but in my sight,
Dear heart, forbear to glance thine eye aside:
What need’st thou wound with cunning, when thy might
Is more than my o’erpressed defence can bide?
Let me excuse thee: ah! my love well knows
Her pretty looks have been mine enemies;
And therefore from my face she turns my foes,
That they elsewhere might dart their injuries:
Yet do not so; but since I am near slain,
Kill me outright with looks, and rid my pain.




Read Sonnet 139 in Easy, Modern English:


Oh, don’t expect me to justify 
the heartache that your cruelty causes me. 
Don’t wound me with your eye; do it with your tongue. 
Use your power openly; don’t kill me with your clever tricks. 
Tell me you love someone else but please, sweetheart, 
when you’re with me control yourself from looking around at other men. 
Why do you need to hurt me with cunning 
when your power is already too much for me to cope with?
Let me make excuses for you: Ah, my love knows very well 
that the way she looks at me can harm me, 
so she turns those looks on my enemies to kill them instead. 
And yet, don’t do that. Instead, as I’m almost dead, 
kill me outright with your looks and put me out of my misery.



