---
title: "Shakespeare Sonnet 110: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 110 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 110



Alas! ’tis true, I have gone here and there,
And made my self a motley to the view,
Gored mine own thoughts, sold cheap what is most dear,
Made old offences of affections new;
Most true it is, that I have looked on truth
Askance and strangely; but, by all above,
These blenches gave my heart another youth,
And worse essays proved thee my best of love.
Now all is done, have what shall have no end:
Mine appetite I never more will grind
On newer proof, to try an older friend,
A god in love, to whom I am confined.
Then give me welcome, next my heaven the best,
Even to thy pure and most most loving breast.




Read Sonnet 110 in Easy, Modern English:


Alas, it’s true; I have gone here and there, 
and made myself look like a fool, 
allowed my mind to be confused, 
treated my most valuable things as worthless items 
and behaved in the same unfaithful way towards new friends, as I did with the old ones. 
It’s very true that I’ve viewed fidelity disdainfully and strangely. But by everything that’s sacred, 
these moments have made my heart young again, 
and these adventures in infidelity have shown me that I love you best. 
I’ve finished with that now and know that our love will never end. 
I won’t ever again sharpen my appetite on new relationships, 
causing unhappiness for an older friend, 
the god of love, to whom I’m committed. 
So welcome me, my next best thing to heaven, 
back into your pure and most loving heart.



