---
title: "Shakespeare Sonnet 149: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 149 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 149



Canst thou, O cruel! Say I love thee not,
When I against myself with thee partake?
Do I not think on thee, when I forgot
Am of my self, all tyrant, for thy sake?
Who hateth thee that I do call my friend,
On whom frown’st thou that I do fawn upon,
Nay, if thou lour’st on me, do I not spend
Revenge upon myself with present moan?
What merit do I in my self respect,
That is so proud thy service to despise,
When all my best doth worship thy defect,
Commanded by the motion of thine eyes?
But, love, hate on, for now I know thy mind,
Those that can see thou lov’st, and I am blind.




Read Sonnet 149 in Easy, Modern English:


Can you, oh cruel woman, say that I don’t love you 
when I take your side against myself? 
Don’t I think about you 
and forget about myself, you tyrant? 
Who dislikes you that I would call my friend? 
Who do you dislike who I like? 
Yes, if you scowl at me 
don’t I take immediate revenge on myself by moaning in pain? 
What quality do I see in myself 
that would make me too proud to serve you 
when the best in me worships your defects, 
commanded as I am by the merest flickering of your eyes? 
But carry on hating me, my love, because I know your mind now. 
You love those who can see, and I am blind!



