---
title: "Shakespeare Sonnet 63: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 63 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 63



Against my love shall be as I am now,
With Time’s injurious hand crush’d and o’erworn;
When hours have drain’d his blood and fill’d his brow
With lines and wrinkles; when his youthful morn
Hath travell’d on to age’s steepy night;
And all those beauties whereof now he’s king
Are vanishing, or vanished out of sight,
Stealing away the treasure of his spring;
For such a time do I now fortify
Against confounding age’s cruel knife,
That he shall never cut from memory
My sweet love’s beauty, though my lover’s life:
His beauty shall in these black lines be seen,
And they shall live, and he in them still green.




Read Sonnet 63 in Easy, Modern English:


In anticipation of the time when my love will be as I am now, 
crushed and worn out by time’s destroying hand; 
when the years will have sapped his energy 
and covered his forehead with wrinkles; 
when the morning of his youth 
will have journeyed on to the hard night of old age, 
and all the beauty which crowns him now 
will be disappearing or have completely disappeared, 
stealing the treasures of his youth – 
I’m preparing myself for that time, 
defending myself against the cruel knife of damaging old age 
to make sure that he will never cut the beauty of my sweet love from my memory, even if he should die. 
His beauty will be seen in these black verses, 
which will survive, and he will live in them, forever young.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 63










Sonnet 63 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 63, as published in Shakespeare’s 1609 Quarto:


AGainſt my loue ſhall be as I am now
With times iniurious hand chruſht and ore-worne,
When houres haue dreind his blood and fild his brow
With lines and wrincles,when his youthfull morne
Hath trauaild on to Ages ſteepie night,
And all thoſe beauties whereof now he’s King
Are vaniſhing,or vaniſht out of ſight,
Stealing away the treaſure of his Spring.
For ſuch a time do I now fortifie
Againſt confounding Ages cruell knife,
That he ſhall neuer cut from memory
My ſweet loues beauty,though my louers life.
His beautie ſhall in theſe blacke lines be ſeene,
And they ſhall liue , and he in them ſtill greene.




 





