---
title: "Shakespeare Sonnet 147: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 147 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 147



My love is as a fever longing still,
For that which longer nurseth the disease;
Feeding on that which doth preserve the ill,
The uncertain sickly appetite to please.
My reason, the physician to my love,
Angry that his prescriptions are not kept,
Hath left me, and I desperate now approve
Desire is death, which physic did except.
Past cure I am, now Reason is past care,
And frantic-mad with evermore unrest;
My thoughts and my discourse as madmen’s are,
At random from the truth vainly expressed;
For I have sworn thee fair, and thought thee bright,
Who art as black as hell, as dark as night.




Read Sonnet 147 in Easy, Modern English:


My love is like a fever, still constantly desiring 
the thing that caused the illness; 
feeding on the thing that prolongs it, 
to please the unhealthy appetite of my body. 
My reason, the doctor of my love, 
angry that I’m not following his directions, 
has abandoned me and now I find that I’m dying 
from the desire that his medicine would have cured. 
I’m past cure now, and my reason doesn’t care, 
and I’m frantic with increasing worry. 
My thoughts and words are like a madman’s, 
randomly expressing nonsense; 
because I have insisted that you are good, and bright as day, 
whereas you are as black as hell and dark as night.



