---
title: "Shakespeare Sonnet 99: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 99 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 99



The forward violet thus did I chide:
Sweet thief, whence didst thou steal thy sweet that smells,
If not from my love’s breath? The purple pride
Which on thy soft cheek for complexion dwells
In my love’s veins thou hast too grossly dy’d.
The lily I condemned for thy hand,
And buds of marjoram had stol’n thy hair;
The roses fearfully on thorns did stand,
One blushing shame, another white despair;
A third, nor red nor white, had stol’n of both,
And to his robbery had annex’d thy breath;
But, for his theft, in pride of all his growth
A vengeful canker eat him up to death.
More flowers I noted, yet I none could see,
But sweet, or colour it had stol’n from thee.




Read Sonnet 99 in Easy, Modern English:


I scolded the presumptuous violet like this: 
Dear thief, where did you steal your perfume 
if not from my love’s breath? You’ve very clearly got the deep purple colour of your velvet petals 
by dying them in my beloved’s blood. 
I condemned the lily for using the whiteness of your hand 
and the marjoram buds for stealing your hair. 
The roses were on tenterhooks, 
one blushing with shame, the other pale with despair; 
a third, neither red nor white, had stolen both red and white from your complexion, 
adding the perfume of your breath to his robbery. 
But as punishment for his theft 
a vengeful worm cut him off in his prime. 
I observed many more flowers 
but I couldn’t see any that hadn’t stolen its perfume or colour from you.



