---
title: "Shakespeare Sonnet 117: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 117 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 117



Accuse me thus: that I have scanted all
Wherein I should your great deserts repay,
Forgot upon your dearest love to call,
Whereto all bonds do tie me day by day;
That I have frequent been with unknown minds,
And giv’n to time your own dear purchased right;
That I have hoisted sail to all the winds
Which should transport me farthest from your sight.
Book both my willfulness and errors down,
And on just proof surmise accumulate.
Bring me within the level of your frown,
But shoot not at me in your wakened hate,
Since my appeal says I did strive to prove
The constancy and virtue of your love.




Read Sonnet 117 in Easy, Modern English:


Accuse me like this: that I’ve entirely neglected 
to repay what you so richly deserve; 
that I’ve forgotten to regard the great love you show me, 
even though I’m more and more in your debt every day; 
that I’ve spent most of my time with strangers, 
giving that time away when you have earned the right to it; 
that I’ve set my sails to all the winds that would blow me the furthest distance from you. 
Make a record of all the stubborn and mistaken things I’ve done 
and use the evidence to compile a long list. 
Look sternly at me 
but don’t give me the full force of the new hatred I’ve awakened in you because, 
in defence of myself, 
I claim that I was trying to test the constancy and quality of your love.



