---
title: "Shakespeare Sonnet 135: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 135 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 135



Whoever hath her wish, thou hast thy Will,
And Will to boot, and Will in over-plus;
More than enough am I that vexed thee still,
To thy sweet will making addition thus.
Wilt thou, whose will is large and spacious,
Not once vouchsafe to hide my will in thine?
Shall will in others seem right gracious,
And in my will no fair acceptance shine?
The sea, all water, yet receives rain still,
And in abundance addeth to his store;
So thou, being rich in Will, add to thy Will
One will of mine, to make thy large will more.
Let no unkind, no fair beseechers kill;
Think all but one, and me in that one Will.




Read Sonnet 135 in Easy, Modern English:


Whatever sexual fulfilment other women get, you have your Will, 
and another Will, too, and more will than you need. 
I, who never stop pestering you, would like to add myself 
to give you more than enough to satisfy your sweet vagina. 
Won’t you, with such a spacious vagina, 
allow me to hide my will in it just once? 
Are you going to let other men’s wills attract you 
but reject mine? 
The sea is full of water but continues to accept the rain 
and keeps adding it to its stock. 
So, like that, you are rich in having Wills. 
Add my will to the one you already have, stretching your spacious vagina even more. 
Don’t be so cruel as to kill a genuine petitioner. 
Think of all your lovers as one entity and accept me as a part of that one Will.



