---
title: "Shakespeare Sonnet 132: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 132 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 132



Thine eyes I love, and they, as pitying me,
Knowing thy heart torments me with disdain,
Have put on black and loving mourners be,
Looking with pretty ruth upon my pain.
And truly not the morning sun of heaven
Better becomes the grey cheeks of the east,
Nor that full star that ushers in the even,
Doth half that glory to the sober west,
As those two mourning eyes become thy face:
O! let it then as well beseem thy heart
To mourn for me since mourning doth thee grace,
And suit thy pity like in every part.
Then will I swear beauty herself is black,
And all they foul that thy complexion lack.




Read Sonnet 132 in Easy, Modern English:


I love your eyes, and they, appearing to pity me, 
knowing that your heart torments me with scornfulness, 
look like mourners offering me polite sympathy on my bereavement. 
And honestly, the morning sun 
doesn’t become the grey eastern sky, 
nor the evening star the western twilight, 
half as much as those two mourning eyes become your face. 
Oh, let it also become your heart, then, 
to mourn for me, since mourning suits you so well 
in all your other parts. 
Then I’ll swear that beauty itself is dark 
and that all those who don’t have your complexion are ugly.



