---
title: "Shakespeare Sonnet 49: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 49 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 49



Against that time, if ever that time come,
When I shall see thee frown on my defects,
When as thy love hath cast his utmost sum,
Called to that audit by advis’d respects;
Against that time when thou shalt strangely pass,
And scarcely greet me with that sun, thine eye,
When love, converted from the thing it was,
Shall reasons find of settled gravity;
Against that time do I ensconce me here,
Within the knowledge of mine own desert,
And this my hand, against my self uprear,
To guard the lawful reasons on thy part:
To leave poor me thou hast the strength of laws,
Since why to love I can allege no cause.




Read Sonnet 49 in Easy, Modern English:


Anticipating that time, if that time ever comes, 
when I will see you frowning at my defects; 
when after serious consideration, 
your love for me has outlived itself – 
anticipating that time when you will walk past me as you would a stranger, 
hardly even glancing at me with that sun-like eye; 
when that love has changed to something else, 
informed, now, by serious judgment – 
anticipating that time, I’m ensconcing myself here, 
in the full knowledge of what I deserve, 
testifying against myself to defend the arguments in your favour. 
All the arguments for leaving me are on your side 
since I can offer none for your loving me.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 49










Sonnet 49 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 49, as published in Shakespeare’s 1609 Quarto:


AGainſt that time ( if ever that time come )
When I ſhall ſee thee frowne on my defects,
When as thy loue hath caſt his vtmoſt ſumme,
Cauld to that audite by aduiſ’d reſpects,
Againſt that time when thou ſhalt ſtrangely paſſe,
And ſcarcely greete me with that ſunne thine eye,
When loue conuerted from the thing it was
Shall reaſons finde of ſetled grauitie.
Againſt that time do I inſconce me here
Within the knowledge of mine owne deſart,
And this my hand,againſt my ſelfe vpreare,
To guard the lawfull reaſons on thy part,
To leaue poore me,thou haſt the ſtrength of lawes,
Since why to loue,I can alledge no cauſe.






 





