---
title: "Shakespeare Sonnet 123: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 123 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 123



No, Time, thou shalt not boast that I do change
Thy pyramids built up with newer might
To me are nothing novel, nothing strange;
They are but dressings of a former sight.
Our dates are brief, and therefore we admire
What thou dost foist upon us that is old;
And rather make them born to our desire
Than think that we before have heard them told.
Thy registers and thee I both defy,
Not wondering at the present nor the past,
For thy records and what we see doth lie,
Made more or less by thy continual haste.
This I do vow and this shall ever be;
I will be true despite thy scythe and thee.




Read Sonnet 123 in Easy, Modern English:


No, Time, you cannot boast that I’m decaying. 
Your pyramids, recently built, 
are nothing new to me, nothing remarkable; 
they’re just new clothes on an old design. 
We have a short life and so we admire 
anything old that you care to palm off on us 
and view them as though we had designed them 
rather than as the repetition of old sights. 
I defy both you and the records you keep, 
and refuse to be in awe of either the present or the past, 
because history, made in a hurry by your haste, lies. 
I promise – and this will be for all time – 
that in spite of you and your scythe, I will show the truth in my verse.



