---
title: "Shakespeare Sonnet 22: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 22 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 22



My glass shall not persuade me I am old,
So long as youth and thou are of one date;
But when in thee time’s furrows I behold,
Then look I death my days should expiate.
For all that beauty that doth cover thee,
Is but the seemly raiment of my heart,
Which in thy breast doth live, as thine in me:
How can I then be elder than thou art?
O! therefore love, be of thyself so wary
As I, not for myself, but for thee will;
Bearing thy heart, which I will keep so chary
As tender nurse her babe from faring ill.
Presume not on thy heart when mine is slain,
Thou gav’st me thine not to give back again.




Read Sonnet 22 in Easy, Modern English:


As long as you appear eternally young 
my mirror will not persuade me that I am old. 
But when I begin to see wrinkles on your brow 
then it will be time to anticipate my death. 
All that beauty that covers you 
is only the fine clothing of this heart of mine 
that lives in your heart, as yours lives in mine. 
How can I then be older than you? 
Oh, therefore, love, you should take as good care of yourself 
as I take care, not of myself, but of you, 
because your heart is in me 
and I will take care of it as a loving nurse protects her baby from harm. 
Don’t presume that your heart will survive when mine is dead; 
you gave me yours, never to be given back.




Listen to Sir John Gielgud read Shakespeare’s sonnet 22










Sonnet 22 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 22, as published in Shakespeare’s 1609 Quarto:


MY glaſſe fhall not perſwade me I am ould,
So long as youth and thou are of one date,
But when in thee times forrwes I behould,
Then look I death my daies ſhould expiate.
For all that beauty that doth couer thee,
Is but the ſeemely rayment of my heart,
Which in thy breſt doth liue,as thine in me,
How can I then be elder than thou art?
O therefore loue be of thy ſelfe ſo wary,
As I not for my ſelfe,but for thee will,
Bearing thy heart which I will keepe ſo chary
As tender nurſe her babe from faring ill,
Preſume not on thy heart when mine is ſlaine,
Thou gau’ſt me thine not to giue backe againe.


 




 

