---
title: "Shakespeare Sonnet 128: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 128 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 128



How oft when thou, my music, music play’st,
Upon that blessed wood whose motion sounds
With thy sweet fingers when thou gently sway’st
The wiry concord that mine ear confounds,
Do I envy those jacks that nimble leap,
To kiss the tender inward of thy hand,
Whilst my poor lips which should that harvest reap,
At the wood’s boldness by thee blushing stand!
To be so tickled, they would change their state
And situation with those dancing chips,
O’er whom thy fingers walk with gentle gait,
Making dead wood more bless’d than living lips.
Since saucy jacks so happy are in this,
Give them thy fingers, me thy lips to kiss.




Read Sonnet 128 in Easy, Modern English:


How often – when you, my joy, make music 
on those wooden keys whose movement 
responds to your sweet fingers, 
and stuns my ears with the harmony of the strings – 
do I envy those keys that leap nimbly up and down 
to kiss the tender palms of your hands 
while my poor lips, that should be doing the kissing, 
look on, blushing at the boldness of the keys! 
To be tickled like that my lips would willingly be transformed into wood 
and change places with those dancing chips over which your fingers walk with gentle steps, 
making dead wood more blessed than living lips. 
Since those cheeky keys are so happy doing this 
give them your fingers and me your lips to kiss.



