---
title: "Shakespeare Sonnet 17: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 17 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 17



Who will believe my verse in time to come,
If it were fill’d with your most high deserts?
Though yet heaven knows it is but as a tomb
Which hides your life, and shows not half your parts.
If I could write the beauty of your eyes,
And in fresh numbers number all your graces,
The age to come would say ‘This poet lies;
Such heavenly touches ne’er touch’d earthly faces.’
So should my papers, yellow’d with their age,
Be scorn’d, like old men of less truth than tongue,
And your true rights be term’d a poet’s rage
And stretched metre of an antique song:
But were some child of yours alive that time,
You should live twice, in it, and in my rhyme.




Read Sonnet 17 in Easy, Modern English:


Who will believe my poem in times to come 
if it were filled with your great qualities? 
Heaven knows that it’s only like a grave 
that conceals your qualities, and doesn’t even show half your talents. 
Even if I had the ability to describe the beauty of your eyes, 
and write good lines that would enumerate all your gracious qualities, 
those who read it in the future would say ‘This poet is telling lies: 
no human face has ever possessed such heavenly beauty,’ 
so, my pages, yellowed with age, 
would be scorned like old men who talk nonsense, 
and the right that you have to such praise would be dismissed as a poet’s exaggeration – 
the elaborate metre of old-fashioned poems. 
But if there were a child of yours alive at that time, 
you would be doubly alive – in the child and in my poem.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 17










Sonnet 17 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 17, as published in Shakespeare’s 1609 Quarto:


WHo will beleeue my verſe in time to come,
If it were fild with your moſt high deſerts?
Though yet heauen knowes it is but as a tombe
Which hides your life , and ſhewes not halfe your parts:
If I could write the beauty of your eyes,
And in freſh numbers number all your graces,
The age to come would ſay this Poet lies,
Such heauenly touches nere toucht earthly faces.
So ſhould my papers (yellowed with their age)
Be ſcorn d,like old men of leſſe truth then tongue,
And your true rights be termed a Poets rage,
And ſtretched miter of an Antique ſong.
But were ſome childe of yours aliue that time,
You ſhould liue twiſe in it,and in my rime.


 




 

