---
title: "Shakespeare Sonnet 40: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 40 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 40



Take all my loves, my love, yea take them all;
What hast thou then more than thou hadst before?
No love, my love, that thou mayst true love call;
All mine was thine, before thou hadst this more.
Then, if for my love, thou my love receivest,
I cannot blame thee, for my love thou usest;
But yet be blam’d, if thou thy self deceivest
By wilful taste of what thyself refusest.
I do forgive thy robbery, gentle thief,
Although thou steal thee all my poverty:
And yet, love knows it is a greater grief
To bear love’s wrong, than hate’s known injury.
Lascivious grace, in whom all ill well shows,
Kill me with spites yet we must not be foes.




Read Sonnet 40 in Easy, Modern English:


Take everything I love, my love; yes, take it all. 
What do you have then, that you didn’t have before? 
Not love that you could call true love, my love;
all my love was already yours before you took this extra love from me. 
If you make love to another person instead of accepting my love 
I can’t blame you, love, 
because you’re just using my love. 
But still, you are to blame if you deceive yourself 
by taking from someone else what you won’t take from me. 
I forgive that robbery, dear thief, 
even though you’re stealing from someone so poor. 
And yet, everyone who loves knows 
that it’s more hurtful to be wounded by someone one loves than by an enemy. 
You – gracious and lascivious at the same time, in whom everything bad appears good – 
may kill me with hurtfulness, but we must not be enemies.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 40










Sonnet 40 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 40, as published in Shakespeare’s 1609 Quarto:


TAke all my loues,my loue,yea take them all,
What haſt thou then more then thou hadſt before?
No loue, my loue,that thou maiſt true loue call,
All mine was thine,before thou hadſt this more:
Then if for my loue,thou my loue receiueſt,
I cannot blame thee,for my loue thou vſeſt,
But yet be blam’d,if thou this ſelfe deceaueſt
By wilfull taſte of what thy ſelfe refuſeſt.
I doe forgiue thy robb’rie gentle theefe
Although thou ſteale thee all my pouerty:
And yet loue knowes it is a greater griefe
To beare loues wrong,then hates knowne injury.
Laſciuious grace,in whom all il wel ſhowes,
Kill me with ſpights yet we must not be foes.






 



