---
title: "Shakespeare Sonnet 12: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 12 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 12



When I do count the clock that tells the time,
And see the brave day sunk in hideous night;
When I behold the violet past prime,
And sable curls, all silvered o’er with white;
When lofty trees I see barren of leaves,
Which erst from heat did canopy the herd,
And summer’s green all girded up in sheaves,
Borne on the bier with white and bristly beard,
Then of thy beauty do I question make,
That thou among the wastes of time must go,
Since sweets and beauties do themselves forsake
And die as fast as they see others grow;
And nothing ‘gainst Time’s scythe can make defence
Save breed, to brave him when he takes thee hence.




Read Sonnet 12 in Easy, Modern English:


When I count the chimes of the clock 
and watch the bright day sunken into terrifying night; 
when I see violets fading, 
and black curls all silvered over with white; 
when I see tall trees which 
previously offered shade to sheep and cattle but now with no leaves; 
and the green crops of summer tied up in harvested sheaves 
covered with scratchy dried out leaves, carried away on a wagon; 
then I begin to think about the endurance of your beauty 
and that you will have to decline and decay like everything else 
because sweet and beautiful things lose their sweetness and beauty 
and die while watching new sweet and beautiful things taking their place. 
The only defense against Time’s scythe 
is to defy him when he takes you away, by having children.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 12










Sonnet 12 as Originally Published in The 1609 Quarto


When I doe count the clock that tels the time,
And ſee the braue day ſunck in hidious night,
When I behold the violet paſt prime,
And ſable curls or ſiluer’d ore with white :
When lofty trees I ſee barren of leaues,
Which erſt from heat did canopie the herd
And Sommers greene all girded vp in ſheaues
Borne on the beare with white and briſtly beard:
Then of thy beauty do I queſtion make
That thou among the waſtes of time muſt goe,
Since ſweets and beauties do them-ſelues forſake,
And die as faſt as they ſee others grow,
And nothing gainſt Times ſieth can make defence
Saue breed to braue him,when he takes thee hence.


 




 

