---
title: "Shakespeare Sonnet 29: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 29 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 29



When in disgrace with fortune and men’s eyes
I all alone beweep my outcast state,
And trouble deaf heaven with my bootless cries,
And look upon myself, and curse my fate,
Wishing me like to one more rich in hope,
Featured like him, like him with friends possessed,
Desiring this man’s art, and that man’s scope,
With what I most enjoy contented least;
Yet in these thoughts my self almost despising,
Haply I think on thee, and then my state,
Like to the lark at break of day arising
From sullen earth, sings hymns at heaven’s gate;
For thy sweet love remembered such wealth brings
That then I scorn to change my state with kings.




Read Sonnet 29 in Easy, Modern English:


When my luck has failed and no-one gives me any sympathy, 
I sit all alone and cry about being an outcast, 
and bother the deaf ears of heaven with my useless cries; 
and examine myself and curse my fate, 
wishing that I was like someone with good prospects; 
or that I looked like another, or had friends like yet another, 
coveting this man’s skill, and that man’s range – 
totally dissatisfied with the things I usually enjoy. 
Yet, as I’m thinking these thoughts, almost believing myself despicable, 
I think of you by chance and then my soul, 
like the lark rising from the glum earth at daybreak, 
sings hymns at heaven’s gate. 
Because when I remember your sweet love, 
the thought brings such wealth that I’d then refuse to change places with kings.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 29










Sonnet 29 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 29, as published in Shakespeare’s 1609 Quarto:


HOw can I then returne in happy plight
That am debard the benefit of reſt?
When daies oppreſſion is not eazd by night,
But day by night and night by day opreſt.
And each(though enimes to ethers raigne)
Doe in conſent ſhake hands to torture me,
The one by toyle,the other to complaine
How far I toyle,ſtill farther off from thee.
I tell the Day to pleaſe him thou art bright,
And do’ſt him grace when clouds doe blot the heauen:
So flatter I the ſwart complexiond night,
When ſparkling ſtars twire not thou guil’ſt th’ eauen.
But day doth daily draw my ſorrowes longer,
And night doth nightly make greefes length ſeeme ſtronger






 



