---
title: "Shakespeare Sonnet 38: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 38 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 38



How can my muse want subject to invent,
While thou dost breathe, that pour’st into my verse
Thine own sweet argument, too excellent
For every vulgar paper to rehearse?
O! give thy self the thanks, if aught in me
Worthy perusal stand against thy sight;
For who’s so dumb that cannot write to thee,
When thou thy self dost give invention light?
Be thou the tenth Muse, ten times more in worth
Than those old nine which rhymers invocate;
And he that calls on thee, let him bring forth
Eternal numbers to outlive long date.
If my slight muse do please these curious days,
The pain be mine, but thine shall be the praise.




Read Sonnet 38 in Easy, Modern English:


How could I lack a subject to write my poems about 
while you are alive; you who pours your own sweet self – 
too excellent a subject for lesser poets to deal with – into my verse? 
Oh, give yourself the credit 
if anything of mine strikes you as being worth reading. 
For who is so inarticulate that he can’t write to you 
when you yourself provide the creative spark? 
You could be the tenth muse, worth ten times more 
than the usual nine invoked by poets. 
And let whoever calls on you 
write eternal verses that will outlive the ages. 
If my poor efforts please the demanding readers of these modern times 
the hard work of that will be mine but you will have the praise.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 38










Sonnet 38 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 38, as published in Shakespeare’s 1609 Quarto:


How can my Muſe want ſubiect to inuent
While thou doſt breath that poor’ſt into my verſe
Thine owne ſweet argument,to excellent,
For euery vulgar paper to rehearſe:
Oh giue thy ſelfe the thankes if ought in me,
Worthy peruſal ſtand againt thy ſight,
For who’s ſo dumbe that cannot write to thee,
When thou thy ſelfe doſt giue inuention light?
Be thou the tenth Muſe,ten times more in worth
Then thoſe old nine which rimers inuocate,
And he that calls on thee,let him bring forth
Eternal numbers to out-liue long date.
If my ſlight Muſe doe pleaſe theſe curious daies,
The paine be mine,but thine ſhal be the praiſe.






 



