---
title: "Shakespeare Sonnet 115: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 115 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 115



Those lines that I before have writ do lie,
Even those that said I could not love you dearer:
Yet then my judgment knew no reason why
My most full flame should afterwards burn clearer.
But reckoning Time, whose million’d accidents
Creep in ‘twixt vows, and change decrees of kings,
Tan sacred beauty, blunt the sharp’st intents,
Divert strong minds to the course of altering things;
Alas! why, fearing of Time’s tyranny,
Might I not then say, ‘Now I love you best,’
When I was certain o’er incertainty,
Crowning the present, doubting of the rest?
Love is a babe, then might I not say so,
To give full growth to that which still doth grow?




Read Sonnet 115 in Easy, Modern English:


The sonnets that I have written lie, 
especially those that said I could not love you more deeply. 
When I wrote them my power of discernment didn’t know 
that I had yet to reach the heights of my creative fire. 
But ticking Time, whose millions of chance occurrences surreptitiously disrupt vows, make laws obsolete 
and turn exquisite beauty into ugliness, 
makes the sharpest of intentions blunt and diverts even the strongest minds to the demands of changing fashion. 
It’s sad: being aware of Time’s tyrannies, 
why should I not have said, ‘My love for you could never be greater than it is now,’ 
at a time when I was sure that my love was strong enough to overcome the uncertainties of time, 
believing the present to be the best it could be, and doubting that the future could bring better? 
Cupid is an infant, so surely I shouldn’t have said that 
something that is still growing was fully mature?



