---
title: "Shakespeare Sonnet 54: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 54 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 54



O! how much more doth beauty beauteous seem
By that sweet ornament which truth doth give.
The rose looks fair, but fairer we it deem
For that sweet odour, which doth in it live.
The canker blooms have full as deep a dye
As the perfumed tincture of the roses,
Hang on such thorns, and play as wantonly
When summer’s breath their masked buds discloses:
But, for their virtue only is their show,
They live unwoo’d, and unrespected fade;
Die to themselves. Sweet roses do not so;
Of their sweet deaths are sweetest odours made:
And so of you, beauteous and lovely youth,
When that shall vade, my verse distills your truth.




Read Sonnet 54 in Easy, Modern English:


Oh, how much more beautiful beauty appears 
when accompanied by the lovely ornament of integrity! 
Roses look beautiful but we see them as 
even more beautiful because of that wonderful perfume that lives in them. 
Dog roses have every bit as intense a colour 
as the perfumed hue of those roses; 
have the same thorns, and blow as appealingly 
when the breath of summer opens their buds. 
But because their appearance is their only virtue 
they live obscurely and die unnoticed, in loneliness. Sweet roses don’t – 
the most fragrant odours are distilled from their beautiful corpses. 
And that’s the case with you, beautiful and lovely youth: 
when that fades my verse will distill your essence.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 54










Sonnet 54 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 54, as published in Shakespeare’s 1609 Quarto:


OH how much more doth beautie beautious ſeeme,
By that ſweet ornament which truth doth giue,
The Roſe lookes faire, but fairer we it deeme
For that ſweet odor,which doth in it liue:
The Canker bloomes haue full as deepe a die,
As the perfumed tincture of the Roſes,
Hang on ſuch thornes,and play as wantonly,
When ſommers breath their masked buds diſcloſes:
But for their virtue only is their ſhow,
They liue vnwoo’d, and vnreſpected fade,
Die to themſelues .Sweet Roſes doe not ſo,
Of their ſweet deathes, are ſweeteſt odors made:
And ſo of you,beautious and louely youth,
When that ſhall vade,by verse diſtils your truth.






 





