---
title: "Shakespeare Sonnet 55: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 55 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 55



Not marble, nor the gilded monuments
Of princes, shall outlive this powerful rhyme;
But you shall shine more bright in these contents
Than unswept stone, besmear’d with sluttish time.
When wasteful war shall statues overturn,
And broils root out the work of masonry,
Nor Mars his sword, nor war’s quick fire shall burn
The living record of your memory.
‘Gainst death, and all oblivious enmity
Shall you pace forth; your praise shall still find room
Even in the eyes of all posterity
That wear this world out to the ending doom.
So, till the judgment that yourself arise,
You live in this, and dwell in lovers’ eyes.




Read Sonnet 55 in Easy, Modern English:


Neither marble nor the gilded tombs 
of princes will outlive this powerful poetry, 
but you will shine more brightly in these pages 
than those neglected buildings that crumble to dust, 
besmirched by heartless time. 
When devastating war overturns statues, 
and battles uproot buildings, 
neither the sword of Mars nor the quick-burning fires of war 
shall destroy this living record of your memory. 
You will continue on strongly in the face of death and dispassionate enmity. 
Praise of you by all the successive generations 
that will wear this world out will continue until doomsday. 
So till the Day of Judgment, when you will be raised up, 
you will live in this poetry and remain in the eyes of the lovers who read this.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 55










Sonnet 55 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 55, as published in Shakespeare’s 1609 Quarto:


NOt marble, nor the guilded monument,
Of Princes ſhall out-liue this powrefull rime,
But you ſhall ſhine more bright in theſe contents
Then vnſwept ſtone, beſmeer’d with ſluttiſh time.
When waſtefull warre ſhall Statues ouer-turne,
And broiles roote out the worke of maſonry,
Nor Mars his ſword,nor warres quick fire ſhall burn:
The liuing record of your memory.
Gainſt death,and all obliuious emnity
Shall you pace forth,your praiſe ſhall ſtil find roome,
Euen in the eyes of all poſterity
That weare this world out to the ending doome.
So til the iudgement that your ſelfe ariſe,
You liue in this,and dwell in louers eies.






 





