---
title: "Shakespeare Sonnet 77: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 77 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 77



Thy glass will show thee how thy beauties wear,
Thy dial how thy precious minutes waste;
The vacant leaves thy mind’s imprint will bear,
And of this book, this learning mayst thou taste.
The wrinkles which thy glass will truly show
Of mouthed graves will give thee memory;
Thou by thy dial’s shady stealth mayst know
Time’s thievish progress to eternity.
Look what thy memory cannot contain,
Commit to these waste blanks, and thou shalt find
Those children nursed, deliver’d from thy brain,
To take a new acquaintance of thy mind.
These offices, so oft as thou wilt look,
Shall profit thee and much enrich thy book.




Read Sonnet 77 in Easy, Modern English:


Your mirror will show you how your beauty is wearing out; 
your sundial how your precious minutes are wasting away. 
Blank pages will record your thoughts 
and you may learn this from your notebook: 
The wrinkles that your mirror will honestly reveal 
will remind you of gaping graves: 
from the stealthy movement of the shade on your dial 
you will learn about time’s thievish progress to eternity. 
Write down the thoughts you won’t be able to remember on these blank pages 
and you will see that those children, nursed and grown-up, 
will strike you as new acquaintances in time to come. 
If you do all that it will be of benefit to you 
and greatly enrich your book.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 77










Sonnet 77 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 77, as published in Shakespeare’s 1609 Quarto:


THy glaſſe will ſhew thee how thy beauties were,
Thy dyall how thy pretious mynuits waſte,
The vacant leaues thy mindes imprint will beare,
And of this booke,this learning maiſt thou taſte.
The wrinckles which thy glaſſe will truly ſhow,
Of mouthed graues will giue thee memorie,
Thou by thy dyals ſhady ſtealth maiſt know,
Times theeuiſh progreſſe to eternitie.
Looke what thy memorie cannot containe,
Commit to theſe waſte blacks,and thou ſhalt finde
Thoſe children nurſt,deliuerd from thy braine,
To take a new acquaintance of thy minde.
Theſe offices,ſo oft as thou wilt looke,
Shall profit thee,and much inrich thy booke.






 





