---
title: "Shakespeare Sonnet 122: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 122 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 122



Thy gift, thy tables, are within my brain
Full charactered with lasting memory,
Which shall above that idle rank remain,
Beyond all date, even to eternity:
Or, at the least, so long as brain and heart
Have faculty by nature to subsist;
Till each to razed oblivion yield his part
Of thee, thy record never can be missed.
That poor retention could not so much hold,
Nor need I tallies thy dear love to score;
Therefore to give them from me was I bold,
To trust those tables that receive thee more:
To keep an adjunct to remember thee
Were to import forgetfulness in me.




Read Sonnet 122 in Easy, Modern English:


The gift you gave me, a copybook, has already been filled in my imagination – 
with verses that will stay in my memory far longer 
than they would in that pathetic book, 
outlasting any date, for eternity: 
or at the very least, as long as my brain and heart 
have the ability to survive. 
You will be recorded there until each of them has to give you up 
as they pass into oblivion. 
That poor book couldn’t hold as much, 
nor do I need to keep notes to record the deep love I have for you. 
So I took the liberty of giving it away, 
trusting to that book that presents you more accurately. 
Keeping a written record of you would be admitting that I’m forgetful.



