---
title: "Shakespeare Sonnet 138: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 138 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 138



When my love swears that she is made of truth
I do believe her, though I know she lies,
That she might think me some untutor’d youth,
Unlearned in the world’s false subtleties.
Thus vainly thinking that she thinks me young,
Although she knows my days are past the best,
Simply I credit her false speaking tongue:
On both sides thus is simple truth suppress’d.
But wherefore says she not she is unjust?
And wherefore say not I that I am old?
O, love’s best habit is in seeming trust,
And age in love loves not to have years told:
Therefore I lie with her and she with me,
And in our faults by lies we flatter’d be.




Read Sonnet 138 in Easy, Modern English:


When my mistress swears that she speaks nothing but the truth 
I believe her so that she will think that I’m a naïve youth, 
ignorant of the complex ways of the world – 
even though I know she’s lying. 
So, to satisfy my vanity, I believe that she regards me as young, 
even though she knows that my best days are behind me. 
I agree with her lies without reservation. 
And so we’re both concealing the truth from each other. 
But why does she insist on her lies? 
And why don’t I insist that I’m old? 
Oh, it’s best for lovers to pretend to trust each other; 
and older lovers don’t like having their age pointed out. 
So I lie with her and she lies with me, 
and both being imperfect, we flatter each other with our lies.



