---
title: "Shakespeare Sonnet 30: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 30 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 30



When to the sessions of sweet silent thought
I summon up remembrance of things past,
I sigh the lack of many a thing I sought,
And with old woes new wail my dear time’s waste:
Then can I drown an eye, unused to flow,
For precious friends hid in death’s dateless night,
And weep afresh love’s long since cancell’d woe,
And moan the expense of many a vanish’d sight:
Then can I grieve at grievances foregone,
And heavily from woe to woe tell o’er
The sad account of fore-bemoaned moan,
Which I new pay as if not paid before.
But if the while I think on thee, dear friend,
All losses are restor’d and sorrows end.




Read Sonnet 30 in Easy, Modern English:


When I summons the remembrance of past things
 to the court of sweet silent thought 
I regret not having achieved many of the things I strived for, 
and I add new tears to the old griefs, 
crying about the waste of my valuable time.
It is then that I can drown my eyes, which don’t often flow, 
thinking about precious friends who are dead; 
and weep all over again for love that has lost its pain long ago; 
and cry over many a sight I’ll never see again. 
At those times I’m able to cry over sorrows I’ve long ago let go of, 
and sadly count them one by one, and feel them all over again, 
as though I hadn’t suffered their pain before. 
But if, while doing that, I think about you, my dear friend, 
all those losses are restored and my pain ends.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 30










Sonnet 30 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 30, as published in Shakespeare’s 1609 Quarto:


WHen to the Seſſions of ſweet ſilent thought,
I ſummon vp remembrance of things paſt,
I ſigh the lacke of many a thing I ſought,
And with old woes new waile my deare times waſte:
Then can I drowne an eye(vn-vſ’d to flow)
For precious friends hid in deaths dateles night,
And weepe a freſh loues long ſince canceld woe,
And mone th’expence of many a vanniſht ſight.
Then can I greeue at greeuances fore-gon,
And heauily from woe to woe tell ore
The ſad account of fore-bemoned mone,
Which I new pay as if not payd before.
But if the while I thinke on thee (deare friend)
All loſſes are reſtord,and ſorrowes end.






 



