---
title: "Shakespeare Sonnet 4: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 4 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 4



Unthrifty loveliness, why dost thou spend
Upon thyself thy beauty’s legacy?
Nature’s bequest gives nothing but doth lend,
And being frank she lends to those are free.
Then, beauteous niggard, why dost thou abuse
The bounteous largess given thee to give?
Profitless usurer, why dost thou use
So great a sum of sums, yet canst not live?
For having traffic with thyself alone,
Thou of thyself thy sweet self dost deceive.
Then how, when nature calls thee to be gone,
What acceptable audit canst thou leave?
Thy unused beauty must be tomb’d with thee,
Which, used, lives th’ executor to be.




Read Sonnet 4 in Easy, Modern English:


Wasteful youth, why do you squander on yourself 
the riches that you should leave to the world? 
Nature gives nothing but only makes a loan 
and, being generous, she lends only to those who are open-hearted. 
Then, beautiful miser, why do you abuse
the generous inheritance given to you to leave to someone else? 
Unsuccessful money-lender, 
why do you spend such great sums when you can’t live forever, 
by thinking of yourself only? 
You are only cheating yourself, 
so, when nature calls you away 
what reasonable account will you be able to give of yourself? 
Your unused seed will have to be buried with you, 
which, if used, would live as the administrator of your beauty.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 4










Sonnet 4 as Originally Published inThe 1609 Quarto


Here’s the exact wording and spelling of Sonnet 4, as published in Shakespeare’s 1609 Quarto:


VNthrifty louelineſſe why doſt thou ſpend,
Vpon thy ſelfe thy beauties legacy?
Natures bequeſt giues nothing but doth lend,
And being franck ſhe lends to thoſe are free:
Then beautious nigard why dooſt thou abuſe,
The bountious largeſſe giuen thee to giue?
Profitles vſerer why dooſt thou vſe
So great a ſumme of ſummes yet can’ſt not liue?
For hauing traffike with thy ſelfe alone,
Thou of thy ſelfe thy ſweet ſelfe doſt deceaue,
Then how when nature calls thee to be gone,
What acceptable Audit can’ſt thou leaue?
Thy vnuſ’d beauty muſt be tomb’d with thee,
Which vſed liues th’executor to be.






 



