---
title: "Shakespeare Sonnet 48: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 48 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 48



How careful was I when I took my way,
Each trifle under truest bars to thrust,
That to my use it might unused stay
From hands of falsehood, in sure wards of trust!
But thou, to whom my jewels trifles are,
Most worthy comfort, now my greatest grief,
Thou best of dearest, and mine only care,
Art left the prey of every vulgar thief.
Thee have I not lock’d up in any chest,
Save where thou art not, though I feel thou art,
Within the gentle closure of my breast,
From whence at pleasure thou mayst come and part;
And even thence thou wilt be stol’n I fear,
For truth proves thievish for a prize so dear.




Read Sonnet 48 in Easy, Modern English:


How careful I used to be when I went travelling, 
to put even the most trivial of my possessions 
behind the most secure locks available 
to keep them from the hands of thieves. 
But you – my best comfort – compared with whom my jewels are no more than trifles, 
have become my greatest worry, 
you dearest of dears who means everything to me, 
because you’re left open to every vulgar thief. 
I haven’t locked you up in any chest, 
except the one where you are not – although I feel you are – 
inside the tender enclosure of my breast, 
from where you may come and go as you please. 
And I’m afraid that you’ll be stolen even from there 
because even honest men would become thieves to get a prize so rich.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 48










Sonnet 48 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 48, as published in Shakespeare’s 1609 Quarto:


HOw careful was I when I tooke my way,
Each trifle vnder trueſt barres to thruſt,
That to my vſe it might vn-vſed ſtay
From hands of falſehood,in ſure wards of truſt ?
But thou,to whom my iewels trifles are,
Moſt worthy comfort,now my greateſt griefe,
Thou beſt of deereſt,and mine onely care,
Art left the prey of euery vulgar theefe.
Thee haue I not lockt vp in any cheſt,
Saue where thou art not,though I feele thou art,
Within the gentle cloſure of my breſt,
From whence at pleaſure thou maiſt come and part,
And euen thence thou wilt be ſtolne I feare,
For truth prooues theeuiſh for a prize ſo deare.






 



