---
title: "Shakespeare Sonnet 102: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 102 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 102



My love is strengthened, though more weak in seeming;
I love not less, though less the show appear;
That love is merchandized, whose rich esteeming,
The owner’s tongue doth publish every where.
Our love was new, and then but in the spring,
When I was wont to greet it with my lays;
As Philomel in summer’s front doth sing,
And stops his pipe in growth of riper days:
Not that the summer is less pleasant now
Than when her mournful hymns did hush the night,
But that wild music burthens every bough,
And sweets grown common lose their dear delight.
Therefore like her, I sometime hold my tongue:
Because I would not dull you with my song.




Read Sonnet 102 in Easy, Modern English:


My love is stronger, although it appears weaker: 
I don’t love any less, although I show my love less. 
Love becomes a product 
when one widely advertises the strength of his feelings about the one he loves. 
Our love was new – only in its spring – 
when I used to celebrate it with my verse, 
similar to the nightingale singing in the early summer 
and stopping as the summer progresses. 
It’s not that the summer is less pleasant now 
than when the nightingale sang in the silence of the night: 
it’s more that every branch is full of the wild music of song birds 
and that when things become common they’re less delightful. 
And so, like her, I sometimes hold my tongue 
because I don’t want my poems to appear dull to you.



