---
title: "Shakespeare Sonnet 111: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 111 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 111



O, for my sake do you with fortune chide,
The guilty goddess of my harmful deeds,
That did not better for my life provide,
Than public means which public manners breeds.
Thence comes it that my name receives a brand,
And almost thence my nature is subdu’d
To what it works in, like the dyer’s hand:
Pity me then and wish I were renew’d;
Whilst, like a willing patient, I will drink
Potions of eysell, ‘gainst my strong infection;
No bitterness that I will bitter think,
Nor double penance, to correct correction.
Pity me then, dear friend, and I assure ye
Even that your pity is enough to cure me. 




Read Sonnet 111 in Easy, Modern English:


Oh, you’re cursing fortune – 
the cause of my bad behaviour – 
that didn’t provide better for my life 
than to make me perform in front of the public which was bound to influence my behaviour. 
That’s how I have come to have a bad name 
and it follows that my nature is affected by working with the public 
in the way a dyer’s hand is stained by working with dye. 
So with me, and I hope that I will be regenerated. 
In the meantime, like a willing patient, 
I will take better medicines for this strong infection. 
No matter how bitter it is I won’t think of it as bitter, 
nor will I complain about having to do double penance to correct this bad influence. 
Pity me, then, dear friend: 
I assure you that your pity is enough to cure me.



