---
title: "Shakespeare Sonnet 66: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 66 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 66



Tired with all these, for restful death I cry,
As to behold desert a beggar born,
And needy nothing trimm’d in jollity,
And purest faith unhappily forsworn,
And gilded honour shamefully misplac’d,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgrac’d,
And strength by limping sway disabled
And art made tongue-tied by authority,
And folly, doctor-like, controlling skill,
And simple truth miscall’d simplicity,
And captive good attending captain ill:
Tir’d with all these, from these would I be gone,
Save that, to die, I leave my love alone.




Read Sonnet 66 in Easy,  Modern English:


Exhausted with the following things I cry out for releasing death: 
for example, seeing a deserving person who has been born into poverty; 
and an undeserving one dressed in the finest clothes; 
and someone who shows trustworthiness wretchedly betrayed; 
and public honour shamefully bestowed on the unfit; 
and unblemished goodness forced into bad ways; 
and genuine perfection unjustly disgraced; 
and conviction crippled by corruption; 
and skill suppressed by those with the power to do it; 
and stupidity restraining the advance of knowledge; 
and simple truth being dismissed as simplistic; 
and good taking orders from evil. 
Exhausted with all these things I want to escape, 
except that by dying I would be abandoning my love.




Listen to Sir John Gielgud read Shakespeare’s sonnet 66










Sonnet 66 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 66, as published in Shakespeare’s 1609 Quarto:


TYr’d with all theſe for reſtfull death I cry,
As to behold deſert a begger borne,
And needie Nothing trimd in iollitie,
And pureſt faith vnhappily forſworne,
And gilded honor ſhamefully miplaſt,
And maiden vertue rudely ſtrumpeted,
And right perfection wrongfully diſgrac’d,
And ſtrength by limping ſway diſabled,
And arte made tung-tide by authoritie,
And Folly (Doctor-like) controuling skill,
And ſimple-Truth miſcalde Simplicitie,
And captiue-good attending Captaine ill.
Tyr’d with all theſe,from theſe would I be gone;
Saue that to dye,I leaue my loue alone.




 





