---
title: "Shakespeare Sonnet 108: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 108 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 108



What’s in the brain, that ink may character,
Which hath not figured to thee my true spirit?
What’s new to speak, what now to register,
That may express my love, or thy dear merit?
Nothing, sweet boy; but yet, like prayers divine,
I must each day say o’er the very same;
Counting no old thing old, thou mine, I thine,
Even as when first I hallowed thy fair name.
So that eternal love in love’s fresh case,
Weighs not the dust and injury of age,
Nor gives to necessary wrinkles place,
But makes antiquity for aye his page;
Finding the first conceit of love there bred,
Where time and outward form would show it dead.




Read Sonnet 108 in Easy, Modern English:


What is there in the imagination that can be captured by ink, 
that hasn’t served to demonstrate my constant soul to you? 
What else is there to say – what novelty to create – 
that may express my love or your worth? 
There is nothing, sweet boy. And yet, as though I were praying, 
I have to repeat the same things every day 
without thinking about how stale they are. 
You are mine and I am yours, just as on the first occasion I honoured your name. 
Eternal love, always new, 
doesn’t care about the decay and rages of age, 
nor does it take any notice of wrinkles 
but turns old age into an eternal youth, 
finding the original source of one’s love there, 
even though your age and outward appearance would suggest that it’s dead.



