---
title: "Shakespeare Sonnet 91: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 91 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 91



Some glory in their birth, some in their skill,
Some in their wealth, some in their body’s force,
Some in their garments though new-fangled ill;
Some in their hawks and hounds, some in their horse;
And every humour hath his adjunct pleasure,
Wherein it finds a joy above the rest:
But these particulars are not my measure,
All these I better in one general best.
Thy love is better than high birth to me,
Richer than wealth, prouder than garments’ cost,
Of more delight than hawks and horses be;
And having thee, of all men’s pride I boast:
Wretched in this alone, that thou mayst take
All this away, and me most wretched make.




Read Sonnet 91 in Easy, Modern English:


Some people take pride in their social rank; some in their abilities; 
some in their wealth; some in their physical strength; 
some in their clothes – even in ghastly fashions – 
some in their horses: 
every disposition has its particular pleasure – a favourite, 
enjoyed above the rest. 
But I don’t rate any of those things. 
I put one above them all. 
Your love is better than high birth to me; 
richer than wealth; worth more than expensive clothes; 
more pleasurable than hawks or horses could ever be. 
In having you I have something better than anyone can boast of. 
There’s just one potential source of sorrow in that – 
that you could take it all away and make me utterly wretched.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 91










Sonnet 91 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 91, as published in Shakespeare’s 1609 Quarto:


SOme glory in their birth,ſome in their skill ,
Some in their wealth,ſome in their bodies force,
Some in their garments though new-fangled ill:
Some in their Hawkes and Hounds,ſome in their Horſe.
And euery humor hath his adiunct pleaſure,
Wherein it findes a ioy aboue the reſt,
But theſe perticulers are not my meaſure,
All theſe I better in one generall beſt.
Thy loue is bitter then high birth to me,
Richer then wealth,prouder then garments coſt,
Of more delight then Hawkes or Horſes bee:
And hauing thee,of all mens pride I boaſt.
Wretched in this alone,that thou maiſt take,
All this away, and me moſt wretched make.




 





