---
title: "Shakespeare Sonnet 64: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 64 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 64



When I have seen by Time’s fell hand defac’d
The rich proud cost of outworn buried age;
When sometime lofty towers I see down-raz’d,
And brass eternal slave to mortal rage;
When I have seen the hungry ocean gain
Advantage on the kingdom of the shore,
And the firm soil win of the watery main,
Increasing store with loss, and loss with store;
When I have seen such interchange of state,
Or state itself confounded to decay;
Ruin hath taught me thus to ruminate
That Time will come and take my love away.
This thought is as a death which cannot choose
But weep to have that which it fears to lose.




Read Sonnet 64 in Easy, Modern English:


Having seen the glorious monuments of ages past – 
built by men now dead and buried – defaced by time’s terrible hand; 
having seen once high towers torn down, 
and hard brass destroyed by human anger; 
having seen the hungry ocean flood the shore 
and firm land fill parts of the sea, 
each one gaining and losing; 
having seen the way things change their nature, 
or even that very nature forced into decay, 
all that destruction has taught me to think this: 
that Time will come and take my love away. 
This thought is like death and I can’t do anything 
but weep about having something that I’m so afraid of losing.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 64










Sonnet 64 as Originally Published in The 1609 Quarto 


Here’s the exact wording and spelling of Sonnet 64, as published in Shakespeare’s 1609 Quarto:


WHen I haue ſeene by times fell hand defaced
The rich proud coſt of outworne buried age,
When ſometime loftie towers I ſee downe raſed,
And braſſe eternall ſlaue to mortall rage.
When I haue ſeene the hungry Ocean gaine
Aduantage on the Kingdome of the ſhoare,
And the firme ſoile win of the watry maine,
Increaſing ſtore with loſſe,and loſſe with ſtore.
When I haue ſeene ſuch interchange of ſtate,
Or ſtate it ſelfe confounded, to decay,
Ruine hath taught me thus to ruminate
That Time will come and take my loue away.
This thought is as a death which cannot chooſe
But weepe to haue,that which it feares to looſe.






 





