---
title: "Shakespeare Sonnet 92: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 92 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 92



But do thy worst to steal thyself away,
For term of life thou art assured mine;
And life no longer than thy love will stay,
For it depends upon that love of thine.
Then need I not to fear the worst of wrongs,
When in the least of them my life hath end.
I see a better state to me belongs
Than that which on thy humour doth depend:
Thou canst not vex me with inconstant mind,
Since that my life on thy revolt doth lie.
O what a happy title do I find,
Happy to have thy love, happy to die!
But what’s so blessed-fair that fears no blot?
Thou mayst be false, and yet I know it not.




Read Sonnet 92 in Easy, Modern English:


But do your worst. Leave me. 
Be assured you’re mine for life 
because my life won’t be able to outlive your love for me 
because it depends on your love. 
Therefore I don’t have to worry about all the worst things you might do to hurt me 
because the moment you hurt me in any way I will die. 
I see now, that I’m better off than I would be 
if I depended on your kindness to me. 
Your fickleness can’t upset me 
since my life would end the moment your mood changed. 
Oh, what a happy situation I’m in: 
happy to have your love, happy to die! 
But what situation is so well blessed that it’s completely without doubts? 
You may be unfaithful without my knowing it.




Listen to Sir John Gielgud read Shakespeare’s sonnet 92










Sonnet 92 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 92, as published in Shakespeare’s 1609 Quarto:


BVt doe thy worſt to ſteale thy ſelfe away,
For tearme of life thou art aſſured mine,
And life no longer then thy loue will ſtay,
For it depends vpon that loue of thine.
Then need I not to feare the worſt of wrongs,
When in the leaſt of them my life hath end,
I ſee,a better ſtate to me belongs
Then that,which on thy humor doth depend.
Thou canſt not vex me with inconſtant minde,
Since that my life on thy reuolt doth lie,
Oh what a happy title do I find ,
Happy to haue thy loue,happy to die!
But whats ſo bleſſed faire that feares no blot,
Thou maiſt be falce, and yet I know it not.




 



