---
title: "Shakespeare Sonnet 58: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 58 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 58



That god forbid, that made me first your slave,
I should in thought control your times of pleasure,
Or at your hand the account of hours to crave,
Being your vassal, bound to stay your leisure!
O! let me suffer, being at your beck,
The imprison’d absence of your liberty;
And patience, tame to sufferance, bide each check,
Without accusing you of injury.
Be where you list, your charter is so strong
That you yourself may privilege your time
To what you will; to you it doth belong
Yourself to pardon of self-doing crime.
I am to wait, though waiting so be hell,
Not blame your pleasure be it ill or well.




Read Sonnet 58 in Easy, Modern English:


May that god who made me your slave in the first place 
forbid that I should even think about trying to control what you do with your own time 
or demand that you account to me for it: 
as your slave, I’m obliged to attend on your leisure. 
Oh, being at your beck and call, 
let me bear with patience your liberty 
to go out and do as you like as I wait here in this prison. 
And let me cultivate the patience to endure each disappointment 
without accusing you of hurting me. 
Go wherever you like, your license is so strong 
that you can suit yourself as to what you do. 
You have the right to pardon yourself for any crime you may commit. 
I have to wait, even though waiting is hell, 
and not blame you for following your pleasure, whatever it may be – good or bad.




Listen to Sir John Gielgud read Shakespeare’s sonnet 58










Sonnet 58 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 58, as published in Shakespeare’s 1609 Quarto:


THat God forbid, that made me firſt your ſlaue,
I ſhould in thought controule your times of pleaſure,
Or at your hand th’ account of houres to craue,
Being your vaſſail, bound to ſtaie your leiſure.
Oh let me ſuffer( being at your beck)
Th’ impriſon’d abſence of your libertie,
And patience tame,to ſufferance bide each check,
Without accuſing you of iniury.
Be where you liſt,your charter is ſo ſtrong,
That you your ſelfe may priuiledge your time
To what you will,to you it doth belong,
Your ſelfe to pardon of ſelfe-doing crime.
I am to waite,though waiting ſo be hell,
Not blame your pleaſure be it ill or well.






 





