---
title: "Shakespeare Sonnet 85: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 85 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 85



My tongue-tied Muse in manners holds her still,
While comments of your praise richly compiled,
Reserve thy character with golden quill,
And precious phrase by all the Muses filed.
I think good thoughts, whilst others write good words,
And like unlettered clerk still cry ‘Amen’
To every hymn that able spirit affords,
In polished form of well-refined pen.
Hearing you praised, I say ”tis so, ’tis true,’
And to the most of praise add something more;
But that is in my thought, whose love to you,
Though words come hindmost, holds his rank before.
Then others, for the breath of words respect,
Me for my dumb thoughts, speaking in effect.




Read Sonnet 85 in Easy, Modern English:


My tongue-tied muse politely remains silent 
while accounts in praise of you mount up, 
expressing themselves with golden words 
and precious phrases inspired by all the muses. 
I think good thoughts about you while others write good words, 
and like an illiterate church clerk, I keep crying ‘amen’ 
to every hymn that competent poets devise in praise of you 
in polished and refined verse. 
Hearing you praised I say ‘that’s right, it’s true,’ 
and add something to their already high praise. 
But that’s only in my mind, which loves you most, 
even though I say the least. 
Therefore, respect others for their spoken words 
and me for my unspoken thoughts, that speak only through their actions.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 85










Sonnet 85 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 85, as published in Shakespeare’s 1609 Quarto:


MY toung-tide Muſe in manners holds her ſtill,
While comments of your praiſe richly compil’d,
Reſerue their Character with goulden quill,
And precious phraſe by all the Mufes fil’d.
I thinke good thoughts,whilſt other write good wordes,
And like vnlettered clarke ſtill crie Amen,
To euery Himne that able ſpirit affords,
In poliſht forme of well refined pen.
Hearing you praiſd,I ſay ’tis ſo, ’tis true,
And to the moſt of praife adde ſome-thing more,
But that is in my thought, whoſe loue to you
(Though words come hind-moſt)holds his ranke before,
Then others,for the breath of words reſpect,
Me for my dombe thoughts,ſpeaking in effect.




 





