---
title: "Shakespeare Sonnet 76: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 76 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 76



Why is my verse so barren of new pride,
So far from variation or quick change?
Why with the time do I not glance aside
To new-found methods, and to compounds strange?
Why write I still all one, ever the same,
And keep invention in a noted weed,
That every word doth almost tell my name,
Showing their birth, and where they did proceed?
O! know sweet love I always write of you,
And you and love are still my argument;
So all my best is dressing old words new,
Spending again what is already spent:
For as the sun is daily new and old,
So is my love still telling what is told.




Read Sonnet 76 in Easy, Modern English:


Why is my verse so devoid of new devices – 
so resistant to variation and novelty? 
Why don’t I go along with the times and look around 
at newly adopted techniques and unfamiliar juxtapositions? 
Why do I write everything the same – always the same, 
confining all my ideas to their well-known clothes 
so that every word almost proclaims my name, 
where it was born and where it’s going to? 
Oh, you know, sweet love, I always write about you, 
and you, and love, are always my subject. 
So all I can do is clothe what I’ve already said in new words, 
spending again what I’ve already spent. 
In the same way that the sun is old and new every day, 
my love is always saying what has already been said.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 76










Sonnet 76 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 76, as published in Shakespeare’s 1609 Quarto:


WHy is my verſe ſo barren of new pride?
So far from variation or quicke change?
Why with the time do I not glance aſide
To new found methods,and to compounds ſtrange?
Why write I ſtill all one,euer the fame,
And keepe inuention in a noted weed,
That euery word doth almoſt fel my name,
Shewing their birth,and where they did proceed?
O know ſweet loue I alwaies write of you,
And you and loue are ſtill my argument:
So all my beſt is dreſſing old words new,
Spending againe what is already ſpent:
For as the Sun is daily new and old,
So is my loue ſtill telling what is told






 



