---
title: "Shakespeare Sonnet 3: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 3 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 3



Look in thy glass, and tell the face thou viewest
Now is the time that face should form another;
Whose fresh repair if now thou not renewest,
Thou dost beguile the world, unbless some mother.
For where is she so fair whose unear’d womb
Disdains the tillage of thy husbandry?
Or who is he so fond will be the tomb
Of his self-love, to stop posterity?
Thou art thy mother’s glass, and she in thee
Calls back the lovely April of her prime:
So thou through windows of thine age shall see
Despite of wrinkles this thy golden time.
But if thou live, remember’d not to be,
Die single, and thine image dies with thee.




Read Sonnet 3 in Easy, Modern English:


Look in your mirror and tell the face you see 
that it’s time it should create another;
If you do not renew yourself 
you would be depriving the world, and stop some woman from becoming a mother. 
For where is the lovely woman whose unploughed womb 
would not appreciate the way you plow your field? 
Or who is he foolish enough to love himself so much 
as to neglect reproducing? 
You are the mirror of your mother, and she is the mirror of you, and in you, 
she recalls the lovely April of her youth. 
In the same way, you will see your youth in your own children, 
in spite of the wrinkles caused by age. 
But if you live your life avoiding being remembered 
you will die single and your image will die with you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 3










Sonnet 3 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 3, as published in Shakespeare’s 1609 Quarto:


Looke in thy glaſſe and tell the face thou veweſt,
Now is the time that face ſhould forme an other,
Whoſe freſh repaire if now thou not reneweſt,
Thou doo’ſt beguile the world,vnbleſſe ſome
mother.
For where is ſhe ſo faire whoſe vn-eard wombe
Diſdaines the tillage of thy huſbandry?
Or who is he ſo fond will be the tombe,
Of his ſelfe loue to ſtop poſterity?
Thou art thy mothers glaſſe and ſhe in thee
Calls backe the louely Aprill of her prime,
So thou through windowes of thine age ſhalt ſee,
Diſpight of wrinkles this thy goulden time.
But if thou liue remembred not to be,
Die ſingle and thine Image dies with thee.






 


Interested in Shakespeare’s sonnet 3? If so you can get some additional free information by visiting our friends over at 
PoemAnalysis to read their analysis of sonnet 3
.


 





