---
title: "Shakespeare Sonnet 31: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 31 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 31



Thy bosom is endeared with all hearts,
Which I by lacking have supposed dead;
And there reigns Love, and all Love’s loving parts,
And all those friends which I thought buried.
How many a holy and obsequious tear
Hath dear religious love stol’n from mine eye,
As interest of the dead, which now appear
But things remov’d that hidden in thee lie!
Thou art the grave where buried love doth live,
Hung with the trophies of my lovers gone,
Who all their parts of me to thee did give,
That due of many now is thine alone:
Their images I lov’d, I view in thee,
And thou (all they) hast all the all of me.




Read Sonnet 31 in Easy, Modern English:


Your heart has collected all the hearts 
which I, thinking them all dead, don’t have anymore. 
Love reigns in your heart – everything that love is, 
as well as all those friends whom I supposed to be dead and gone. 
How many tears of deep and devoted love 
I have shed for dead friends 
only to discover, now, 
that they are all just hiding in your heart. 
You’re the grave in which dead love springs back to life, 
adorned with trophies of my departed lovers, 
giving you all the love I once gave to them. 
All that love I owed them is now yours alone. 
I see the pictures of all those lovers in you; 
and you, who contain them all, have all of me.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 31










Sonnet 31 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 31, as published in Shakespeare’s 1609 Quarto:


Thy boſome is indeared with all hearts,
Which I by lacking have ſuppoſed dead,
And there raignes Loue and all Loues louing parts,
And all thoſe friends which I thought buried.
How many a holy and obſequious teare
Hath deare religious loue ſtolne from mine eye,
As intereſt of the dead,which now appeare,
But things remou’d that hidden in there lie.
Thou art the graue where buried loue doth liue,
Hung with the tropheis of my louers gon,
Who all their parts of me to thee did giue,
That due of many,now is thine alone.
Their images I lou’d, I view in thee,
And thou(all they)haſt all the all of me.






 



