---
title: "Shakespeare Sonnet 80: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 80 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 80



O! how I faint when I of you do write,
Knowing a better spirit doth use your name,
And in the praise thereof spends all his might,
To make me tongue-tied speaking of your fame.
But since your worth, wide as the ocean is,
The humble as the proudest sail doth bear,
My saucy bark, inferior far to his,
On your broad main doth wilfully appear.
Your shallowest help will hold me up afloat,
Whilst he upon your soundless deep doth ride;
Or, being wrack’d, I am a worthless boat,
He of tall building, and of goodly pride:
Then if he thrive and I be cast away,
The worst was this, my love was my decay.




Read Sonnet 80 in Easy, Modern English:


Oh, how faint I feel when I write about you, 
knowing that a better poet can claim you as his patron. 
And in singing your praises he uses all his energy 
to make me tongue-tied. 
But since your worth is as wide as the ocean, 
and the humblest can sail on it as well as the proudest, 
my insolent boat, far inferior to his, 
insists on sailing on your vast open sea. 
Your most shallow favour will keep me afloat 
while he sails on your deepest favour. 
But, if I am wrecked it’s because I’m a worthless boat, 
while he is stately and proud. 
Then if he prospers and I am cast ashore, 
the worst aspect of it was this: my love for you was my ruin.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 80










Sonnet 80 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 80, as published in Shakespeare’s 1609 Quarto:


OHow I faint when I of you do write,
Knowing a better ſpirit doth vſe your name,
And in the praiſe thereof ſpends all his might,
To make me toung-tide ſpeaking of your fame.
But ſince your worth(wide as the Ocean is)
The humble as the proudeſt ſaile doth beare,
My ſawſie barke (inferior farre to his)
On your broad maine doth wilfully appeare.
Your ſhalloweſt helpe will hold me vp a floate,
Whilſt he vpon your ſoundleſſe deepe doth ride,
Or (being wrackt ) I am a worthleſſe bote,
He of tall building,and of goodly pride.
Then If he thriue and I be caſt away,
The worſt was this,my loue was my decay.




 





