---
title: "Shakespeare Sonnet 134: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 134 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 134



So now I have confessed that he is thine,
And I my self am mortgaged to thy will,
Myself I’ll forfeit, so that other mine
Thou wilt restore to be my comfort still:
But thou wilt not, nor he will not be free,
For thou art covetous, and he is kind;
He learned but surety-like to write for me,
Under that bond that him as fast doth bind.
The statute of thy beauty thou wilt take,
Thou usurer, that put’st forth all to use,
And sue a friend came debtor for my sake;
So him I lose through my unkind abuse.
Him have I lost; thou hast both him and me:
He pays the whole, and yet am I not free.




Read Sonnet 134 in Easy, Modern English:


So now I’ve admitted that he’s yours, 
and that I’m still contracted to your desire, 
I’ll sacrifice myself if you’ll let my friend go 
so that he can comfort me. 
But you won’t; nor does he want his freedom, 
because you’re greedy and he’s soft-hearted. 
He tried to bail me out 
but that action has bound him to you as securely as I am. 
You’ll insist on the legal right your beauty entitles you to – 
you loan-shark, who lends your body to everyone, 
and then pursues my friend, who only borrowed from you for my sake! 
So I lose him because I abused him cruelly by allowing him to go to you. 
I’ve lost him: you’ve got both him and me. 
He repays both our debts with all the sex you want and yet I’m still not free.



