---
title: "Shakespeare Sonnet 83: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 83 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 83



I never saw that you did painting need,
And therefore to your fair no painting set;
I found, or thought I found, you did exceed
The barren tender of a poet’s debt:
And therefore have I slept in your report,
That you yourself, being extant, well might show
How far a modern quill doth come too short,
Speaking of worth, what worth in you doth grow.
This silence for my sin you did impute,
Which shall be most my glory being dumb;
For I impair not beauty being mute,
When others would give life, and bring a tomb.
There lives more life in one of your fair eyes
Than both your poets can in praise devise.




Read Sonnet 83 in Easy, Modern English:


I’ve never thought that representations of you need elaboration, 
so I haven’t described your beauty in elaborate verse. 
I could see – or thought I could see – 
that you were above the skills of any poet. 
Therefore, I’ve made no effort to represent you 
so that you yourself, by virtue of your very existence, would be able to demonstrate 
how far short modern verse would come 
in representing quality – the real quality that you possess. 
You regarded my silence as a fault, 
but I’m proud of it because my silence doesn’t detract from your beauty, 
whereas others destroy it by trying to bring it to life. 
There’s more life in one of your beautiful eyes 
than all of your poets can invent in their praise of you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 83










Sonet 83 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 83, as published in Shakespeare’s 1609 Quarto:


INeuer ſaw that you did painting need,
And therefore to your faire no painting ſet,
I found ( or thought I found) you did exceed,
The barren tender of a Poets debt:
And therefore haue I ſlept in your report,
That you your ſelfe being extant well might ſhow,
How farre a moderne quill doth come to ſhort,
Speaking of worth,what worth in you doth grow,
This ſilence for my ſinne you did impute,
Which ſhall be moſt my glory being dombe,
For I impaire not beautie being mute,
When others would giue life,and bring a tombe.
There liues more life in one of your faire eyes,
Than both your Poets can in praiſe deuiſe.




 





