---
title: "Shakespeare Sonnet 95: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 95 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 95



How sweet and lovely dost thou make the shame
Which, like a canker in the fragrant rose,
Doth spot the beauty of thy budding name!
O! in what sweets dost thou thy sins enclose.
That tongue that tells the story of thy days,
Making lascivious comments on thy sport,
Cannot dispraise, but in a kind of praise;
Naming thy name blesses an ill report.
O! what a mansion have those vices got
Which for their habitation chose out thee,
Where beauty’s veil doth cover every blot
And all things turns to fair that eyes can see!
Take heed, dear heart, of this large privilege;
The hardest knife ill-used doth lose his edge.




Read Sonnet 95 in Easy, Modern English:


How sweet and lovely you make the flaw appear 
that is spoiling your reputation, 
just as a blight spoils the reputation of a fragrant rose! 
Oh, with what a sweet exterior you cover over your sins! 
Those who talk about you, 
while commenting on your lustful ways, 
can’t help couching that criticism in the language of praise. 
Just the mention of your name makes bad actions appear good. 
Oh what a beautiful house those vices that chose you as their home have – 
a place where the veil of beauty covers every flaw 
and everything that’s visible appears beautiful! 
Be careful, dear heart, of this great privilege: 
even the hardest knife will lose its edge if abused.




Listen to Sir John Gielgud read Shakespeare’s sonnet 95










Sonnet 95 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 95, as published in Shakespeare’s 1609 Quarto:


HOw ſweet and louely doſt thou make the ſhame,
Which like a canker in the fragrant Roſe,
Doth ſpot the beautie of thy budding name?
Oh in what ſweets doeſt thou thy ſinnes incloſe!
That tongue that tells the ſtorie of thy daies,
(Making laſciuious comments on thy ſport)
Cannot diſpraiſe,but in a kind of praiſe,
Naming thy name, bleſſes an ill report.
Oh what a manſion haue thoſe vices got,
Which for their habitation choſe out thee,
Where beauties vaile doth couer euery blot,
And all things turnes to faire,that eies can ſee!
Take heed(deare heart)of this large priuiledge,
The hardeſt knife ill vſ’d doth looſe his edge.




 





