---
title: "Shakespeare Sonnet 136: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 136 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 136



If thy soul check thee that I come so near,
Swear to thy blind soul that I was thy Will,
And will, thy soul knows, is admitted there;
Thus far for love, my love-suit, sweet, fulfil.
Will, will fulfil the treasure of thy love,
Ay, fill it full with wills, and my will one.
In things of great receipt with ease we prove
Among a number one is reckoned none:
Then in the number let me pass untold,
Though in thy store’s account I one must be;
For nothing hold me, so it please thee hold
That nothing me, a something sweet to thee:
Make but my name thy love, and love that still,
And then thou lovest me for my name is ‘Will’.




Read Sonnet 136 in Easy, Modern English:


If your conscience troubles you that I keep pestering you 
tell it that I’m your Will. 
Your conscience knows that my will is allowed to go there. 
Grant that much for the sake of love. 
Will will fill your sweet love treasure; 
oh yes, he’ll fill it full of wills and my will will be one of them. 
We know that one is never enough for things that can hold a lot. 
Therefore, let me be included among all the others: 
don’t count me, but value me nevertheless. 
Consider me as nothing as long as that nothing is sweet to you. 
Just love my name, and continue loving it, 
and then you’ll love me because my name is Will.



