---
title: "Shakespeare Sonnet 133: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 133 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 133



Beshrew that heart that makes my heart to groan
For that deep wound it gives my friend and me!
Is’t not enough to torture me alone,
But slave to slavery my sweet’st friend must be?
Me from myself thy cruel eye hath taken,
And my next self thou harder hast engrossed:
Of him, myself, and thee I am forsaken;
A torment thrice three-fold thus to be crossed.
Prison my heart in thy steel bosom’s ward,
But then my friend’s heart let my poor heart bail;
Whoe’er keeps me, let my heart be his guard;
Thou canst not then use rigour in my jail:
And yet thou wilt; for I, being pent in thee,
Perforce am thine, and all that is in me.




Read Sonnet 133 in Easy, Modern English:


Damn that heart of yours that makes mine ache 
with the deep wound it gives both my friend and me! 
Isn’t it enough to torture me 
without subjecting my dearest friend to the same slavery? 
Your cruel eyes have unmanned me 
and enslaved my closest friend even more cruelly. 
So I’ve been abandoned by him, by myself, and by you, 
and such a frustration is a triple torment multiplied by three. 
Imprison my heart in the barred cell of your heart 
but allow it to bail my friend’s heart. 
No matter who guards me in my prison, let me be in charge of guarding him,
 then nothing you can do to me in my jail will be a torment to me. 
But you will still torment me because, being imprisoned in your heart, 
I belong to you, and everything that’s in my heart is yours.



