---
title: "Shakespeare Sonnet 89: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 89 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 89



Say that thou didst forsake me for some fault,
And I will comment upon that offence:
Speak of my lameness, and I straight will halt,
Against thy reasons making no defence.
Thou canst not, love, disgrace me half so ill,
To set a form upon desired change,
As I’ll myself disgrace; knowing thy will,
I will acquaintance strangle, and look strange;
Be absent from thy walks; and in my tongue
Thy sweet beloved name no more shall dwell,
Lest I, too much profane, should do it wrong,
And haply of our old acquaintance tell.
For thee, against my self I’ll vow debate,
For I must ne’er love him whom thou dost hate.




Read Sonnet 89 in Easy, Modern English:


Just say that you left me because of some fault of mine 
and I’ll accept that fault. 
If you say I’m lame I’ll immediately begin limping 
and make no arguments in my own defense. 
My love, you could not disgrace me half as much 
in an effort to improve me, 
as I would disgrace myself if I knew what you wanted. 
I’ll suppress our acquaintanceship and become a stranger, 
stay away from the places you go, 
and not mention your dear, beloved name again 
in case I, being so unworthy, should reveal the fact 
that we once knew each other. 
I’ll swear to be my own enemy for your sake, 
because I must not love the person who you hate.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 89










Sonnet 89 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 89, as published in Shakespeare’s 1609 Quarto:


SAy that thou didſt forſake mee for ſome falt,
And I will comment vpon that offence,
Speake of my lameneſſe, and I ſtraight will halt:
Againt thy reaſons making no defence.
Thou canſt not(loue)diſgrace me halfe ſo ill,
To ſet a forme vpon deſired change,
As ile my ſelfe diſgrace,knowing thy wil,
I will acquaintance ſtrangle and looke ſtrange:
Be abſent from thy walkes and in my tongue,
Thy ſweet beloued name no more ſhall dwell,
Leaſt I(too much prophane)ſhould do it wronge:
And haplie of our old acquaintance tell.
For thee,againſt my ſelfe ile vow debate,
For I muſt nere loue him whom thou doſt hate.




 



