---
title: "Shakespeare Sonnet 103: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 103 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 103



Alack! what poverty my Muse brings forth,
That having such a scope to show her pride,
The argument all bare is of more worth
Than when it hath my added praise beside!
O! blame me not, if I no more can write!
Look in your glass, and there appears a face
That over-goes my blunt invention quite,
Dulling my lines, and doing me disgrace.
Were it not sinful then, striving to mend,
To mar the subject that before was well?
For to no other pass my verses tend
Than of your graces and your gifts to tell;
And more, much more, than in my verse can sit,
Your own glass shows you when you look in it.




Read Sonnet 103 in Easy, Modern English:


Alas, what poor poetry my muse brings out of me,
considering the scope she has to display her skills. 
The subject can’t be improved on 
and doesn’t need my added praise! 
Oh don’t criticise me for not being able to write anymore! 
Look in your mirror and a face will appear 
that out-does my poor creative powers, 
stunting my verses and putting me to shame. 
Wouldn’t it be a sin if, in trying to improve my subject, 
I damaged something that was perfectly good before? 
Because there is nothing my verses aim at
other than to count your charms and qualities; 
and there are many many more to be seen in your mirror, 
when you look in it, than can be contained in my verse.



