---
title: "Shakespeare Sonnet 151: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 151 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 151



Love is too young to know what conscience is,
Yet who knows not conscience is born of love?
Then, gentle cheater, urge not my amiss,
Lest guilty of my faults thy sweet self prove:
For, thou betraying me, I do betray
My nobler part to my gross body’s treason;
My soul doth tell my body that he may
Triumph in love; flesh stays no farther reason,
But rising at thy name doth point out thee,
As his triumphant prize. Proud of this pride,
He is contented thy poor drudge to be,
To stand in thy affairs, fall by thy side.
No want of conscience hold it that I call
Her love, for whose dear love I rise and fall.




Read Sonnet 151 in Easy, Modern English:


Cupid is too young to know what sexual desire is; 
but who doesn’t know that it is first felt with love? 
So, gentle manager of my heart, don’t dwell on my weakness 
lest you also prove guilty of it, 
because your infidelity incites me to be unfaithful 
to my better self by becoming physically aroused. 
My soul tells my body that it may 
be a conqueror in love: the penis doesn’t wait for any further reason, 
but, rising at the mere mention of you, points at you 
as the reward of his conquest. 
Swollen up with the thrill of victory, he is happy to be at your service; 
to stand to attention when you need him, and then fall beside you. 
I don’t feel guilty about calling a woman ‘Love’ when 
for the sake of her love I am always ready to rise and fall.



