---
title: "Shakespeare Sonnet 47: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 47 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 47



Betwixt mine eye and heart a league is took,
And each doth good turns now unto the other:
When that mine eye is famish’d for a look,
Or heart in love with sighs himself doth smother,
With my love’s picture then my eye doth feast,
And to the painted banquet bids my heart;
Another time mine eye is my heart’s guest,
And in his thoughts of love doth share a part:
So, either by thy picture or my love,
Thy self away, art present still with me;
For thou not farther than my thoughts canst move,
And I am still with them, and they with thee;
Or, if they sleep, thy picture in my sight
Awakes my heart, to heart’s and eyes’ delight.




Read Sonnet 47 in Easy, Modern English:


An agreement has been reached between my eye and my heart 
and each one is doing the other favours now. 
When my eye is starving for a glimpse of you 
or my heart is busy smothering himself sighing for you 
then my eye feasts on a picture of you 
and invites my heart to the painted banquet. 
Another time my eye is my heart’s guest 
and shares some of his thoughts of love. 
So either by your picture or my thoughts of love 
you are always with me even though you’re not here. 
You can’t travel further than my thoughts 
and I am always with them and they are always with you. 
If they go to sleep, as long as your picture is within sight 
my heart will wake and it will delight both heart and eye.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 47










Sonnet 47 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 47, as published in Shakespeare’s 1609 Quarto:


BEtwixt mine eye and heart a league is tooke,
And each doth good turnes now vnto the other,
When that mine eye is famiſht for a looke,
Or heart in loue with ſighes himſelfe doth ſmother;
With my loues picture then my eye doth feaſt,
And to the painted banquet bids my heart:
An other time mine eye is my hearts gueſt,
And in his thoughts of loue doth ſhare a part.
So either by thy picture or my loue,
Thy ſeife away,are preſent ſtill with me,
For thou nor farther then my thoughts canſt moue,
And I am ſtill with them,and they with thee.
Or if they ſleepe, thy picture in my ſight
Awakes my heart,to hearts and eyes delight.






 



