---
title: "Shakespeare Sonnet 125: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 125 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 125



Were’t ought to me I bore the canopy,
With my extern the outward honouring,
Or laid great bases for eternity,
Which prove more short than waste or ruining?
Have I not seen dwellers on form and favour
Lose all and more by paying too much rent,
For compound sweet forgoing simple savour,
Pitiful thrivers, in their gazing spent?
No, let me be obsequious in thy heart,
And take thou my oblation, poor but free,
Which is not mixed with seconds, knows no art,
But mutual render, only me for thee.
Hence, thou suborned informer! A true soul
When most impeached stands least in thy control.




Read Sonnet 125 in Easy, Modern English:


Would it mean anything to me if I were to carry the processional royal canopy, 
dignifying such shows of power with my presence; 
or lay the foundations of monuments intended to last for eternity 
but which in reality endure no longer than it takes them to decay or be destroyed by such things as war? 
Haven’t I seen those who dwell on outward appearance and the favour of the powerful 
lose everything and even more than that by putting everything into it, 
spending all they have on lavish displays instead of enjoying simple pleasures in pursuit of their superficial desires? 
No, let me be committed only to you. 
Accept my offer, simple, but freely given, 
containing nothing but the best, having no ulterior motives, 
with only mutual exchange – myself for yourself. 
Go away, you paid spy! 
When an honest soul is accused you have no power over him.



