---
title: "Shakespeare Sonnet 82: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 82 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 82



I grant thou wert not married to my Muse,
And therefore mayst without attaint o’erlook
The dedicated words which writers use
Of their fair subject, blessing every book.
Thou art as fair in knowledge as in hue,
Finding thy worth a limit past my praise;
And therefore art enforced to seek anew
Some fresher stamp of the time-bettering days.
And do so, love; yet when they have devis’d,
What strained touches rhetoric can lend,
Thou truly fair, wert truly sympathiz’d
In true plain words, by thy true-telling friend;
And their gross painting might be better usd
Where cheeks need blood; in thee it is abusd.




Read Sonnet 82 in Easy, Modern English:


I admit that you’ve had no commitment to my poetry 
and can therefore survey, without guilt,
the words of dedication other writers use 
about the beautiful subjects who grace their books. 
You are as knowledgeable as you are beautiful, 
and your qualities are beyond any skills I have to praise them. 
Therefore you’re forced to look again 
for a fresher representative of these modern literary times. 
So do that, Love. And yet, when that new poet has invented 
whatever elaborate devices he can borrow from rhetoric, 
you would – because you are truly beautiful – have been accurately represented by the true plain words of your honest friend. 
His exaggerated painting 
might be better employed on subjects who need colour: in you it’s a misuse.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 82










Sonnet 82 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 82, as published in Shakespeare’s 1609 Quarto:


IGrant thou wert not married to my Muſe,
And therefore maieſt without attaint ore-looke
The dedicated words which writers vſe
Of their faire ſubiect,bleſſing euery booke.
Thou art as faire in knowledge as in hew,
Finding thy worth a limmit paſt my praiſe,
And therefore art inforc’d to ſeeke anew,
Some freſher ſtampe of the time bettering dayes.
And do ſo loue,yet when they haue deuiſde,
What ſtrained touches Rhethorick can lend,
Thou truly faire,wert truly ſimpathizde,
In true plaine words ,by thy true telling friend.
And their groſſe painting might be better vſ’d,
Where cheekes need blood,in thee it is abuſ’d.




 



