---
title: "Shakespeare Sonnet 10: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 10 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 10



For shame deny that thou bear’st love to any,
Who for thy self art so unprovident.
Grant, if thou wilt, thou art beloved of many,
But that thou none lov’st is most evident:
For thou art so possessed with murderous hate,
That ‘gainst thy self thou stick’st not to conspire,
Seeking that beauteous roof to ruinate
Which to repair should be thy chief desire.
O! change thy thought, that I may change my mind:
Shall hate be fairer lodged than gentle love?
Be, as thy presence is, gracious and kind,
Or to thyself at least kind-hearted prove:
Make thee another self for love of me,
That beauty still may live in thine or thee.




Read Sonnet 10 in Easy, Modern English:


Out of a sense of shame you, who are so unwilling to provide for the future, 
should admit that you don’t love anyone. 
I grant you, if you like, that you are loved by many, 
but it’s very clear that you don’t love anyone; 
because, being someone who doesn’t hesitate to conspire against himself, 
you are determined to murder your potential progeny. 
You are prepared to end your noble line, 
which it should be your main concern to maintain. 
Oh! Change your mind, so that I can change my opinion of you. 
Do you, the most beautiful creature, want to be the house where hate lives? 
Be as gracious and generous to your relatives as you are to everyone else, 
or at least be generous to yourself. 
Change your mind for my sake so that you will be a noble person 
and that your beauty will live on in your descendants.




Watch Sir Patrick Stewart Read Shakespeare’s Sonnet 10










Sonnet 10 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 10, as published in Shakespeare’s 1609 Quarto:


FOr ſhame deny that thou bear’ſt loue to any
Who for thy ſelfe art ſo vnprouident
Graunt if thou wilt,thou art belou’d of many,
But that thou none lou’ſt is moſt euident:
For thou art ſo poſſeſt with murdrous hate,
That gainſt thy ſelfe thou ſtickſt not to conſpire,
Seeking that beautious roofe to ruinate
Which to repaire ſhould be thy chiefe deſire :
O change thy thought,that I may change my minde,
Shall hate be fairer log’d then gentle loue?
Be as thy preſence is gracious and kind,
Or to thy ſelfe at leaſt kind harted proue,
Make thee an other ſelfe for loue of me,
That beauty ſtill may liue in thine or thee.




 

