---
title: "Shakespeare Sonnet 105: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 105 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 105



Let not my love be called idolatry,
Nor my beloved as an idol show,
Since all alike my songs and praises be
To one, of one, still such, and ever so.
Kind is my love to-day, to-morrow kind,
Still constant in a wondrous excellence;
Therefore my verse to constancy confined,
One thing expressing, leaves out difference.
Fair, kind, and true, is all my argument,
Fair, kind, and true, varying to other words;
And in this change is my invention spent,
Three themes in one, which wondrous scope affords.
Fair, kind, and true, have often lived alone,
Which three till now, never kept seat in one.




Read Sonnet 105 in Easy, Modern English:


Don’t let anyone call my love idolatry 
nor say that I regard my beloved as an idol 
because all my songs and praises have been 
directed to one person and always will be. 
The one I love is kind today, will be kind tomorrow – 
forever wonderfully constant. 
And so, because my verse is confined to something that’s permanently constant, 
it always expresses the same thing, never varying. 
All I write about is beauty, kindness and faithfulness. 
I write about the beautiful, kind and faithful in different variations, 
and that is how I expend my creativity – 
three themes in one, offering wonderful scope. 
Beauty, kindness and faithfulness are often found separately 
and have never been found in one person until now.



