---
title: "Shakespeare Sonnet 96: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 96 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 96



Some say thy fault is youth, some wantonness;
Some say thy grace is youth and gentle sport;
Both grace and faults are lov’d of more and less:
Thou mak’st faults graces that to thee resort.
As on the finger of a throned queen
The basest jewel will be well esteem’d,
So are those errors that in thee are seen
To truths translated, and for true things deem’d.
How many lambs might the stern wolf betray,
If like a lamb he could his looks translate!
How many gazers mightst thou lead away,
If thou wouldst use the strength of all thy state!
But do not so; I love thee in such sort,
As, thou being mine, mine is thy good report.




Read Sonnet 96 in Easy, Modern English:


Some say the problem is your youth; some say it’s your lustfulness: 
some say your charm lies in your youth and playfulness. 
Everyone, important or less important, loves both your charms and your faults: 
you turn faults into charms. 
Just as a worthless ornament will assume value 
when a queen is wearing it, 
your visible faults become virtues. 
How many lambs the fierce wolf could beguile 
if he could make himself look like a lamb! 
How many admirers you could lead astray 
if you employed the full force of your beauty and position! 
But don’t do that. I love you so much that, 
because you belong to me, I enjoy a reflected glory from your good reputation.




Listen to Sir John Gielgud read Shakespeare’s sonnet 96










Sonnet 96 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 96, as published in Shakespeare’s 1609 Quarto:


SOme ſay thy fault is youth,ſome wantoneſſe,
Some ſay thy grace is youth and gentle ſport,
Both grace and faults are lou’d of more and leſſe:
Thou makſt faults graces,that to thee reſort:
As on the finger of a throned Queene,
The baſeſt Iewell will be well eſteem’d:
So are thoſe errors that in thee are ſeene,
To truths tranſlated,and for true things deem’d.
How many Lambs might the ſterne Wolfe betray,
If like a Lambe he could his lookes tranſlate.
How many gazers mighſt thou lead away,
If thou wouldſt vſe the ſtrength of all thy ſtate?
But doe not ſo,I loue thee in ſuch ſort,
As thou being mine,mine is thy good report.




 



