---
title: "Shakespeare Sonnet 14: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 14 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 14



Not from the stars do I my judgement pluck;
And yet methinks I have Astronomy,
But not to tell of good or evil luck,
Of plagues, of dearths, or seasons’ quality;
Nor can I fortune to brief minutes tell,
Pointing to each his thunder, rain and wind,
Or say with princes if it shall go well
By oft predict that I in heaven find:
But from thine eyes my knowledge I derive,
And, constant stars, in them I read such art
As truth and beauty shall together thrive,
If from thyself, to store thou wouldst convert;
Or else of thee this I prognosticate:
Thy end is truth’s and beauty’s doom and date.




Read Sonnet 14 in Easy, Modern English:


I don’t pick my wisdom from the stars, 
but I think I understand astronomy, 
although not to predict good or bad luck, 
or plagues and famines or what the seasons will be like. 
Nor can I tell fortunes, 
showing individuals their own moods and their ups and downs, 
nor tell rulers whether things will go well 
by frequent predictions from what I see in the heavens. 
But I get my knowledge from your eyes, 
and as they are constant stars, I’m able to predict 
that truth and beauty will thrive together 
if you would turn your attention from yourself to the reproduction of yourself; 
otherwise, this is my prediction for you: 
your death will be the final end of truth and beauty.




Watch Sir Patrick Stewart read Shakespeare’s sonnet 14










Sonnet 14 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 14, as published in Shakespeare’s 1609 Quarto:


Not from the ſtars do I my iudgement plucke,
And yet me thinkes I haue Aſtronomy,
But not to tell of good,or euil lucke,
Of plagues,of dearths,or ſeaſons quallity,
Nor can I fortune to breefe mynuits tell);
Pointing to each his thunder, raine and winde,
Or ſay with Princes if it ſhal go wel
By oft predict that I in heauen finde.
But from thine eies my knowledge I deriue,
And conſtant ſtars in them I read ſuch art
As truth and beautie ſhal together thriue
If from thy ſelfe,to ſtore thou wouldſt conuert:
Or elſe of thee this I prognoſticate,
Thy end is Truthes and Beauties doome and date.


 




 

