---
title: "Shakespeare Sonnet 20: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 20 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 20



A woman’s face with nature’s own hand painted,
Hast thou, the master mistress of my passion;
A woman’s gentle heart, but not acquainted
With shifting change, as is false women’s fashion:
An eye more bright than theirs, less false in rolling,
Gilding the object whereupon it gazeth;
A man in hue all hues in his controlling,
Which steals men’s eyes and women’s souls amazeth.
And for a woman wert thou first created;
Till Nature, as she wrought thee, fell a-doting,
And by addition me of thee defeated,
By adding one thing to my purpose nothing.
But since she prick’d thee out for women’s pleasure,
Mine be thy love and thy love’s use their treasure.




Read Sonnet 20 in Easy, Modern English:


Your face is more beautiful than a woman’s because it’s been painted by nature and not artificially. 
You are both master and mistress of my passion. 
You have the gentle heart of a woman 
but without the fickleness characteristic of women. 
Your eyes, that light up the very object that they look on, 
are brighter than theirs but without their shallow flirtatiousness. 
You have all the best qualities a man could have. 
All other men look to you as a model: 
you catch the eye of men and you amaze women. 
Nature first intended you as a woman, 
but as she was making you, she fell madly in love with you 
and, by adding something, deprived me of you; 
by adding one thing she made you unattainable to me. 
But since she equipped you for the pleasure of women,
 let me have your love and them your body.




Listen to Sir John Geilgud read Shakespeare’s sonnet 20










Sonnet 20 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 20, as published in Shakespeare’s 1609 Quarto:


AWomans face with natures owne hande painted,
Haſte thou, the Maſter Miſtris of my paſſion,
A womans gentle hart but not acquainted
With ſhifting change as is falſe womens faſhion,
An eye more bright then theirs,leſſe falſe in rowling:
Gilding the obiect where-vpon it gazeth,
A man in hew all Hews in his controwling,
Which ſteales mens eyes and womens ſoules amaſeth,
And for a woman wert thou firſt created,
Till nature as ſhe wrought thee fell a dotinge,
And by addition me of thee defeated,
By adding one thing to my purpoſe nothing.
But ſince ſhe prickt thee out for womens pleaſure,
Mine be thy loue and thy loues vſe their treaſure.


 




 

