---
title: "Shakespeare Sonnet 27: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 27 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 27



Weary with toil, I haste me to my bed,
The dear repose for limbs with travel tired;
But then begins a journey in my head
To work my mind, when body’s work’s expired:
For then my thoughts–from far where I abide–
Intend a zealous pilgrimage to thee,
And keep my drooping eyelids open wide,
Looking on darkness which the blind do see:
Save that my soul’s imaginary sight
Presents thy shadow to my sightless view,
Which, like a jewel hung in ghastly night,
Makes black night beauteous, and her old face new.
Lo! thus, by day my limbs, by night my mind,
For thee, and for myself, no quiet find.




Read Sonnet 27 in Easy, Modern English:


Weary from travelling, I hasten to my bed – 
that welcome place of rest for limbs tired out from travel. 
But then another journey begins in my head 
that puts my mind to work after my body’s work has ended; 
because my mind begins another, arduous, trip, 
from far away from home, to where you are, 
keeping my drooping eyelids wide open. 
It makes them stare at darkness, as blind people do, 
except that my imagination makes me see your image, 
that hangs like a jewel in the black night 
and makes it beautiful, transforming its old face to a young one. 
Look, now! Because of you, neither my limbs by day, nor my mind by night, 
enjoy any rest.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 27










Sonnet 27 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 27, as published in Shakespeare’s 1609 Quarto:


WEary with toyle,I haſt me to my bed ,
The deare repoſe for lims with trauail tired,
But then begins a iourny in my head
To worke my mind,when boddies work’s expired.
For then my thoughts(from far where I abide)
Intend a zelous pilgrimage to thee,
And keepe my drooping eye-lids open wide,
Looking on darknes which the blind doe ſee.
Saue that my ſoules imaginary ſight
Preſents their ſhaddoe to my ſightles view,
Which like a iewell(hunge in gaſtlynight)
Makes blacke night beautious,and her old face new.
Loe thus by day my lims,by night my mind,
For thee,and for my ſelfe,noe quiet finde.






 


Interested in Shakespeare’s sonnet 27? If so you can get some additional free information by visiting our friends over at 
PoemAnalysis to read their analysis of sonnet 27
.


 





