---
title: "Shakespeare Sonnet 127: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 127 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 127



In the old age black was not counted fair,
Or if it were, it bore not beauty’s name;
But now is black beauty’s successive heir,
And beauty slandered with a bastard shame:
For since each hand hath put on Nature’s power,
Fairing the foul with Art’s false borrowed face,
Sweet beauty hath no name, no holy bower,
But is profaned, if not lives in disgrace.
Therefore my mistress’ eyes are raven black,
Her eyes so suited, and they mourners seem
At such who, not born fair, no beauty lack,
Sland’ring creation with a false esteem:
Yet so they mourn becoming of their woe,
That every tongue says beauty should look so.




Read Sonnet 127 in Easy, Modern English:


In ancient times a dark complexion wasn’t considered beautiful, 
or if anyone thought so they never said it. 
But now being dark is legitimately beautiful 
and it’s become less legitimate to call being fair-skinned beautiful in itself 
because these days anyone can take on the power that used to belong only to nature, 
and even unattractive people can make themselves beautiful with makeup. 
True beauty doesn’t exist anymore, has no special place: 
it has become devalued, even disgraced. 
And so, my mistress’ eyes are raven black – 
well suited to current fashion – seeming to be in mourning 
for those who are not naturally beautiful 
but insult nature by making themselves beautiful. 
But her eyes are so beautiful in their sadness that everyone is saying 
that that’s how beauty should look.



