---
title: "Shakespeare Sonnet 74: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 74 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 74



But be contented when that fell arrest
Without all bail shall carry me away,
My life hath in this line some interest,
Which for memorial still with thee shall stay.
When thou reviewest this, thou dost review
The very part was consecrate to thee:
The earth can have but earth, which is his due;
My spirit is thine, the better part of me:
So then thou hast but lost the dregs of life,
The prey of worms, my body being dead;
The coward conquest of a wretch’s knife,
Too base of thee to be remembered.
The worth of that is that which it contains,
And that is this, and this with thee remains.




Read Sonnet 74 in Easy, Modern English:


But be contented when that dreadful arrest 
takes me away to where there is no bail. 
My life will continue to some extent in this verse, 
which will stay with you as a memorial. 
When you read it again you will be reading again 
the very thing about me that was dedicated to you. 
The earth can have only the earth in me, which is what I owe it. 
My spirit, the better part of me, is yours, 
which means that you will only have lost the dregs of my life, 
the food of worms, preying on my dead body, 
the conquest of the cowardly knife of that wretch, Death, 
too dire to be remembered by you. 
The value of that body is only what it contains, 
and that is this poem, and it will stay with you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 74










Sonnet 74 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 74, as published in Shakespeare’s 1609 Quarto:


BVt be contented when that fell areſt,
With out all bayle ſhall carry me away,
My life hath in this line ſome intereſt,
Which for memoriall ſtill with thee ſhall ſtay.
When thou reueweſt this,thou doeſt reuew,
The very part was conſecrate to thee,
The earth can haue but earth,which is his due,
My ſpirit is thine the better part of me,
So then thou haſt but loſt the dregs of life,
The pray of wormes,my body being dead,
The coward conqueſt of a wretches knife,
To baſe of thee to be remembred,
The worth of that,is that which it containes,
And that is this, and this with thee remaines.






 



