---
title: "Shakespeare Sonnet 93: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 93 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 93



So shall I live, supposing thou art true,
Like a deceived husband; so love’s face
May still seem love to me, though altered new;
Thy looks with me, thy heart in other place:
For there can live no hatred in thine eye,
Therefore in that I cannot know thy change.
In many’s looks, the false heart’s history
Is writ in moods, and frowns, and wrinkles strange.
But heaven in thy creation did decree
That in thy face sweet love should ever dwell;
Whate’er thy thoughts, or thy heart’s workings be,
Thy looks should nothing thence, but sweetness tell.
How like Eve’s apple doth thy beauty grow,
If thy sweet virtue answer not thy show.




Read Sonnet 93 in Easy, Modern English:


So I’ll just go on like that, assuming, 
like a deceived husband, that you’re faithful. 
If I do that your face may still seem to show me that you love me, 
even though you don’t. 
Your looks will reassure me even though your heart is somewhere else. 
I would never be able to tell the difference 
because your eyes could never show hatred. 
With many people a false heart is shown by 
a moody expression – frowns and strange wrinkles 
but when heaven created you it decreed that 
your face would always express sweet love – 
that whatever your thoughts or the workings of your heart may be 
your looks would never show anything but sweetness. 
Your beauty is much the same as Eve’s apple 
when your level of sweet virtue doesn’t match your looks.




Listen to Sir John Gielgud read Shakespeare’s sonnet 93










Sonnet 93 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 93, as published in Shakespeare’s 1609 Quarto:


SO ſhall I liue,ſuppoſing thou art true,
Like a deceiued husband,ſo loues face,
May ſtill ſeem loue to me,though alter’d new:
Thy lookes with me,thy heart in other place.
For their can liue no hatred in thine eye,
Therefore in that I cannot know thy change,
In manies lookes,the falce hearts hiſtory
Is writ in moods and frounes and wrinckles ſtrange.
But heauen in thy creation did decree,
That in thy face ſweet loue ſhould euer dwell,
What ere thy thoughts,or thy hearts workings be,
Thy lookes ſhould nothing thence,but ſweetneſſe tell.
How like Eaues apple doth thy beauty grow,
If thy fweet vertue anſwere not thy ſhow.




 



