---
title: "Shakespeare Sonnet 43: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 43 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 43



When most I wink, then do mine eyes best see,
For all the day they view things unrespected;
But when I sleep, in dreams they look on thee,
And darkly bright, are bright in dark directed.
Then thou, whose shadow shadows doth make bright,
How would thy shadow’s form form happy show
To the clear day with thy much clearer light,
When to unseeing eyes thy shade shines so!
How would, I say, mine eyes be blessed made
By looking on thee in the living day,
When in dead night thy fair imperfect shade
Through heavy sleep on sightless eyes doth stay!
All days are nights to see till I see thee,
And nights bright days when dreams do show thee me.




Read Sonnet 43 in Easy, Modern English:


It’s when I’m most soundly asleep that my eyes best see 
because all day long they are looking at things that aren’t significant; 
but when I’m asleep they see you in dreams and glitter brightly, 
directed to your bright image in the dark. 
So how would you, whose very shadow brightens the dark, 
appear in daylight with your even brighter light, 
when your shadow shines so brightly to unseeing eyes? 
How would my eyes be blessed 
by seeing you in the full daylight 
when they already look at your beautiful image 
when sleep lies heavy upon them? 
Every day is a dark night until I’m able to see you 
and the nights are bright days when I see you in my dreams.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 43










Sonnet 43 as Originally Published in The 1609 Quarto


When moſt I winke then doe mine eyes beſt ſee,
For all the day they view things vnreſpected,
But when I ſleepe,in dreames they looke on thee,
And darkely bright,are bright in darke directed.
Then thou whoſe ſhaddow ſhaddowes doth make bright,
How would thy ſhadowes forme,forme happy ſhow,
To the cleere day with thy much cleerer light,
When to vn-ſeeing eyes thy ſhade ſhines ſo?
How would (I ſay )mine eyes be bleſſed made,
By looking on thee in the liuing day ?
When in dead night their faire imperfect ſhade,
Through heauy ſleepe on ſightleſſe eyes doth ſtay?
All dayes are nights to ſee till I ſee thee,
And nights bright daies when dreams do ſhew thee me.






 



