---
title: "Shakespeare Sonnet 144: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 144 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 144



Two loves I have of comfort and despair,
Which like two spirits do suggest me still:
The better angel is a man right fair,
The worser spirit a woman coloured ill.
To win me soon to hell, my female evil,
Tempteth my better angel from my side,
And would corrupt my saint to be a devil,
Wooing his purity with her foul pride.
And whether that my angel be turned fiend,
Suspect I may, yet not directly tell;
But being both from me, both to each friend,
I guess one angel in another’s hell:
Yet this shall I ne’er know, but live in doubt,
Till my bad angel fire my good one out.




Read Sonnet 144 in Easy, Modern English:


I love two people: one brings me comfort, the other despair. 
Like two angels, they’re always suggesting things to me. 
The good angel is a fair-haired man; 
the bad one is a dark complexioned woman. 
To take me swiftly into hell, my evil female 
tempts my good angel away from me, 
trying to turn him into a devil, 
corrupting him with her evil self-assurance. 
And whether that angel has indeed turned into a fiend 
is something I suspect but can’t be sure about. 
But since they are both away from me and friends with each other 
I’m guessing that one angel is inside the other’s hell. 
I’ll never know, though, and I’ll live in doubt 
until my bad angel shoots my good one out of hell.



