---
title: "Shakespeare Sonnet 154: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 154 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 154



The little Love-god lying once asleep,
Laid by his side his heart-inflaming brand,
Whilst many nymphs that vowed chaste life to keep
Came tripping by; but in her maiden hand
The fairest votary took up that fire
Which many legions of true hearts had warmed;
And so the General of hot desire
Was, sleeping, by a virgin hand disarmed.
This brand she quenched in a cool well by,
Which from Love’s fire took heat perpetual,
Growing a bath and healthful remedy,
For men diseased; but I, my mistress’ thrall,
Came there for cure and this by that I prove,
Love’s fire heats water, water cools not love.




Read Sonnet 154 in Easy, Modern English:


One day the little love god was asleep, 
having put his heart-inflaming torch down, 
while several of Diana’s maids, who had all taken vows of lifelong chastity, 
were tripping by. The most beautiful votary 
lifted the torch that had 
warmed the hearts of legions of true lovers. 
And so, the general of hot desire 
was disarmed while sleeping. 
The maid quenched the torch in a nearby cool spring 
and the spring took eternal heat from this fire of love 
and became a hot bath full of healthful qualities. 
But when I, entirely captivated by my mistress, 
went there to be cured, this is what I found: 
the fire of love heats water but water doesn’t cool love down.



