---
title: "Shakespeare Sonnet 2: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 2 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 2



When forty winters shall besiege thy brow,
And dig deep trenches in thy beauty’s field,
Thy youth’s proud livery, so gazed on now,
Will be a tatter’d weed, of small worth held:
Then being ask’d where all thy beauty lies,
Where all the treasure of thy lusty days,
To say, within thine own deep-sunken eyes,
Were an all-eating shame and thriftless praise.
How much more praise deserved thy beauty’s use,
If thou couldst answer ‘This fair child of mine
Shall sum my count and make my old excuse,’
Proving his beauty by succession thine!
This were to be new made when thou art old,
And see thy blood warm when thou feel’st it cold.




Read Sonnet 2 in Easy, Modern English


When forty winters have attacked your brow 
and wrinkled your beautiful skin, 
the pride and impressiveness of your youth, so much admired by everyone now, 
will have become a worthless, tattered weed. 
Then, when you are asked where your beauty’s gone 
and what’s happened to all the treasures you had during your youth, 
you will have to say only within your own eyes, now sunk deep in their sockets, 
where there is only a shameful confession of greed and self-obsession. 
How much more praise you would have deserved if you could have answered, 
‘This beautiful child of mine shall give an account of my life 
and show that I made no misuse of my time on earth,’ 
proving that his beauty, because he is your son, was once yours! 
This child would be new-made when you are old 
and you would see your own blood warm when you are cold.




Listen to Sir Patrick Stewart Read Shakespeare’s Sonnet 2










Sonnet 2 as Originally Published in the 1609 Quarto


Here’s the exact wording and spelling of Sonnet 2, as published in Shakespeare’s 1609 Quarto:


WHen fortie Winters ſhall beſeige thy brow,
And digge deep trenches in thy beauties field,
Thy youthes proud liuery ſo gaz’d on now,
Wil be a totter’d weed of ſmal worth held:
Then being askt,where all thy beautie lies,
Where all the treaſure of thy luſty daies;
To ſay within thine owne deepe ſunken eyes,
Were an all-eating ſhame,and thriftleſſe praiſe.
How much more praiſe deſeru’d thy beauties uſe,
If thou couldſt anſwere this faire child of mine
Shall ſum my count,and make my old excuſe
Proouing his beautie by ſucceſſion thine.
This were to be new made when thou art ould,
And ſee thy blood warme when thou feel’ſt it could.









