---
title: "Shakespeare Sonnet 39: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 39 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 39



O! How thy worth with manners may I sing,
When thou art all the better part of me?
What can mine own praise to mine own self bring?
And what is’t but mine own when I praise thee?
Even for this, let us divided live,
And our dear love lose name of single one,
That by this separation I may give
That due to thee which thou deserv’st alone.
O absence! what a torment wouldst thou prove,
Were it not thy sour leisure gave sweet leave,
To entertain the time with thoughts of love,
Which time and thoughts so sweetly doth deceive,
And that thou teachest how to make one twain,
By praising him here who doth hence remain.




Read Sonnet 39 in Easy, Modern English:


How can I proclaim your worth with due modesty 
when you are my better half? 
What could I get out of praising myself, 
and what else am I doing but praising myself when I praise you? 
For this reason we should part 
and our great love lose its common identity 
so that I can give you the praise that you deserve for yourself alone. 
Oh absence, what a torment you would be 
if it weren’t that the ill-intentioned leisure you give me 
allows me the pleasure of passing the time with thoughts of love, 
which makes it pass so swiftly. 
And that you teach me how to bring us together 
through my praising him here, while he remains elsewhere.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 39










Sonnet 39 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 39, as published in Shakespeare’s 1609 Quarto:


O how thy worth with manners may I ſinge,
When thou art all the better part of me?
What can mine owne praiſe to mine owne ſelfe bring;
And what is’t but mine owne when I praiſe thee,
Euen for this,let vs deuided liue,
And our deare loue looſe name of ſingle one,
That by this ſeperation I may giue:
That due to thee which thou deſeru’ſt alone:
Oh abſence what a torment wouldſt thou proue,
Were it not thy ſoure leiſure gaue ſweet leaue,
To entertaine the time with thoughts of loue,
VVhich time and thoughts ſo ſweetly doſt deceiue.
And that thou teacheſt how to make one twaine,
By praiſing him here who doth hence remaine.






 



