---
title: "Shakespeare Sonnet 112: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 112 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 112



Your love and pity doth th’ impression fill
Which vulgar scandal stamped upon my brow;
For what care I who calls me well or ill,
So you o’er green my bad, my good allow?
You are my all the world, and I must strive
To know my shames and praises from your tongue;
None else to me, nor I to none alive,
That my steeled sense or changes right or wrong.
In so profound abysm I throw all care
Of others’ voices, that my adder’s sense
To critic and to flatt’rer stopped are.
Mark how with my neglect I do dispense:
You are so strongly in my purpose bred
That all the world besides methinks y’are dead.




Read Sonnet 112 in Easy, Modern English:


Your love and pity compensate for 
the gossip that’s branded me 
because what do I care about being called either good or bad 
as long as you ignore the bad things about me and acknowledge the things that are good? 
You’re all the world to me and I have to try and work out 
what’s good or bad about myself from the things you say. 
No-one else matters to me and I don’t matter to anyone alive 
so it’s entirely your opinion that determines what’s right or wrong. 
I have such a profound contempt for what others say 
that my sharp senses are cut off from both criticism and flattery. 
Notice how I don’t care that the world neglects me. 
You mean so much to me that 
everyone, apart from me, thinks you’re dead.



