---
title: "Shakespeare Sonnet 98: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 98 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 98



From you have I been absent in the spring,
When proud-pied April, dress’d in all his trim,
Hath put a spirit of youth in every thing,
That heavy Saturn laughed and leapt with him.
Yet nor the lays of birds, nor the sweet smell
Of different flowers in odour and in hue,
Could make me any summer’s story tell,
Or from their proud lap pluck them where they grew:
Nor did I wonder at the lily’s white,
Nor praise the deep vermilion in the rose;
They were but sweet, but figures of delight,
Drawn after you, you pattern of all those.
Yet seemed it winter still, and you away,
As with your shadow I with these did play.




Read Sonnet 98 in Easy, Modern English:


I have been away from you during the spring 
when the impressively vivid April, in all its finery, 
instilled such a feeling of youth in everything 
that even grave Saturn laughed and leapt with it. 
Yet neither the birdsong nor the sweet smell 
of a multitude of different coloured and perfumed flowers 
could put in a summery mood 
or make me feel like picking flowers. 
Nor could I summon up any enthusiasm for the amazing whiteness of the lilies 
nor praise the deep red of the roses. 
They were only sweet images of delight 
drawn in imitation of you, the model for them all. 
It still felt like winter and with you not here 
all I did was toy with them as though they were pictures of you.



