---
title: "Shakespeare Sonnet 140: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 140 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 140



Be wise as thou art cruel; do not press
My tongue-tied patience with too much disdain;
Lest sorrow lend me words, and words express
The manner of my pity-wanting pain.
If I might teach thee wit, better it were,
Though not to love, yet, love to tell me so;
As testy sick men, when their deaths be near,
No news but health from their physicians know;
For, if I should despair, I should grow mad,
And in my madness might speak ill of thee;
Now this ill-wresting world is grown so bad,
Mad slanderers by mad ears believed be.
That I may not be so, nor thou belied,
Bear thine eyes straight, though thy proud heart go wide.




Read Sonnet 140 in Easy, Modern English:


Be as wise as you are cruel; don’t test 
my silent patience with too much disdain 
or my unhappiness may drive me to speak out, 
telling about your ruthlessness in hurting me. 
If you would allow me to advise you about an intelligent way of going about it, 
I would say it would be better to tell me you loved me even if you don’t, 
like a doctor who knows that it’s better to tell sensitive men who are near death that they are healthy. 
Because, if I start to despair I shall go mad, 
and in my madness I may speak ill of you. 
The faults of this world have become so bad that 
mad people believe the lies that mad people tell. 
To stop me from going mad and lying about you 
keep your eyes in place, even when your stubborn heart is wandering where it wants to.



