---
title: "Shakespeare Sonnet 24: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 24 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 24



Mine eye hath play’d the painter and hath steel’d,
Thy beauty’s form in table of my heart;
My body is the frame wherein ’tis held,
And perspective it is best painter’s art.
For through the painter must you see his skill,
To find where your true image pictur’d lies,
Which in my bosom’s shop is hanging still,
That hath his windows glazed with thine eyes.
Now see what good turns eyes for eyes have done:
Mine eyes have drawn thy shape, and thine for me
Are windows to my breast, where-through the sun
Delights to peep, to gaze therein on thee;
Yet eyes this cunning want to grace their art,
They draw but what they see, know not the heart.




Read Sonnet 24 in Easy, Modern English:


My eye has taken the role of the artist and engraved 
an image of your beauty on my heart. 
My body is the frame that surrounds it, 
setting its proportions in that space. 
It is through the painter that one may see how art depicts nature, 
and where the best image of anything is, 
and yours hangs in the studio of my heart, 
which has your eyes as its windows, forever. 
Now see what a good turn your eyes and mine have done each other. 
My eyes have drawn your form 
and yours are the windows of my heart, through which the sun loves to peep, 
to look at you in there. 
But eyes lack the artistry to show what lies within the heart; 
they draw only what they see and cannot know what’s in the heart.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 24










Sonnet 24 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 24, as published in Shakespeare’s 1609 Quarto:


Mine eye hath play’d the painter and hath ſteeld,
Thy beauties forme in table of my heart,
My body is the frame wherein ti’s held,
And perſpectiue it is beſt Painters art.
For through the Painter muſt you ſee his skill,
To finde where your true Image pictur’d lies,
Which in my boſomes ſhop is hanging ſtil,
That hath his windowes glazed with thine eyes:
Now ſee what good-turnes eyes for eies haue done,
Mine eyes haue drawne thy ſhape,and thine for me
Are windowes to my breſt, where-through the Sun
Delights to peepe,to gaze therein on thee
Yet eyes this cunning want to grace their art
They draw but what they ſee,know not the hart.


 




 

