---
title: "Shakespeare Sonnet 113: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 113 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 113



Since I left you, mine eye is in my mind,
And that which governs me to go about
Doth part his function, and is partly blind,
Seems seeing, but effectively is out;
For it no form delivers to the heart
Of bird, of flow’r, or shape which it doth latch.
Of his quick objects hath the mind no part,
Nor his own vision holds what it doth catch;
For if it see the rud’st or gentlest sight,
The most sweet favour or deformed’st creature,
The mountain, or the sea, the day, or night,
The crow, or dove, it shapes them to your feature.
Incapable of more, replete with you,
My most true mind thus makes mine untrue.




Read Sonnet 113 in Easy, Modern English:


Since I left you I’ve been preoccupied with my thoughts, and my eyes, 
that allow me to see what’s going on around me, 
function only partly, so that I’m half blind. 
I have some vision but it’s unfocused 
because it can’t define any form, 
such as birds, flowers or anything else it lands on. 
My mind can’t grasp anything my eyes show it, 
nor can my vision retain anything it captures. 
That’s because whatever it sees – the most crude or gentlest sight, 
the most sweetly-formed or the most deformed creature, 
the mountain or the sea, the day or the night, 
the crow or the dove – my vision shapes it to resemble you. 
Incapable of doing anything else, and filled with your image, 
my faithful mind makes me see everything unfaithfully.



