---
title: "Shakespeare Sonnet 101: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 101 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 101



O truant Muse what shall be thy amends
For thy neglect of truth in beauty dyed?
Both truth and beauty on my love depends;
So dost thou too, and therein dignified.
Make answer Muse: wilt thou not haply say,
‘Truth needs no colour, with his colour fixed;
Beauty no pencil, beauty’s truth to lay;
But best is best, if never intermixed’?
Because he needs no praise, wilt thou be dumb?
Excuse not silence so, for’t lies in thee
To make him much outlive a gilded tomb
And to be praised of ages yet to be.
Then do thy office, Muse; I teach thee how
To make him seem, long hence, as he shows now.




Read Sonnet 101 in Easy, Modern English:


Oh truant Muse, how are you going to make up for 
neglecting the perfect combination of truth and beauty? 
Both truth and beauty depend on my beloved, 
as you also do, and are dignified by that. 
Come on, answer, Muse. Perhaps you’ll say that 
truth doesn’t need any ornament, 
being already attached to beauty; 
that beauty needs no poet’s pen to advertise it, and that the best things don’t need any help. 
But are you going to be silent just because my beloved needs no praise? 
You can’t excuse your silence on those grounds because you have the ability 
to make him outlive a gilded tomb 
to be praised by generations yet to come. 
Then do your job, Muse. I’m showing you how 
to make him as vivid in the far distant future as he is now.



