---
title: "Shakespeare Sonnet 45: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 45 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 45



The other two, slight air, and purging fire
Are both with thee, wherever I abide;
The first my thought, the other my desire,
These present-absent with swift motion slide.
For when these quicker elements are gone
In tender embassy of love to thee,
My life, being made of four, with two alone
Sinks down to death, oppress’d with melancholy;
Until life’s composition be recured
By those swift messengers return’d from thee,
Who even but now come back again, assured
Of thy fair health, recounting it to me:
This told, I joy; but then no longer glad,
I send them back again, and straight grow sad.




Sonnet 45 in modern English


The other two elements, light air and purging fire, 
are with you, wherever I may be. 
The first is my thought, the other my desire. 
They slide easily between us. 
When those faster elements are away 
on a loving mission to you 
my life, which is made of four, left with only two, 
sinks downwards to death with depression 
until it’s revived 
by the return from you of those swift messengers. 
Even now, making sure that you’re in good health, 
they’ve just returned to tell me that. 
Hearing that I rejoice but then I become sad once more 
and send them back again and immediately fall into a depression.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 45










Sonnet 45 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 45, as published in Shakespeare’s 1609 Quarto:


THe other two,ſlight ayre,and purging fire,
Are both with thee,where euer I abide,
The firſt my thought,the other my deſire,
Theſe preſent abſent with ſwift motion ſlide.
For when theſe quicker Elements are gone
In tender Embaſſie of loue to thee,
My life being made of foure,with two alone,
Sinkes downe to death,oppreſt with melancholie.
Vntill liues compoſition be recured,
By thoſe ſwift meſſengers return’d from thee,
Who euen but now come back againe aſſured,
Of their faire health,recounting it to me.
This told,I ioy,but then no longer glad,
I ſend them back againe and ſtraight grow ſad.






 



