---
title: "Shakespeare Sonnet 19: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 19 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 19



Devouring Time, blunt thou the lion’s paws,
And make the earth devour her own sweet brood;
Pluck the keen teeth from the fierce tiger’s jaws,
And burn the long-liv’d phoenix, in her blood;
Make glad and sorry seasons as thou fleet’st,
And do whate’er thou wilt, swift-footed Time,
To the wide world and all her fading sweets;
But I forbid thee one most heinous crime:
O! carve not with thy hours my love’s fair brow,
Nor draw no lines there with thine antique pen;
Him in thy course untainted do allow
For beauty’s pattern to succeeding men.
Yet, do thy worst old Time: despite thy wrong,
My love shall in my verse ever live young.




Read Sonnet 19 in Easy, Modern English:


Devouring Time, you may make the lion’s claws blunt 
and return all creatures to the earth from which they sprang; 
pull the teeth from the fierce tiger’s jaws, 
and destroy the phoenix in her fire. 
Do whatever you like, 
fast-running Time, 
to any beautiful fading thing in the world; 
but I forbid you to commit one heinous crime: 
oh don’t cut into my love’s beautiful brow, 
nor draw wrinkles there with your insane pen. 
As you go on your destructive course 
spare him as a pattern of beauty for posterity. 
But, do your worst, old Time. Whatever harm you do 
my love will remain young forever in my poetry.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 19










Sonnet 19 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 19, as published in Shakespeare’s 1609 Quarto:


DEuouring time blunt thou the Lyons pawes,
And make the earth deuoure her owne ſweet brood,
Plucke the keene teeth from the fierce Tygers yawes,
And burne the long liu’d Phœnix in her blood,
Make glad and ſorry ſeaſons as thou fleet’ſt,
And do what ere thou wilt ſwift-footed time
To the wide world and all her fading ſweets:
But I forbid thee one moſt hainous crime,
O carue not with thy howers my loues faire brow,
Nor draw noe lines there with thine antique pen,
Him in thy courſe vntainted doe allow,
For beauties patterne to ſucceding men.
Yet doe thy worſt ould Time diſpight thy wrong,
My loue ſhall in my verſe euer liue young.


 




Interested in Shakespeare’s sonnet 19? If so you can get some additional free information by visiting our friends over at 
PoemAnalysis to read their analysis of sonnet 19
.


 




 

