---
title: "Shakespeare Sonnet 87: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 87 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 87



Farewell! thou art too dear for my possessing,
And like enough thou know’st thy estimate,
The charter of thy worth gives thee releasing;
My bonds in thee are all determinate.
For how do I hold thee but by thy granting?
And for that riches where is my deserving?
The cause of this fair gift in me is wanting,
And so my patent back again is swerving.
Thy self thou gavest, thy own worth then not knowing,
Or me to whom thou gav’st it else mistaking;
So thy great gift, upon misprision growing,
Comes home again, on better judgement making.
Thus have I had thee, as a dream doth flatter,
In sleep a king, but waking no such matter.




Read Sonnet 87 in Easy, Modern English:


Farewell, you’re too valuable for me to own. 
I’m sure you know your worth. 
The extent of that allows you to be released from me: 
you have broken the bonds between us. 
For how can I hold on to you without your consent, 
and how have I come to deserve such riches? 
Reasons for receiving such a beautiful gift are lacking 
so my right to own you is reverting back to you. 
You gave yourself to me without knowing your value, 
or else you mistook me. 
So your great gift, based on misunderstanding, 
is returned now that you’re capable of making better judgments. 
I have had you as in a flattering dream, 
thinking of myself as a king while I slept, but on waking, finding I was no such thing.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 87










Sonnet 87 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 87, as published in Shakespeare’s 1609 Quarto:


FArewell thou art too deare for my poſſeſſing,
And like enough thou knowſt thy eſtimate,
The Charter of thy worth giues thee releaſing:
My bonds in thee are all determinate.
For how do I hold thee but by thy granting,
And for that ritches where is my deſeruing?
The cauſe of this faire guift in me is wanting,
And ſo my pattent back againe is ſweruing.
Thy ſelfe thou gau’ſt,thy owne worth then not knowing,
Or mee to whom thou gau’ſt it,elſe miſtaking,
So thy great guift vpon miſpriſion growing,
Comes home againe,on better iudgement making.
Thus haue I had thee as a dreame doth flatter,
In ſleepe a King,but waking no ſuch matter.




 





