---
title: "Shakespeare Sonnet 28: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 28 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 28



How can I then return in happy plight,
That am debarred the benefit of rest?
When day’s oppression is not eas’d by night,
But day by night and night by day oppress’d,
And each, though enemies to either’s reign,
Do in consent shake hands to torture me,
The one by toil, the other to complain
How far I toil, still farther off from thee.
I tell the day, to please him thou art bright,
And dost him grace when clouds do blot the heaven:
So flatter I the swart-complexion’d night,
When sparkling stars twire not thou gild’st the even.
But day doth daily draw my sorrows longer,
And night doth nightly make grief’s length seem stronger.




Read Sonnet 28 in Easy, Modern English:


So how can I, who am prevented from the benefit of rest, 
return in a contented frame of mind 
when the oppression of the day isn’t relieved at night, 
but the day is oppressed by the night and the night oppressed by the day? 
And although they are natural enemies 
they shake hands on an agreement to torture me, 
the one with travel, the other to dwell on thoughts 
of how far away from you I have travelled. 
To please the day I tell him that your brightness lights him up 
when clouds conceal the sky, 
and I flatter the black-complexioned night 
that you brighten the evening sky when the sparkling stars are not shining. 
But day prolongs my sorrows daily, 
and night makes my grief grow stronger nightly.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 28










Sonnet 28 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 28, as published in Shakespeare’s 1609 Quarto:


HOw can I then returne in happy plight
That am debard the benefit of reſt?
When daies oppreſſion is not eazd by night,
But day by night and night by day opreſt.
And each(though enimes to ethers raigne)
Doe in conſent ſhake hands to torture me,
The one by toyle,the other to complaine
How far I toyle,ſtill farther off from thee.
I tell the Day to pleaſe him thou art bright,
And do’ſt him grace when clouds doe blot the heauen:
So flatter I the ſwart complexiond night,
When ſparkling ſtars twire not thou guil’ſt th’ eauen.
But day doth daily draw my ſorrowes longer,
And night doth nightly make greefes length ſeeme ſtronger






 



