---
title: "Shakespeare Sonnet 36: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 36 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 36



Let me confess that we two must be twain,
Although our undivided loves are one:
So shall those blots that do with me remain,
Without thy help, by me be borne alone.
In our two loves there is but one respect,
Though in our lives a separable spite,
Which though it alter not love’s sole effect,
Yet doth it steal sweet hours from love’s delight.
I may not evermore acknowledge thee,
Lest my bewailed guilt should do thee shame,
Nor thou with public kindness honour me,
Unless thou take that honour from thy name:
But do not so, I love thee in such sort,
As thou being mine, mine is thy good report.




Read Sonnet 36 in Easy, Modern English:


Let me admit that we two have to part 
even though we are united in love. 
By parting those disgraces that we’ve brought on ourselves 
can be born by me alone, without any help from you. 
In our love for each other there is a single mind, 
even though circumstances, which force us apart, 
can’t destroy our love, but rob us of those sweet hours of mutual pleasure. 
I can’t ever openly acknowledge you again 
because my wretched guilt would bring shame on you. 
Nor can you honour me with public notice 
without dishonouring yourself. 
So don’t do that: my love for you is such that 
I value your reputation as though it were my own.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 36










Sonnet 36 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 36, as published in Shakespeare’s 1609 Quarto:


LEt me confeſſe that we two muſt be twaine,
Although our vndeuided loues are one:
So ſhall thoſe blots that do with me remaine,
Without thy helpe, by me be borne alone.
In our two loues there is but one reſpect,
Though in our liues a ſeperable ſpight,
Which though it alter not loues ſole effect,
Yet doth it ſteal ſweete houres from loues delight,
I may not euer-more acknowledge thee,
Leaſt my bewailed guilt ſhould do thee ſhame,
Nor thou with publike kindneſſe honour me,
Vnleſſe thou take that honour from thy name:
But doe not ſo,I loue thee in ſuch ſort,
As thou being mine,mine is thy good report.






 



