---
title: "Shakespeare Sonnet 106: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 106 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 106



When in the chronicle of wasted time
I see descriptions of the fairest wights,
And beauty making beautiful old rhyme,
In praise of ladies dead and lovely knights,
Then, in the blazon of sweet beauty’s best,
Of hand, of foot, of lip, of eye, of brow,
I see their antique pen would have express’d
Even such a beauty as you master now.
So all their praises are but prophecies
Of this our time, all you prefiguring;
And for they looked but with divining eyes,
They had not skill enough your worth to sing:
For we, which now behold these present days,
Have eyes to wonder, but lack tongues to praise.




Read Sonnet 106 in Easy, Modern English:


When I come across descriptions of 
extremely beautiful people in historical records 
and the beautiful poems 
in praise of ladies long dead and lovely knights inspired by them then, 
in that catalogue of that great beauty – 
their hands, feet, lips, eyes, foreheads – 
it strikes me that they are trying to express just the kind of beauty that you have. 
So all the praise of these writers is only a prophecy of our time, 
all of it anticipating you. 
And unless they had had the power of prophesy
they wouldn’t have had enough skill to depict your worth. 
We who live in the present time 
are able to be overwhelmed by your beauty but don’t have the skill to describe it.


 



