---
title: "Shakespeare Sonnet 26: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 26 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 26



Lord of my love, to whom in vassalage
Thy merit hath my duty strongly knit,
To thee I send this written embassage,
To witness duty, not to show my wit:
Duty so great, which wit so poor as mine
May make seem bare, in wanting words to show it,
But that I hope some good conceit of thine
In thy soul’s thought, all naked, will bestow it:
Till whatsoever star that guides my moving,
Points on me graciously with fair aspect,
And puts apparel on my tottered loving,
To show me worthy of thy sweet respect:
Then may I dare to boast how I do love thee;
Till then, not show my head where thou mayst prove me.




Read Sonnet 26 in Easy,  Modern English:


Lord of my love, whose merit has ensured 
that I will serve you loyally, 
I send this written message to you 
to demonstrate my devotion, not my intellectual skills – 
devotion so vast that my skill seems bare and meaningless by comparison, 
because I can’t find the words to express it. 
I nevertheless retain the hope that some imaginative inspiration deep in your heart 
will bestow some meaning on my completely bare love. 
Only when whichever star that guides my actions 
looks on me with a benign and gracious blessing, 
and puts clothes on my ragged love 
so that I will appear worthy of your respect, 
will I dare to proclaim my love for you. 
Until then I dare not reveal myself for you to put it to the test.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 26










Sonnet 26 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 26, as published in Shakespeare’s 1609 Quarto:


LOrd of my loue,to whome in vaſſalage
Thy merrit hath my dutie ſtrongly knit;
To thee I ſend this written ambaſſage
To witneſſe duty, not to ſhew my wit.
Duty ſo great, which wit ſo poore as mine
May make ſeeme bare,in wanting words to ſhew it;
But that I hope ſome good conceipt of thine
In thy ſoules thought( all naked ) will beſtow it:
Til whatſoeuer ſtar that guides my mouing,
Points on me gratiouſly with faire aſpect,
And puts apparrell on my tottered louing,
To ſhow me worthy of their ſweet reſpect,
Then may I dare to boaſt how I doe loue thee,
Til then,not ſhow my head where thou maiſt proue me.






 



