---
title: "Shakespeare Sonnet 70: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 70 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 70



That thou art blamed shall not be thy defect,
For slander’s mark was ever yet the fair;
The ornament of beauty is suspect,
A crow that flies in heaven’s sweetest air.
So thou be good, slander doth but approve
Thy worth the greater, being woo’d of time;
For canker vice the sweetest buds doth love,
And thou present’st a pure unstained prime.
Thou hast pass’d by the ambush of young days,
Either not assail’d or victor being charged;
Yet this thy praise cannot be so thy praise,
To tie up envy evermore enlarged:
If some suspect of ill mask’d not thy show,
Then thou alone kingdoms of hearts shouldst owe.




Read Sonnet 70 in Easy, Modern English:


That some people find fault with you won’t be counted as a defect, or a blot on your character, 
because those who are beautiful have always been the target of slanderous tongues. 
Suspicion always accompanies beauty – 
a crow taints the air of heaven by flying through it. 
If you could only remain good your critics would recognise 
that your worth is greater than they had thought, in that time has bestowed gifts on you, 
because vice, which is like a canker, often attacks the sweetest buds; 
and you present to the world a springtime of youth which is chaste and unsullied. 
You have bypassed the temptations of youth, 
either not having been attacked by temptation or by having been victorious when assaulted by it. 
Yet, this praise of you cannot forever be so powerful as to restrain envy, which is perpetually at liberty. 
If suspicion of sin did not cover your appearance 
you would reign supreme in love over multitudes of people.




Watch Molly Vincent read Shakespeare’s sonnet 70










Sonnet 70 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 70, as published in Shakespeare’s 1609 Quarto:


THat thou art blam’d ſhall not be thy defect,
For ſlanders marke was euer yet the faire,
The ornament of beauty is ſuſpect,
A Crow that flies in heauens ſweeteſt ayre.
So thou be good,ſlander doth but approue,
Their worth the greater being woo’d of time,
For Canker vice the ſweeteſt buds doth loue,
And thou preſent’ſt a pure vnſtayined prime.
Thou haſt paſt by the ambuſh of young daies,
Either not aſſayld,or victor beeing charg’d,
Yet this thy praiſe cannot be ſoe thy praiſe,
To tye vp enuy,euermore inlarged,
If ſome ſuſpect of ill maskt not thy ſhow,
Then thou alone kingdomes of hearts ſhouldſt owe.




 



