---
title: "Shakespeare Sonnet 65: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 65 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 65



Since brass, nor stone, nor earth, nor boundless sea,
But sad mortality o’ersways their power,
How with this rage shall beauty hold a plea,
Whose action is no stronger than a flower?
O! how shall summer’s honey breath hold out,
Against the wrackful siege of battering days,
When rocks impregnable are not so stout,
Nor gates of steel so strong but Time decays?
O fearful meditation! where, alack,
Shall Time’s best jewel from Time’s chest lie hid?
Or what strong hand can hold his swift foot back?
Or who his spoil of beauty can forbid?
O! none, unless this miracle have might,
That in black ink my love may still shine bright.




Read Sonnet 65 in Easy, Modern English:


Since neither brass nor stone nor earth nor the limitless ocean 
can resist the power of mortality, 
how could beauty have a chance of resisting its force 
when beauty’s power is no stronger than that of a flower? 
Oh, how could the sweet-smelling breath of summer hold out 
against the fierce attack of war-like time 
when invulnerable rocks are not strong enough, 
nor steel gates firm enough, to resist its decaying force? 
Oh, terrifying thought! Where, oh where 
could time’s finest jewel be hidden from time itself? 
Or what strong hand could slow time down? 
Or who is there to forbid its destruction of your beauty? 
Oh, no-one unless this miracle should happen: 
that the one I love will continue to shine brightly in black ink.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 65










Sonnet 65 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 65, as published in Shakespeare’s 1609 Quarto:


SInce braſſe,nor ſtone,nor earth,nor boundleſſe ſea,
But ſad mortallity ore-ſwaies their power,
How with this rage ſhall beautie hold a plea,
Whoſe action is no ſtronger then a flower?
O how ſhall ſummers hunny breath hold out,
Againſt the wrackfull ſiedge of battring dayes,
When rocks impregnable are not ſo ſtoute ,
Nor gates of ſteele ſo ſtrong but time decayes?
O fearfull meditation , where alack,
Shall times beſt Iewell from times cheſt lie hid?
Or what ſtrong hand can hold his ſwift foote back,
Or who his ſpoile or beautie can forbid ?
O none,vnleſſe this miracle haue might,
That in black inck my loue may ſtill ſhine bright.




 





