---
title: "Shakespeare Sonnet 146: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 146 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 146



Poor soul, the centre of my sinful earth,
Thrall to these rebel powers that thee array,
Why dost thou pine within and suffer dearth,
Painting thy outward walls so costly gay?
Why so large cost, having so short a lease,
Dost thou upon thy fading mansion spend?
Shall worms, inheritors of this excess,
Eat up thy charge? Is this thy body’s end?
Then soul, live thou upon thy servant’s loss,
And let that pine to aggravate thy store;
Buy terms divine in selling hours of dross;
Within be fed, without be rich no more:
So shall thou feed on Death, that feeds on men,
And Death once dead, there’s no more dying then.




Read Sonnet 146 in Easy, Modern English:


Poor soul, right at the centre of your sinful body, 
slave to its rebellious worldliness, ever attacking you. 
Why do you dwindle away inside, suffering starvation, 
while decorating your outside walls with such expensive paint? 
Why such expenditure when the lease 
on your crumbling mansion is so short? 
Are you doing it so that worms can inherit this excess 
and eat up what you’ve spent? Is that the purpose of your body? 
Instead, live on by starving your body 
and let it dwindle away while you enrich yourself. 
Gain spiritual wealth by discarding worthless worldly things. 
Feed the inner self and allow your body to be poor. 
In that way you’ll eat up death, that feeds on men, 
and once death is dead there will be no more dying.



