---
title: "Shakespeare Sonnet 90: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 90 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 90



Then hate me when thou wilt; if ever, now;
Now, while the world is bent my deeds to cross,
Join with the spite of fortune, make me bow,
And do not drop in for an after-loss:
Ah! do not, when my heart hath ‘scaped this sorrow,
Come in the rearward of a conquered woe;
Give not a windy night a rainy morrow,
To linger out a purposed overthrow.
If thou wilt leave me, do not leave me last,
When other petty griefs have done their spite,
But in the onset come: so shall I taste
At first the very worst of fortune’s might;
And other strains of woe, which now seem woe,
Compared with loss of thee, will not seem so.




Read Sonnet 90 in Easy, Modern English:


So hate me whenever it pleases you, but if you are going to, 
do it now – now while the world is determined to frustrate all my actions. 
Join with the spitefulness of Fortune, make me bow under the burden, 
but don’t come and bite me from behind 
just when I’ve got over this particular blow. 
Don’t be a rainy morning after a stormy night,
 drawing out the defeat that you’re determined to impose on me. 
If you’re going to go, don’t leave it to the end, 
when other small sorrows have done their worst 
but do it at the beginning 
so that I’ll experience the very worst misfortune first. 
Then other painful things that are hurting now 
won’t seem so bad compared with the loss of you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 90










Sonnet 90 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 90, as published in Shakespeare’s 1609 Quarto:


THen hate me when thou wilt, if euer,now,
Now while the world is bent my deeds to croſſe,
Ioyne with the ſpight of fortune,make me bow,
And doe not drop in for an after loſſe:
Ah doe not,when my heart hath ſcapte this ſorrow,
Come in the rereward of a conquerd woe,
Giue not a windy night a rainie morrow,
To linger out a purpoſd ouer-throw.
If thou wilt leaue me, do not leaue me laſt,
When other pettie griefes haue done their ſpight,
But in the onſet come,ſo ſtall I taſte
At firſt the very worſt of fortunes might.
And other ſtraines of woe, which now ſeeme woe,
Compar’d with loſſe of thee,will not ſeeme ſo.




 





