---
title: "Shakespeare Sonnet 59: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 59 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 59



If there be nothing new, but that which is
Hath been before, how are our brains beguil’d,
Which labouring for invention bear amiss
The second burthen of a former child.
Oh that record could with a backward look,
Even of five hundred courses of the sun,
Show me your image in some antique book,
Since mind at first in character was done,
That I might see what the old world could say
To this composed wonder of your frame;
Whether we are mended, or where better they,
Or whether revolution be the same.
Oh sure I am the wits of former days,
To subjects worse have given admiring praise.




Read Sonnet 59 in Easy, Modern English:


If there really is nothing new and everything that exists 
has always existed then we’re misleading ourselves 
in struggling to create something new and will always end up, 
after all that hard work, with imitations of imitations. 
Oh, that I could look back through the records, 
even as far as five hundred years, 
to find a representation of you in some ancient book 
from the time when human thoughts were first being put down in writing 
to see what the ancient world had to say 
about the wonder of your physical appearance. 
Then I would see whether modern or ancient writers are better, or just the same. 
Oh I’m sure that the writers of earlier times 
have given immense praise to worse subjects than you are.




Listen to Dame Penelope Keith read Shakespeare’s sonnet 59










Sonnet 59 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 59, as published in Shakespeare’s 1609 Quarto:


IF their bee nothing new,but that which is,
Hath beene before , how are our braines beguild,
Which laboring for inuention beare amiſſe
The ſecond burthen of a former child ?
Oh that record could with a back-ward looke,
Euen of fiue hundreth courſes of the Sunne,
Show me your image in ſome antique booke,
Since minde at firſt in carrecter was done.
That I might ſee what the old world could ſay,
To this compoſed wonder of your frame,
Whether we are mended,or where better they,
Or whether reuolution be the ſame.
Oh ſure I am the wits of former daies,
To ſubiects worſe haue giuen admiring praiſe.




 





