---
title: "Shakespeare Sonnet 33: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 33 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 33



Full many a glorious morning have I seen
Flatter the mountain tops with sovereign eye,
Kissing with golden face the meadows green,
Gilding pale streams with heavenly alchemy;
Anon permit the basest clouds to ride
With ugly rack on his celestial face,
And from the forlorn world his visage hide,
Stealing unseen to west with this disgrace:
Even so my sun one early morn did shine,
With all triumphant splendour on my brow;
But out, alack, he was but one hour mine,
The region cloud hath mask’d him from me now.
Yet him for this my love no whit disdaineth;
Suns of the world may stain when heaven’s sun staineth.




Read Sonnet 33 in Easy, Modern English:


I’ve seen so many glorious mornings 
when the royal sun lights up the mountaintops, 
kisses the green meadows with its golden face, 
and makes streams shine with its celestial magic. 
But then it allows the blackest clouds to ride 
across its heavenly face with ugly gloom, 
and hides that face from the dull world, 
sneaking off to the west with the disgrace of it. 
In just that way my sun shone on my brow early one morning 
with that same triumphant splendor. 
But alas, he was mine for only one hour: 
the dark clouds have hidden him from me now. 
Yet, my love doesn’t condemn him in the least. 
The suns of humanity may show their faults if the sun of heaven does.




Alongside the above explanation of sonnet 33, the Centuries of SummerDays project put Shakespeare’s sonnets into modern, singer/songwriter-inspired music. Below is their take on sonnet 33:








Listen to Sir Patrick Stewart read Shakespeare’s sonnet 33










Sonnet 33 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 33, as published in Shakespeare’s 1609 Quarto:


FVll many a glorious morning haue I ſeene,
Flatter the mountaine tops with ſoueraine eie,
Kiſſing with golden face the meddowes greene;
Guilding pale ſtreames with heauenly alcumy:
Anon permit the baſeſt cloudes to ride,
With ougly rack on his celeſtiall face,
And from the for-lorne world his viſage hide
Stealing un’eene to weſt with this diſgrace:
Euen ſo my Sunne one early morne did ſhine,
With all triumphant ſplendor on my brow,
But out alack,he was but one houre mine,
The region cloude hath mask’d him from me now.
Yet him for this,my loue no whit diſdaineth,
Suns of the world may ſtaine,whë heauens ſun ſtainteh.






 



