---
title: "Shakespeare Sonnet 79: Original & Modern Translation"
description: "Read William Shakespeare's Sonnet 79 along with a modern English translation."
date: "2026-08-07"
categories: [Literature, Poetry, Shakespeare, English Learning]
---

# Sonnet 79



Whilst I alone did call upon thy aid,
My verse alone had all thy gentle grace;
But now my gracious numbers are decay’d,
And my sick Muse doth give an other place.
I grant, sweet love, thy lovely argument
Deserves the travail of a worthier pen;
Yet what of thee thy poet doth invent
He robs thee of, and pays it thee again.
He lends thee virtue, and he stole that word
From thy behaviour; beauty doth he give,
And found it in thy cheek: he can afford
No praise to thee, but what in thee doth live.
Then thank him not for that which he doth say,
Since what he owes thee, thou thyself dost pay.




Read Sonnet 79 in Easy, Modern English:


When I was the only one who sought inspiration from you 
it was only my verse that contained the effects of your noble grace, 
but now my inspired verses have declined 
as my muse makes room for another. 
I admit, sweet love, that such a lovely subject 
deserves the labour of a better writer. 
But whatever praise of your qualities your new poet makes, 
all he’s doing is stealing them then giving them back to you. 
He attributes virtue to you but he only got that word from observing you. 
He gives you beauty but only discovered beauty by looking at your face. 
He’s unable to offer any praise other than those things that he’s already found in you. 
So don’t be grateful for the things he says about you: 
because you’re paying for everything that he owes you.




Listen to Sir Patrick Stewart read Shakespeare’s sonnet 79










Sonnet 79 as Originally Published in The 1609 Quarto


Here’s the exact wording and spelling of Sonnet 79, as published in Shakespeare’s 1609 Quarto:


WHilſt I alone did call vpon thy ayde,
My verſe alone had all thy gentle grace,
But now my gracious numbers are decayde,
And my ſick Muſe doth giue an other place.
I grant ( ſweet loue )thy louely argument
Deſerues the trauaile of a worthier pen,
Yet what of thee thy Poet doth inuent,
He robs thee of,and payes it thee againe,
He lends thee vertue,and he ſtole that word,
From thy behauiour,beautie doth he giue
And found it in thy cheeke: he can affoord
No praiſe to thee,but what in thee doth liue.
Then thanke him not for that which he doth ſay,
Since what he owes thee,thou thy ſelfe dooſt pay




 



