---
title: "Hamlet - Act V"
author: "William Shakespeare"
description: "Act V of Hamlet."
categories: [Literature, Classic]
format:
  html:
    page-layout: article
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 300px
    reference-location: margin
    citation-location: margin
---

# Act V

SCENE I. A churchyard.


Enter two Clowns with spades, &c.

FIRST CLOWN.
Is she to be buried in Christian burial, when she wilfully seeks her
own salvation?

SECOND CLOWN.
I tell thee she is, and therefore make her grave straight. The crowner
hath sat on her, and finds it Christian burial.

FIRST CLOWN.
How can that be, unless she drowned herself in her own defence?

SECOND CLOWN.
Why, ’tis found so.

FIRST CLOWN.
It must be _se offendendo_, it cannot be else. For here lies the point:
if I drown myself wittingly, it argues an act: and an act hath three
branches. It is to act, to do, and to perform: argal, she drowned
herself wittingly.

SECOND CLOWN.
Nay, but hear you, goodman delver,—

FIRST CLOWN.
Give me leave. Here lies the water; good. Here stands the man; good. If
the man go to this water and drown himself, it is, will he nill he, he
goes,—mark you that. But if the water come to him and drown him, he
drowns not himself. Argal, he that is not guilty of his own death
shortens not his own life.

SECOND CLOWN.
But is this law?

FIRST CLOWN.
Ay, marry, is’t, crowner’s quest law.

SECOND CLOWN.
Will you ha’ the truth on’t? If this had not been a gentlewoman, she
should have been buried out o’ Christian burial.

FIRST CLOWN.
Why, there thou say’st. And the more pity that great folk should have
countenance in this world to drown or hang themselves more than their
even Christian. Come, my spade. There is no ancient gentlemen but
gardeners, ditchers, and grave-makers: they hold up Adam’s profession.

SECOND CLOWN.
Was he a gentleman?

FIRST CLOWN.
He was the first that ever bore arms.

SECOND CLOWN.
Why, he had none.

FIRST CLOWN.
What, art a heathen? How dost thou understand the Scripture? The
Scripture says Adam digg’d. Could he dig without arms? I’ll put another
question to thee. If thou answerest me not to the purpose, confess
thyself—

SECOND CLOWN.
Go to.

FIRST CLOWN.
What is he that builds stronger than either the mason, the shipwright,
or the carpenter?

SECOND CLOWN.
The gallows-maker; for that frame outlives a thousand tenants.

FIRST CLOWN.
I like thy wit well in good faith, the gallows does well. But how does
it well? It does well to those that do ill. Now, thou dost ill to say
the gallows is built stronger than the church; argal, the gallows may
do well to thee. To’t again, come.

SECOND CLOWN.
Who builds stronger than a mason, a shipwright, or a carpenter?

FIRST CLOWN.
Ay, tell me that, and unyoke.

SECOND CLOWN.
Marry, now I can tell.

FIRST CLOWN.
To’t.

SECOND CLOWN.
Mass, I cannot tell.

Enter Hamlet and Horatio, at a distance.

FIRST CLOWN.
Cudgel thy brains no more about it, for your dull ass will not mend his
pace with beating; and when you are asked this question next, say ‘a
grave-maker’. The houses he makes last till doomsday. Go, get thee to
Yaughan; fetch me a stoup of liquor.

[_Exit Second Clown._]

[_Digs and sings._]

   In youth when I did love, did love,
     Methought it was very sweet;
   To contract, O, the time for, a, my behove,
     O methought there was nothing meet.

HAMLET.
Has this fellow no feeling of his business, that he sings at
grave-making?

HORATIO.
Custom hath made it in him a property of easiness.

HAMLET.
’Tis e’en so; the hand of little employment hath the daintier sense.

FIRST CLOWN.
[_Sings._]
   But age with his stealing steps
     Hath claw’d me in his clutch,
   And hath shipp’d me into the land,
     As if I had never been such.

[_Throws up a skull._]

HAMLET.
That skull had a tongue in it, and could sing once. How the knave jowls
it to th’ ground, as if ’twere Cain’s jawbone, that did the first
murder! This might be the pate of a politician which this ass now
o’er-offices, one that would circumvent God, might it not?

HORATIO.
It might, my lord.

HAMLET.
Or of a courtier, which could say ‘Good morrow, sweet lord! How dost
thou, good lord?’ This might be my lord such-a-one, that praised my
lord such-a-one’s horse when he meant to beg it, might it not?

HORATIO.
Ay, my lord.

HAMLET.
Why, e’en so: and now my Lady Worm’s; chapless, and knocked about the
mazard with a sexton’s spade. Here’s fine revolution, an we had the
trick to see’t. Did these bones cost no more the breeding but to play
at loggets with ’em? Mine ache to think on’t.

FIRST CLOWN.
[_Sings._]
   A pickaxe and a spade, a spade,
     For and a shrouding-sheet;
   O, a pit of clay for to be made
     For such a guest is meet.

[_Throws up another skull._]

HAMLET.
There’s another. Why may not that be the skull of a lawyer? Where be
his quiddits now, his quillets, his cases, his tenures, and his tricks?
Why does he suffer this rude knave now to knock him about the sconce
with a dirty shovel, and will not tell him of his action of battery?
Hum. This fellow might be in’s time a great buyer of land, with his
statutes, his recognizances, his fines, his double vouchers, his
recoveries. Is this the fine of his fines, and the recovery of his
recoveries, to have his fine pate full of fine dirt? Will his vouchers
vouch him no more of his purchases, and double ones too, than the
length and breadth of a pair of indentures? The very conveyances of his
lands will scarcely lie in this box; and must the inheritor himself
have no more, ha?

HORATIO.
Not a jot more, my lord.

HAMLET.
Is not parchment made of sheep-skins?

HORATIO.
Ay, my lord, and of calf-skins too.

HAMLET.
They are sheep and calves which seek out assurance in that. I will
speak to this fellow.—Whose grave’s this, sir?

FIRST CLOWN.
Mine, sir.
[_Sings._]
   O, a pit of clay for to be made
     For such a guest is meet.

HAMLET.
I think it be thine indeed, for thou liest in’t.

FIRST CLOWN.
You lie out on’t, sir, and therefore ’tis not yours.
For my part, I do not lie in’t, yet it is mine.

HAMLET.
Thou dost lie in’t, to be in’t and say it is thine. ’Tis for the dead,
not for the quick; therefore thou liest.

FIRST CLOWN.
’Tis a quick lie, sir; ’t will away again from me to you.

HAMLET.
What man dost thou dig it for?

FIRST CLOWN.
For no man, sir.

HAMLET.
What woman then?

FIRST CLOWN.
For none neither.

HAMLET.
Who is to be buried in’t?

FIRST CLOWN.
One that was a woman, sir; but, rest her soul, she’s dead.

HAMLET.
How absolute the knave is! We must speak by the card, or equivocation
will undo us. By the Lord, Horatio, these three years I have taken note
of it, the age is grown so picked that the toe of the peasant comes so
near the heel of the courtier he galls his kibe.—How long hast thou
been a grave-maker?

FIRST CLOWN.
Of all the days i’ th’ year, I came to’t that day that our last King
Hamlet o’ercame Fortinbras.

HAMLET.
How long is that since?

FIRST CLOWN.
Cannot you tell that? Every fool can tell that. It was the very day
that young Hamlet was born,—he that is mad, and sent into England.

HAMLET.
Ay, marry, why was he sent into England?

FIRST CLOWN.
Why, because he was mad; he shall recover his wits there; or if he do
not, it’s no great matter there.

HAMLET.
Why?

FIRST CLOWN.
’Twill not be seen in him there; there the men are as mad as he.

HAMLET.
How came he mad?

FIRST CLOWN.
Very strangely, they say.

HAMLET.
How strangely?

FIRST CLOWN.
Faith, e’en with losing his wits.

HAMLET.
Upon what ground?

FIRST CLOWN.
Why, here in Denmark. I have been sexton here, man and boy, thirty
years.

HAMLET.
How long will a man lie i’ th’earth ere he rot?

FIRST CLOWN.
Faith, if he be not rotten before he die,—as we have many pocky corses
nowadays that will scarce hold the laying in,—he will last you some
eight year or nine year. A tanner will last you nine year.

HAMLET.
Why he more than another?

FIRST CLOWN.
Why, sir, his hide is so tann’d with his trade that he will keep out
water a great while. And your water is a sore decayer of your whoreson
dead body. Here’s a skull now; this skull hath lain in the earth
three-and-twenty years.

HAMLET.
Whose was it?

FIRST CLOWN.
A whoreson, mad fellow’s it was. Whose do you think it was?

HAMLET.
Nay, I know not.

FIRST CLOWN.
A pestilence on him for a mad rogue! A pour’d a flagon of Rhenish on my
head once. This same skull, sir, was Yorick’s skull, the King’s jester.

HAMLET.
This?

FIRST CLOWN.
E’en that.

HAMLET.
Let me see. [_Takes the skull._] Alas, poor Yorick. I knew him,
Horatio, a fellow of infinite jest, of most excellent fancy. He hath
borne me on his back a thousand times; and now, how abhorred in my
imagination it is! My gorge rises at it. Here hung those lips that I
have kiss’d I know not how oft. Where be your gibes now? your gambols?
your songs? your flashes of merriment, that were wont to set the table
on a roar? Not one now, to mock your own grinning? Quite chop-fallen?
Now get you to my lady’s chamber, and tell her, let her paint an inch
thick, to this favour she must come. Make her laugh at that.—Prithee,
Horatio, tell me one thing.

HORATIO.
What’s that, my lord?

HAMLET.
Dost thou think Alexander looked o’ this fashion i’ th’earth?

HORATIO.
E’en so.

HAMLET.
And smelt so? Pah!

[_Throws down the skull._]

HORATIO.
E’en so, my lord.

HAMLET.
To what base uses we may return, Horatio! Why may not imagination trace
the noble dust of Alexander till he find it stopping a bung-hole?

HORATIO.
’Twere to consider too curiously to consider so.

HAMLET.
No, faith, not a jot. But to follow him thither with modesty enough,
and likelihood to lead it; as thus. Alexander died, Alexander was
buried, Alexander returneth into dust; the dust is earth; of earth we
make loam; and why of that loam whereto he was converted might they not
stop a beer-barrel?
Imperious Caesar, dead and turn’d to clay,
Might stop a hole to keep the wind away.
O, that that earth which kept the world in awe
Should patch a wall t’expel the winter’s flaw.
But soft! but soft! aside! Here comes the King.

Enter priests, &c, in procession; the corpse of Ophelia, Laertes and
Mourners following; King, Queen, their Trains, &c.

The Queen, the courtiers. Who is that they follow?
And with such maimed rites? This doth betoken
The corse they follow did with desperate hand
Fordo it own life. ’Twas of some estate.
Couch we awhile and mark.

[_Retiring with Horatio._]

LAERTES.
What ceremony else?

HAMLET.
That is Laertes, a very noble youth. Mark.

LAERTES.
What ceremony else?

PRIEST.
Her obsequies have been as far enlarg’d
As we have warranties. Her death was doubtful;
And but that great command o’ersways the order,
She should in ground unsanctified have lodg’d
Till the last trumpet. For charitable prayers,
Shards, flints, and pebbles should be thrown on her.
Yet here she is allowed her virgin rites,
Her maiden strewments, and the bringing home
Of bell and burial.

LAERTES.
Must there no more be done?

PRIEST.
No more be done.
We should profane the service of the dead
To sing sage requiem and such rest to her
As to peace-parted souls.

LAERTES.
Lay her i’ th’earth,
And from her fair and unpolluted flesh
May violets spring. I tell thee, churlish priest,
A minist’ring angel shall my sister be
When thou liest howling.

HAMLET.
What, the fair Ophelia?

QUEEN.
[_Scattering flowers._] Sweets to the sweet. Farewell.
I hop’d thou shouldst have been my Hamlet’s wife;
I thought thy bride-bed to have deck’d, sweet maid,
And not have strew’d thy grave.

LAERTES.
O, treble woe
Fall ten times treble on that cursed head
Whose wicked deed thy most ingenious sense
Depriv’d thee of. Hold off the earth a while,
Till I have caught her once more in mine arms.
[_Leaps into the grave._]
Now pile your dust upon the quick and dead,
Till of this flat a mountain you have made,
To o’ertop old Pelion or the skyish head
Of blue Olympus.

HAMLET.
[_Advancing._]
What is he whose grief
Bears such an emphasis? whose phrase of sorrow
Conjures the wand’ring stars, and makes them stand
Like wonder-wounded hearers? This is I,
Hamlet the Dane.
[_Leaps into the grave._]

LAERTES.
[_Grappling with him._] The devil take thy soul!

HAMLET.
Thou pray’st not well.
I prithee take thy fingers from my throat;
For though I am not splenative and rash,
Yet have I in me something dangerous,
Which let thy wiseness fear. Away thy hand!

KING.
Pluck them asunder.

QUEEN.
Hamlet! Hamlet!

All.
Gentlemen!

HORATIO.
Good my lord, be quiet.

[_The Attendants part them, and they come out of the grave._]

HAMLET.
Why, I will fight with him upon this theme
Until my eyelids will no longer wag.

QUEEN.
O my son, what theme?

HAMLET.
I lov’d Ophelia; forty thousand brothers
Could not, with all their quantity of love,
Make up my sum. What wilt thou do for her?

KING.
O, he is mad, Laertes.

QUEEN.
For love of God forbear him!

HAMLET.
’Swounds, show me what thou’lt do:
Woul’t weep? woul’t fight? woul’t fast? woul’t tear thyself?
Woul’t drink up eisel? eat a crocodile?
I’ll do’t. Dost thou come here to whine?
To outface me with leaping in her grave?
Be buried quick with her, and so will I.
And if thou prate of mountains, let them throw
Millions of acres on us, till our ground,
Singeing his pate against the burning zone,
Make Ossa like a wart. Nay, an thou’lt mouth,
I’ll rant as well as thou.

QUEEN.
This is mere madness:
And thus awhile the fit will work on him;
Anon, as patient as the female dove,
When that her golden couplets are disclos’d,
His silence will sit drooping.

HAMLET.
Hear you, sir;
What is the reason that you use me thus?
I lov’d you ever. But it is no matter.
Let Hercules himself do what he may,
The cat will mew, and dog will have his day.

[_Exit._]

KING.
I pray thee, good Horatio, wait upon him.

[_Exit Horatio._]

[_To Laertes_]
Strengthen your patience in our last night’s speech;
We’ll put the matter to the present push.—
Good Gertrude, set some watch over your son.
This grave shall have a living monument.
An hour of quiet shortly shall we see;
Till then in patience our proceeding be.

[_Exeunt._]

 SCENE II. A hall in the Castle.

Enter Hamlet and Horatio.

HAMLET.
So much for this, sir. Now let me see the other;
You do remember all the circumstance?

HORATIO.
Remember it, my lord!

HAMLET.
Sir, in my heart there was a kind of fighting
That would not let me sleep. Methought I lay
Worse than the mutinies in the bilboes. Rashly,
And prais’d be rashness for it,—let us know,
Our indiscretion sometime serves us well,
When our deep plots do pall; and that should teach us
There’s a divinity that shapes our ends,
Rough-hew them how we will.

HORATIO.
That is most certain.

HAMLET.
Up from my cabin,
My sea-gown scarf’d about me, in the dark
Grop’d I to find out them; had my desire,
Finger’d their packet, and in fine, withdrew
To mine own room again, making so bold,
My fears forgetting manners, to unseal
Their grand commission; where I found, Horatio,
Oh royal knavery! an exact command,
Larded with many several sorts of reasons,
Importing Denmark’s health, and England’s too,
With ho! such bugs and goblins in my life,
That on the supervise, no leisure bated,
No, not to stay the grinding of the axe,
My head should be struck off.

HORATIO.
Is’t possible?

HAMLET.
Here’s the commission, read it at more leisure.
But wilt thou hear me how I did proceed?

HORATIO.
I beseech you.

HAMLET.
Being thus benetted round with villanies,—
Or I could make a prologue to my brains,
They had begun the play,—I sat me down,
Devis’d a new commission, wrote it fair:
I once did hold it, as our statists do,
A baseness to write fair, and labour’d much
How to forget that learning; but, sir, now
It did me yeoman’s service. Wilt thou know
The effect of what I wrote?

HORATIO.
Ay, good my lord.

HAMLET.
An earnest conjuration from the King,
As England was his faithful tributary,
As love between them like the palm might flourish,
As peace should still her wheaten garland wear
And stand a comma ’tween their amities,
And many such-like ‘as’es of great charge,
That on the view and know of these contents,
Without debatement further, more or less,
He should the bearers put to sudden death,
Not shriving-time allow’d.

HORATIO.
How was this seal’d?

HAMLET.
Why, even in that was heaven ordinant.
I had my father’s signet in my purse,
Which was the model of that Danish seal:
Folded the writ up in the form of the other,
Subscrib’d it: gave’t th’impression; plac’d it safely,
The changeling never known. Now, the next day
Was our sea-fight, and what to this was sequent
Thou know’st already.

HORATIO.
So Guildenstern and Rosencrantz go to’t.

HAMLET.
Why, man, they did make love to this employment.
They are not near my conscience; their defeat
Does by their own insinuation grow.
’Tis dangerous when the baser nature comes
Between the pass and fell incensed points
Of mighty opposites.

HORATIO.
Why, what a king is this!

HAMLET.
Does it not, thinks’t thee, stand me now upon,—
He that hath kill’d my king, and whor’d my mother,
Popp’d in between th’election and my hopes,
Thrown out his angle for my proper life,
And with such cozenage—is’t not perfect conscience
To quit him with this arm? And is’t not to be damn’d
To let this canker of our nature come
In further evil?

HORATIO.
It must be shortly known to him from England
What is the issue of the business there.

HAMLET.
It will be short. The interim is mine;
And a man’s life’s no more than to say ‘One’.
But I am very sorry, good Horatio,
That to Laertes I forgot myself;
For by the image of my cause I see
The portraiture of his. I’ll court his favours.
But sure the bravery of his grief did put me
Into a tow’ring passion.

HORATIO.
Peace, who comes here?

Enter Osric.

OSRIC.
Your lordship is right welcome back to Denmark.

HAMLET.
I humbly thank you, sir. Dost know this waterfly?

HORATIO.
No, my good lord.

HAMLET.
Thy state is the more gracious; for ’tis a vice to know him. He hath
much land, and fertile; let a beast be lord of beasts, and his crib
shall stand at the king’s mess; ’tis a chough; but, as I say, spacious
in the possession of dirt.

OSRIC.
Sweet lord, if your lordship were at leisure, I should impart a thing
to you from his Majesty.

HAMLET.
I will receive it with all diligence of spirit. Put your bonnet to his
right use; ’tis for the head.

OSRIC.
I thank your lordship, ’tis very hot.

HAMLET.
No, believe me, ’tis very cold, the wind is northerly.

OSRIC.
It is indifferent cold, my lord, indeed.

HAMLET.
Methinks it is very sultry and hot for my complexion.

OSRIC.
Exceedingly, my lord; it is very sultry,—as ’twere—I cannot tell how.
But, my lord, his Majesty bade me signify to you that he has laid a
great wager on your head. Sir, this is the matter,—

HAMLET.
I beseech you, remember,—

[_Hamlet moves him to put on his hat._]

OSRIC.
Nay, in good faith; for mine ease, in good faith. Sir, here is newly
come to court Laertes; believe me, an absolute gentleman, full of most
excellent differences, of very soft society and great showing. Indeed,
to speak feelingly of him, he is the card or calendar of gentry; for
you shall find in him the continent of what part a gentleman would see.

HAMLET.
Sir, his definement suffers no perdition in you, though I know, to
divide him inventorially would dizzy th’arithmetic of memory, and yet
but yaw neither, in respect of his quick sail. But, in the verity of
extolment, I take him to be a soul of great article and his infusion of
such dearth and rareness as, to make true diction of him, his semblable
is his mirror and who else would trace him his umbrage, nothing more.

OSRIC.
Your lordship speaks most infallibly of him.

HAMLET.
The concernancy, sir? Why do we wrap the gentleman in our more rawer
breath?

OSRIC.
Sir?

HORATIO.
Is’t not possible to understand in another tongue? You will do’t, sir,
really.

HAMLET.
What imports the nomination of this gentleman?

OSRIC.
Of Laertes?

HORATIO.
His purse is empty already, all’s golden words are spent.

HAMLET.
Of him, sir.

OSRIC.
I know you are not ignorant,—

HAMLET.
I would you did, sir; yet in faith if you did, it would not much
approve me. Well, sir?

OSRIC.
You are not ignorant of what excellence Laertes is,—

HAMLET.
I dare not confess that, lest I should compare with him in excellence;
but to know a man well were to know himself.

OSRIC.
I mean, sir, for his weapon; but in the imputation laid on him, by them
in his meed he’s unfellowed.

HAMLET.
What’s his weapon?

OSRIC.
Rapier and dagger.

HAMLET.
That’s two of his weapons. But well.

OSRIC.
The King, sir, hath wager’d with him six Barbary horses, against the
which he has imponed, as I take it, six French rapiers and poniards,
with their assigns, as girdle, hangers, and so. Three of the carriages,
in faith, are very dear to fancy, very responsive to the hilts, most
delicate carriages, and of very liberal conceit.

HAMLET.
What call you the carriages?

HORATIO.
I knew you must be edified by the margin ere you had done.

OSRIC.
The carriages, sir, are the hangers.

HAMLET.
The phrase would be more german to the matter if we could carry cannon
by our sides. I would it might be hangers till then. But on. Six
Barbary horses against six French swords, their assigns, and three
liberal conceited carriages: that’s the French bet against the Danish.
Why is this all imponed, as you call it?

OSRIC.
The King, sir, hath laid that in a dozen passes between you and him, he
shall not exceed you three hits. He hath laid on twelve for nine. And
it would come to immediate trial if your lordship would vouchsafe the
answer.

HAMLET.
How if I answer no?

OSRIC.
I mean, my lord, the opposition of your person in trial.

HAMLET.
Sir, I will walk here in the hall. If it please his Majesty, it is the
breathing time of day with me. Let the foils be brought, the gentleman
willing, and the King hold his purpose, I will win for him if I can; if
not, I will gain nothing but my shame and the odd hits.

OSRIC.
Shall I re-deliver you e’en so?

HAMLET.
To this effect, sir; after what flourish your nature will.

OSRIC.
I commend my duty to your lordship.

HAMLET.
Yours, yours.

[_Exit Osric._]

He does well to commend it himself, there are no tongues else for’s
turn.

HORATIO.
This lapwing runs away with the shell on his head.

HAMLET.
He did comply with his dug before he suck’d it. Thus has he,—and many
more of the same bevy that I know the drossy age dotes on,— only got
the tune of the time and outward habit of encounter; a kind of yeasty
collection, which carries them through and through the most fanned and
winnowed opinions; and do but blow them to their trial, the bubbles are
out.

Enter a Lord.

LORD.
My lord, his Majesty commended him to you by young Osric, who brings
back to him that you attend him in the hall. He sends to know if your
pleasure hold to play with Laertes or that you will take longer time.

HAMLET.
I am constant to my purposes, they follow the King’s pleasure. If his
fitness speaks, mine is ready. Now or whensoever, provided I be so able
as now.

LORD.
The King and Queen and all are coming down.

HAMLET.
In happy time.

LORD.
The Queen desires you to use some gentle entertainment to Laertes
before you fall to play.

HAMLET.
She well instructs me.

[_Exit Lord._]

HORATIO.
You will lose this wager, my lord.

HAMLET.
I do not think so. Since he went into France, I have been in continual
practice. I shall win at the odds. But thou wouldst not think how ill
all’s here about my heart: but it is no matter.

HORATIO.
Nay, good my lord.

HAMLET.
It is but foolery; but it is such a kind of gain-giving as would
perhaps trouble a woman.

HORATIO.
If your mind dislike anything, obey it. I will forestall their repair
hither, and say you are not fit.

HAMLET.
Not a whit, we defy augury. There’s a special providence in the fall of
a sparrow. If it be now, ’tis not to come; if it be not to come, it
will be now; if it be not now, yet it will come. The readiness is all.
Since no man has aught of what he leaves, what is’t to leave betimes?

Enter King, Queen, Laertes, Lords, Osric and Attendants with foils &c.

KING.
Come, Hamlet, come, and take this hand from me.

[_The King puts Laertes’s hand into Hamlet’s._]

HAMLET.
Give me your pardon, sir. I have done you wrong;
But pardon’t as you are a gentleman.
This presence knows, and you must needs have heard,
How I am punish’d with sore distraction.
What I have done
That might your nature, honour, and exception
Roughly awake, I here proclaim was madness.
Was’t Hamlet wrong’d Laertes? Never Hamlet.
If Hamlet from himself be ta’en away,
And when he’s not himself does wrong Laertes,
Then Hamlet does it not, Hamlet denies it.
Who does it, then? His madness. If’t be so,
Hamlet is of the faction that is wrong’d;
His madness is poor Hamlet’s enemy.
Sir, in this audience,
Let my disclaiming from a purpos’d evil
Free me so far in your most generous thoughts
That I have shot my arrow o’er the house
And hurt my brother.

LAERTES.
I am satisfied in nature,
Whose motive in this case should stir me most
To my revenge. But in my terms of honour
I stand aloof, and will no reconcilement
Till by some elder masters of known honour
I have a voice and precedent of peace
To keep my name ungor’d. But till that time
I do receive your offer’d love like love,
And will not wrong it.

HAMLET.
I embrace it freely,
And will this brother’s wager frankly play.—
Give us the foils; come on.

LAERTES.
Come, one for me.

HAMLET.
I’ll be your foil, Laertes; in mine ignorance
Your skill shall like a star i’ th’ darkest night,
Stick fiery off indeed.

LAERTES.
You mock me, sir.

HAMLET.
No, by this hand.

KING.
Give them the foils, young Osric. Cousin Hamlet,
You know the wager?

HAMLET.
Very well, my lord.
Your Grace has laid the odds o’ the weaker side.

KING.
I do not fear it. I have seen you both;
But since he is better’d, we have therefore odds.

LAERTES.
This is too heavy. Let me see another.

HAMLET.
This likes me well. These foils have all a length?

[_They prepare to play._]

OSRIC.
Ay, my good lord.

KING.
Set me the stoups of wine upon that table.
If Hamlet give the first or second hit,
Or quit in answer of the third exchange,
Let all the battlements their ordnance fire;
The King shall drink to Hamlet’s better breath,
And in the cup an union shall he throw
Richer than that which four successive kings
In Denmark’s crown have worn. Give me the cups;
And let the kettle to the trumpet speak,
The trumpet to the cannoneer without,
The cannons to the heavens, the heavens to earth,
‘Now the King drinks to Hamlet.’ Come, begin.
And you, the judges, bear a wary eye.

HAMLET.
Come on, sir.

LAERTES.
Come, my lord.

[_They play._]

HAMLET.
One.

LAERTES.
No.

HAMLET.
Judgement.

OSRIC.
A hit, a very palpable hit.

LAERTES.
Well; again.

KING.
Stay, give me drink. Hamlet, this pearl is thine;
Here’s to thy health.

[_Trumpets sound, and cannon shot off within._]

Give him the cup.

HAMLET.
I’ll play this bout first; set it by awhile.

[_They play._]

Come. Another hit; what say you?

LAERTES.
A touch, a touch, I do confess.

KING.
Our son shall win.

QUEEN.
He’s fat, and scant of breath.
Here, Hamlet, take my napkin, rub thy brows.
The Queen carouses to thy fortune, Hamlet.

HAMLET.
Good madam.

KING.
Gertrude, do not drink.

QUEEN.
I will, my lord; I pray you pardon me.

KING.
[_Aside._] It is the poison’d cup; it is too late.

HAMLET.
I dare not drink yet, madam. By and by.

QUEEN.
Come, let me wipe thy face.

LAERTES.
My lord, I’ll hit him now.

KING.
I do not think’t.

LAERTES.
[_Aside._] And yet ’tis almost ’gainst my conscience.

HAMLET.
Come for the third, Laertes. You do but dally.
I pray you pass with your best violence.
I am afeard you make a wanton of me.

LAERTES.
Say you so? Come on.

[_They play._]

OSRIC.
Nothing neither way.

LAERTES.
Have at you now.

[_Laertes wounds Hamlet; then, in scuffling, they change rapiers, and
Hamlet wounds Laertes._]

KING.
Part them; they are incens’d.

HAMLET.
Nay, come again!

[_The Queen falls._]

OSRIC.
Look to the Queen there, ho!

HORATIO.
They bleed on both sides. How is it, my lord?

OSRIC.
How is’t, Laertes?

LAERTES.
Why, as a woodcock to my own springe, Osric.
I am justly kill’d with mine own treachery.

HAMLET.
How does the Queen?

KING.
She swoons to see them bleed.

QUEEN.
No, no, the drink, the drink! O my dear Hamlet!
The drink, the drink! I am poison’d.

[_Dies._]

HAMLET.
O villany! Ho! Let the door be lock’d:
Treachery! Seek it out.

[_Laertes falls._]

LAERTES.
It is here, Hamlet. Hamlet, thou art slain.
No medicine in the world can do thee good.
In thee there is not half an hour of life;
The treacherous instrument is in thy hand,
Unbated and envenom’d. The foul practice
Hath turn’d itself on me. Lo, here I lie,
Never to rise again. Thy mother’s poison’d.
I can no more. The King, the King’s to blame.

HAMLET.
The point envenom’d too!
Then, venom, to thy work.

[_Stabs the King._]

OSRIC and LORDS.
Treason! treason!

KING.
O yet defend me, friends. I am but hurt.

HAMLET.
Here, thou incestuous, murderous, damned Dane,
Drink off this potion. Is thy union here?
Follow my mother.

[_King dies._]

LAERTES.
He is justly serv’d.
It is a poison temper’d by himself.
Exchange forgiveness with me, noble Hamlet.
Mine and my father’s death come not upon thee,
Nor thine on me.

[_Dies._]

HAMLET.
Heaven make thee free of it! I follow thee.
I am dead, Horatio. Wretched Queen, adieu.
You that look pale and tremble at this chance,
That are but mutes or audience to this act,
Had I but time,—as this fell sergeant, death,
Is strict in his arrest,—O, I could tell you,—
But let it be. Horatio, I am dead,
Thou liv’st; report me and my cause aright
To the unsatisfied.

HORATIO.
Never believe it.
I am more an antique Roman than a Dane.
Here’s yet some liquor left.

HAMLET.
As th’art a man,
Give me the cup. Let go; by Heaven, I’ll have’t.
O good Horatio, what a wounded name,
Things standing thus unknown, shall live behind me.
If thou didst ever hold me in thy heart,
Absent thee from felicity awhile,
And in this harsh world draw thy breath in pain,
To tell my story.

[_March afar off, and shot within._]

What warlike noise is this?

OSRIC.
Young Fortinbras, with conquest come from Poland,
To the ambassadors of England gives
This warlike volley.

HAMLET.
O, I die, Horatio.
The potent poison quite o’er-crows my spirit:
I cannot live to hear the news from England,
But I do prophesy th’election lights
On Fortinbras. He has my dying voice.
So tell him, with the occurrents more and less,
Which have solicited. The rest is silence.

[_Dies._]

HORATIO.
Now cracks a noble heart. Good night, sweet prince,
And flights of angels sing thee to thy rest.
Why does the drum come hither?

[_March within._]

Enter Fortinbras, the English Ambassadors and others.

FORTINBRAS.
Where is this sight?

HORATIO.
What is it you would see?
If aught of woe or wonder, cease your search.

FORTINBRAS.
This quarry cries on havoc. O proud death,
What feast is toward in thine eternal cell,
That thou so many princes at a shot
So bloodily hast struck?

FIRST AMBASSADOR.
The sight is dismal;
And our affairs from England come too late.
The ears are senseless that should give us hearing,
To tell him his commandment is fulfill’d,
That Rosencrantz and Guildenstern are dead.
Where should we have our thanks?

HORATIO.
Not from his mouth,
Had it th’ability of life to thank you.
He never gave commandment for their death.
But since, so jump upon this bloody question,
You from the Polack wars, and you from England
Are here arriv’d, give order that these bodies
High on a stage be placed to the view,
And let me speak to th’ yet unknowing world
How these things came about. So shall you hear
Of carnal, bloody and unnatural acts,
Of accidental judgements, casual slaughters,
Of deaths put on by cunning and forc’d cause,
And, in this upshot, purposes mistook
Fall’n on the inventors’ heads. All this can I
Truly deliver.

FORTINBRAS.
Let us haste to hear it,
And call the noblest to the audience.
For me, with sorrow I embrace my fortune.
I have some rights of memory in this kingdom,
Which now to claim my vantage doth invite me.

HORATIO.
Of that I shall have also cause to speak,
And from his mouth whose voice will draw on more.
But let this same be presently perform’d,
Even while men’s minds are wild, lest more mischance
On plots and errors happen.

FORTINBRAS.
Let four captains
Bear Hamlet like a soldier to the stage,
For he was likely, had he been put on,
To have prov’d most royally; and for his passage,
The soldiers’ music and the rites of war
Speak loudly for him.
Take up the bodies. Such a sight as this
Becomes the field, but here shows much amiss.
Go, bid the soldiers shoot.

[_A dead march._]

[_Exeunt, bearing off the bodies, after which a peal of ordnance is
shot off._]
