---
title: "Macbeth - Act V"
author: "William Shakespeare"
description: "Act V of Macbeth."
categories: [Literature, Classic]
format:
  html:
    page-layout: article
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 300px
    reference-location: margin
    citation-location: margin
---

# Act V

Scene I. Dunsinane. A Room in the Castle.
Scene II. The Country near Dunsinane.
Scene III. Dunsinane. A Room in the Castle.
Scene IV. Country near Dunsinane: a Wood in view.
Scene V. Dunsinane. Within the castle.
Scene VI. The same. A Plain before the Castle.
Scene VII. The same. Another part of the Plain.
Scene VIII. The same. Another part of the field.




Dramatis Personæ

DUNCAN, King of Scotland.
MALCOLM, his Son.
DONALBAIN, his Son.
MACBETH, General in the King’s Army.
BANQUO, General in the King’s Army.
MACDUFF, Nobleman of Scotland.
LENNOX, Nobleman of Scotland.
ROSS, Nobleman of Scotland.
MENTEITH, Nobleman of Scotland.
ANGUS, Nobleman of Scotland.
CAITHNESS, Nobleman of Scotland.
FLEANCE, Son to Banquo.
SIWARD, Earl of Northumberland, General of the English Forces.
YOUNG SIWARD, his Son.
SEYTON, an Officer attending on Macbeth.
BOY, Son to Macduff.
An English Doctor.
A Scottish Doctor.
A Soldier.
A Porter.
An Old Man.

LADY MACBETH.
LADY MACDUFF.
Gentlewoman attending on Lady Macbeth.
HECATE, and three Witches.

Lords, Gentlemen, Officers, Soldiers, Murderers, Attendants and
Messengers.

The Ghost of Banquo and several other Apparitions.

SCENE: In the end of the Fourth Act, in England; through the rest of
the Play, in Scotland; and chiefly at Macbeth’s Castle.
