---
title: "Romeo and Juliet - Act V"
author: "William Shakespeare"
description: "Act V of Romeo and Juliet."
categories: [Literature, Classic]
format:
  html:
    page-layout: article
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 300px
    reference-location: margin
    citation-location: margin
---

# Act V

Scene I. Mantua. A Street.
Scene II. Friar Lawrence’s Cell.
Scene III. A churchyard; in it a Monument belonging to the Capulets.




 Dramatis Personæ

ESCALUS, Prince of Verona.
MERCUTIO, kinsman to the Prince, and friend to Romeo.
PARIS, a young Nobleman, kinsman to the Prince.
Page to Paris.

MONTAGUE, head of a Veronese family at feud with the Capulets.
LADY MONTAGUE, wife to Montague.
ROMEO, son to Montague.
BENVOLIO, nephew to Montague, and friend to Romeo.
ABRAM, servant to Montague.
BALTHASAR, servant to Romeo.

CAPULET, head of a Veronese family at feud with the Montagues.
LADY CAPULET, wife to Capulet.
JULIET, daughter to Capulet.
TYBALT, nephew to Lady Capulet.
CAPULET’S COUSIN, an old man.
NURSE to Juliet.
PETER, servant to Juliet’s Nurse.
SAMPSON, servant to Capulet.
GREGORY, servant to Capulet.
Servants.

FRIAR LAWRENCE, a Franciscan.
FRIAR JOHN, of the same Order.
An Apothecary.
CHORUS.
Three Musicians.
An Officer.
Citizens of Verona; several Men and Women, relations to both houses;
Maskers, Guards, Watchmen and Attendants.

SCENE. During the greater part of the Play in Verona; once, in the
Fifth Act, at Mantua.




THE PROLOGUE


 Enter Chorus.

CHORUS.
Two households, both alike in dignity,
In fair Verona, where we lay our scene,
From ancient grudge break to new mutiny,
Where civil blood makes civil hands unclean.
From forth the fatal loins of these two foes
A pair of star-cross’d lovers take their life;
Whose misadventur’d piteous overthrows
Doth with their death bury their parents’ strife.
The fearful passage of their death-mark’d love,
And the continuance of their parents’ rage,
Which, but their children’s end, nought could remove,
Is now the two hours’ traffic of our stage;
The which, if you with patient ears attend,
What here shall miss, our toil shall strive to mend.

 [_Exit._]
