---
title: "The Odyssey - Book i"
author: "Homer"
description: "Book i of The Odyssey."
categories: [Literature, Classic]
format:
  html:
    page-layout: article
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 300px
    reference-location: margin
    citation-location: margin
---

# Book i

., is continued to the end of Book iv., and not resumed till
Ulysses wakes in the middle of line 187, Book xiii., from whence it
continues to the end of Book xxiv.

In “The Authoress of the Odyssey”, I wrote:

the introduction of lines xi., 115-137 and of line ix., 535, with the
writing a new council of the gods at the beginning of Book v., to take
the place of the one that was removed to Book i., 1-79, were the only
things that were done to give even a semblance of unity to the old
scheme and the new, and to conceal the fact that the Muse, after being
asked to sing of one subject, spend two-thirds of her time in singing a
very different one, with a climax for which no-one has asked her. For
roughly the Return occupies eight Books, and Penelope and the Suitors
sixteen.


I believe this to be substantially correct.

Lastly, to deal with a very unimportant point, I observe that the
Leipsic Teubner edition of 894 makes Books ii. and iii. end with a
comma. Stops are things of such far more recent date than the
“Odyssey,” that there does not seem much use in adhering to the text in
so small a matter; still, from a spirit of mere conservatism, I have
preferred to do so. Why [Greek] at the beginnings of Books ii. and
viii., and [Greek], at the beginning of Book vii. should have initial
capitals in an edition far too careful to admit a supposition of
inadvertence, when [Greek] at the beginning of Books vi. and xiii., and
[Greek] at the beginning of Book xvii. have no initial capitals, I
cannot determine. No other Books of the “Odyssey” have initial capitals
except the three mentioned unless the first word of the Book is a
proper name.

S. BUTLER.


_July_ 25, 1900.




PREFACE TO SECOND EDITION


Butler’s Translation of the “Odyssey” appeared originally in 1900, and
The Authoress of the Odyssey in 1897. In the preface to the new edition
of “The Authoress”, which is published simultaneously with this new
edition of the Translation, I have given some account of the genesis of
the two books.

The size of the original page has been reduced so as to make both books
uniform with Butler’s other works; and, fortunately, it has been
possible, by using a smaller type, to get the same number of words into
each page, so that the references remain good, and, with the exception
of a few minor alterations and rearrangements now to be enumerated so
far as they affect the Translation, the new editions are faithful
reprints of the original editions, with misprints and obvious errors
corrected—no attempt having been made to edit them or to bring them up
to date.

(a) The Index has been revised.

(b) Owing to the reduction in the size of the page it has been
necessary to shorten some of the headlines, and here advantage has been
taken of various corrections of and additions to the headlines and
shoulder-notes made by Butler in his own copies of the two books.

(c) For the most part each of the illustrations now occupies a page,
whereas in the original editions they generally appeared two on the
page. It has been necessary to reduce the plan of the House of Ulysses.

On page 153 of “The Authoress” Butler says: “No great poet would
compare his hero to a paunch full of blood and fat, cooking before the
fire (xx, 24-28).” This passage is not given in the abridged Story of
the “Odyssey” at the beginning of the book, but in the Translation it
occurs in these words:

“Thus he chided with his heart, and checked it into endurance, but he
tossed about as one who turns a paunch full of blood and fat in front
of a hot fire, doing it first on one side then on the other, that he
may get it cooked as soon as possible; even so did he turn himself
about from side to side, thinking all the time how, single-handed as he
was, he should contrive to kill so large a body of men as the wicked
suitors.”

It looks as though in the interval between the publication of “The
Authoress” (1897) and of the Translation (1900) Butler had changed his
mind; for in the first case the comparison is between Ulysses and a
paunch full, etc., and in the second it is between Ulysses and a man
who turns a paunch full, etc. The second comparison is perhaps one
which a great poet might make.

In seeing the works through the press I have had the invaluable
assistance of Mr. A. T. Bartholomew of the University Library,
Cambridge, and of Mr. Donald S. Robertson, Fellow of Trinity College,
Cambridge. To both these friends I give my most cordial thanks for the
care and skill exercised by them. Mr. Robertson has found time for the
labour of checking and correcting all the quotations from and
references to the “Iliad” and “Odyssey,” and I believe that it could
not have been better performed. It was, I know, a pleasure for him; and
it would have been a pleasure also for Butler if he could have known
that his work was being shepherded by the son of his old friend, Mr. H.
R. Robertson, who more than half a century ago was a fellow-student
with him at Cary’s School of Art in Streatham Street, Bloomsbury.

HENRY FESTING JONES.

 120 MAIDA VALE, W.9.
4th _December_, 1921.

THE ODYSSEY
